### ISSUE TITLE
[Bug] 部署通过XTuner训练的Qwen-1.8B-Chat报错

### ISSUE THREAD

**Issue by TS10armourer** [InternLM/lmdeploy#1008]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

首先是我未在支持的列表里找到对Qwen-1.8B-chat的支持
```
(lmdeploy) (base) tangshi@tangshi:~/TangShi$ lmdeploy serve api_server /home/tangshi/TangShi/work_dirs/qwen_1_8b_chat_qlora_alpaca
_zh_e3_copy/qwen_qlora/model/step1 --server-name 0.0.0.0 --server-port 2048 --tp 1
/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
model_source: hf_model
Please input a model_name for hf_model
Traceback (most recent call last):
  File "/home/tangshi/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/cli/serve.py", line 237, in api_server
    run_api_server(args.model_path,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 962, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 67, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 108, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=local_path,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 182, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 265, in _from_hf
    assert engine_config.model_name in MODELS.module_dict.keys(), \
AssertionError: 'None' is not supported. The supported models are: dict_keys(['base', 'llama', 'internlm', 'vicuna', 'wizardlm', 'internlm-chat-7b', 'internlm-chat', 'internlm-chat-7b-8k', 'internlm-chat-20b', 'internlm-20b', 'internlm2-7b', 'internlm2-20b', 'internlm2-chat-7b', 'internlm2-chat-20b', 'baichuan-7b', 'baichuan2-7b', 'puyu', 'llama2', 'llama-2', 'llama-2-chat', 'qwen-7b', 'qwen-14b', 'codellama', 'falcon', 'chatglm2-6b', 'solar', 'solar-70b', 'ultralm', 'ultracm', 'yi', 'yi-chat', 'yi-200k', 'yi-34b'])

```

但是我通过修改文件夹名为base解决了：

但是现在又报错：
```
(lmdeploy) (base) tangshi@tangshi:~/TangShi$ lmdeploy serve api_server /home/tangshi/TangShi/work_dirs/qwen_1_8b_chat_qlora_alpaca_zh_e3_copy/qwen_qlora/model/base --server-name 0.0.0.0 --server-port 2048 --tp 1
/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
model_source: hf_model
01/20 23:58:51 - turbomind - WARNING - kwargs model_name is deprecated to initialize model, use TurbomindEngineConfig instead.
Traceback (most recent call last):
  File "/home/tangshi/miniconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/cli/serve.py", line 237, in api_server
    run_api_server(args.model_path,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 962, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 67, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 108, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=local_path,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 182, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 296, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 26, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 141, in __init__
    self.cfg = self.get_config(cfg)
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 30, in get_config
    final_cfg = super().get_config(cfg).__dict__
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 157, in get_config
    final_cfg.update(self.input_model.model_info())
  File "/home/tangshi/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 185, in model_info
    norm_eps = model_arg['rms_norm_eps']
KeyError: 'rms_norm_eps'
```

### Reproduction

```
lmdeploy serve api_server /home/tangshi/TangShi/work_dirs/qwen_1_8b_chat_qlora_alpaca_zh_e3_copy/qwen_qlora/model/base --server-name 0.0.0.0 --server-port 2048 --tp 1
```

### Environment

```Shell
我是通过如下代码安装的，因为我的CUDA版本是12.3：

export LMDEPLOY_VERSION=0.2.0
export PYTHON_VERSION=38
pip install https://github.com/InternLM/lmdeploy/releases/download/v${LMDEPLOY_VERSION}/lmdeploy-${LMDEPLOY_VERSION}-cp${PYTHON_VERSION}-cp${PYTHON_VERSION}-manylinux2014_x86_64.whl
```
```


### Error traceback

_No response_

**Comment by lvhan028** [comment]
加上参数--model-name qwen-7b 试试
