### ISSUE TITLE
[Bug] RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/allocator.h:262

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1058]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When I set `concurrency` to `1000` and `num_prompts` to `10000`, this is the server's traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 499, in _func
    output = self.model_insts[device_id].forward(
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/allocator.h:262 
```

### Reproduction

```
GPU: NVIDIA A100-SXM4-80GB

CUDA: 11.8

LMDeploy: 0.2.1

Llama-2-13b-chat-hf: https://huggingface.co/meta-llama/Llama-2-13b-chat-hf

ShareGPT_V3_unfiltered_cleaned_split.json: https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json

profile_restful_api.py: https://github.com/InternLM/lmdeploy/blob/main/benchmark/profile_restful_api.py
```

server

```
python3 -m lmdeploy serve api_server  Llama-2-13b-chat-hf
```

client

```
python3 profile_restful_api.py --server_addr 127.0.0.1:23333 --tokenizer_path Llama-2-13b-chat-hf --dataset ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 1000 --num_prompts 10000
```

### Environment

```Shell
sys.platform: linux
Python: 3.9.16 (main, Aug 15 2023, 19:38:56) [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
PyTorch: 2.1.2+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1a0+5e8e2f1
LMDeploy: 0.2.1+
transformers: 4.36.0
gradio: Not Found
fastapi: 0.104.1
pydantic: 2.5.3
```

**Comment by zhyncs** [comment]
When I use the **same** instance, model and data, it works well with vLLM. I have set the `request-rate` to `1000` and `num-prompts` to 10000.

```
vllm: 0.2.7

Llama-2-13b-chat-hf: https://huggingface.co/meta-llama/Llama-2-13b-chat-hf

ShareGPT_V3_unfiltered_cleaned_split.json: https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/resolve/main/ShareGPT_V3_unfiltered_cleaned_split.json

benchmark_serving.py: https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py
```

server
```
python3 -m vllm.entrypoints.api_server --model Llama-2-13b-chat-hf --trust-remote-code
```

client
```
python3 v.py --dataset ShareGPT_V3_unfiltered_cleaned_split.json --tokenizer Llama-2-13b-chat-hf --request-rate 1000 --num-prompts 10000
```

**Comment by AllentDan** [comment]
I found that the bug was caused by https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/async_engine.py#L254-L258

The branch is for pytorch engine, but it introduced a bug for high-concurrency requests for turbomind.

**Comment by zhyncs** [comment]
> I found that the bug was caused by https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/serve/async_engine.py#L254-L258
> 
> 
> 
> The branch is for pytorch engine, but it introduced a bug for high-concurrency requests for turbomind.

Ok I will fix it soon

**Comment by AllentDan** [comment]
We will remove the condition branch and make the pytorch backend the same as turbomind. It requires pytorch backend to distingue the session and engine instance.

**Comment by zhyncs** [comment]
> We will remove the condition branch and make the pytorch backend the same as turbomind. It requires pytorch backend to distingue the session and engine instance.

May we use a temporary quick fix, such as a workaround by distinguishing between different backends

**Comment by AllentDan** [comment]
#1098 is one.

**Comment by zhyncs** [comment]
> #1098 is one.

Similar work LOL. After this quick fix https://github.com/InternLM/lmdeploy/pull/1100, I rerun `python3 profile_restful_api.py --server_addr 127.0.0.1:23333 --tokenizer_path Llama-2-13b-chat-hf --dataset ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 1000 --num_prompts 10000` to make sure that it has been resolved. And when PyTorch backend to distingue the session and engine instance, we may refactor the `get_generator` at that time. Do you have any suggestions?

**Comment by lvhan028** [comment]
What's the benefits of concurreny 1000?

**Comment by zhyncs** [comment]
> What's the benefits of concurreny 1000?
> How much gain do we get comparing to concurreny 256?

1000 is just a simple way to reproduce. In fact, in the default case of 128 instances, if the request concurrency exceeds the number of instances, such as 256 concurrency, it will still trigger.

**Comment by zhyncs** [comment]
> What's the benefits of concurreny 1000?
> How much gain do we get comparing to concurreny 256?

There is also a situation where if you want to use the benchmark serving script that comes with vLLM for testing, there may be issues with the request rate defaulting to inf. As we all know, vLLM's benchmark script is quite widely used, which makes people think that LMDeploy cannot handle high instantaneous loads.

**Comment by zhyncs** [comment]
Therefore, I believe this fix https://github.com/InternLM/lmdeploy/pull/1100 is a relatively urgent one

**Comment by zhyncs** [comment]
fixed https://github.com/InternLM/lmdeploy/pull/1100

**Comment by lvhan028** [comment]
I was not challenging. Just want to know the performance result of concurrency 1000

**Comment by zhyncs** [comment]
> I was not challenging. Just want to know the performance result of concurrency 1000

**almost no significant improvement**

commit: [78a6fd](https://github.com/InternLM/lmdeploy/commit/78a6fd45873669f52bbade5a45c7625fea31a77e) After this commit, LMDeploy can handle high instantaneous loads.
model: Llama-2-13b-chat-hf
dataset: ShareGPT_V3_unfiltered_cleaned_split.json
num_prompts: 1000

```
# first
concurrency: 256
elapsed_time: 138.563s

number of prompt tokens: 241688
number of completion tokens: 228637
token throughput (completion token): 1650.055 token/s
token throughput (prompt + completion token): 3394.297 token/s
RPS (request per second): 7.217 req/s
RPM (request per minute): 433.015 req/min

# second
concurrency: 256
elapsed_time: 138.012s

number of prompt tokens: 241688
number of completion tokens: 228637
token throughput (completion token): 1656.648 token/s
token throughput (prompt + completion token): 3407.861 token/s
RPS (request per second): 7.246 req/s
RPM (request per minute): 434.745 req/min

# third
concurrency: 256
elapsed_time: 137.994s

number of prompt tokens: 241688
number of completion tokens: 228637
token throughput (completion token): 1656.867 token/s
token throughput (prompt + completion token): 3408.312 token/s
RPS (request per second): 7.247 req/s
RPM (request per minute): 434.803 req/min
```

```
# first
concurrency: 1000
elapsed_time: 133.429s

number of prompt tokens: 241688
number of completion tokens: 228637
token throughput (completion token): 1713.553 token/s
token throughput (prompt + completion token): 3524.918 token/s
RPS (request per second): 7.495 req/s
RPM (request per minute): 449.679 req/min

# second
concurrency: 1000
elapsed_time: 137.238s

number of prompt tokens: 241688
number of completion tokens: 228637
token throughput (completion token): 1665.989 token/s
token throughput (prompt + completion token): 3427.076 token/s
RPS (request per second): 7.287 req/s
RPM (request per minute): 437.197 req/min

# third
concurrency: 1000
elapsed_time: 135.119s

number of prompt tokens: 241688
number of completion tokens: 228637
token throughput (completion token): 1692.122 token/s
token throughput (prompt + completion token): 3480.832 token/s
RPS (request per second): 7.401 req/s
RPM (request per minute): 444.055 req/min
```
