### ISSUE TITLE
internLM2 20B长本文部署后，调用接口异常

### ISSUE THREAD

**Issue by testTech92** [InternLM/lmdeploy#1078]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

给一个1-20万字的文本，让它总结文本内容，只要超过1万字，就一定会有2个问题中的一个 1. 每次只输出几个字，输出内容不变，答非所问，缺乏长文本总结能力  2.从文本中找一段文字重复输出。文本越长，第一个发生的概率越大

### Reproduction

使用  lmdeploy serve api_server部署 session_len 160000  rope_scaling_factor 2.0 其他参数默认

### Environment

```Shell
Python 3.10 cuda 11.8 torch 2.1.0
```

**Comment by irexyc** [comment]
用的是internlm-20b 还是 internlm2-chat-20b？

几千几百的输入正常么？一般的对话比如‘你好`，结果正常么？

**Comment by testTech92** [comment]
几百几千正常，1万也正常，超过1w就不行，用的8卡3090，7B和20B模型都尝试过，结果一样（代码和权重从modelscope上下载的）

**Comment by testTech92** [comment]
最新测试：将除权重外的所有代码换成Huggingface, 一样超过1万就不正常了，如果转成TurboMind，1w都跑不了, 服务端就直接异常退出code segemented. 客户端报错： Traceback (most recent call last):
  File "c:/Users/test/Desktop/大模型/qa/long_text.py", line 43, in <module>
    for _ in res.iter_content(None):
  File "E:\ProgramFiles\Miniconda3\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by irexyc** [comment]
那外推看起来是模型的问题。

这个报错是client端的，得看server端的log，可以把log_level改成info看下。kv cache 的话，128的长度需要12MB，1w长度的haul大概1个g，cache_max_entry_count 设置的多大？

**Comment by testTech92** [comment]
cache_max_entry_count 使用的默认设置0.8

INFO错误：
[TM][INFO] [Forward] [0, 1), dc_bsz = 0, pf_bsz = 1, n_tok = 13668, max_q = 13668, max_k = 13668
Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:66 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
Illegal instruction (core dumped)

DEBUG 错误
[TM][DEBUG] virtual void* turbomind::Allocator<turbomind::AllocatorType::CUDA>::malloc(size_t, bool, bool)
[TM][DEBUG] malloc buffer 0xe324bcc00 with size 27992064
[TM][DEBUG] void turbomind::cublasMMWrapper::Gemm(cublasOperation_t, cublasOperation_t, int, int, int, const void*, int, const void*, int, void*, int)
[TM][DEBUG] void turbomind::cublasMMWrapper::Gemm(cublasOperation_t, cublasOperation_t, int, int, int, const void*, int, const void*, int, void*, int, float, float)
[TM][DEBUG] void turbomind::cublasMMWrapper::Gemm(cublasOperation_t, cublasOperation_t, int, int, int, const void*, int, const void*, int, void*, int)
[TM][DEBUG] void turbomind::cublasMMWrapper::Gemm(cublasOperation_t, cublasOperation_t, int, int, int, const void*, int, const void*, int, void*, int, float, float)
[TM][DEBUG] void turbomind::cublasMMWrapper::Gemm(cublasOperation_t, cublasOperation_t, int, int, int, const void*, int, const void*, int, void*, int)
[TM][DEBUG] void turbomind::cublasMMWrapper::Gemm(cublasOperation_t, cublasOperation_t, int, int, int, const void*, int, const void*, int, void*, int, float, float)
[TM][DEBUG] void turbomind::ftNcclAllReduceSum(const T*, T*, int, turbomind::NcclParam, cudaStream_t) [with T = __half; cudaStream_t = CUstream_st*] start
[TM][DEBUG] ncclDataType_t turbomind::getNcclDataType() [with T = __half] start
[TM][DEBUG] void turbomind::ftNcclAllReduceSum(const T*, T*, int, turbomind::NcclParam, cudaStream_t) [with T = __half; cudaStream_t = CUstream_st*] start
[TM][DEBUG] ncclDataType_t turbomind::getNcclDataType() [with T = __half] start
[TM][DEBUG] void turbomind::ftNcclAllReduceSum(const T*, T*, int, turbomind::NcclParam, cudaStream_t) [with T = __half; cudaStream_t = CUstream_st*] start
[TM][DEBUG] ncclDataType_t turbomind::getNcclDataType() [with T = __half] start
Failed, NCCL error /lmdeploy/src/turbomind/utils/nccl_utils.cc:66 'unhandled cuda error (run with NCCL_DEBUG=INFO for details)'
Illegal instruction (core dumped)

**Comment by testTech92** [comment]
使用vllm部署，可以支持长文本读入，但是也遇到了超过2万token时无法遵循指令的问题，会乱输出
