### ISSUE TITLE
[Bug] ValueError: need at least one array to stack in benchmark 

### ISSUE THREAD

**Issue by Jackwin** [InternLM/lmdeploy#1145]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

按照[guide](https://lmdeploy.readthedocs.io/en/latest/benchmark/profile_generation.html)进行benchmark的复现，执行`python3 profile_generation.py ./internlm-7b`后，通过log可以看出warmup，前2-3次的warmup都是成功，但随后的warmup出现ValueError: need at least one array to stack

### Reproduction

pip install 'lmdeploy>=0.1.0a1' -i https://pypi.tuna.tsinghua.edu.cn/simple
git clone --depth=1 https://github.com/InternLM/lmdeploy
cd lmdeploy/benchmark
lmdeploy convert internlm internlm/internlm-7b --dst-path ./internlm-7b
python3 profile_generation.py ./internlm-7b

### Environment

```Shell
硬件为NVIDIA A100-SXM4-80GB
```

### Error traceback

```Shell
[WARNING] gemm_config.in is not found; using default GEMM algo
2024-02-15 04:56:59,770 - lmdeploy - WARNING - kwargs ignore_eos is deprecated for inference, use GenerationConfig instead.
2024-02-15 04:56:59,770 - lmdeploy - WARNING - kwargs top_k is deprecated for inference, use GenerationConfig instead.
2024-02-15 04:56:59,770 - lmdeploy - WARNING - kwargs top_p is deprecated for inference, use GenerationConfig instead.
2024-02-15 04:56:59,770 - lmdeploy - WARNING - kwargs temperature is deprecated for inference, use GenerationConfig instead.
2024-02-15 04:56:59,770 - lmdeploy - WARNING - kwargs request_output_len is deprecated for inference, use GenerationConfig instead.
end warmup, elapsed time: 27.32s
 17%|████████████████████████████████████▌                                                                                                                                                                                      | 1/6 [00:20<01:44, 20.91s/it]Exception in thread Thread-11 (infer):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/lmdeploy/benchmark/profile_generation.py", line 62, in infer
    assert output_seqlen <= n_token <= output_seqlen + 1, \
AssertionError: Error. session_id(1) request 2048 tokens, but generate 1928 tokens
 17%|████████████████████████████████████▌                                                                                                                                                                                      | 1/6 [00:20<01:44, 20.91s/it]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/workspace/lmdeploy/benchmark/profile_generation.py", line 149, in profile_throughput
    token_latency_stats = np.stack(token_latency_stats, axis=0)
  File "<__array_function__ internals>", line 200, in stack
  File "/opt/conda/lib/python3.10/site-packages/numpy/core/shape_base.py", line 460, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/lmdeploy/benchmark/profile_generation.py", line 407, in <module>
    main()
  File "/workspace/lmdeploy/benchmark/profile_generation.py", line 360, in main
    output = Pool(1).map(profile_target, (args.model_path, ))
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
ValueError: need at least one array to stack
```

**Comment by ispobock** [comment]
This issue is caused by the prompt_tokens + completion_tokens < the default session_len (2048). So I raised the PR https://github.com/InternLM/lmdeploy/pull/1181 for fixing this.
