### ISSUE TITLE
[Bug] docker 运行报错 KeyError: 'model.layers.0.feed_forward.w1.weight'

### ISSUE THREAD

**Issue by rainbownmm** [InternLM/lmdeploy#1212]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用最新的docker镜像
配置
windows10
2*3090
运行命令如下
docker run --runtime nvidia --gpus all   -v ~/.cache/huggingface:/root/.cache/huggingface   --env "HUGGING_FACE_HUB_TOKEN=<secret>"  -p 23333:23333  --ipc=host openmmlab/lmdeploy:latest  lmdeploy serve api_server internlm/internlm2-chat-20b-4bits

### Reproduction

docker run --runtime nvidia --gpus all   -v ~/.cache/huggingface:/root/.cache/huggingface   --env "HUGGING_FACE_HUB_TOKEN=<secret>"  -p 23333:23333  --ipc=host openmmlab/lmdeploy:latest  lmdeploy serve api_server internlm/internlm2-chat-20b-4bits

### Environment

```Shell
win10+docker+w*3090
```

### Error traceback

```Shell
报错信息如下:

=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.12 (build 50109463)
Triton Server Version 2.29.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

2024-02-28 12:15:41,906 - lmdeploy - WARNING - Best matched chat template name: internlm2-chat-20b
2024-02-28 12:15:42,071 - lmdeploy - WARNING - model_source: hf_model
/opt/py38/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Fetching 18 files: 100%|██████████| 18/18 [00:00<00:00, 197637.36it/s]
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 11, in <module>
    load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')()
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 252, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1007, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 68, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 145, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 426, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 195, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 312, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "/opt/lmdeploy/lmdeploy/turbomind/deploy/target_model/fp.py", line 26, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/opt/lmdeploy/lmdeploy/turbomind/deploy/target_model/base.py", line 141, in __init__
    self.cfg = self.get_config(cfg)
  File "/opt/lmdeploy/lmdeploy/turbomind/deploy/target_model/fp.py", line 38, in get_config
    w1, _, _ = bin.ffn(i)
  File "/opt/lmdeploy/lmdeploy/turbomind/deploy/source_model/internlm2.py", line 64, in ffn
    return self._ffn(i, 'weight')
  File "/opt/lmdeploy/lmdeploy/turbomind/deploy/source_model/internlm2.py", line 58, in _ffn
    tensor = self.params[f'model.layers.{i}.feed_forward.{key}.{kind}']
KeyError: 'model.layers.0.feed_forward.w1.weight'
```

**Comment by rainbownmm** [comment]
期待您的回答，感谢

**Comment by irexyc** [comment]
报错的原因是因为起server的时候少了 `--model-format awq`

不过加上之后应该推理时应该会卡住。原因是windows上的docker环境似乎跟linux还是有区别，这两个地方需要用windows同步的方式。

https://github.com/InternLM/lmdeploy/blob/7f943a26b69b1e8f80aecb0a660b15eb5719b7b5/src/turbomind/kernels/bert_preprocess_kernels.cu#L71-L75

https://github.com/InternLM/lmdeploy/blob/4c9959f6b95e20f0a4a0a45c21d168ee7b568dc9/src/turbomind/kernels/stop_criteria_kernels.cu#L154-L158

上周有验证这个问题的时候编过一个包，你可以试试。也可以参照修改这里，然后参考docs/zh_cn/build.md 这个文档编译代码。

https://1drv.ms/u/s!Aqis6w3rjKXSjgKiEomX1Ej-tgo7?e=HijWha

**Comment by lvhan028** [comment]
close it since no more activities over 2 weeks. Feel free to reopen it if it is still an issue

**Comment by NB-Group** [comment]
``` shell 
(MOSS_2.0) D:\AI_model>lmdeploy chat turbomind ./internlm2-chat-20b-4bits
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin, please note cuda version should >= 11.3 when compiled with cuda 11
2024-06-07 22:02:57,937 - lmdeploy - WARNING - The sub command `lmdeploy chat turbomind` will be deprecated in future. Please use `lmdeploy chat` instead.
2024-06-07 22:02:57,940 - lmdeploy - WARNING - model_source: hf_model
2024-06-07 22:02:57,940 - lmdeploy - WARNING - kwargs cache_block_seq_len is deprecated to initialize model, use TurbomindEngineConfig instead.
2024-06-07 22:02:57,941 - lmdeploy - WARNING - kwargs cache_max_entry_count is deprecated to initialize model, use TurbomindEngineConfig instead.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\software\Anaconda3\envs\MOSS_2.0\Scripts\lmdeploy.exe\__main__.py", line 7, in <module>
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\cli\entrypoint.py", line 37, in run
    args.run(args)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\cli\chat.py", line 131, in turbomind
    main(**kwargs)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\chat.py", line 74, in main
    tm_model = tm.TurboMind.from_pretrained(
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 387, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 161, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 270, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\fp.py", line 26, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\base.py", line 156, in __init__
    self.cfg = self.get_config(cfg)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\target_model\fp.py", line 38, in get_config
    w1, _, _ = bin.ffn(i)
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\source_model\internlm2.py", line 69, in ffn
    return self._ffn(i, 'weight')
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\deploy\source_model\internlm2.py", line 62, in _ffn
    tensor = self.params[
KeyError: 'model.layers.0.feed_forward.w1.weight'
```

该问题在最新版本仍然存在

**Comment by lvhan028** [comment]
@NB-Group 增加选项 --model-format awq，再试试看呢？

**Comment by NB-Group** [comment]
加上就好了
