### ISSUE TITLE
'.bf16' requires .target sm_80 or higher

### ISSUE THREAD

**Issue by zqszqszqstvt** [InternLM/lmdeploy#1266]
**GPU:**`v100-5xm2-116GB * 2`
**This is the code:**`from lmdeploy import pipeline, GenerationConfig, PytorchEngineConfig

backend_config = PytorchEngineConfig(session_len=2048, tp=2)
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = pipeline('internlm/internlm-chat-7b',
                backend_config=backend_config)
prompts = [[{
    'role': 'user',
    'content': 'Hi, pls intro yourself'
}], [{
    'role': 'user',
    'content': 'Shanghai is'
}]]
response = pipe(prompts, gen_config=gen_config)
print(response)`
**This is the running log:**`/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.2+cu121)
    Python  3.9.18 (you have 3.9.17)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.2+cu121)
    Python  3.9.18 (you have 3.9.17)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
You shouldn't move a model when it is dispatched on multiple devices.
2024-03-09 16:18:06,952 - lmdeploy - INFO - distribute model parameters.
2024-03-09 16:18:46,198 - lmdeploy - INFO - build CacheEngine with config:CacheConfig(block_size=64, num_cpu_blocks=256, num_gpu_blocks=63, cache_max_entry_count=0.2)
2024-03-09 16:18:47,901 - lmdeploy - ERROR - Rank[0] failed.
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 867, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 831, in _tp_model_loop
    output = model_forward(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 334, in model_forward
    output = patched_model.patched_forward(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 239, in __call__
    output = self._model(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ls/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 686, in forward
    outputs = self.model(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 470, in forward
    return self._continuous_batching_forward_7b(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 349, in _continuous_batching_forward_7b
    layer_outputs = decoder_layer(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ls/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 87, in forward
    return self._contiguous_batching_forward(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 142, in _contiguous_batching_forward
    query_states, key_states, value_states = _rotary_emb_fn(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 131, in _rotary_emb_fn
    query_states, key_states = apply_rotary_pos_emb(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/kernels/apply_rotary_pos_emb.py", line 165, in apply_rotary_pos_emb
    apply_rotary_pos_emb_qk_kernel[grid](q,
  File "<string>", line 63, in apply_rotary_pos_emb_qk_kernel
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/triton/compiler/compiler.py", line 476, in compile
    next_module = compile_kernel(module)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/triton/compiler/compiler.py", line 351, in <lambda>
    lambda src: ptx_to_cubin(src, arch))
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/triton/compiler/compiler.py", line 150, in ptx_to_cubin
    return compile_ptx_to_cubin(ptx, ptxas, arch)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/compile-ptx-src-74ccbe, line 344; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 344; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 348; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 348; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 352; error   : Feature '.bf16' requires .target sm_80 or higher
.........
ptxas /tmp/compile-ptx-src-74ccbe, line 1103; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1107; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1107; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1111; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1111; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1115; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1115; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1119; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-74ccbe, line 1119; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas fatal   : Ptx assembly aborted due to errors

2024-03-09 16:18:47,925 - lmdeploy - ERROR - Rank[1] failed.
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 867, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 831, in _tp_model_loop
    output = model_forward(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 334, in model_forward
    output = patched_model.patched_forward(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 239, in __call__
    output = self._model(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ls/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 686, in forward
    outputs = self.model(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 470, in forward
    return self._continuous_batching_forward_7b(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 349, in _continuous_batching_forward_7b
    layer_outputs = decoder_layer(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ls/.cache/huggingface/modules/transformers_modules/Baichuan2-7B-Chat/modeling_baichuan.py", line 273, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 87, in forward
    return self._contiguous_batching_forward(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 142, in _contiguous_batching_forward
    query_states, key_states, value_states = _rotary_emb_fn(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/baichuan.py", line 131, in _rotary_emb_fn
    query_states, key_states = apply_rotary_pos_emb(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/kernels/apply_rotary_pos_emb.py", line 165, in apply_rotary_pos_emb
    apply_rotary_pos_emb_qk_kernel[grid](q,
  File "<string>", line 63, in apply_rotary_pos_emb_qk_kernel
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/triton/compiler/compiler.py", line 476, in compile
    next_module = compile_kernel(module)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/triton/compiler/compiler.py", line 351, in <lambda>
    lambda src: ptx_to_cubin(src, arch))
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/triton/compiler/compiler.py", line 150, in ptx_to_cubin
    return compile_ptx_to_cubin(ptx, ptxas, arch)
RuntimeError: Internal Triton PTX codegen error: 
ptxas /tmp/compile-ptx-src-b5bf24, line 344; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 344; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 348; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 348; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 352; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 352; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 356; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 356; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 360; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 360; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 364; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 364; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 368; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 368; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 372; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 372; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 376; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 376; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 380; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 380; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 384; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 384; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 388; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 388; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 392; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 392; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 396; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 396; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 400; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 400; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 404; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 404; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 409; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 409; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 413; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 413; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 417; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 417; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 421; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 421; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 425; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 425; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 429; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 429; error   : Feature '.bf16' requires .target sm_80 or higher
......
ptxas /tmp/compile-ptx-src-b5bf24, line 1095; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1099; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1099; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1103; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1103; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1107; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1107; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1111; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1111; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1115; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1115; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1119; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas /tmp/compile-ptx-src-b5bf24, line 1119; error   : Feature '.bf16' requires .target sm_80 or higher
ptxas fatal   : Ptx assembly aborted due to errors

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 857, in loop
    step_tokens: Dict[int, InferOutput] = self.step(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 649, in step
    output = self._model_forward(inputs,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 622, in _model_forward
    return __forward(inputs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 564, in __forward
    return self.model_agent.forward(inputs,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1005, in forward
    resp: TPResponse = _queue_get_response(self.tp_model_out_que,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 893, in _queue_get_response
    __check_context_alive()
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 886, in __check_context_alive
    raise RuntimeError(f'Rank[{idx}] failed.')
RuntimeError: Rank[0] failed.
2024-03-09 16:18:51,432 - lmdeploy - ERROR - Engine main loop stopped.
`
May I ask if anyone has a similar question? What are the solutions?Thank you!

**Comment by zqszqszqstvt** [comment]
python=3.9
cuda 12.2
torch=2.1.0

**Comment by grimoire** [comment]
V100 does not support bf16.

**Comment by zqszqszqstvt** [comment]
> V100 does not support bf16.↳

那有办法在v100-sxm2-16GB上运行吗？或者RTX2080ti

**Comment by grimoire** [comment]
Or you can change the `torch_dtype` in the config.json of your model. But I do not guarantee that will works

**Comment by zqszqszqstvt** [comment]
> 或者您可以更改`torch_dtype`模型的 config.json 中的 。但我不保证会起作用↳

好的  我试试

**Comment by zqszqszqstvt** [comment]
谢谢你 我改成float16成功了

**Comment by happyday-lkj** [comment]
T4卡是不是也不支持啊
