### ISSUE TITLE
[Bug] Pytorch引擎部署Baichuan2-7B，输出为空

### ISSUE THREAD

**Issue by lzq603** [InternLM/lmdeploy#1273]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

我尝试部署百川2-7B，模型没有输出：
```python
from lmdeploy.messages import PytorchEngineConfig
from lmdeploy.pytorch.engine.engine import Engine
from lmdeploy import GenerationConfig
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

adapters = {
    'zwrz': '/root/LLaMA-Efficient-Tuning/saves/Baichuan2-7B-Chat/lora/2024-03-12-09-28-59_self'
}
# adapters = {
#     'zwrz': '/root/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-03-12-10-39-24_zwrz'
# }
if __name__ == '__main__':

    tokenizer = AutoTokenizer.from_pretrained("/root/autodl-tmp/baichuan-inc/Baichuan2-7B-Chat", use_fast=False, trust_remote_code=True)

    engine_config = PytorchEngineConfig(session_len=256, tp=2, adapters=adapters)

    # engine = Engine.from_pretrained('/root/autodl-tmp/baichuan-inc/Baichuan2-13B-Chat', engine_config=engine_config, trust_remote_code=True)
    engine = Engine.from_pretrained('/root/autodl-tmp/baichuan-inc/Baichuan2-7B-Chat', engine_config=engine_config, trust_remote_code=True)

    generator = engine.create_instance()
    gen_config = GenerationConfig(top_p=0.8,
                                    top_k=40,
                                    temperature=0.8,
                                    max_new_tokens=1024)
    prompt = '你好啊？'
    input_ids = tokenizer(prompt, return_tensors='pt')['input_ids']
    print(input_ids)
    for outputs in generator.stream_infer(session_id=1, input_ids=input_ids, gen_config=gen_config):
        print(outputs[1])
        print(tokenizer.decode(outputs[1], skip_special_tokens=True))
```
![微信截图_20240312120848](https://github.com/InternLM/lmdeploy/assets/30162988/4cd9f299-ac71-42ca-98af-edb019ac0f6f)

### Reproduction

使用autodl服务器，配置3张4090，在命令行执行上述代码
python test_bc.py

### Environment

```Shell
- 操作系统：Ubuntu 20.04
- GPU：RTX 4090(24GB) * 3
- python：3.9.18
- pytorch：2.1.2
- lmdeploy：0.2.4
```

### Error traceback

```Shell
(aichat) root@autodl-container-1cfb4c801e-375de8dd:~# python test_bc.py
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-03-12 11:52:28,705 - lmdeploy - INFO - Checking environment for PyTorch Engine.
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.80s/it]
2024-03-12 11:52:40,996 - lmdeploy - INFO - load adapter <zwrz> from "/root/LLaMA-Efficient-Tuning/saves/Baichuan2-7B-Chat/lora/2024-03-12-09-28-59_self".
You shouldn't move a model when it is dispatched on multiple devices.
2024-03-12 11:52:41,132 - lmdeploy - INFO - distribute model parameters.
2024-03-12 11:52:46,008 - lmdeploy - WARNING - infered block size: 8
2024-03-12 11:52:46,174 - lmdeploy - INFO - build CacheEngine with config:CacheConfig(block_size=8, num_cpu_blocks=2048, num_gpu_blocks=5763, cache_max_entry_count=0.8)
2024-03-12 11:52:47,733 - lmdeploy - INFO - tp paging adapters.
tensor([[16829, 93488,    68]])
[]

/root/miniconda3/envs/aichat/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
(aichat) root@autodl-container-1cfb4c801e-375de8dd:~#
```

**Comment by lzq603** [comment]
[2024-03-12-09-28-59_self.zip](https://github.com/InternLM/lmdeploy/files/14570383/2024-03-12-09-28-59_self.zip)
这是我训练后的lora权重

**Comment by grimoire** [comment]
下不下来。你试过最新的 lmdeploy 吗

**Comment by lzq603** [comment]
> 下不下来。你试过最新的 lmdeploy 吗

试过，最新的会报错
(aichat) root@autodl-container-b07c47a3b9-526801f2:~# python test_bc.py
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-03-14 09:34:45,443 - lmdeploy - INFO - Checking environment for PyTorch Engine.
2024-03-14 09:34:45,566 - lmdeploy - INFO - Checking model.
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
2024-03-14 09:34:49,834 - lmdeploy - ERROR - rank[0] failed with error: __init__() got an unexpected keyword argument 'use_dora'
2024-03-14 09:34:49,844 - lmdeploy - ERROR - rank[1] failed with error: __init__() got an unexpected keyword argument 'use_dora'
2024-03-14 09:34:49,996 - lmdeploy - ERROR - Rank[1] failed.
2024-03-14 09:34:49,996 - lmdeploy - ERROR - Rank[0] failed.
Traceback (most recent call last):
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 952, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 890, in _tp_model_loop
    patched_model, cache_engine = _tp_build_model(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 767, in _tp_build_model
    resp.raise_error(RuntimeError('failed to init model.'))
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 602, in raise_error
    raise err
TypeError: __init__() got an unexpected keyword argument 'use_dora'
Traceback (most recent call last):
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 952, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 890, in _tp_model_loop
    patched_model, cache_engine = _tp_build_model(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 767, in _tp_build_model
    resp.raise_error(RuntimeError('failed to init model.'))
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 602, in raise_error
    raise err
TypeError: __init__() got an unexpected keyword argument 'use_dora'
2024-03-14 09:34:49,997 - lmdeploy - ERROR - Init tp model failed with error: [TypeError("__init__() got an unexpected keyword argument 'use_dora'"), TypeError("__init__() got an unexpected keyword argument 'use_dora'")]
Traceback (most recent call last):
  File "/root/test_bc.py", line 20, in <module>
    engine = Engine.from_pretrained('/root/autodl-tmp/baichuan-inc/Baichuan2-7B-Chat', engine_config=engine_config, trust_remote_code=True)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 247, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 193, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 438, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1151, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1026, in __init__
    self.patch_model_tp(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1085, in patch_model_tp
    raise next(err for err in resp.error if err is not None)
TypeError: __init__() got an unexpected keyword argument 'use_dora'

**Comment by grimoire** [comment]
> TypeError: init() got an unexpected keyword argument 'use_dora'

你的 adapter 用 0.8.2 的 peft load 会失败，可能是因为用的更高的版本训练的。我们目前没有试过更高版本的
https://github.com/InternLM/lmdeploy/blob/e7b2833441be6a4ac374ec191001ba6ae97647e0/requirements/runtime.txt#L5

把会引起失败的 key 删了以后就成功了

**Comment by lzq603** [comment]
感谢，可以了
