### ISSUE TITLE
[QA] liuhaotian/llava-v1.5-7b cannot find a default match chat template. Can we support a default chat template in for this model?

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#1319]
### Motivation

Can we support a default chat template in for this model?

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/__w/lmdeploy/lmdeploy/autotest/utils/pipeline_chat.py", line 134, in run_pipeline_vl_chat_test
    pipe = pipeline(hf_path, backend_config=backend_config)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/api.py", line 86, in pipeline
    return pipeline_class(model_path,
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/vl_async_engine.py", line 18, in __init__
    raise RuntimeError(
RuntimeError: please specify chat template as guided in https://lmdeploy.readthedocs.io/en/latest/inference/vl_pipeline.html#set-chat-template
```

**Comment by lvhan028** [comment]
set `model_name` being `vicuna`
https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/vl_pipeline.md#set-chat-template
