### ISSUE TITLE
[Feature] Can you ignore the model name of the OpenAI API, or allow us to set "fake" model names?

### ISSUE THREAD

**Issue by StarCycle** [InternLM/lmdeploy#1338]
### Motivation

Hello,

There is a client program which calls different types of opanai models, like "gpt-3.5-turbo" and "gpt-4-turbo". Now I want to use local llm instead of openai models and I **cannot modify the source code of the client program**.

Thus, is it possible to use LMDeploy and a local llm (e.g., internlm2) to mimic a fake "gpt-3.5-turbo"? For example, when I call
```
response = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": test_prompt  
            }
        ],
        model="gpt-3.5-turbo", # It's a fake name of the model, I actually use internlm instead of gpt-3.5
        stream=True 
    )
```
I am actually using the local llm.

I guess there are 2 possible ways:

1. Simply disable the model name check. Whatever model name I call, I actually use the same local llm.
2. Allow us to set fake names of the local llm, i.e., a single local llm has different names like "internlm",  "gpt-3.5-turbo" and "gpt-4-turbo".

**Comment by lvhan028** [comment]
model_name can be obtained from API
please refer to https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving/api_server.md#integrate-with-openai

**Comment by StarCycle** [comment]
Hello @lvhan028,

Yes I can get the model_name from model_name = client.models.list().data[0].id.

But I want to **CHANGE** the model_name, instead of just **obtain** the model_name. I need to change it because I cannot modify the source code of the client program.

How to **change** the model_name?

Best,
Starcycle

**Comment by lvhan028** [comment]
@AllentDan any idea?

**Comment by AllentDan** [comment]
Basically, it is not allowed to change the model name since it should be readable only. But there are still methods that meet your needs.

One way, change https://github.com/InternLM/lmdeploy/blob/f43d099724bb6c8203cc241df87cc0611cd2ad05/lmdeploy/serve/openai/api_server.py#L81 to `return ['your_name']`

Another method, pass a json chat template with your own name and template following [doc](https://lmdeploy.readthedocs.io/en/latest/advance/chat_template.html).

**Comment by StarCycle** [comment]
The first approach does not work.

If I `return ['your_name']`, I will get this error:

```
2024-03-27 10:50:05,571 - lmdeploy - ERROR - Engine loop failed with error: 'NoneType' object has no attribute 'is_actived'
Traceback (most recent call last):
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 17, in _raise_exception_on_finish
    task.result()
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 977, in async_loop
    InferOutput] = await self.async_step(
  File "/workspace/lmdeploy/lmdeploy/utils.py", line 246, in __tmp
    return (await func(*args, **kwargs))
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 719, in async_step
    schedule_output = self.scheduler.schedule(is_prefill=is_prefill)
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/scheduler.py", line 281, in schedule
    output = self._schedule_prefill()
  File "/workspace/lmdeploy/lmdeploy/utils.py", line 236, in __func_warpper
    return func(*args, **kwargs)
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/scheduler.py", line 188, in _schedule_prefill
    if not block_manager.can_allocate(seq):
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/block_manager/default_block_manager.py", line 58, in can_allocate
    num_required_blocks += self.num_required_blocks(adapter)
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/block_manager/default_block_manager.py", line 37, in num_required_blocks
    if obj.is_actived():
AttributeError: 'NoneType' object has no attribute 'is_actived'
ERROR:    Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 249, in stream_response
    async for chunk in self.body_iterator:
  File "/workspace/lmdeploy/lmdeploy/serve/openai/api_server.py", line 371, in completion_stream_generator
    async for res in result_generator:
  File "/workspace/lmdeploy/lmdeploy/serve/async_engine.py", line 581, in generate
    async for outputs in generator.async_stream_infer(
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 1053, in async_stream_infer
    resp = await self.req_sender.async_recv(req_id)
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 320, in async_recv
    resp: Response = await self._async_resp_get()
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 190, in _async_resp_get
    return await __no_threadsafe_get()
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 175, in __no_threadsafe_get
    exit(1)
  File "/opt/conda/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 743, in lifespan
    await receive()
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/opt/conda/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 264, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 237, in listen_for_disconnect
    message = await receive()
  File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "/opt/conda/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/opt/conda/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 257, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/opt/conda/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.BaseExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/conda/lib/python3.10/asyncio/runners.py", line 44, in run
    |     return loop.run_until_complete(main)
    |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    |     self.run_forever()
    |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    |     self._run_once()
    |   File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    |     handle._run()
    |   File "/opt/conda/lib/python3.10/asyncio/events.py", line 80, in _run
    |     self._context.run(self._callback, *self._args)
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 260, in wrap
    |     await func()
    |   File "/opt/conda/lib/python3.10/site-packages/starlette/responses.py", line 249, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/workspace/lmdeploy/lmdeploy/serve/openai/api_server.py", line 371, in completion_stream_generator
    |     async for res in result_generator:
    |   File "/workspace/lmdeploy/lmdeploy/serve/async_engine.py", line 581, in generate
    |     async for outputs in generator.async_stream_infer(
    |   File "/workspace/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 1053, in async_stream_infer
    |     resp = await self.req_sender.async_recv(req_id)
    |   File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 320, in async_recv
    |     resp: Response = await self._async_resp_get()
    |   File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 190, in _async_resp_get
    |     return await __no_threadsafe_get()
    |   File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 175, in __no_threadsafe_get
    |     exit(1)
    |   File "/opt/conda/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    |     raise SystemExit(code)
    | SystemExit: 1
    +------------------------------------
Future exception was never retrieved
future: <Future finished exception=AttributeError("'NoneType' object has no attribute 'is_actived'")>
Traceback (most recent call last):
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/request.py", line 17, in _raise_exception_on_finish
    task.result()
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 977, in async_loop
    InferOutput] = await self.async_step(
  File "/workspace/lmdeploy/lmdeploy/utils.py", line 246, in __tmp
    return (await func(*args, **kwargs))
  File "/workspace/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 719, in async_step
    schedule_output = self.scheduler.schedule(is_prefill=is_prefill)
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/scheduler.py", line 281, in schedule
    output = self._schedule_prefill()
  File "/workspace/lmdeploy/lmdeploy/utils.py", line 236, in __func_warpper
    return func(*args, **kwargs)
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/scheduler.py", line 188, in _schedule_prefill
    if not block_manager.can_allocate(seq):
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/block_manager/default_block_manager.py", line 58, in can_allocate
    num_required_blocks += self.num_required_blocks(adapter)
  File "/workspace/lmdeploy/lmdeploy/pytorch/paging/block_manager/default_block_manager.py", line 37, in num_required_blocks
    if obj.is_actived():
AttributeError: 'NoneType' object has no attribute 'is_actived'
```

The second approach works for gpt-4-turbo. I can set the template.json as
```
{
    "model_name": "gpt-4-turbo",
    "system": "<|im_start|>system\n",
    "user": "<|im_start|>user\n",
    "assistant": "<|im_start|>assistant\n",
    "eosys": "<|im_end|>\n",
    "eoh": "<|im_end|>\n",
    "eoa": "<|im_end|>",
    "separator": "\n",
    "stop_words": ["<|im_end|>", "<|action_end|>"]
}
```
And then run 
```
lmdeploy serve api_server internlm/internlm2-chat-7b --server-port 23333 --chat-template template.json
```
However, if you want to mimic a gpt3.5, then the model_name 'gpt-3.5-turbo' will always be splitted into 'gpt-3' and '5-turbo' by mmengine:

https://github.com/open-mmlab/mmengine/blob/2c4516c62294964065d058d98799402f50afdef6/mmengine/registry/registry.py#L198

Any idea to solve it? @AllentDan @lvhan028
