### ISSUE TITLE
[Bug] Pytorch引擎启动Baichuan2-13B-Chat服务，一段时间后卡死，重新启动报错RuntimeError: Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]

### ISSUE THREAD

**Issue by lzq603** [InternLM/lmdeploy#1362]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy serve api_server --backend pytorch --tp 2 --cache-max-entry-count 0.2 /media/ls/graph_data/baichuan-inc/Baichuan2-13B-Chat --adapters fgzx=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_fgzx jiucuo=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_jiucuo labels=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_labels rs=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_rs xs=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_xs

### Reproduction

报错

### Environment

```Shell
- 操作系统：Ubuntu 23.04
- GPU：RTX 4090(24GB) * 2
- python：3.9.17
- pytorch：2.1.0
```

### Error traceback

```Shell
ls@ls-System-Product-Name:~$ lmdeploy serve api_server --backend pytorch --tp 2 --cache-max-entry-count 0.2 /media/ls/graph_data/baichuan-inc/Baichuan2-13B-Chat --adapters fgzx=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_fgzx jiucuo=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_jiucuo labels=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_labels rs=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_rs xs=/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_xs
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.2+cu121)
    Python  3.9.18 (you have 3.9.17)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.2+cu121)
    Python  3.9.18 (you have 3.9.17)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
Loading checkpoint shards: 100%|██████████████████| 6/6 [00:00<00:00,  7.24it/s]
2024-03-27 16:09:35,646 - lmdeploy - INFO - load adapter <fgzx> from "/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_fgzx".
2024-03-27 16:09:35,706 - lmdeploy - INFO - load adapter <jiucuo> from "/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_jiucuo".
2024-03-27 16:09:35,763 - lmdeploy - INFO - load adapter <labels> from "/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_labels".
2024-03-27 16:09:35,814 - lmdeploy - INFO - load adapter <rs> from "/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_rs".
2024-03-27 16:09:35,865 - lmdeploy - INFO - load adapter <xs> from "/home/ls/LLaMA-Efficient-Tuning/saves/Baichuan2-13B-Chat/lora/2024-01-26-16-42-49_xs".
2024-03-27 16:09:35,988 - lmdeploy - INFO - distribute model parameters.
2024-03-27 16:10:13,305 - lmdeploy - WARNING - infered block size: 8
2024-03-27 16:10:13,588 - lmdeploy - INFO - build CacheEngine with config:CacheConfig(block_size=8, num_cpu_blocks=1310, num_gpu_blocks=-56, window_size=-1, cache_max_entry_count=0.2, max_prefill_token_num=4096)
2024-03-27 16:10:13,605 - lmdeploy - ERROR - rank[0] failed with error: Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]
2024-03-27 16:10:13,605 - lmdeploy - ERROR - rank[1] failed with error: Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]
2024-03-27 16:10:13,605 - lmdeploy - ERROR - Rank[1] failed.
2024-03-27 16:10:13,605 - lmdeploy - ERROR - Rank[0] failed.
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 970, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 908, in _tp_model_loop
    patched_model, cache_engine = _tp_build_model(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 785, in _tp_build_model
    resp.raise_error(RuntimeError('failed to init model.'))
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 620, in raise_error
    raise err
Traceback (most recent call last):
RuntimeError: Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 970, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 908, in _tp_model_loop
    patched_model, cache_engine = _tp_build_model(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 785, in _tp_build_model
    resp.raise_error(RuntimeError('failed to init model.'))
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 620, in raise_error
    raise err
RuntimeError: Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]
2024-03-27 16:10:13,606 - lmdeploy - ERROR - Init tp model failed with error: [RuntimeError('Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]'), RuntimeError('Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]')]
Traceback (most recent call last):
  File "/home/ls/anaconda3/envs/aichat/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/cli/serve.py", line 275, in api_server
    run_api_server(args.model_path,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/openai/api_server.py", line 1054, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 144, in __init__
    self._build_pytorch(model_path=model_path,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 209, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 195, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 456, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1169, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1044, in __init__
    self.patch_model_tp(model_path,
  File "/home/ls/anaconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1103, in patch_model_tp
    raise next(err for err in resp.error if err is not None)
RuntimeError: Trying to create tensor with negative dimension -56: [-56, 8, 20, 128]
```

**Comment by grimoire** [comment]
try use small `max_prefill_token_num`

**Comment by grimoire** [comment]
or try this branch.

**Comment by lvhan028** [comment]
> or try this branch.

link is missed

**Comment by grimoire** [comment]
https://github.com/InternLM/lmdeploy/pull/1373 Note that you might need to enlarge `--cache-max-entry-count`
