### ISSUE TITLE
[Bug] 8*A800 lmdeploy load Qwen1.5-72B-Chat get RuntimeError: Rank[0] failed.

### ISSUE THREAD

**Issue by ThunderingII** [InternLM/lmdeploy#1366]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

load Qwen1.5 get an error: 
RuntimeError: Rank[0] failed. 
codes:
``` python
import lmdeploy
from lmdeploy import pipeline, GenerationConfig, PytorchEngineConfig,TurbomindEngineConfig

backend_config = PytorchEngineConfig(tp=8)
# backend_config = TurbomindEngineConfig(tp=2)
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = lmdeploy.pipeline("./Qwen1.5-72B-Chat",backend_config = backend_config)
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    return pipeline_class(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 194, in __init__
    self._build_pytorch(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 259, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 195, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 456, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1169, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1044, in __init__
    self.patch_model_tp(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1081, in patch_model_tp
    self.mp_context = mp.spawn(
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 193, in start_processes
    process.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.9/runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "t.py", line 10, in <module>
    pipe = lmdeploy.pipeline("./Qwen1.5-72B-Chat",backend_config = backend_config)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/api.py", line 86, in pipeline
    return pipeline_class(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 194, in __init__
    self._build_pytorch(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 259, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 195, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 456, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1169, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1044, in __init__
    self.patch_model_tp(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1081, in patch_model_tp
    self.mp_context = mp.spawn(
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/usr/local/lib/python3.9/dist-packages/torch/multiprocessing/spawn.py", line 193, in start_processes
    process.start()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 993, in _queue_get_response
    return que.get(timeout=interval)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 10, in <module>
    pipe = lmdeploy.pipeline("./Qwen1.5-72B-Chat",backend_config = backend_config)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/api.py", line 86, in pipeline
    return pipeline_class(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 194, in __init__
    self._build_pytorch(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 259, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 195, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 456, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1169, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1044, in __init__
    self.patch_model_tp(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1100, in patch_model_tp
    resp: TPResponse = _queue_get_response(out_que, self.mp_context)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 995, in _queue_get_response
    _check_context_alive(mp_context)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 983, in _check_context_alive
    raise RuntimeError(f'Rank[{idx}] failed.')
RuntimeError: Rank[0] failed.

```

### Reproduction

``` python
import lmdeploy
from lmdeploy import pipeline, GenerationConfig, PytorchEngineConfig,TurbomindEngineConfig

backend_config = PytorchEngineConfig(tp=8)
# backend_config = TurbomindEngineConfig(tp=2)
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = lmdeploy.pipeline("./Qwen1.5-72B-Chat",backend_config = backend_config)
response = pipe(["Hi, pls intro yourself", "Shanghai is"])
print(response)
```

### Environment

```Shell
sys.platform: linux
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A800-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: x86_64-linux-gnu-gcc (Debian 10.2.1-6) 10.2.1 20210110
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0+cu121
LMDeploy: 0.2.6+
transformers: 4.38.1
gradio: Not Found
fastapi: 0.110.0
pydantic: 2.6.4
```

**Comment by grimoire** [comment]
Please put the script inside `if __name__ == '__main__'`

**Comment by ThunderingII** [comment]
use cmd to load the model, get the same error
``` bash
lmdeploy serve api_server --tp 8 --backend pytorch ./Qwen1.5-72B-Chat
```

```
lmdeploy serve api_server --tp 8 --backend pytorch ./Qwen1.5-72B-Chat
[W socket.cpp:436] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
[W socket.cpp:436] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
[E socket.cpp:472] [c10d] The server socket has failed to listen on any local network address.
2024-03-29 14:01:16,679 - lmdeploy - ERROR - Rank[0] failed.
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 965, in _start_tp_process
    dist.init_process_group('nccl', rank=rank, world_size=world_size)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/distributed_c10d.py", line 1141, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/rendezvous.py", line 241, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/rendezvous.py", line 172, in _create_c10d_store
    return TCPStore(
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use). The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
Traceback (most recent call last):
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 993, in _queue_get_response
    return que.get(timeout=interval)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tiger/.local/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/cli/serve.py", line 272, in api_server
    run_api_server(args.model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/openai/api_server.py", line 1041, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 194, in __init__
    self._build_pytorch(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 259, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 195, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 456, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1169, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1044, in __init__
    self.patch_model_tp(model_path,
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1100, in patch_model_tp
    resp: TPResponse = _queue_get_response(out_que, self.mp_context)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 995, in _queue_get_response
    _check_context_alive(mp_context)
  File "/home/tiger/.local/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 983, in _check_context_alive
    raise RuntimeError(f'Rank[{idx}] failed.')
RuntimeError: Rank[0] failed.
```

**Comment by ThunderingII** [comment]
> Please put the script inside `if __name__ == '__main__'`



> Please put the script inside `if __name__ == '__main__'`

use cmd to load the model, get the same error

**Comment by grimoire** [comment]
> use cmd to load the model, get the same error
> 
> ```shell
> lmdeploy serve api_server --tp 8 --backend pytorch ./Qwen1.5-72B-Chat
> ```
> 
> ```
> lmdeploy serve api_server --tp 8 --backend pytorch ./Qwen1.5-72B-Chat
> [W socket.cpp:436] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
> [W socket.cpp:436] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
> ```

Not the same error. your port 29500 has been used.

**Comment by ThunderingII** [comment]
> > use cmd to load the model, get the same error
> > ```shell
> > lmdeploy serve api_server --tp 8 --backend pytorch ./Qwen1.5-72B-Chat
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > lmdeploy serve api_server --tp 8 --backend pytorch ./Qwen1.5-72B-Chat
> > [W socket.cpp:436] [c10d] The server socket has failed to bind to [::]:29500 (errno: 98 - Address already in use).
> > [W socket.cpp:436] [c10d] The server socket has failed to bind to 0.0.0.0:29500 (errno: 98 - Address already in use).
> > ```
> 
> Not the same error. your port 29500 has been used.

no process use this port, when restart the machine, the same error  will appear


run cmd to check if this port has been used

``` bash
sudo netstat -nlp | grep 29500

<Trial worker_0> resources $
```

**Comment by ThunderingII** [comment]
我怀疑是监听网卡的问题，但是不知道书生启动服务器 如何指定监听网卡或者 ip

**Comment by grimoire** [comment]
Try this pr https://github.com/InternLM/lmdeploy/pull/1345/files if you want to custom master addr and port.

**Comment by ThunderingII** [comment]
> Try this pr https://github.com/InternLM/lmdeploy/pull/1345/files if you want to custom master addr and port.

use '0.0.0.0' as addr
23333 as port

this make nosense

**Comment by ThunderingII** [comment]
。没有其他人遇到嘛

**Comment by zhulinJulia24** [comment]
> 29500

我这边是好的，可以试下自定义 https://github.com/InternLM/lmdeploy/pull/1345/files 自定义master_port 的功能

**Comment by ThunderingII** [comment]
> > 29500
> 
> 我这边是好的，可以试下自定义 https://github.com/InternLM/lmdeploy/pull/1345/files 自定义master_port 的功能

hello，我直接修改了         os.environ['MASTER_PORT'] = str(port) 这行，强制 指定  os.environ['MASTER_PORT'] = str("23333")

模型就启动了，感觉还是哪里有点问题，现在是 通过改代码来启动的，之前改环境变量不work，改代码work
