### ISSUE TITLE
[Bug] serve 加载 internlm-chat-7b的模型，有qwen的报错

### ISSUE THREAD

**Issue by chynphh** [InternLM/lmdeploy#1385]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

加载 internlm-chat-7b的模型，不知道怎么有qwen的报错
internlm-chat-7b经过awq量化

### Reproduction

```
>>> engine_config = TurbomindEngineConfig(model_format='awq', model_name='internlm-chat-7b')
>>> serve = serve(model_path, 'internlm-chat-7b', backend_config=engine_config)
2024-04-02 17:42:31,160 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name='internlm-chat-7b', model_format='awq', tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192)
2024-04-02 17:42:31,160 - lmdeploy - INFO - input chat_template_config=None
2024-04-02 17:42:31,259 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='internlm-chat-7b', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, capability=None)
2024-04-02 17:42:31,259 - lmdeploy - WARNING - model_source: hf_model
2024-04-02 17:42:31,259 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
Process Process-2:
Traceback (most recent call last):
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1035, in serve
    VariableInterface.async_engine = AsyncEngine(
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 138, in __init__
    self._build_turbomind(model_path=model_path,
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 187, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 431, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 200, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 317, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 80, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 148, in __init__
    self.cfg = self.get_config(cfg)
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 92, in get_config
    w1s, _, _ = bin.ffn_scale(i)
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/qwen_awq.py", line 42, in ffn_scale
    return ensure_fp16orint32(self._ffn(i, 'scales'))
  File "/mnt/workspace/miniconda3/envs/py310llm/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/qwen.py", line 56, in _ffn
    tensor = self.params[f'transformer.h.{i}.mlp.{key}.{kind}']
KeyError: 'transformer.h.0.mlp.w2.scales'
```

### Environment

```Shell
ys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.3, V11.3.109
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.2  (built against CUDA 11.3)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

LMDeploy: 0.2.6+
transformers: 4.36.2
gradio: 3.50.2
fastapi: 0.110.0
pydantic: 2.5.3
```

**Comment by lvhan028** [comment]
可以把INFO日志打开，看看详情

**Comment by chynphh** [comment]
> 可以把INFO日志打开，看看详情

通过设置 log_level='INFO' 结果是一样的

```
serve = serve(model_path, 'internlm-chat-7b', backend_config=engine_config, log_level='INFO')
2024-04-02 18:50:35,013 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format='awq', tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192)
2024-04-02 18:50:35,013 - lmdeploy - INFO - input chat_template_config=None
2024-04-02 18:50:35,210 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='internlm-chat-7b', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-04-02 18:50:35,210 - lmdeploy - WARNING - model_source: hf_model

Process Process-3:
Traceback (most recent call last):
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1041, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/serve/vl_async_engine.py", line 16, in __init__
    super().__init__(model_path, **kwargs)
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 188, in __init__
    self._build_turbomind(model_path=model_path,
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 237, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 431, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 200, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 317, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 80, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 148, in __init__
    self.cfg = self.get_config(cfg)
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 92, in get_config
    w1s, _, _ = bin.ffn_scale(i)
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/qwen_awq.py", line 42, in ffn_scale
    return ensure_fp16orint32(self._ffn(i, 'scales'))
  File "/mnt/workspace/miniconda3/envs/xtuner/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/qwen.py", line 56, in _ffn
    tensor = self.params[f'transformer.h.{i}.mlp.{key}.{kind}']
KeyError: 'transformer.h.0.mlp.w2.scales'
```

**Comment by lvhan028** [comment]
model_path 中的config.json 内容贴上来看看？
