### ISSUE TITLE
[Bug] 更新0.4.0版本后，qwen1.5运行报错

### ISSUE THREAD

**Issue by Dingxiangxiang** [InternLM/lmdeploy#1487]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Traceback (most recent call last):
  File "/home/q1/dx/qwen15_test/lmdeploy_test.py", line 26, in <module>
    pipe = pipeline('/data/dx/Qwen1.5-32B-Chat-AWQ', # /home/q1/dx/qwen_accelerate/Qwen-72B-Chat-Int4
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/api.py", line 94, in pipeline
    return pipeline_class(model_path,
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 206, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 254, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 396, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 170, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 279, in _from_hf
    output_model = OUTPUT_MODELS.get(output_format)(
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 26, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 155, in __init__
    self.cfg = self.get_config(cfg)
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 38, in get_config
    w1, _, _ = bin.ffn(i)
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 106, in ffn
    return self._ffn(i, 'weight')
  File "/home/q1/anaconda3/envs/dx_lmdeploy_qwen15/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 99, in _ffn
    tensor = self.params[
KeyError: 'model.layers.0.mlp.gate_proj.weight'

### Reproduction

from lmdeploy import pipeline
import time
pipe = pipeline('/data/dx/Qwen1.5-32B-Chat-AWQ')
t0 = time.time()
response = pipe(['你好啊,'])
t1 = time.time()
print(response[0].text)
print(t1-t0)
print(len(response[0].text)/(t1-t0))

### Environment

```Shell
lmdeploy==0.4.0
```

**Comment by Dingxiangxiang** [comment]
![7a49ca96e544ecbc3fd8e1eb26de64e](https://github.com/InternLM/lmdeploy/assets/34124232/d16a7d30-89b7-43f4-966a-c41237102dce)

**Comment by irexyc** [comment]
我觉得之前也会报错的。

试下增加一个参数 `--model-format awq`

**Comment by Dingxiangxiang** [comment]
> 我觉得之前也会报错的。
> 
> 试下增加一个参数 `--model-format awq`

试了的一样报错

**Comment by Dingxiangxiang** [comment]
> Hi @Dingxiangxiang You may try this
> 
> ```shell
> # https://huggingface.co/Qwen/Qwen1.5-32B-Chat
> 
> # convert
> python3 -m lmdeploy lite auto_awq /workdir/Qwen1.5-32B-Chat --calib-dataset 'wikitext2' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir /workdir/Qwen1.5-32B-Chat-AWQ
> 
> # server
> python3 -m lmdeploy serve api_server /workdir/Qwen1.5-32B-Chat-AWQ
> 
> # client
> python3 benchmark/profile_restful_api.py --server_addr 127.0.0.1:23333 --tokenizer_path /workdir/Qwen1.5-32B-Chat --dataset /workdir/ShareGPT_V3_unfiltered_cleaned_split.json --concurrency 128 --num_prompts 1000
> ```

好了，可以运行了，非常感谢！！！

**Comment by renmada** [comment]
转AWQ的时候64g内存不够怎么办
```python3 -m lmdeploy lite auto_awq /workdir/Qwen1.5-32B-Chat --calib-dataset 'wikitext2' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir /workdir/Qwen1.5-32B-Chat-AWQ
```

**Comment by lvhan028** [comment]
> 转AWQ的时候64g内存不够怎么办
> 
> ```
> python3 -m lmdeploy lite auto_awq /workdir/Qwen1.5-32B-Chat --calib-dataset 'wikitext2' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir /workdir/Qwen1.5-32B-Chat-AWQ
> ```

@AllentDan @pppppM
