### ISSUE TITLE
[Bug] qwen-32b-awq 报错

### ISSUE THREAD

**Issue by renmada** [InternLM/lmdeploy#1517]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

报错信息
```
2024-04-29 13:01:58,599 - lmdeploy - WARNING - get 771 model params
Convert to turbomind format:   0%|                                                                                    | 0/64 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/torch3/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/cli/entrypoint.py", line 37, in run
    args.run(args)
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/cli/cli.py", line 249, in chat
    run_chat(**kwargs)
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/chat.py", line 74, in main
    tm_model = tm.TurboMind.from_pretrained(
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 396, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 170, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 305, in _from_hf
    output_model.export()
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 273, in export
    self.export_transformer_block(bin, i)
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 127, in export_transformer_block
    self.save_split(qkv_sz, f'layers.{i}.attention.w_qkv.scales_zeros', -1)
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 251, in save_split
    self.export_weight(split, f'{prefix}.{i}{ext}')
  File "/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 229, in export_weight
    tm_tensor.copy_from(torch_tensor)
RuntimeError: [TM][ERROR]  Assertion fail: /lmdeploy/src/turbomind/python/bind.cpp:294 
```

### Reproduction

启动命令
```
lmdeploy chat /home/ps/.cache/modelscope/hub/qwen/Qwen1___5-32B-Chat-AWQ/ --model-format awq
```

### Environment

```Shell
/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/ps/anaconda3/envs/torch3/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
sys.platform: linux
Python: 3.9.19 (main, Mar 21 2024, 17:11:28) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.6, V11.6.55
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.4.1  (built against CUDA 11.6)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.15.1+cu118
LMDeploy: 0.4.0+
transformers: 4.38.2
gradio: 3.50.2
fastapi: 0.110.2
pydantic: 2.7.1
triton: 2.2.0
```
```


### Error traceback

_No response_

**Comment by renmada** [comment]
另外请教怎么用代码加载这个模型

**Comment by zhyncs** [comment]
ref https://github.com/InternLM/lmdeploy/issues/1487#issuecomment-2075039723
