### ISSUE TITLE
[Bug] qwen1.5-14b-awq服务部署error

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#1532]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用lmdeploy lite auto_awq生成awq模型；
然后使用tp=2部署服务，会出现如下error:

2024-04-30 08:57:04,150 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format='awq', tp=2, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, quant_policy=8, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192)
2024-04-30 08:57:04,150 - lmdeploy - INFO - input chat_template_config=ChatTemplateConfig(model_name=None, system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability='chat', stop_words=None)
2024-04-30 08:57:04,150 - lmdeploy - INFO - matched chat template name: qwen
2024-04-30 08:57:05,750 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='qwen', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability='chat', stop_words=None)
2024-04-30 08:57:05,750 - lmdeploy - WARNING - model_source: hf_model
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 26, in run
    args.run(args)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/cli/serve.py", line 284, in api_server
    run_api_server(args.model_path,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 1056, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 200, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 248, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 385, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 168, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 272, in _from_hf
    input_model = INPUT_MODELS.get(inferred_model_format)(
TypeError: 'NoneType' object is not callable

### Reproduction

lmdeploy serve api_server ../pretrained-models/qwen1.5-14b-chat-w4-lmdeploy/ --backend turbomind --model-format awq --log-level INFO --tp 2 --quant-policy 8

### Environment

```Shell
使用docker镜像：0.4.0
```

**Comment by Vincent131499** [comment]
tp=1部署服务运行正常

**Comment by Vincent131499** [comment]
please help!

**Comment by lvhan028** [comment]
assert tensor.shape[split_dim] % tp == 0

量化参数的tensor shape不能被tp整除，无法tp

**Comment by shikimoon** [comment]
> assert tensor.shape[split_dim] % tp == 0
> 
> 量化参数的tensor shape不能被tp整除，无法tp

碰到同样的问题了。请问要怎么解决呢

**Comment by lvhan028** [comment]
现在还没有解决
