### ISSUE TITLE
[Bug] lmdeploy doesn't support OpenGVLab/InternVL-Chat-V1-5-Int8

### ISSUE THREAD

**Issue by mattate** [InternLM/lmdeploy#1570]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy works great on OpenGVLab/InternVL-Chat-V1-5, but does not work with in quantized version OpenGVLab/InternVL-Chat-V1-5-Int8, it looks like it only supports the int16 version. The same machine can run OpenGVLab/InternVL-Chat-V1-5-Int8 via code without any issue.

### Reproduction

﻿lmdeploy serve api_server OpenGVLab/InternVL-Chat-V1-5-Int8 --tp 4 --quant-policy 8

### Environment

```Shell
sys.platform: linux
Python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5: NVIDIA GeForce RTX 3090
CUDA_HOME: None
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.0+cu121
LMDeploy: 0.4.1+
transformers: 4.40.2
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.7.1
triton: 2.3.0
```

### Error traceback

```Shell
Convert to turbomind format:   0%|                                                                                                                                                             | 0/48 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/aicore/anaconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/cli/entrypoint.py", line 37, in run
    args.run(args)
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/cli/serve.py", line 283, in api_server
    run_api_server(args.model_path,
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/openai/api_server.py", line 1191, in serve
    VariableInterface.async_engine = pipeline_class(
                                     ^^^^^^^^^^^^^^^
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/vl_async_engine.py", line 17, in __init__
    super().__init__(model_path, **kwargs)
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 206, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 254, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/turbomind.py", line 396, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/turbomind.py", line 170, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/turbomind.py", line 305, in _from_hf
    output_model.export()
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 273, in export
    self.export_transformer_block(bin, i)
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 60, in export_transformer_block
    self.save_split(qkv_w, f'layers.{i}.attention.w_qkv.weight', -1)
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 251, in save_split
    self.export_weight(split, f'{prefix}.{i}{ext}')
  File "/home/aicore/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 218, in export_weight
    assert torch_tensor.dtype in [
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by BIGBALLON** [comment]
InternVL-Chat-V1-5-Int8 is currently not supported.
Please check issue https://github.com/InternLM/lmdeploy/issues/1555 and this [answer](https://github.com/InternLM/lmdeploy/issues/1555)

**Comment by lvhan028** [comment]
Close since @BIGBALLON offered the answer.
