### ISSUE TITLE
[Feature] ModuleNotFoundError: No module named 'timm' with Internal Vision model

### ISSUE THREAD

**Issue by pseudotensor** [InternLM/lmdeploy#1672]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

```
docker run -d --restart=always --runtime nvidia --gpus '"device=6"' \
    -v $HOME/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
    -p 23333:23333 \
    --ipc=host \
    openmmlab/lmdeploy:latest \
    lmdeploy serve api_server OpenGVLab/InternVL-Chat-V1-5
```

```
Fetching 33 files: 100%|??????????| 33/33 [00:55<00:00,  1.69s/it]
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 11, in <module>
    load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')()
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 37, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 303, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1191, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 20, in __init__
    self.vl_encoder = ImageEncoder(model_path, vision_config)
  File "/opt/lmdeploy/lmdeploy/vl/engine.py", line 69, in __init__
    self.model = load_vl_model(model_path)
  File "/opt/lmdeploy/lmdeploy/vl/model/builder.py", line 42, in load_vl_model
    return InternVLVisionModel(model_path, with_llm)
  File "/opt/lmdeploy/lmdeploy/vl/model/internvl.py", line 83, in __init__
    self.build_model()
  File "/opt/lmdeploy/lmdeploy/vl/model/internvl.py", line 93, in build_model
    model = AutoModel.from_config(config, trust_remote_code=True)
  File "/opt/py38/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 428, in from_config
    model_class = get_class_from_dynamic_module(class_ref, repo_id, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 510, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module)
  File "/opt/py38/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 208, in get_class_in_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.cache/huggingface/modules/transformers_modules/fdc2259adb05898e81e9095757c8dde7b7c31470/modeling_internvl_chat.py", line 20, in <module>
    from .modeling_intern_vit import InternVisionModel
  File "/root/.cache/huggingface/modules/transformers_modules/fdc2259adb05898e81e9095757c8dde7b7c31470/modeling_intern_vit.py", line 12, in <module>
    from timm.models.layers import DropPath
ModuleNotFoundError: No module named 'timm'

```

### Reproduction

above

### Environment

```Shell
docker

Digest: sha256:c2439c09f2432c72f99cfec814a91fbaa6f5d16d93ee1869a07109d37a9ab402
Status: Downloaded newer image for openmmlab/lmdeploy:latest
```

Latest image pulled just minute ago.

### Error traceback

```Shell
above
```

**Comment by pseudotensor** [comment]
I guess this is normal problem, that I should build my own model-specific image?  Given the size of the image already, seems should be already in the image.

```
Each model may require specific dependencies not included in the Docker image. If you run into issues, you may need to install those yourself on a case-by-case basis. If in doubt, refer to the specific model’s project for documentation.

For example, for Llava:

FROM openmmlab/lmdeploy:latest

RUN apt-get update && apt-get install -y python3 python3-pip git

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install timm
RUN pip3 install git+https://github.com/haotian-liu/LLaVA.git --no-deps

COPY . .

CMD ["lmdeploy", "serve", "api_server", "liuhaotian/llava-v1.6-34b"]
```

**Comment by lvhan028** [comment]
Yes. we recommend users build model-specific images by themselves
Please refer to the following guide for an explanation
https://lmdeploy.readthedocs.io/en/latest/serving/api_server_vl.html#option-2-deploying-with-docker
