### ISSUE TITLE
[Feature] support for MiniCPM-Llama3-V 2.5

### ISSUE THREAD

**Issue by LRHstudy** [InternLM/lmdeploy#1693]
### Motivation

a relatively lightweight, but the effect is very good multimodal model
https://github.com/OpenBMB/MiniCPM-V

**Comment by irexyc** [comment]
It looks like the structure is similar to llava, shoud support next week.

**Comment by HaoLiuHust** [comment]
Thanks for your work @irexyc , I have tried the PR, the quant step successed, but when load the mode, an error occured:
```
Traceback (most recent call last):
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/demo.py", line 4, in <module>
    pipe = pipeline('./MiniCPM-Llama3-V-2_5-4bit')
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/api.py", line 89, in pipeline
    return pipeline_class(model_path,
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 21, in __init__
    super().__init__(model_path, **kwargs)
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/serve/async_engine.py", line 206, in __init__
    self._build_pytorch(model_path=model_path,
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/serve/async_engine.py", line 268, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 135, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 610, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 1271, in build_model_agent
    model_agent = BaseModelAgent(model_path,
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 638, in __init__
    self.patched_model = self._build_model(
  File "/mnt/pai-storage-8/jieshen/code/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 657, in _build_model
    hf_model = AutoModelForCausalLM.from_pretrained(
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3640, in from_pretrained
    hf_quantizer.preprocess_model(
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/quantizers/base.py", line 182, in preprocess_model
    return self._process_model_before_weight_loading(model, **kwargs)
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/quantizers/quantizer_awq.py", line 85, in _process_model_before_weight_loading
    model, has_been_replaced = replace_with_awq_linear(
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/integrations/awq.py", line 178, in replace_with_awq_linear
    _, has_been_replaced = replace_with_awq_linear(
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/integrations/awq.py", line 178, in replace_with_awq_linear
    _, has_been_replaced = replace_with_awq_linear(
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/integrations/awq.py", line 178, in replace_with_awq_linear
    _, has_been_replaced = replace_with_awq_linear(
  [Previous line repeated 2 more times]
  File "/data/miniconda3/lib/python3.9/site-packages/transformers/integrations/awq.py", line 165, in replace_with_awq_linear
    model._modules[name] = target_cls(
  File "/data/miniconda3/lib/python3.9/site-packages/awq/modules/linear/gemm.py", line 101, in __init__
    assert self.in_features % self.group_size == 0
AssertionError
```
