### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named '_turbomind' loading llava Mistral 7B

### ISSUE THREAD

**Issue by Alexis-IMBERT** [InternLM/lmdeploy#1699]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

trying to do offline inference with liuhaotian/llava-v1.6-mistral-7b model and git No module named '_turbomind'

### Reproduction

Here the code : lmdeploy check_env
```python
from lmdeploy import TurbomindEngineConfig, pipeline
from lmdeploy.vl import load_image

pipe = pipeline(
    "liuhaotian/llava-v1.6-mistral-7b",
    backend_config=TurbomindEngineConfig(
        tp=1,
        model_format="hf",
        session_len=8192,
        cache_max_entry_count=0.1,
    ),
    log_level="INFO",
)
image = load_image(
    "https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg"
)
response = pipe(("describe this image", image))
print(response.text)

```

here the package installed
```shell
pip install git+https://github.com/InternLM/lmdeploy.git

pip install git+https://github.com/haotian-liu/LLaVA.git --no-deps
```

the lmdeploy librairy is at commit 7ee48ed006f022d9e9f55b7648d6c6fcf6fb49e3 at the moment when it was done

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA GeForce RTX 3090 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.4.2+c3999f3
transformers: 4.41.2
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.7.2
triton: 2.2.0
```

### Error traceback

```Shell
CUDA_VISIBLE_DEVICES=1 python test.py 
Fetching 15 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 20393.70it/s]
2024-05-31 16:18:25,815 - lmdeploy - INFO - Using turbomind engine
2024-05-31 16:18:26,711 - lmdeploy - INFO - CLIPVisionTower.load_model: openai/clip-vit-large-patch14-336
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
2024-05-31 16:18:26,997 - lmdeploy - INFO - CLIPVisionTower.load_model: openai/clip-vit-large-patch14-336
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2024-05-31 16:18:31,644 - lmdeploy - INFO - start ImageEncoder._forward_loop
2024-05-31 16:18:31,709 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format='hf', tp=1, session_len=8192, max_batch_size=128, cache_max_entry_count=0.1, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
2024-05-31 16:18:31,709 - lmdeploy - INFO - input chat_template_config=None
2024-05-31 16:18:31,717 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='mistral', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
Traceback (most recent call last):
  File "/home/users/.../test.py", line 4, in <module>
    pipe = pipeline(
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/api.py", line 94, in pipeline
    return pipeline_class(model_path,
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/serve/vl_async_engine.py", line 21, in __init__
    super().__init__(model_path, **kwargs)
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 200, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 246, in _build_turbomind
    from lmdeploy import turbomind as tm
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/turbomind/__init__.py", line 24, in <module>
    from .turbomind import TurboMind  # noqa: E402
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 23, in <module>
    from .deploy.converter import (get_model_format, supported_formats,
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/converter.py", line 15, in <module>
    from .target_model.base import OUTPUT_MODELS, TurbomindModelConfig
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/__init__.py", line 4, in <module>
    from .plora_w4 import TurbomindPloraW4Model  # noqa: F401
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/plora_w4.py", line 5, in <module>
    from .w4 import convert_s4, get_cuda_tensor, tp_m_s4, transpose_qk_s4
  File "/home/users/.../.virtualenvs/tmp-e2cc2f9775a45c7/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 17, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'
```

**Comment by lvhan028** [comment]
`liuhaotian/llava-v1.6-mistral-7b` hasn't been supported in v0.4.2.
It is supported in the latest main branch and must be built before installation. 
You may refer to the [build-from-source](https://lmdeploy.readthedocs.io/en/latest/build.html) guide for detailed information
