### ISSUE TITLE
[Bug] RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src/turbomind/models/llama/Barrier.h:20 

### ISSUE THREAD

**Issue by NB-Group** [InternLM/lmdeploy#1703]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

在 0.4.2 的 lmdeploy 中部署 Interlm-chat-int4 时报错：`[Bug] RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src/turbomind/models/llama/Barrier.h:20 `

另有以下几点：
1. 使用命令`lmdeploy chat turbomind ./workspace`能够正常运行
2. 报错所指向的`D:\a\lmdeploy\lmdeploy\src/turbomind/models/llama/Barrier.h:20`目录并不存在

### Reproduction
``` python
from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig

backend_config = TurbomindEngineConfig(tp=2)
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = pipeline('D:\AI_model\workspace',
                backend_config=backend_config)
prompts = [
    [{
    'role': 'user',
    'content': 'Hi, pls intro yourself'
}]
]
response = pipe(prompts,gen_config=gen_config)
print(response)
```

### Environment

```Shell
D:\AI_model>lmdeploy check_env
sys.platform: win32
Python: 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4
NVCC: Cuda compilation tools, release 12.4, V12.4.131
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.35.32217.1 版
GCC: n/a
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930151
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.8.1  (built against CUDA 12.0)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.8.1, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cpu
LMDeploy: 0.4.2+
transformers: 4.34.0
gradio: 3.41.0
fastapi: 0.111.0
pydantic: Not Found
triton: Not Found

D:\AI_model>lmdeploy chat turbomind ./workspace
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin, please note cuda version should >= 11.3 when compiled with cuda 11
2024-06-03 19:49:40,968 - lmdeploy - WARNING - The sub command `lmdeploy chat turbomind` will be deprecated in future. Please use `lmdeploy chat` instead.
2024-06-03 19:49:40,970 - lmdeploy - WARNING - model_source: workspace
2024-06-03 19:49:40,971 - lmdeploy - WARNING - kwargs cache_block_seq_len is deprecated to initialize model, use TurbomindEngineConfig instead.
2024-06-03 19:49:40,971 - lmdeploy - WARNING - kwargs cache_max_entry_count is deprecated to initialize model, use TurbomindEngineConfig instead.
2024-06-03 19:49:41,713 - lmdeploy - WARNING - model_config:

[llama]
model_name = internlm-chat
。。。
__initialised__ = True


2024-06-03 19:51:47,520 - lmdeploy - WARNING - Input chat template with model_name is None. Forcing to use internlm-chat
[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> 你好

<|System|>:You are an AI assistant whose name is InternLM (书生·浦语).
- InternLM (书生·浦语) is a conversational language model that is developed by Shanghai AI Laboratory (上海人工智能实验 室). It is designed to be helpful, honest, and harmless.
- InternLM (书生·浦语) can understand and communicate fluently in the language chosen by the user such as English and 中文.

<|User|>:你好
<|Bot|>: 2024-06-03 19:52:02,619 - lmdeploy - WARNING - kwargs ignore_eos is deprecated for inference, use GenerationConfig instead.
2024-06-03 19:52:02,619 - lmdeploy - WARNING - kwargs random_seed is deprecated for inference, use GenerationConfig instead.
你好！有什么我可以帮助你的吗？
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "E:\Code\Python\MOSS2.0\test\Interlm_test.py", line 8, in <module>
    pipe = pipeline('D:\AI_model\workspace',
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\api.py", line 94, in pipeline
    return pipeline_class(model_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\serve\async_engine.py", line 206, in __init__
    self._build_turbomind(model_path=model_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\serve\async_engine.py", line 253, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 388, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 154, in __init__
    self.model_comm = self._from_workspace(model_path=model_path,
  File "E:\software\Anaconda3\envs\MOSS_2.0\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 342, in _from_workspace
    model_comm = _tm.AbstractTransformerModel.create_llama_model(
RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src/turbomind/models/llama/Barrier.h:20
```

**Comment by NB-Group** [comment]
那么如何解决这个问题呢，感谢大佬回答

**Comment by NB-Group** [comment]
那么如何解决这个问题呢，感谢大佬回答

**Comment by irexyc** [comment]
> 那么如何解决这个问题呢，感谢大佬回答

如果要tp的话，可以试试wsl2或者用linux

**Comment by NB-Group** [comment]
哦，打扰了，我看到相关的参数了

**Comment by NB-Group** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/121747915/8d1286ca-5823-41ab-81a0-35233496e195)
emm，为什么Response text 会等于空字符串呢

**Comment by NB-Group** [comment]
@irexyc 我仍然使用这段代码
```python
from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig

backend_config = TurbomindEngineConfig(tp=2)
gen_config = GenerationConfig(top_p=0.8,
                              top_k=40,
                              temperature=0.8,
                              max_new_tokens=1024)
pipe = pipeline('D:\AI_model\workspace',
                backend_config=backend_config)
prompts = [
    [{
    'role': 'user',
    'content': 'Hi, pls intro yourself'
}]
]
response = pipe(prompts,gen_config=gen_config)
print(response)
```

但是Response text 会等于空字符串。
遂测试官方文档里的几种方式，都等于空字符串，这是为什么

**Comment by irexyc** [comment]
可以在创建pipeline的时候把log打开，然后把完整的log发上来。

`pipe = pipeline('D:\AI_model\workspace',
                backend_config=backend_config,
                log_level='INFO')`

**Comment by irexyc** [comment]
```
prompts = [
    [{
    'role': 'user',
    'content': 'Hi, pls intro yourself'
}]
]
response = pipe(prompts,gen_config=gen_config)
print(response)
```

需要运行的log

**Comment by NB-Group** [comment]
Add dll path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin, please note cuda version should >= 11.3 when compiled with cuda 11
2024-06-05 18:08:37,657 - lmdeploy - WARNING - D:\AI_model\workspace seems to be a turbomind workspace, which can only be ran with turbomind engine.
2024-06-05 18:08:37,658 - lmdeploy - INFO - Using turbomind engine
2024-06-05 18:08:37,659 - lmdeploy - INFO - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
2024-06-05 18:08:37,659 - lmdeploy - INFO - input chat_template_config=None
2024-06-05 18:08:37,988 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='internlm-chat', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-06-05 18:08:37,989 - lmdeploy - WARNING - model_source: workspace
2024-06-05 18:08:40,631 - lmdeploy - WARNING - model_config:

[llama]
model_name = internlm-chat
tensor_para_size = 1
head_num = 40
kv_head_num = 40
vocab_size = 103168
num_layer = 60
inter_size = 13824
norm_eps = 1e-06
attn_bias = 0
start_id = 1
end_id = 2
session_len = 2056
weight_type = int4
rotary_embedding = 128
rope_theta = 10000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 4
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = 1
enable_prefix_caching = False
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 0
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 
__initialised__ = True


[TM][INFO] Set logger level by INFO
[TM][WARNING] [LlamaTritonModel] `max_position_embeddings` is not set, default to 2048.
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 8224.
[TM][WARNING] [LlamaTritonModel] `num_tokens_per_iter` is not set, default to `max_context_token_num` (8224).
[TM][INFO] Barrier(1)
[TM][INFO] Set logger level by INFO
2024-06-05 18:11:25,328 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[TM][INFO] Set logger level by INFO
[WARNING] gemm_config.in is not found; using default GEMM algo
[TM][INFO] NCCL group_id = 0
[TM][INFO] [BlockManager] block_size = 75 MB
[TM][INFO] [BlockManager] max_block_count = 118
[TM][INFO] [BlockManager] chunk_size = 1
[TM][INFO] LlamaBatch<T>::Start()
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
[TM][INFO] Set logger level by INFO
2024-06-05 18:11:25,929 - lmdeploy - INFO - prompt='<|System|>:You are an AI assistant whose name is InternLM (书生·浦语).\n- InternLM (书生·浦语) is a conversational language model that is developed by Shanghai AI Laboratory (上海人工智能实验室). It is designed to be helpful, honest, and harmless.\n- InternLM (书生·浦语) can understand and communicate fluently in the language chosen by the user such as English and 中文.\n\n<|User|>:Hi, pls intro yourself\n<|Bot|>:', gen_config=EngineGenerationConfig(n=1, max_new_tokens=1024, top_p=0.8, top_k=40, temperature=0.8, repetition_penalty=1.0, ignore_eos=False, random_seed=11750564137709924326, stop_words=[103028], bad_words=None, min_new_tokens=None, skip_special_tokens=True, logprobs=None), prompt_token_id=[1, 333, 352, 2472, 352, 27232, 2770, 657, 589, 15358, 17993, 6843, 963, 505, 4576, 11146, 451, 60614, 60381, 98666, 62412, 60735, 4452, 285, 4576, 11146, 451, 60614, 60381, 98666, 62412, 60735, 313, 505, 395, 7659, 1813, 4287, 1762, 560, 505, 8020, 684, 36956, 15358, 31288, 451, 67738, 75808, 70730, 699, 1226, 505, 6342, 442, 517, 11100, 328, 10894, 328, 454, 51978, 756, 285, 4576, 11146, 451, 60614, 60381, 98666, 62412, 60735, 313, 777, 3696, 454, 19187, 19829, 4563, 435, 410, 4287, 12032, 684, 410, 1341, 1893, 569, 6519, 454, 262, 68242, 512, 333, 352, 1621, 352, 27232, 13195, 328, 757, 269, 19876, 6286, 364, 333, 352, 23845, 352, 27232], adapter_name=None.
2024-06-05 18:11:25,929 - lmdeploy - INFO - session_id=0, history_tokens=0, input_tokens=110, max_new_tokens=1024, seq_start=True, seq_end=True, step=0, prep=True
2024-06-05 18:11:25,929 - lmdeploy - WARNING - run out of tokens. session_id=0
[Response(text='', generate_token_len=0, input_token_len=110, session_id=0, finish_reason='length', token_ids=[], logprobs=None)]
[TM][INFO] ~LlamaBatch()
[TM][INFO] Set logger level by INFO
[TM][INFO] [InternalThreadEntry] stop requested.
[TM][INFO] Set logger level by INFO
[TM][INFO] [OutputThreadEntry] stop requested.

**Comment by irexyc** [comment]
有一处逻辑估计有点问题。

目前的话，你把 workspace/triton_models/weights/config.ini 里面的max_position_embeddings 改成2048吧。

或者也可以不做模型转换，直接加载hf模型文件夹。

**Comment by NB-Group** [comment]
没问题了！谢谢你！

**Comment by lsl0901** [comment]
> 没问题了！谢谢你！
您好，我也遇到了相同的问题，模型下载到本地，用的最新的InterVL2-8B，请问您最终是怎么解决的

**Comment by NB-Group** [comment]
把 workspace/triton_models/weights/config.ini 里面的max_position_embeddings 改成2048 就行了
