### ISSUE TITLE
huggingface safetensor support

### ISSUE THREAD

**Issue by yuanze1024** [InternLM/lmdeploy#176]
I'm trying to deploy LLaMA2 70b chat model locally and find that this LMDeploy seems don't support huggingface safetensor ckpt.  It just raise a confusing Exception:
```python
Traceback (most recent call last):
  File "/opt/conda/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/workspace/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 592, in <module>
    fire.Fire(main)
  File "/opt/conda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 562, in main
    res = deploy_hf(model_name, model_path, tokenizer_path,
  File "/workspace/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 482, in deploy_hf
    assert num_layer == i, f'miss matched layers: {num_layer} vs {i}'
AssertionError: miss matched layers: 80 vs 0
```
because it only read *.bin:
https://github.com/InternLM/lmdeploy/blob/c1c1353dbdec4a2905a94dedba320c4a66d3511f/lmdeploy/serve/turbomind/deploy.py#L395

**Comment by lzhangzz** [comment]
We had a version that supports safetensors but it was removed.

For now you can modify `get_tensor_transposed` to call safetensors' `get_tensor` API and it will work.

**Comment by yuanze1024** [comment]
Hi @lzhangzz , thank you for your really fast reply.
Can you tell me more details? Maybe you still got the codes that are removed.

**Comment by yuanze1024** [comment]
So, I just followed your suggestion and add reading .safetensors code:
```python
    _files = [file for file in os.listdir(model_path) if file.endswith('.bin')]
    _params = {}
    if len(_files) == 0:
        _files = [file for file in os.listdir(model_path) if file.endswith('.safetensors')]
        _files = sorted(_files)
        print(_files)
        for _file in _files:
            with safetensors.safe_open(osp.join(model_path, _file), framework='pt', device='cpu') as f:
                _tmp = {}
                for k in f.keys():
                    _tmp[k] = f.get_tensor(k)
            _params.update(_tmp)
    else:
        _files = sorted(_files)
        print(_files)

        for _file in _files:
            _tmp = torch.load(osp.join(model_path, _file), map_location='cpu')
            _params.update(_tmp)
```
in place of 
https://github.com/InternLM/lmdeploy/blob/859658ebf9029f16073c98a66cdfdf4463c3a827/lmdeploy/serve/turbomind/deploy.py#L395-L402

And then, the ckpt was exported successfully (though I still need to check if it is right).
Anyway, thank you very much for your helping!

-----
BTW, should I make a PR? Because it seems you guys know this problem.
