### ISSUE TITLE
Error When loading 'openbmb/MiniCPM-Llama3-V-2_5'

### ISSUE THREAD

**Issue by Fahmie23** [InternLM/lmdeploy#1771]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

I try loading and make inference using the sample code given in the github examples directory. The model that i want to load is MiniCPM-Llama3-V-2_5. Could someone help me.

### Reproduction

from lmdeploy import pipeline
from lmdeploy.vl import load_image

pipe = pipeline('openbmb/MiniCPM-Llama3-V-2_5')

image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
response = pipe(('describe this image', image))
print(response)

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA A100 80GB PCIe
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.4.2+
transformers: 4.41.2
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.7.3
triton: 2.2.0
```

### Error traceback

```Shell
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[1], line 7
      4 pipe = pipeline('openbmb/MiniCPM-Llama3-V-2_5')
      6 image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
----> 7 response = pipe(('describe this image', image))
      8 print(response)

File ~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py:326, in AsyncEngine.__call__(self, prompts, gen_config, request_output_len, top_k, top_p, temperature, repetition_penalty, ignore_eos, do_preprocess, adapter_name, use_tqdm, **kwargs)
    318 if gen_config is None:
    319     gen_config = GenerationConfig(
    320         max_new_tokens=request_output_len,
    321         top_k=top_k,
   (...)
    324         repetition_penalty=repetition_penalty,
    325         ignore_eos=ignore_eos)
--> 326 return self.batch_infer(prompts,
    327                         gen_config=gen_config,
    328                         do_preprocess=do_preprocess,
    329                         adapter_name=adapter_name,
    330                         use_tqdm=use_tqdm,
    331                         **kwargs)

File ~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py:402, in AsyncEngine.batch_infer(self, prompts, gen_config, do_preprocess, adapter_name, use_tqdm, **kwargs)
    399 need_list_wrap = isinstance(prompts, str) or isinstance(
...
--> 402 assert isinstance(prompts, List), 'prompts should be a list'
    403 if gen_config is None:
    404     gen_config = GenerationConfig()

AssertionError: prompts should be a list
```

**Comment by irexyc** [comment]
How did you install LMDeploy? The version 0.4.2 doesn't support `openbmb/MiniCPM-Llama3-V-2_5`, you should build the latest code or copy the latest code to the installation folder.

**Comment by Fahmie23** [comment]
> How did you install LMDeploy? The version 0.4.2 doesn't support `openbmb/MiniCPM-Llama3-V-2_5`, you should build the latest code or copy the latest code to the installation folder.

i install using pip install lmdeploy.

**Comment by Fahmie23** [comment]
which version do i need to install. I thought version 0.4.2 is the latest version

**Comment by Fahmie23** [comment]
2024-06-13 07:19:06,357 - lmdeploy - ERROR - Engine loop failed with error: MiniCPMV.forward() missing 1 required positional argument: 'data'
Traceback (most recent call last):
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 17, in _raise_exception_on_finish
    task.result()
  File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 824, in async_loop
    await __step(True)
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 810, in __step
    raise e
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 802, in __step
    raise out
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 751, in _async_loop_background
    await self._async_step_background(
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 659, in _async_step_background
    output = await self._async_model_forward(inputs,
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/utils.py", line 250, in __tmp
    return (await func(*args, **kwargs))
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 576, in _async_model_forward
    return await __forward(inputs)
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 554, in __forward
    return await self.model_agent.async_forward(
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 735, in async_forward
...
    return self._call_impl(*args, **kwargs)
  File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: MiniCPMV.forward() missing 1 required positional argument: 'data'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?5f3149bb-9cf3-4717-84e8-0945cf7101c6) or open in a [text editor](command:workbench.action.openLargeOutput?5f3149bb-9cf3-4717-84e8-0945cf7101c6). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...
[/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/pygments/regexopt.py:77](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/pygments/regexopt.py:77): RuntimeWarning: coroutine 'AsyncEngine.batch_infer.<locals>.gather' was never awaited
  '|'.join(regex_opt_inner(list(group[1]), '')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
File /usr/lib/python3.10/asyncio/tasks.py:234, in Task.__step(***failed resolving arguments***)
    [233](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:233)     else:
--> [234](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:234)         result = coro.throw(exc)
    [235](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:235) except StopIteration as exc:

File /usr/lib/python3.10/asyncio/queues.py:159, in Queue.get(self)
    [158](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:158) try:
--> [159](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:159)     await getter
    [160](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:160) except:

File /usr/lib/python3.10/asyncio/futures.py:285, in Future.__await__(self)
    [284](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:284)     self._asyncio_future_blocking = True
--> [285](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:285)     yield self  # This tells Task to wait for completion.
    [286](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:286) if not self.done():

File /usr/lib/python3.10/asyncio/tasks.py:304, in Task.__wakeup(self, future)
    [303](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:303) try:
--> [304](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:304)     future.result()
    [305](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:305) except BaseException as exc:
    [306](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:306)     # This may also be a cancellation.

File /usr/lib/python3.10/asyncio/futures.py:196, in Future.result(self)
    [195](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:195)     exc = self._make_cancelled_error()
...
--> [178](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:178)         exit(1)
    [179](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:179)     continue
    [180](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:180) except Exception as e:

NameError: name 'exit' is not defined

**Comment by irexyc** [comment]
0.4.2 is the latest version published, but `openbmb/MiniCPM-Llama3-V-2_5` is added after that release. 

To use `openbmb/MiniCPM-Llama3-V-2_5`, you could use one of the following method.

- build LMDeploy yourself according to our [docs](https://lmdeploy.readthedocs.io/en/latest/build.html) 
- Use Githbu Action to build LMDeploy according to [this comments](https://github.com/InternLM/lmdeploy/issues/1495#issuecomment-2084828229)
- Install 0.4.2 and replace the installation file with latest file.

**Comment by Fahmie23** [comment]
i already git clone the repo. After that i got new error.  Below is the error:

2024-06-13 07:19:06,357 - lmdeploy - ERROR - Engine loop failed with error: MiniCPMV.forward() missing 1 required positional argument: 'data'
Traceback (most recent call last):
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 17, in _raise_exception_on_finish
task.result()
File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
raise self._exception.with_traceback(self._exception_tb)
File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
result = coro.send(None)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 824, in async_loop
await __step(True)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 810, in __step
raise e
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 802, in __step
raise out
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 751, in _async_loop_background
await self._async_step_background(
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 659, in _async_step_background
output = await self._async_model_forward(inputs,
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/utils.py", line 250, in __tmp
return (await func(*args, **kwargs))
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 576, in _async_model_forward
return await __forward(inputs)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 554, in __forward
return await self.model_agent.async_forward(
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 735, in async_forward
...
return self._call_impl(*args, **kwargs)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
TypeError: MiniCPMV.forward() missing 1 required positional argument: 'data'
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
[/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/pygments/regexopt.py:77](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/pygments/regexopt.py:77): RuntimeWarning: coroutine 'AsyncEngine.batch_infer..gather' was never awaited
'|'.join(regex_opt_inner(list(group[1]), '')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
CancelledError Traceback (most recent call last)
File /usr/lib/python3.10/asyncio/tasks.py:234, in Task.__step(failed resolving arguments)
[233](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:233) else:
--> [234](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:234) result = coro.throw(exc)
[235](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:235) except StopIteration as exc:

File /usr/lib/python3.10/asyncio/queues.py:159, in Queue.get(self)
[158](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:158) try:
--> [159](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:159) await getter
[160](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:160) except:

File /usr/lib/python3.10/asyncio/futures.py:285, in Future.await(self)
[284](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:284) self._asyncio_future_blocking = True
--> [285](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:285) yield self # This tells Task to wait for completion.
[286](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:286) if not self.done():

File /usr/lib/python3.10/asyncio/tasks.py:304, in Task.__wakeup(self, future)
[303](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:303) try:
--> [304](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:304) future.result()
[305](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:305) except BaseException as exc:
[306](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:306) # This may also be a cancellation.

File /usr/lib/python3.10/asyncio/futures.py:196, in Future.result(self)
[195](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:195) exc = self._make_cancelled_error()
...
--> [178](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:178) exit(1)
[179](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:179) continue
[180](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:180) except Exception as e:

NameError: name 'exit' is not defined

**Comment by irexyc** [comment]
Clone repo is not enougth. 

You should either build LMDeploy yourself (the first two methods) or copy the latest code to the installation folder (`/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy`).

**Comment by Fahmie23** [comment]
i already follow your step. After that i got new error. Can you help me. Below is the error:

2024-06-13 07:19:06,357 - lmdeploy - ERROR - Engine loop failed with error: MiniCPMV.forward() missing 1 required positional argument: 'data'
Traceback (most recent call last):
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 17, in _raise_exception_on_finish
task.result()
File "/usr/lib/python3.10/asyncio/futures.py", line 201, in result
raise self._exception.with_traceback(self._exception_tb)
File "/usr/lib/python3.10/asyncio/tasks.py", line 232, in __step
result = coro.send(None)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 824, in async_loop
await __step(True)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 810, in __step
raise e
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 802, in __step
raise out
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 751, in _async_loop_background
await self._async_step_background(
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 659, in _async_step_background
output = await self._async_model_forward(inputs,
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/utils.py", line 250, in __tmp
return (await func(*args, **kwargs))
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 576, in _async_model_forward
return await __forward(inputs)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 554, in __forward
return await self.model_agent.async_forward(
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 735, in async_forward
...
return self._call_impl(*args, **kwargs)
File "/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
return forward_call(*args, **kwargs)
TypeError: MiniCPMV.forward() missing 1 required positional argument: 'data'
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
[/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/pygments/regexopt.py:77](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/pygments/regexopt.py:77): RuntimeWarning: coroutine 'AsyncEngine.batch_infer..gather' was never awaited
'|'.join(regex_opt_inner(list(group[1]), '')
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
CancelledError Traceback (most recent call last)
File /usr/lib/python3.10/asyncio/tasks.py:234, in Task.__step(failed resolving arguments)
[233](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:233) else:
--> [234](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:234) result = coro.throw(exc)
[235](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:235) except StopIteration as exc:

File /usr/lib/python3.10/asyncio/queues.py:159, in Queue.get(self)
[158](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:158) try:
--> [159](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:159) await getter
[160](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/queues.py:160) except:

File /usr/lib/python3.10/asyncio/futures.py:285, in Future.await(self)
[284](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:284) self._asyncio_future_blocking = True
--> [285](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:285) yield self # This tells Task to wait for completion.
[286](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:286) if not self.done():

File /usr/lib/python3.10/asyncio/tasks.py:304, in Task.__wakeup(self, future)
[303](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:303) try:
--> [304](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:304) future.result()
[305](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:305) except BaseException as exc:
[306](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/tasks.py:306) # This may also be a cancellation.

File /usr/lib/python3.10/asyncio/futures.py:196, in Future.result(self)
[195](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/usr/lib/python3.10/asyncio/futures.py:195) exc = self._make_cancelled_error()
...
--> [178](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:178) exit(1)
[179](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:179) continue
[180](https://vscode-remote+ssh-002dremote-002b172-002e191-002e45-002e94.vscode-resource.vscode-cdn.net/home/mcmcssuserdata/fahmie/lm_deploy/~/fahmie/lm_deploy/lm_deploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py:180) except Exception as e:

NameError: name 'exit' is not defined

**Comment by QwertyJack** [comment]
You are using the pytorch backend. However, currently MiniCPM-V only works with turbomind backend.

**Comment by QwertyJack** [comment]
See also: https://lmdeploy.readthedocs.io/zh-cn/latest/api/pipeline.html

**Comment by irexyc** [comment]
> pipe = pipeline('openbmb/MiniCPM-Llama3-V-2_5')

@Fahmie23
If you replaced all files, the above code will use turobmind backend to init the pipeline, but according to your log, there are lines like `lmdeploy/pytorch/engine/engine.py` saying that you are actually using pytorch backend.

**Comment by Fahmie23** [comment]
can i know how can i get the latest code?

**Comment by irexyc** [comment]
Git clone will clone the latest code. 

But I have no way to know whether your correctly replaced the installation files. The log information is not right as pytorch backend should not be used.

So I suggest you to build LMDeploy with github action and install the built wheel package.

**Comment by AnyangAngus** [comment]
@irexyc  I run the MINICPMV-2,5 infer in lmdeploy successfully, Nice Work!
one question is that the model forward in lmdeploy is based on Fastertransfomer or pytorch ?

since there is a bug in the batch infer in Huggingface  modeling_minicpmv.py [https://huggingface.co/openbmb/MiniCPM-Llama3-V-2_5/discussions/29], so dose lmdeploy supports a correct batch infer?
Thank U!  ^_^

**Comment by irexyc** [comment]
@AnyangAngus 

Currently, the LLM part of INICPMV-2.5 only support `turbomind backend` which is developed based on Fastertransfomer. But in the last few versions, almost all kernels except for sampling have been rewritten.  And we support batch inference.

**Comment by irexyc** [comment]
@AnyangAngus 

For offline usage(pipeline api), you can refer to [this docs](https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/vl_pipeline.md#set-sampling-parameters) 
For servering, we provide openai-compatible api usage, you can refer to [this docs](https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving/api_server_vl.md)

**Comment by AnyangAngus** [comment]
> @AnyangAngus
> 
> For offline usage(pipeline api), you can refer to [this docs](https://github.com/InternLM/lmdeploy/blob/main/docs/en/inference/vl_pipeline.md#set-sampling-parameters) For servering, we provide openai-compatible api usage, you can refer to [this docs](https://github.com/InternLM/lmdeploy/blob/main/docs/en/serving/api_server_vl.md)

@irexyc 

As for minicpm offline usage pipeline api, I observe that the backend_config and VisionConfig do not go into effect
I reduce the cache_max_entry_count but the GPU memory still need 55G as the same as cache_max_entry_count=0.8
                backend_config = TurbomindEngineConfig(cache_max_entry_count=0.2)
                pipe = pipeline('/models/MiniCPM-Llama3-V-2_5', backend_config=backend_config))

I set the batch size try to reduce the GPU memory, but I still can infer batch items and the GPU memory dose not change.
             vision_config=VisionConfig(max_batch_size=1)
             pipe = pipeline('/models/MiniCPM-Llama3-V-2_5', vision_config=vision_config)

Is the way I passed the parameters incorrect？ 
and How can I pass this parameters to Minicpm2,5 correctly?
Many Thanks

**Comment by QwertyJack** [comment]
This issue has been identified and has been resolved through fix #1778.

**Comment by WANGSSSSSSS** [comment]
which branch should i use for suppoorting the minicpm-v-2.5?

**Comment by lvhan028** [comment]
the latest main
