### ISSUE TITLE
[Bug] awq for Qwen2-72B-instruct

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#1826]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

针对qwen2-72b-instruct这个模型，使用awq进行量化，尝试了很多设置，都会出现如下bug error,麻烦尽快check下啊，是不是我的使用方式有什么问题呢？

Move model.norm to GPU.
Move lm_head to CPU.
Loading calibrate dataset ...
Using the latest cached version of the module from /hpc_stor01/home/guangfeng.liu/.cache/huggingface/modules/datasets_modules/datasets/ptb_text_only/8d1b97746fb9765d140e569ec5ddd35e20af4d37761f5e1bf357ea0b081f2c1f (last modified on Fri Jun 21 07:15:40 2024) since it couldn't be found locally at ptb_text_only, or remotely on the Hugging Face Hub.
Using the latest cached version of the module from /hpc_stor01/home/guangfeng.liu/.cache/huggingface/modules/datasets_modules/datasets/ptb_text_only/8d1b97746fb9765d140e569ec5ddd35e20af4d37761f5e1bf357ea0b081f2c1f (last modified on Fri Jun 21 07:15:40 2024) since it couldn't be found locally at ptb_text_only, or remotely on the Hugging Face Hub.
Token indices sequence length is longer than the specified maximum sequence length for this model (1104485 > 131072). Running this sequence through the model will result in indexing errors
model.layers.0, samples: 8, max gpu memory: 8.22 GB
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 37, in run
    args.run(args)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/cli/lite.py", line 137, in auto_awq
    auto_awq(**kwargs)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/apis/auto_awq.py", line 96, in auto_awq
    vl_model, model, tokenizer, work_dir = calibrate(model,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/apis/calibrate.py", line 235, in calibrate
    calib_ctx.calibrate(all_data)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/quantization/calibration.py", line 315, in calibrate
    _ = model(data.to(self.device))
  File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1034, in forward
    layer_outputs = decoder_layer(
  File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/quantization/calibration.py", line 505, in _forward
    auto_scale_block(mod, batch_kwargs[i], self.w_bits,
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/quantization/calibration.py", line 416, in auto_scale_block
    _auto_get_scale(
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/quantization/calibration.py", line 400, in _auto_get_scale
    best_ratio = _search_module_scale(module2inspect, layers, inp.value,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/quantization/calibration.py", line 375, in _search_module_scale
    fc.weight.data = pseudo_quantize_tensor(
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/lite/quantization/awq.py", line 289, in pseudo_quantize_tensor
    assert torch.isnan(scales).sum() == 0
AssertionError

### Reproduction

尝试了以下3个配置，均error
1.lmdeploy lite auto_awq ../pretrained-models/qwen2-72b-instruct/ --calib-dataset 'ptb' --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir ../pretrained-models/qwen2-72b-instruct-w4-lmdeploy-new2/ --batch-size 1
2.lmdeploy lite auto_awq ../pretrained-models/qwen2-72b-instruct/ --calib-dataset 'ptb' --calib-samples 32 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir ../pretrained-models/qwen2-72b-instruct-w4-lmdeploy-new2/ --batch-size 1
3.lmdeploy lite auto_awq ../pretrained-models/qwen2-72b-instruct/ --calib-dataset 'ptb' --calib-samples 32 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir ../pretrained-models/qwen2-72b-instruct-w4-lmdeploy-new2/ --batch-size 1 --search-scale True

### Environment

```Shell
都是在docker-v0.4.2版本操作
```

**Comment by zhyncs** [comment]
@Vincent131499 If you want to just use Qwen2-72B-Instruct-AWQ, you may try https://huggingface.co/Qwen/Qwen2-72B-Instruct-AWQ This is out of the box :P

**Comment by serser** [comment]
Related to #1786

**Comment by Vincent131499** [comment]
> @Vincent131499 If you want to just use Qwen2-72B-Instruct-AWQ, you may try https://huggingface.co/Qwen/Qwen2-72B-Instruct-AWQ This is out of the box :P

直接读取官方awq是可以的，但是tp有问题。
tp=1正常推理
tp≥2转换到turbomind异常。
这个我用vllm验证了下，多卡推理正常。
是不是要优先解决下这个awq量化和awq多卡推理的bug，我看qwen2系列模型已经积攒了不少这一类的bug了，感谢！
@lvhan028 @AllentDan @zhyncs

**Comment by lvhan028** [comment]
抱歉，组内目前正在赶6月份的版本，这个问题我们会在7月份处理。

**Comment by Vincent131499** [comment]
> 抱歉，组内目前正在赶6月份的版本，这个问题我们会在7月份处理。
> 
> 

好的，等你们消息

**Comment by Xu-Chen** [comment]
> > @Vincent131499 If you want to just use Qwen2-72B-Instruct-AWQ, you may try https://huggingface.co/Qwen/Qwen2-72B-Instruct-AWQ This is out of the box :P
> 
> 直接读取官方awq是可以的，但是tp有问题。 tp=1正常推理 tp≥2转换到turbomind异常。 这个我用vllm验证了下，多卡推理正常。 是不是要优先解决下这个awq量化和awq多卡推理的bug，我看qwen2系列模型已经积攒了不少这一类的bug了，感谢！ @lvhan028 @AllentDan @zhyncs

主要是中间层隐藏纬度的问题，你会发现官方量化的版本，纬度是25696， 29696÷128=232，232可以被8整除，也就是最多应该可以tp8
而fp16原版是29568, 29568÷128=231,，已经不能被任何2的倍数整除了

自行把原版的fp16转化为25696的版本（补0，不知道影不影响效果），可以解决自行量化后无法tp的问题。

**Comment by Tendo33** [comment]
同问

**Comment by lvhan028** [comment]
@Vincent131499 麻烦贴一下 `lmdeploy check_env` 的结果，我们看下在哪个环境中可以复现

**Comment by Vincent131499** [comment]
> @Vincent131499 麻烦贴一下 `lmdeploy check_env` 的结果，我们看下在哪个环境中可以复现

pull的docker镜像：openmmlab/lmdeploy:v0.4.2
服务器：8卡A100
运行：在docker容器中运行量化相关命令

sys.platform: linux
Python: 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.0+cu118
LMDeploy: 0.4.2+6bb0b37
transformers: 4.41.1
gradio: 3.50.2
fastapi: 0.111.0
pydantic: 2.7.1
triton: 2.1.0

**Comment by AllentDan** [comment]
这个问题我用了 AutoAWQ 也有，本质是因为 Qwen2-72B-instruct 模型权重里有0. 的值，算 scale 时除以 0. 会得到 Nan。目前可以通过 clamp 到一个 min 规避。但是这样得到的量化是有偏的，可能会有精度问题。https://github.com/InternLM/lmdeploy/blob/a5aeee34142fef6a12fba53c09889d4a293572d0/lmdeploy/lite/quantization/calibration.py#L380 这里括号内的分母需要 clamp 下。

**Comment by AllentDan** [comment]
我试了下 https://github.com/InternLM/lmdeploy/pull/1844 量化 72B 模型，量化完可以正常对话

**Comment by Vincent131499** [comment]
> 我试了下 #1844 量化 72B 模型，量化完可以正常对话

@AllentDan 这个https://github.com/InternLM/lmdeploy/pull/1844使用的量化命令是啥呢，已经可以正常量化了是嘛？不会出现NaN-bug了？

**Comment by AllentDan** [comment]
按 PR 修改的内容自己修改本地代码，可以直接跑量化了，不会 NaN。

**Comment by Vincent131499** [comment]
> 按 PR 修改的内容自己修改本地代码，可以直接跑量化了，不会 NaN。

@AllentDan 你这边量化的命令是啥，我复现一下

**Comment by AllentDan** [comment]
默认的

**Comment by Vincent131499** [comment]
@AllentDan 我这边使用tp-4，还是不行：
lmdeploy serve api_server ../pretrained-models/qwen2-72b-instruct-w4-lmdeploy/ --backend turbomind --model-format awq --quant-policy 8 --tp 4  

Convert to turbomind format:   0%|                                                                                                                                                       | 0/80 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 37, in run
    args.run(args)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/cli/serve.py", line 303, in api_server
    run_api_server(args.model_path,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 1197, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 200, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 247, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 344, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 146, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 259, in _from_hf
    output_model.export()
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 283, in export
    self.export_transformer_block(bin, i)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 156, in export_transformer_block
    self.save_split(w2_sz, f'layers.{i}.feed_forward.w2.scales_zeros', 0)
  File "/opt/py38/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 256, in save_split
    assert tensor.shape[split_dim] % tp == 0
AssertionError

**Comment by AllentDan** [comment]
没说支持 tp 的事情，是说量化不报 NaN。

**Comment by Vincent131499** [comment]
@lvhan028 @AllentDan 请教下，目前qwen2-72b 多tp部署的问题解决进度咋样了呢

**Comment by wertyac** [comment]
我用lmdeploy，4卡部署，目前没有发现AWQ的问题，不过会出现重复回答的问题，出现频率有点高。
命令为：lmdeploy serve api_server ./Qwen2-72B-Instruct-AWQ --backend turbomind --model-format awq --tp 4 --server-port 8000 --session-len 32000 --quant-policy 8

##lmdeploy check_env
(lmdeploy) health@144server:/opt/model/ms$ lmdeploy check_env
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda-12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.7  (built against CUDA 12.2)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.1+
transformers: 4.42.4
gradio: 3.50.2
fastapi: 0.109.0
pydantic: 2.5.3
triton: 2.2.0
NVIDIA Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity
GPU0     X      PHB     SYS     SYS     0-19,40-59      0
GPU1    PHB      X      SYS     SYS     0-19,40-59      0
GPU2    SYS     SYS      X      PHB     20-39,60-79     1
GPU3    SYS     SYS     PHB      X      20-39,60-79     1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

**Comment by Xu-Chen** [comment]
> 我用lmdeploy，4卡部署，目前没有发现AWQ的问题，不过会出现重复回答的问题，出现频率有点高。 命令为：lmdeploy serve api_server ./Qwen2-72B-Instruct-AWQ --backend turbomind --model-format awq --tp 4 --server-port 8000 --session-len 32000 --quant-policy 8
> 
> ##lmdeploy check_env (lmdeploy) health@144server:/opt/model/ms$ lmdeploy check_env sys.platform: linux Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] CUDA available: True numpy_random_seed: 2147483648 GPU 0,1,2,3: NVIDIA GeForce RTX 3090 CUDA_HOME: /usr/local/cuda-12.1 NVCC: Cuda compilation tools, release 12.1, V12.1.105 GCC: gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0 PyTorch: 2.2.2+cu121 PyTorch compiling details: PyTorch built with:
> 
> * GCC 9.3
> * C++ Version: 201703
> * Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
> * Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
> * OpenMP 201511 (a.k.a. OpenMP 4.5)
> * LAPACK is enabled (usually provided by MKL)
> * NNPACK is enabled
> * CPU capability usage: AVX2
> * CUDA Runtime 12.1
> * NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
> * CuDNN 8.9.7  (built against CUDA 12.2)
>   
>   * Built with CuDNN 8.9.2
> * Magma 2.6.1
> * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,
> 
> TorchVision: 0.17.2+cu121 LMDeploy: 0.5.1+ transformers: 4.42.4 gradio: 3.50.2 fastapi: 0.109.0 pydantic: 2.5.3 triton: 2.2.0 NVIDIA Topology: GPU0 GPU1 GPU2 GPU3 CPU Affinity NUMA Affinity GPU0 X PHB SYS SYS 0-19,40-59 0 GPU1 PHB X SYS SYS 0-19,40-59 0 GPU2 SYS SYS X PHB 20-39,60-79 1 GPU3 SYS SYS PHB X 20-39,60-79 1
> 
> Legend:
> 
> X = Self SYS = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI) NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node PHB = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU) PXB = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge) PIX = Connection traversing at most a single PCIe bridge NV# = Connection traversing a bonded set of # NVLinks

这个大概率是模型本身的问题， gptq 也有这个问题，可以加惩罚参数

**Comment by wertyac** [comment]
> > 我用lmdeploy，4卡部署，目前没有发现AWQ的问题，不过会出现重复回答的问题，出现频率有点高。 命令为：lmdeploy serve api_server ./Qwen2-72B-Instruct-AWQ --backend turbomind --model-format awq --tp 4 --server-port 8000 --session-len 32000 --quant-policy 8
> > ##lmdeploy check_env (lmdeploy) health@144server:/opt/model/ms$ lmdeploy check_env sys.platform: linux Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] CUDA available: True numpy_random_seed: 2147483648 GPU 0,1,2,3: NVIDIA GeForce RTX 3090 CUDA_HOME: /usr/local/cuda-12.1 NVCC: Cuda compilation tools, release 12.1, V12.1.105 GCC: gcc (Ubuntu 12.2.0-3ubuntu1) 12.2.0 PyTorch: 2.2.2+cu121 PyTorch compiling details: PyTorch built with:
> > 
> > * GCC 9.3
> > * C++ Version: 201703
> > * Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
> > * Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
> > * OpenMP 201511 (a.k.a. OpenMP 4.5)
> > * LAPACK is enabled (usually provided by MKL)
> > * NNPACK is enabled
> > * CPU capability usage: AVX2
> > * CUDA Runtime 12.1
> > * NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
> > * CuDNN 8.9.7  (built against CUDA 12.2)
> >   
> >   * Built with CuDNN 8.9.2
> > * Magma 2.6.1
> > * Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,
> > 
> > TorchVision: 0.17.2+cu121 LMDeploy: 0.5.1+ transformers: 4.42.4 gradio: 3.50.2 fastapi: 0.109.0 pydantic: 2.5.3 triton: 2.2.0 NVIDIA Topology: GPU0 GPU1 GPU2 GPU3 CPU Affinity NUMA Affinity GPU0 X PHB SYS SYS 0-19,40-59 0 GPU1 PHB X SYS SYS 0-19,40-59 0 GPU2 SYS SYS X PHB 20-39,60-79 1 GPU3 SYS SYS PHB X 20-39,60-79 1
> > Legend:
> > X = Self SYS = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI) NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node PHB = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU) PXB = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge) PIX = Connection traversing at most a single PCIe bridge NV# = Connection traversing a bonded set of # NVLinks
> 
> 这个大概率是模型本身的问题， gptq 也有这个问题，可以加惩罚参数

我增加了惩罚参数：
     frequency_penalty: 0  #这个测试设置成别的值会乱输出
     presence_penalty: 0 #这个也是会导致乱输出
     repetition_penalty: 1.1 #按照文档只要是1.1就是有惩罚的，但是效果不明显。

**Comment by Xu-Chen** [comment]
试试
presence_penalty: 0.5

**Comment by AllentDan** [comment]
> 试试 presence_penalty: 0.5

lmdeploy 的 turbomind 不支持这个参数哈。repetition_penalty=1.02 试试

**Comment by wertyac** [comment]
> > 试试 presence_penalty: 0.5
> 
> lmdeploy 的 turbomind 不支持这个参数哈。repetition_penalty=1.02 试试

按照文档说明的话repetition_penalty为1.1才有惩罚效果，其它的反而不行吧。

**Comment by zhyncs** [comment]
May you try the latest release to check if the issue is resolved? https://github.com/InternLM/lmdeploy/releases/tag/v0.6.0a0
