### ISSUE TITLE
[Bug] pytorch方式多卡部署internlm-xcomposer2-vl-7b，报错KeyError: 'parameter name can\'t contain "."'

### ISSUE THREAD

**Issue by zhaoning1987** [InternLM/lmdeploy#1834]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用openmmlab/lmdeploy:latest镜像（或pip install lmdeploy，或源码运行），启动openai api server，在4张T4卡上尝试部署internlm-xcomposer2-vl-7b，在pytorch模式下会报错，turbomind模式下可以运行

### Reproduction

lmdeploy serve api_server /models/internlm-xcomposer2-vl-7b/ --tp 4 --backend pytorch

其中/models/internlm-xcomposer2-vl-7b/是本地目录，从https://huggingface.co/internlm/internlm-xcomposer2-vl-7b下载

### Environment

```Shell
sys.platform: linux
Python: 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.1.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

TorchVision: 0.16.0+cu118
LMDeploy: 0.4.2+eb3125a
transformers: 4.41.2
gradio: 3.50.2
fastapi: 0.111.0
pydantic: 2.7.4
triton: 2.1.0
```

### Error traceback

```Shell
2024-06-24 07:20:34,582 - lmdeploy - ERROR - Rank[2] failed.
Traceback (most recent call last):
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 990, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 935, in _tp_model_loop
    patched_model, cache_engine, _ = _tp_build_model(
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 858, in _tp_build_model
    raise e
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 838, in _tp_build_model
    load_model_weights(patched_model,
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 219, in load_model_weights
    _load_model_weights_impl(model,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 197, in _load_model_weights_impl
    _load_model_weights_impl(child,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 197, in _load_model_weights_impl
    _load_model_weights_impl(child,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 197, in _load_model_weights_impl
    _load_model_weights_impl(child,
  [Previous line repeated 1 more time]
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 192, in _load_model_weights_impl
    model._load_weights(loader, rank, world_size, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/internlm2.py", line 21, in _load_weights
    colwise_parallelize_linear(getattr(self, mod_name),
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/dist_utils.py", line 94, in colwise_parallelize_linear
    return colwise_parallelize_linear_naive(module,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/dist_utils.py", line 51, in colwise_parallelize_linear_naive
    mod.register_parameter(name, param)
  File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 574, in register_parameter
    raise KeyError("parameter name can't contain \".\"")
KeyError: 'parameter name can\'t contain "."'
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 37, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 303, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1197, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 21, in __init__
    super().__init__(model_path, **kwargs)
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 206, in __init__
    self._build_pytorch(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 268, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 135, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 606, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 1236, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 1071, in __init__
    model, cache_engine, cache_config = self._build_model(
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 1140, in _build_model
    model, cache_engine, cache_config = _tp_build_model(
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 858, in _tp_build_model
    raise e
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 838, in _tp_build_model
    load_model_weights(patched_model,
  File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 219, in load_model_weights
    _load_model_weights_impl(model,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 197, in _load_model_weights_impl
    _load_model_weights_impl(child,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 197, in _load_model_weights_impl
    _load_model_weights_impl(child,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 197, in _load_model_weights_impl
    _load_model_weights_impl(child,
  [Previous line repeated 1 more time]
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/model_weight_loader.py", line 192, in _load_model_weights_impl
    model._load_weights(loader, rank, world_size, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/internlm2.py", line 21, in _load_weights
    colwise_parallelize_linear(getattr(self, mod_name),
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/dist_utils.py", line 94, in colwise_parallelize_linear
    return colwise_parallelize_linear_naive(module,
  File "/opt/lmdeploy/lmdeploy/pytorch/weight_loader/dist_utils.py", line 51, in colwise_parallelize_linear_naive
    mod.register_parameter(name, param)
  File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 574, in register_parameter
    raise KeyError("parameter name can't contain \".\"")
KeyError: 'parameter name can\'t contain "."'
```

**Comment by zhaoning1987** [comment]
看了下报错的地方parameter name值是 Plora_A.weight

**Comment by RunningLeon** [comment]
@zhaoning1987 hi, pytorch backend does not support internlm-xcomposer2-vl-7b per https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html#models-supported-by-pytorch

**Comment by zhaoning1987** [comment]
> @zhaoning1987 hi, pytorch backend does not support internlm-xcomposer2-vl-7b per https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html#models-supported-by-pytorch

ok，seems like all the vlm are not supported under pytroch backend，will it be supported in the future？

**Comment by RunningLeon** [comment]
> > @zhaoning1987 hi, pytorch backend does not support internlm-xcomposer2-vl-7b per https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html#models-supported-by-pytorch
> 
> ok，seems like all the vlm are not supported under pytroch backend，will it be supported in the future？ @RunningLeon

@zhaoning1987 hi, there are some vlm models are supported by pytorch backend, such as `cogvlm`, which are not supported in turbomind. No plan to support this model in pytorch engine, since the turbomind has supported and turbomind is much faster.
