### ISSUE TITLE
[Bug] Failed to load InternVL-Chat-V1-5-Int8 quantized model. RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by jiajie-yang** [InternLM/lmdeploy#1907]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

On my A800(and T4) card environment, while running the InternVL-Chat-V1-5-Int8 model service with lmdeploy 0.5.0, an error was reported during the model loading phase: `RuntimeError: Only Tensors of floating point and complex dtype can require gradients`. For details about the Error information, see Error traceback.

Is this int8 quantized model not yet supported in lmdeploy? Because I found that the InternVL-Chat-V1-5 non-quantized model is normal and can run.

### Reproduction

lmdeploy serve api_server OpenGVLab/InternVL-Chat-V1-5-Int8 --tp 2

### Environment

```Shell
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: NVIDIA A800-SXM4-40GB
CUDA_HOME: /usr/local/cuda
NVCC: Not Available
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.0+unknown
transformers: 4.41.2
gradio: 4.36.1
fastapi: 0.111.0
pydantic: 2.7.4
triton: 2.2.0
```

### Error traceback

```Shell
...
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash attention is not available, using eager attention instead.
Traceback (most recent call last):                                                                                                                                                                               
  File "/root/miniconda3/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 43, in run
    args.run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 310, in api_server
    run_api_server(args.model_path,
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1197, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/serve/vl_async_engine.py", line 21, in __init__
    self.vl_encoder = ImageEncoder(model_path,
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 70, in __init__
    self.model = load_vl_model(model_path, backend_config=backend_config)
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/model/builder.py", line 57, in load_vl_model
    return InternVLVisionModel(model_path, with_llm)
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 83, in __init__
    self.build_model()
  File "/root/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 103, in build_model
    load_checkpoint_and_dispatch(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/big_modeling.py", line 607, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1798, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/root/miniconda3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 424, in set_module_tensor_to_device
    new_value = param_cls(new_value, requires_grad=old_value.requires_grad).to(device)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/parameter.py", line 40, in __new__
    return torch.Tensor._make_subclass(cls, data, requires_grad)
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
```

**Comment by tengyunlai** [comment]
same question

**Comment by lvhan028** [comment]
LMDeploy doesn't support InternVL-Chat-V1-5-Int8. 
Instead, it supports InternVL-Chat-V1-5-AWQ in which the weights of LLM part are quantized into 4bit

**Comment by jiajie-yang** [comment]
> LMDeploy doesn't support InternVL-Chat-V1-5-Int8. Instead, it supports InternVL-Chat-V1-5-AWQ in which the weights of LLM part are quantized into 4bit

Ok, thanks. Any plans to support this int8 model in the future?

**Comment by lvhan028** [comment]
> > LMDeploy doesn't support InternVL-Chat-V1-5-Int8. Instead, it supports InternVL-Chat-V1-5-AWQ in which the weights of LLM part are quantized into 4bit
> 
> Ok, thanks. Any plans to support this int8 model in the future?

We probably come back to low-bit quantization in Q4.

**Comment by v3ss0n** [comment]
On the table it shows 8bit is supported , or am i understanding wrong ? Does that mean have to quant myself?

**Comment by lvhan028** [comment]
LMDeploy pytorch engine supports w8a8 quantization for some LLM models. 
But it cannot apply to VLMs yet.

**Comment by v3ss0n** [comment]
Ok so LMDeploy dosen't work with InternVL 4/8 bit quants yet at all? So the table needed to be updated?

**Comment by lvhan028** [comment]
Which table? [this one](https://github.com/InternLM/lmdeploy/blob/main/docs/en/supported_models/supported_models.md#models-supported-by-turbomind)?
KV INT8/INT4 means 8bit/4bit KV cache

**Comment by v3ss0n** [comment]
Ah I see. That's what I am looking.
