### ISSUE TITLE
[Bug]  File "/opt/py38/lib/python3.8/site-packages/packaging/version.py", line 200, in __init__     match = self._regex.search(version) TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by pseudotensor** [InternLM/lmdeploy#1957]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

lmdeploy fails to start due to some handling of transformers.

However, if I go into the image and check, transformers is installed and gives a normal version using the same commands.

So I'm unsure what is wrong.

### Reproduction

On 97ba6aa4fa69072466bc527ffbbaffe207876d0d

```
cd lmdeploy
docker build . -f docker/Dockerfile -t internvlmain --no-cache
docker build - < Dockerfile.internvl -t internvlmain2
```

where `Dockerfile.internvl` is:
```
FROM internvlmain

RUN apt-get update && apt-get install -y python3 python3-pip git

WORKDIR /app

RUN pip3 uninstall pkg_resources -y
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools==66.1.1
RUN pip3 uninstall -y ninja && pip3 install ninja
RUN CUDA_HOME=/usr/local/cuda-11.8/ PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118 pip3 install timm xformers triton==2.1.0
RUN MAX_JOBS=4 CUDA_HOME=/usr/local/cuda-11.8/ PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118 FLASH_ATTENTION_FORCE_BUILD=TRUE pip3 install flash-attn==2.5.2 --no-build-isolation
RUN pip3 install git+https://github.com/haotian-liu/LLaVA.git --no-deps
RUN CUDA_HOME=/usr/local/cuda-11.8/ PIP_EXTRA_INDEX_URL=https://download.pytorch.org/whl/cu118 pip3 install transformers

COPY . .

CMD ["lmdeploy", "serve", "api_server", "OpenGVLab/InternVL2-40B"]
```

then run:
```
docker run -d --restart=always --runtime nvidia --gpus '"device=1"'     -v $HOME/.cache/huggingface:/root/.cache/huggingface     --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN"     -p 30000:23333     --ipc=host     --name internvl40_lmdeploy     internvlmain2     lmdeploy serve api_server OpenGVLab/InternVL2-40B --model-name OpenGVLab/InternVL2-40B
```

It seems transformers is not installed, and it's not.

So I added transformers, and then 

### Environment

```Shell
docker build as above
```

### Error traceback

```Shell
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 22.12 (build 50109463)
Triton Server Version 2.29.0

Copyright (c) 2018-2022, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

Fetching 34 files: 100%|??????????| 34/34 [00:00<00:00, 46971.78it/s]
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 310, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1226, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 24, in __init__
    super().__init__(model_path, **kwargs)
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 189, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 234, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 342, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 143, in __init__
    self.tokenizer = Tokenizer(model_path)
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 561, in __init__
    self.model = HuggingFaceTokenizer(model_folder)
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 199, in __init__
    self._check_transformers_version(model_dir)
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 234, in _check_transformers_version
    required_transformers_version = version.parse(
  File "/opt/py38/lib/python3.8/site-packages/packaging/version.py", line 56, in parse
    return Version(version)
  File "/opt/py38/lib/python3.8/site-packages/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
```

**Comment by zhyncs** [comment]
It's fixed at https://github.com/InternLM/lmdeploy/pull/1952

**Comment by pseudotensor** [comment]
ok thanks, will verify

**Comment by zhyncs** [comment]
The latest commit  is being compiled.
https://github.com/zhyncs/lmdeploy-build/actions/runs/9850377202
https://github.com/zhyncs/lmdeploy-build/actions/runs/9850378026

**Comment by zhyncs** [comment]
Hi @pseudotensor May you try this https://github.com/zhyncs/lmdeploy-build/releases/tag/3030ae4

**Comment by pseudotensor** [comment]
No longer issue, but model is not behaving good.
