### ISSUE TITLE
[Bug] KeyError: 'Qwen2ForCausalLM' for InternVL2 1B

### ISSUE THREAD

**Issue by zhyncs** [InternLM/lmdeploy#1963]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

as titled cc @irexyc 

https://huggingface.co/OpenGVLab/InternVL2-1B/blob/main/config.json#L15
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/__main__.py", line 5, in <module>
    run()
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/cli/serve.py", line 310, in api_server
    run_api_server(args.model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/openai/api_server.py", line 1226, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/vl_async_engine.py", line 24, in __init__
    super().__init__(model_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 189, in __init__
    self._build_turbomind(model_path=model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 234, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 342, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 229, in _from_hf
    input_model = INPUT_MODELS.get(input_model_name)(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/deploy/source_model/internvl.py", line 47, in __init__
    self.Reader = _readers[arch]
KeyError: 'Qwen2ForCausalLM'
```

### Reproduction

LMDeploy
```bash
pip3 install https://github.com/zhyncs/lmdeploy-build/releases/download/3030ae4/lmdeploy-0.5.0+cu121+3030ae4-cp39-cp39-manylinux2014_x86_64.whl
```

```bash
# https://huggingface.co/OpenGVLab/InternVL2-1B
python3 -m lmdeploy serve api_server InternVL2-1B
```

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
TorchVision: 0.17.2+cu121
LMDeploy: 0.5.0+
transformers: 4.41.2
triton: 2.2.0
torch: 2.2.2+cu121
```

**Comment by zhyncs** [comment]
I suspect that the architectures of the models are wrong. Both 8B and 26B are InternLM2ForCausalLM, but 1B is Qwen2ForCausalLM.

**Comment by zhyncs** [comment]
InternVL2-2B works well 😂 @irexyc 
```bash
python3 -m lmdeploy serve api_server InternVL2-2B
```

**Comment by lvhan028** [comment]
The arch is right. `InternVL2-1B` uses `Qwen/Qwen2-0.5B-Instruct` as the LLM model. 
The head dim of Qwen2-0.5B is 64, which is not supported by turbomind engine now.

@RunningLeon please add this feature in pytorch engine

**Comment by zhyncs** [comment]
> The arch is right. `InternVL2-1B` uses `Qwen/Qwen2-0.5B-Instruct` as the LLM model. The head dim of Qwen2-0.5B is 64, which is not supported by turbomind engine now.

ok

**Comment by RunningLeon** [comment]
@zhyncs hi, pls check [this](https://github.com/InternLM/lmdeploy/pull/1983) PR if you have time.

**Comment by zhyncs** [comment]
ok

**Comment by zhyncs** [comment]
Fixed with https://github.com/InternLM/lmdeploy/pull/1983
