### ISSUE TITLE
使用gemma2进行离线推理时报错lmdeploy - ERROR - Engine loop failed with error: 'list' object has no attribute 'get_max_length'

### ISSUE THREAD

**Issue by NBStarry** [InternLM/lmdeploy#1994]
尝试用lmdeloy进行gemma2的离线推理：
```
from lmdeploy import pipeline, GenerationConfig, PytorchEngineConfig

backend_config = PytorchEngineConfig(tp=2)
gen_config = GenerationConfig(top_p=0.8,
                            top_k=40,
                            temperature=0.8,
                            max_new_tokens=1024)
pipeline = pipeline('/root/google/gemma-2-9b-it', backend_config=backend_config)
reply_generator = self.pipeline.stream_infer(["<|CHOICE|>Let's make a _____dinosaur.\n\n A、snowing;\nB、snow;\nC、snowy"], gen_config=gen_config)

for reply_chunk in reply_generator:
   print(reply_chunk, end='', flush=True)
```
遇到了如下报错：
```
Loading checkpoint shards: 100%|███████████████████████| 4/4 [00:04<00:00,  1.21s/it]
WARNING:root:====== NO RAG ======
WARNING:root:====== Choice Question ======
2024-07-11 08:45:54,674 - lmdeploy - ERROR - Engine loop failed with error: 'list' object has no attribute 'get_max_length'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/request.py", line 17, in _raise_exception_on_finish
    task.result()
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 853, in async_loop
    await self._async_loop()
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 843, in _async_loop
    await __step(True)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 829, in __step
    raise e
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 821, in __step
    raise out
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 770, in _async_loop_background
    await self._async_step_background(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 679, in _async_step_background
    output = await self._async_model_forward(inputs,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/utils.py", line 253, in __tmp
    return (await func(*args, **kwargs))
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 586, in _async_model_forward
    return await __forward(inputs)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/engine.py", line 564, in __forward
    return await self.model_agent.async_forward(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/model_agent.py", line 756, in async_forward
    output = self._forward_impl(inputs,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/model_agent.py", line 723, in _forward_impl
    output = model_forward(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/engine/model_agent.py", line 497, in model_forward
    output = patched_model.patched_forward(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/pytorch/models/patch.py", line 210, in __call__
    output = self._model(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gemma2/modeling_gemma2.py", line 1068, in forward
    outputs = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gemma2/modeling_gemma2.py", line 876, in forward
    causal_mask = self._update_causal_mask(
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/gemma2/modeling_gemma2.py", line 957, in _update_causal_mask
    target_length = past_key_values.get_max_length()
AttributeError: 'list' object has no attribute 'get_max_length'
```
我的pytorch版本是2.2.2+cu121，python版本3.10.12

**Comment by zhyncs** [comment]
cc @grimoire

**Comment by grimoire** [comment]
Please try the latest main branch.

**Comment by zhyncs** [comment]
@NBStarry ref https://github.com/zhyncs/lmdeploy-build/releases/tag/ff2e307

**Comment by NBStarry** [comment]
> @NBStarry ref https://github.com/zhyncs/lmdeploy-build/releases/tag/ff2e307

It works，thx.
