### ISSUE TITLE
What is the expected chat template for phi-3-vl?

### ISSUE THREAD

**Issue by xinke-wang** [InternLM/lmdeploy#2024]
Hi, I'm trying to use the phi-3-vision model following the documentation. I am able to run the following demo code with most of the models, such as `internvl` and `llava`, but I failed with `phi-3-vision`.

Here is my code

```python
model = 'microsoft/Phi-3-vision-128k-instruct'
image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
chat_template_config = ChatTemplateConfig('phi-3')
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))
response = pipe(('describe this image', image))
print(response.text)
```

which gives an output with the following errors:

```text
Traceback (most recent call last):
  File "/home/work/LMM-Playground/test.py", line 14, in <module>
    response = pipe(('describe this image', image))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 304, in __call__
    return self.batch_infer(prompts,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 381, in batch_infer
    assert isinstance(prompts, List), 'prompts should be a list'
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: prompts should be a list
```

To solve the above issue, I tried to add [] for the prompt for batch mode:

```python
response = pipe([('describe this image', image)])
```

It further gives the following error:

```text
Traceback (most recent call last):
  File "/home/work/LMM-Playground/test.py", line 14, in <module>
    response = pipe([('describe this image', image)])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 304, in __call__
    return self.batch_infer(prompts,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 428, in batch_infer
    _get_event_loop().run_until_complete(gather())
  File "/home/xinyu/anaconda3/envs/playground/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 425, in gather
    await asyncio.gather(
  File "/home/xinyu/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 410, in _inner_call
    async for out in generator:
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 563, in generate
    prompt_input = await self._get_prompt_input(prompt, do_preprocess,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 516, in _get_prompt_input
    prompt = chat_template.messages2prompt(prompt, sequence_start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/playground/lib/python3.11/site-packages/lmdeploy/model.py", line 226, in messages2prompt
    role = message['role']
           ~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

However, I can run this code with other models such as `InternVL2-2B`:
```python
model = 'OpenGVLab/InternVL2-2B'
image = load_image('https://raw.githubusercontent.com/open-mmlab/mmdeploy/main/tests/data/tiger.jpeg')
chat_template_config = ChatTemplateConfig('internvl-internlm2')
pipe = pipeline(model, chat_template_config=chat_template_config,
                backend_config=TurbomindEngineConfig(session_len=8192))
response = pipe(('describe this image', image))
print(response.text)
```

which successfully outputs the description:
```text
The image features a majestic tiger lying on a lush green grassy field. The tiger is resting with its body slightly turned to the side, showcasing its powerful build and distinctive orange fur with black stripes. The tiger's eyes are focused and alert, giving it an intense and commanding presence. The surrounding grass is vibrant and green, indicating a healthy and thriving ecosystem. The lighting suggests it is a bright, sunny day, casting soft shadows on the grass, enhancing the natural beauty of the scene.
```

Is this because I am using an incorrect chat template? What is the correct way to use Phi-3-vision? Thank you.

**Comment by RunningLeon** [comment]
@xinke-wang hi, you are right. the chattemplate  `model_name` is `phi3` for phi3-vision. Please try with the latest main branch.
The code runs successfully on my side

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.19s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
 The image shows a tiger lying on grass. The tiger has a striped pattern with black and orange colors. The background is a field of green grass, and the sunlight is casting shadows on the grass, suggesting it is a sunny day. The tiger is facing towards the camera, and its posture is relaxed, indicating it is resting.

**Comment by zhulinJulia24** [comment]
> @xinke-wang hi, you are right. the chattemplate `model_name` is `phi3` for phi3-vision. Please try with the latest main branch. The code runs successfully on my side
> 
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:06<00:00, 3.19s/it] Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. The image shows a tiger lying on grass. The tiger has a striped pattern with black and orange colors. The background is a field of green grass, and the sunlight is casting shadows on the grass, suggesting it is a sunny day. The tiger is facing towards the camera, and its posture is relaxed, indicating it is resting.

By using microsoft/Phi-3-mini-4k-instruct model with main code. Same error `prompts should be a list`. 

```
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.71s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.82s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.95s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/__w/lmdeploy/lmdeploy/autotest/utils/pipeline_chat.py", line 310, in run_pipeline_vl_chat_test
    response = pipe((prompt, image))
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 304, in __call__
    return self.batch_infer(prompts,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 3[81](https://github.com/zhulinJulia24/lmdeploy/actions/runs/9937946066/job/27450057058#step:19:82), in batch_infer
    assert isinstance(prompts, List), 'prompts should be a list'
AssertionError: prompts should be a list
```

**Comment by RunningLeon** [comment]
@zhulinJulia24  `microsoft/Phi-3-mini-4k-instruct` is not a vl model.

**Comment by zhulinJulia24** [comment]
> @zhulinJulia24 `microsoft/Phi-3-mini-4k-instruct` is not a vl model.

ok
