### ISSUE TITLE
auto awq转模型时 im_mask = im_mask.view(-1)  AttributeError: 'NoneType' object has no attribute 'view'

### ISSUE THREAD

**Issue by lzcchl** [InternLM/lmdeploy#2031]
我用的是最新的代码 9f3e74813bea44411274e2f08c8ad1dcd1cc9e86
我看到 https://github.com/InternLM/lmdeploy/pull/1890/files 中把 im_mask 设置为 none，
这里我报新的错误：

    Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/ptb_text_only/8d1b97746fb9765d140e569ec5ddd35e20af4d37761f5e1bf357ea0b081f2c1f (last modified on Wed May 29 14:13:26 2024) since it couldn't be found locally at ptb_text_only
    You are using a model of type internlmxcomposer2 to instantiate a model of type internlm2. This is not supported for all configurations of models and can yield errors.
    2024-07-15 14:14:57,754 - lmdeploy - INFO - matching vision model: Xcomposer2VisionModel
    Set max length to 16384
    Dummy Resized
    2024-07-15 14:14:58,739 - lmdeploy - INFO - matching type of ModelType.XCOMPOSER2_4KHD
    Move model.tok_embeddings to GPU.
    Move model.layers.0 to CPU.
    Move model.layers.1 to CPU.
    Move model.layers.2 to CPU.
    Move model.layers.3 to CPU.
    Move model.layers.4 to CPU.
    Move model.layers.5 to CPU.
    Move model.layers.6 to CPU.
    Move model.layers.7 to CPU.
    Move model.layers.8 to CPU.
    Move model.layers.9 to CPU.
    Move model.layers.10 to CPU.
    Move model.layers.11 to CPU.
    Move model.layers.12 to CPU.
    Move model.layers.13 to CPU.
    Move model.layers.14 to CPU.
    Move model.layers.15 to CPU.
    Move model.layers.16 to CPU.
    Move model.layers.17 to CPU.
    Move model.layers.18 to CPU.
    Move model.layers.19 to CPU.
    Move model.layers.20 to CPU.
    Move model.layers.21 to CPU.
    Move model.layers.22 to CPU.
    Move model.layers.23 to CPU.
    Move model.layers.24 to CPU.
    Move model.layers.25 to CPU.
    Move model.layers.26 to CPU.
    Move model.layers.27 to CPU.
    Move model.layers.28 to CPU.
    Move model.layers.29 to CPU.
    Move model.layers.30 to CPU.
    Move model.layers.31 to CPU.
    Move model.norm to GPU.
    Move output to CPU.
    Move vit to GPU.
    Move vision_proj to GPU.
    Loading calibrate dataset ...
    Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/ptb_text_only/8d1b97746fb9765d140e569ec5ddd35e20af4d37761f5e1bf357ea0b081f2c1f (last modified on Wed May 29 14:13:26 2024) since it couldn't be found locally at ptb_text_only
    Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/ptb_text_only/8d1b97746fb9765d140e569ec5ddd35e20af4d37761f5e1bf357ea0b081f2c1f (last modified on Wed May 29 14:13:26 2024) since it couldn't be found locally at ptb_text_only
    Traceback (most recent call last):
    File "/opt/py38/bin/lmdeploy", line 33, in <module>
        sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
    File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
        args.run(args)
    File "/opt/lmdeploy/lmdeploy/cli/lite.py", line 139, in auto_awq
        auto_awq(**kwargs)
    File "/opt/lmdeploy/lmdeploy/lite/apis/auto_awq.py", line 103, in auto_awq
        vl_model, model, tokenizer, work_dir = calibrate(model,
    File "/opt/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 238, in calibrate
        calib_ctx.calibrate(all_data)
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 324, in calibrate
        _ = model(data.to(self.device))
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-4khd-7b/modeling_internlm2.py", line 958, in forward
        layer_outputs = decoder_layer(
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 519, in _forward
        auto_scale_block(mod, batch_kwargs[i], self.w_bits,
    File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 421, in auto_scale_block
        _auto_get_scale(
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 414, in _auto_get_scale
        best_ratio = _search_module_scale(module2inspect, layers, inp.value,
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 361, in _search_module_scale
        org_out = block(x, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-4khd-7b/modeling_internlm2.py", line 260, in forward
        down_proj = self.w2(self.act_fn(self.w1(x, im_mask)) * self.w3(x, im_mask), im_mask)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
        result = forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-4khd-7b/build_mlp.py", line 195, in forward
        im_mask = im_mask.view(-1)
    AttributeError: 'NoneType' object has no attribute 'view'

**Comment by AllentDan** [comment]
@lzcchl May try the file changes in https://huggingface.co/internlm/internlm-xcomposer2-4khd-7b/discussions/14/files

**Comment by AllentDan** [comment]
There is no need to use `--search-scale` actually. Default settings are good enough to quantize this model.

**Comment by lzcchl** [comment]
emm, yeah, but I want quantize this model with lora fine tuning, which is not good without --search-scale,
there is a new error when using --search-scale, likes:
    Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/ptb_text_only/8d1b97746fb9765d140e569ec5ddd35e20af4d37761f5e1bf357ea0b081f2c1f (last modified on Wed May 29 14:13:26 2024) since it couldn't be found locally at ptb_text_only
    Traceback (most recent call last):
    File "/opt/py38/bin/lmdeploy", line 33, in <module>
        sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
    File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
        args.run(args)
    File "/opt/lmdeploy/lmdeploy/cli/lite.py", line 139, in auto_awq
        auto_awq(**kwargs)
    File "/opt/lmdeploy/lmdeploy/lite/apis/auto_awq.py", line 103, in auto_awq
        vl_model, model, tokenizer, work_dir = calibrate(model,
    File "/opt/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 238, in calibrate
        calib_ctx.calibrate(all_data)
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 324, in calibrate
        _ = model(data.to(self.device))
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    File "/root/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-4khd-7b-lora/modeling_internlm2.py", line 958, in forward
        layer_outputs = decoder_layer(
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl    return self._call_impl(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
        return forward_call(*args, **kwargs)
    File "/opt/py38/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
    File "/opt/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 524, in _forward
        item.value.cpu()
    AttributeError: 'NoneType' object has no attribute 'cpu'

**Comment by bonre** [comment]
try to change like this:
```
if key.startswith(f'{mod_name}.'):
    if item.value is not None:
        item.value.cpu()
        del item.value
```

**Comment by AllentDan** [comment]
Yeah, that would fix it.
