### ISSUE TITLE
[Bug] Quantized Model Incompatibility with TurboMind Inference Engine

### ISSUE THREAD

**Issue by Kn0rk** [InternLM/lmdeploy#2032]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

I am attempting to quantize a model and use it with the TurboMind inference engine. I have successfully quantized the model following the[ provided instructions](https://github.com/InternLM/lmdeploy/blob/main/docs/en/quantization/w8a8.md). The  documentation seems to imply that the quantize version only works with the pytorch backend?  If that is the case I  think it would be good to make that explicit in the documentation.

When I try to run the quantized version with TurboMind, I encounter a KeyError (see below).

I tested both latest and [nightly](https://github.com/zhyncs/lmdeploy-build/releases/tag/9f3e748).

### Reproduction

```
lmdeploy lite smooth_quant meta-llama/Meta-Llama-3-8B-Instruct --work-dir ./lmdeploy_llama3_8b_q8
lmdeploy serve api_server ./lmdeploy_llama3_8b_q8 --server-port 23333 # does not work
```

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100-PCIE-40GB MIG 7g.40gb
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 11.5, V11.5.119
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.0+
transformers: 4.42.4
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
```

### Error traceback

```Shell
(.venv) ➜  benchmark_llm_inference lmdeploy serve api_server ./lmdeploy_llama3_8b_q4 --server-port 23333                                                                                       
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 43, in run
    args.run(args)
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 310, in api_server
    run_api_server(args.model_path,
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1197, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 189, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 234, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 342, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 237, in _from_hf
    output_model = OUTPUT_MODELS.get(output_model_name)(
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 80, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 168, in __init__
    self.cfg = self.get_config(cfg)
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 92, in get_config
    w1s, _, _ = bin.ffn_scale(i)
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/llama_awq.py", line 52, in ffn_scale
    return ensure_fp16orint32(self._ffn(i, 'scales'))
  File "/home/ubuntu/jan/benchmark_llm_inference/.venv/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 103, in _ffn
    tensor = self.params[
KeyError: 'model.layers.0.mlp.gate_proj.scales'
```

**Comment by zhyncs** [comment]
W8A8 is only supported on PyTorch Engine for now.

**Comment by Skyseaee** [comment]
hello, i met the problem too. I use lmdeploy to quant a model in kv8 model and use `lmdeploy serve api_server .Meta-Llama-3-8B-kv8-hf/ ` to try to run the service and the same error occured. Just like `KeyError: 'model.layers.0.mlp.gate_proj.scales'`. Although i found in 0.4.* version llmdeploy has already remove the offline quant but i want to benchmark the difference between online mode and offline mode. Is there anyone can help me. thanks a lot

**Comment by Skyseaee** [comment]
oh, i found the comment and added the `--backend pytorch` and it works.
