### ISSUE TITLE
[Bug] intervl26B的Int8量化正常，但是聊天推理失败

### ISSUE THREAD

**Issue by stay-leave** [InternLM/lmdeploy#2042]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

https://lmdeploy.readthedocs.io/zh-cn/latest/quantization/w8a8.html  使用该教程进行量化
结果：
![截屏2024-07-16 17 45 27](https://github.com/user-attachments/assets/70802147-e714-4cc1-b374-3b2803050258)

### Reproduction

推理脚本：
```lmdeploy serve api_server /root/data/models/InternVL2-26B-int8 \
--backend pytorch \
--chat-template /root/lhd/inference/intervl2/chat_template.json \
--server-port 8001 \
--tp 8 \
--model-format awq```


### Environment

```Shell
最新版的whl文件安装的
```

### Error traceback

```Shell
推理报错：
Traceback (most recent call last):
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1016, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 981, in _tp_model_loop
    model_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 497, in model_forward
    output = patched_model.patched_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 210, in __call__
    output = self._model(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1016, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 981, in _tp_model_loop
    model_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 497, in model_forward
    output = patched_model.patched_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1016, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/internvl.py", line 20, in forward
    outputs = self.language_model(input_ids=input_ids,
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 981, in _tp_model_loop
    model_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 210, in __call__
    output = self._model(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 497, in model_forward
    output = patched_model.patched_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 210, in __call__
    output = self._model(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-26B-int8/modeling_internlm2.py", line 1335, in forward
    if self.config.pretraining_tp > 1:
Traceback (most recent call last):
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/internvl.py", line 20, in forward
    outputs = self.language_model(input_ids=input_ids,
Traceback (most recent call last):
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/transformers/configuration_utils.py", line 264, in __getattribute__
    return super().__getattribute__(key)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/internvl.py", line 20, in forward
    outputs = self.language_model(input_ids=input_ids,
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-26B-int8/modeling_internlm2.py", line 1335, in forward
    if self.config.pretraining_tp > 1:
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1016, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1016, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/transformers/configuration_utils.py", line 264, in __getattribute__
    return super().__getattribute__(key)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 981, in _tp_model_loop
    model_forward(
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-26B-int8/modeling_internlm2.py", line 1335, in forward
    if self.config.pretraining_tp > 1:
AttributeError: 'InternLM2Config' object has no attribute 'pretraining_tp'
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 981, in _tp_model_loop
    model_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 497, in model_forward
    output = patched_model.patched_forward(
AttributeError: 'InternLM2Config' object has no attribute 'pretraining_tp'
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/transformers/configuration_utils.py", line 264, in __getattribute__
    return super().__getattribute__(key)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 497, in model_forward
    output = patched_model.patched_forward(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 210, in __call__
    output = self._model(*args, **kwargs)
AttributeError: 'InternLM2Config' object has no attribute 'pretraining_tp'
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 210, in __call__
    output = self._model(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/internvl.py", line 20, in forward
    outputs = self.language_model(input_ids=input_ids,
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/models/internvl.py", line 20, in forward
    outputs = self.language_model(input_ids=input_ids,
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-26B-int8/modeling_internlm2.py", line 1335, in forward
    if self.config.pretraining_tp > 1:
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-26B-int8/modeling_internlm2.py", line 1335, in forward
    if self.config.pretraining_tp > 1:
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/transformers/configuration_utils.py", line 264, in __getattribute__
    return super().__getattribute__(key)
Traceback (most recent call last):
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/transformers/configuration_utils.py", line 264, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'InternLM2Config' object has no attribute 'pretraining_tp'


Traceback (most recent call last):
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/serve/openai/api_server.py", line 530, in chat_completions_v1
    async for res in result_generator:
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 615, in generate
    async for outputs in generator.async_stream_infer(
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine_instance.py", line 159, in async_stream_infer
    await async_try_add_session(self.req_sender, session_id)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine_instance.py", line 36, in async_try_add_session
    resp = await req_sender.async_send(RequestType.ADD_SESSION,
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/request.py", line 347, in async_send
    return await self.async_recv(req_id, que_timeout=que_timeout)
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/request.py", line 314, in async_recv
    resp: Response = await self._async_resp_get()
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/request.py", line 187, in _async_resp_get
    return await __no_threadsafe_get()
  File "/root/lhd/py_env/lmdeploy/lib/python3.9/site-packages/lmdeploy/pytorch/engine/request.py", line 175, in __no_threadsafe_get
    exit(1)
  File "/root/anaconda3/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
```

**Comment by lvhan028** [comment]
Please checkout https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html
InternVL2 (W8A8) is not supported

**Comment by MenglingD** [comment]
> Please checkout https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html InternVL2 (W8A8) is not supported

I've confirmed that none of the current multi-modal models support W8A8 quantization. Could you please explain why?

**Comment by lvhan028** [comment]
> > Please checkout https://lmdeploy.readthedocs.io/en/latest/supported_models/supported_models.html InternVL2 (W8A8) is not supported
> 
> I've confirmed that none of the current multi-modal models support W8A8 quantization. Could you please explain why?

we are short of staff
