### ISSUE TITLE
使用pipline进行批量推理报错[Bug] 

### ISSUE THREAD

**Issue by hitzhu** [InternLM/lmdeploy#2047]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

完全按照readme中的例子会报错，模型是internvl2-40B

### Reproduction

![image](https://github.com/user-attachments/assets/e852fbb4-1dd4-4e76-bf35-ddd8b6648da0)
![image](https://github.com/user-attachments/assets/4bb08096-f3d3-4c69-ad3d-6579e7f56756)

### Environment

```Shell
rt
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/zhujihuai.zjh/cpv_check_for_huohao/huohao_image_internvl.py", line 50, in <module>
    response = pipe(prompts)
               ^^^^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 304, in __call__
    return self.batch_infer(prompts,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 428, in batch_infer
    _get_event_loop().run_until_complete(gather())
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/asyncio/tasks.py", line 279, in __step
    result = coro.throw(exc)
             ^^^^^^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 425, in gather
    await asyncio.gather(
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/asyncio/tasks.py", line 277, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 410, in _inner_call
    async for out in generator:
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 563, in generate
    prompt_input = await self._get_prompt_input(prompt, do_preprocess,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 516, in _get_prompt_input
    prompt = chat_template.messages2prompt(prompt, sequence_start)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhujihuai.zjh/.conda/envs/intern-vl2/lib/python3.11/site-packages/lmdeploy/model.py", line 535, in messages2prompt
    if len(messages) and messages[0]['role'] != 'system':
                         ~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by lvhan028** [comment]
Please share the env info by executing `lmdeploy check_env`

**Comment by lvhan028** [comment]
LMDeploy can not tell the chat template from the model_path. Please change it to `InternVL2-40B` or specify the chat template name by passing `ChatTemplateConfig` to the pipeline.

One more thing,  v0.5.1 should be installed

**Comment by hitzhu** [comment]
> lmdeploy check_env

sys.platform: linux
Python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.3, V12.3.52
GCC: gcc (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3 2.17)
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.0+dcee7a8
transformers: 4.37.2
gradio: Not Found
fastapi: 0.111.0
pydantic: 2.8.0
triton: 2.2.0
(intern-vl2)

**Comment by irexyc** [comment]
@hitzhu 

试下最新的 lmdeploy0.5.1吧，我找不到dcee7a8这个commit的信息。

关于 internvl2 相关的对话模版匹配机制是在0.5.0之后添加的，你的版本应该是匹配到了错误的模版。
