### ISSUE TITLE
多卡部署internvl2-8b报错

### ISSUE THREAD

**Issue by haoduoyu1203** [InternLM/lmdeploy#2050]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

一张3090，一张2080ti22g部署internvl2-8b报错

### Reproduction

使用命令：lmdeploy serve api_server internvl2-8b --backend turbomind --server-port 23334 --tp 2 --chat-template chat_template.json

### Environment

```Shell
TorchVision: 0.18.1
LMDeploy: 0.5.0+
transformers: 4.37.2
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: Not Found
```

### Error traceback

```Shell
报错内容如下
Traceback (most recent call last):
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\baobao\.conda\envs\imdeploy_env\Scripts\lmdeploy.exe\__main__.py", line 7, in <module>
    sys.exit(run())
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\cli\entrypoint.py", line 43, in run
    args.run(args)
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\cli\serve.py", line 310, in api_server
    run_api_server(args.model_path,
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\serve\openai\api_server.py", line 1197, in serve
    VariableInterface.async_engine = pipeline_class(
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\serve\vl_async_engine.py", line 24, in __init__
    super().__init__(model_path, **kwargs)
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\serve\async_engine.py", line 189, in __init__
    self._build_turbomind(model_path=model_path,
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\serve\async_engine.py", line 234, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 342, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "C:\Users\baobao\.conda\envs\imdeploy_env\lib\site-packages\lmdeploy\turbomind\turbomind.py", line 246, in _from_hf
    model_comm = _tm.AbstractTransformerModel.create_llama_model(
RuntimeError: [TM][ERROR]  Assertion fail: D:\a\lmdeploy\lmdeploy\src/turbomind/models/llama/Barrier.h:20
```

**Comment by haoduoyu1203** [comment]
环境内容补充
sys.platform: win32
Python: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.105
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.40.33812 版
GCC: n/a
PyTorch: 2.3.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930154
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.7  (built against CUDA 12.2)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.7, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.18.1
LMDeploy: 0.5.0+
transformers: 4.37.2
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: Not Found

**Comment by zhyncs** [comment]
And perhaps you can give WSL2 a try.

**Comment by haoduoyu1203** [comment]
一张3090，一张2080ti22g部署internvl2-8b报错
WSL2 ubuntu22.04  最新环境如下
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 2080 Ti
CUDA_HOME: /usr/local/cuda-12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.66
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.3+9f3e748
transformers: 4.42.4
gradio: 3.50.2
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
NVIDIA Topology:
        GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS                             N/A
GPU1    SYS      X                              N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks


执行命令 lmdeploy serve api_server /home/a/lmdeploy/InternVL2-8B --backend turbomind --server-port 23333 --tp 2 --chat-template chat_template.json   能正常启动，但是提问会报错。错误如下
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 26, in _raise_exception_on_finish
    raise e
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 22, in _raise_exception_on_finish
    task.result()
  File "/home/a/lmdeploy/venv/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 151, in forward
    outputs = self.model.forward(inputs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 172, in forward
    return self._forward_func(images)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 153, in _forward_v1_5
    outputs = self.model.extract_feature(outputs)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_internvl_chat.py", line 168, in extract_feature
    vit_embeds = self.vision_model(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_intern_vit.py", line 418, in forward
    encoder_outputs = self.encoder(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_intern_vit.py", line 354, in forward
    layer_outputs = encoder_layer(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_intern_vit.py", line 296, in forward
    hidden_states = hidden_states + self.drop_path1(self.attn(self.norm1(hidden_states)) * self.ls1)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_intern_vit.py", line 252, in forward
    x = self._naive_attn(hidden_states) if not self.use_flash_attn else self._flash_attn(hidden_states)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_intern_vit.py", line 244, in _flash_attn
    context, _ = self.inner_attn(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/a/.cache/huggingface/modules/transformers_modules/InternVL2-8B/modeling_intern_vit.py", line 77, in forward
    output = flash_attn_unpadded_qkvpacked_func(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 946, in flash_attn_varlen_qkvpacked_func
    return FlashAttnVarlenQKVPackedFunc.apply(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 314, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
  File "/home/a/lmdeploy/venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 89, in _flash_attn_varlen_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by lvhan028** [comment]
根据日志看，
```
out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
看起来是flash_attn 在这个环境上运行失败了。我不确定nccl是否能跨不同的GPU架构。
在执行命令前，加上 `CUDA_LAUNCH_BLOCKING=1` 看看有没有更详细的日志输出
