### ISSUE TITLE
[Bug] AttributeError: 'dict' object has no attribute 'num_attention_heads'

### ISSUE THREAD

**Issue by ztfmars** [InternLM/lmdeploy#2124]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug
直接安装最新的lmdeploy : pip install lmdeploy[all]
下载internvl 40b 模型，想要应用部署，但是直接报错了：

```
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type internvl_chat to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/home/fusionai/anaconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/fusionai/anaconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/home/fusionai/anaconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 280, in api_server
    backend = autoget_backend(args.model_path)
  File "/home/fusionai/anaconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/archs.py", line 44, in autoget_backend
    turbomind_has = is_supported_turbomind(model_path)
  File "/home/fusionai/anaconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/supported_models.py", line 98, in is_supported
    support_by_turbomind = _is_head_dim_128(cfg.llm_config)
  File "/home/fusionai/anaconda3/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/supported_models.py", line 66, in _is_head_dim_128
    num_attn_head = cfg.num_attention_heads
AttributeError: 'dict' object has no attribute 'num_attention_heads'
```

ref: https://huggingface.co/OpenGVLab/InternVL2-40B#%E7%AE%80%E4%BB%8B

求助一波，在线等，感谢。

### Reproduction

有4卡h800 gpu，internvl 2b,4b可用，chat template已更换internvl-zh-hermes2。相关指令如下：

```
(lmdeploy) fusionai@Pro:~/project/demo/web_serve$ lmdeploy serve api_server \
/home/fusionai/.cache/modelscope/hub/OpenGVLab/InternVL2-40B \
--model-name InternVL2-40B \
--backend turbomind \
--server-port 6006 \
--tp 4 \
--quant-policy 8 \
--cache-max-entry-count 0.8 \
--chat-template internvl40b_chat_template.json
```

### Environment

```Shell
(lmdeploy) fusionai@Pro:~/project/demo/web_serve$ lmdeploy checkenv
usage: lmdeploy [-h] [-v] {lite,serve,convert,list,check_env,chat} ...
lmdeploy: error: argument command: invalid choice: 'checkenv' (choose from 'lite', 'serve', 'convert', 'list', 'check_env', 'chat')
(lmdeploy) fusionai@Pro:~/project/demo/web_serve$ lmdeploy check_env
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A800 80GB PCIe
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.1.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.2+cu121
LMDeploy: 0.5.1+
transformers: 4.43.1
gradio: 4.39.0
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.1.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     PHB     PHB     PHB     PHB     PHB     PHB     0-31    0               N/A
GPU1    PHB      X      PHB     PHB     PHB     PHB     PHB     PHB     0-31    0               N/A
GPU2    PHB     PHB      X      PHB     PHB     PHB     PHB     PHB     0-31    0               N/A
GPU3    PHB     PHB     PHB      X      PHB     PHB     PHB     PHB     0-31    0               N/A
GPU4    PHB     PHB     PHB     PHB      X      PHB     PHB     PHB     0-31    0               N/A
GPU5    PHB     PHB     PHB     PHB     PHB      X      PHB     PHB     0-31    0               N/A
GPU6    PHB     PHB     PHB     PHB     PHB     PHB      X      PHB     0-31    0               N/A
GPU7    PHB     PHB     PHB     PHB     PHB     PHB     PHB      X      0-31    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by xuexidi** [comment]
4卡V100，碰到一样的情况，在线等求助~

**Comment by RunningLeon** [comment]
@xuexidi have you changed anything in lmdeploy or internvl2-40b?  Can not reproduce it on the latest main branch with commit_id `7199b4e`.  Looks good when run on my side
```
python -c 'from lmdeploy.archs import autoget_backend;print(autoget_backend("InternVL2-40B"))'
# output turbomind
```

**Comment by xuexidi** [comment]
well，problems gone when I upgrade lmdeploy to the latest version today（I install the last version 3 days ago using＂pip install lmdeploy＂，I remove this old conda env  and rebuild a new env，and rerun ＂pip install lmdeploy＂）

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/26/2024 19:36 |
| To | InternLM/lmdeploy ***@***.***> |
| Cc | xuexidi ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [InternLM/lmdeploy] [Bug] AttributeError: 'dict' object has no attribute 'num_attention_heads' (Issue #2124) |

@xuexidi hi, have you changed anything in lmdeploy or internvl2-40b? Can not reproduce it on the latest main branch with commit_id 7199b4e. Looks good when run on my side

python -c 'from lmdeploy.archs import autoget_backend;print(autoget_backend("InternVL2-40B"))'
# output turbomind

**Comment by Tendo33** [comment]
Same issue here, but I'm using the` InternVL2-40B-AWQ `model and `lmdeploy` is the latest version`==0.5.2.post1`.
This is my script:
```
export CUDA_VISIBLE_DEVICES=3

python3 -m lmdeploy serve api_server \
    "/workspace/share_data/base_llms/InternVL2-26B-AWQ" \
    --backend turbomind \
    --server-name "xxxxx" \
    --server-port xxx \
    --tp 1 \
    --model-format awq \
    --cache-max-entry-count 0.7 \
    --max-batch-size 256 \
    --model-name "InternVL2-40B-AWQ" \
    --log-level INFO \
    --quant-policy 8 \
    --enable-prefix-caching
```

**Comment by RunningLeon** [comment]
> Same issue here, but I'm using the`InternVL2-40B-AWQ`model and `lmdeploy` is the latest version`==0.5.2.post1`. This is my launch script:
> 
> ```
> export CUDA_VISIBLE_DEVICES=3
> 
> python3 -m lmdeploy serve api_server \
>     "/workspace/share_data/base_llms/InternVL2-26B-AWQ" \
>     --backend turbomind \
>     --server-name "xxxxx" \
>     --server-port xxx \
>     --tp 1 \
>     --model-format awq \
>     --cache-max-entry-count 0.7 \
>     --max-batch-size 256 \
>     --model-name "InternVL2-40B-AWQ" \
>     --log-level INFO \
>     --quant-policy 8 \
>     --enable-prefix-caching
> ```

@Tendo33 Hi, sorry for the trouble. Can you post info by running `lmdeploy check_env`?

**Comment by Tendo33** [comment]
@RunningLeon ah ok 
```
(lmdeploy) ➜  nature_data lmdeploy check_env     
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A800-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.2+
transformers: 4.43.1
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.2.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity
GPU0     X      NV2     NV2     NV2     0-15,32-47      0
GPU1    NV2      X      NV2     NV2     0-15,32-47      0
GPU2    NV2     NV2      X      NV4     16-31,48-63     1
GPU3    NV2     NV2     NV4      X      16-31,48-63     1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by RunningLeon** [comment]
@Tendo33 can you run `python -c 'from lmdeploy.archs import autoget_backend;print(autoget_backend("/workspace/share_data/base_llms/InternVL2-26B-AWQ"))'

**Comment by RunningLeon** [comment]
@Tendo33 hi, the cause is the mismatch of transformers version. pls downgrade your transformers to https://huggingface.co/OpenGVLab/InternVL2-26B-AWQ/blob/7c8f2e6acacd4d974496e0391f16d9f34dcb877d/config.json#L104 .

You can verify with 
```
python -c 'from transformers import AutoConfig; print(AutoConfig.from_pretrained("/workspace/share_data/base_llms/InternVL2-26B-AWQ", trust_remote_code=True))'
```

**Comment by Tendo33** [comment]
> @Tendo33 hi, the cause is the mismatch of transformers version. pls downgrade your transformers to https://huggingface.co/OpenGVLab/InternVL2-26B-AWQ/blob/7c8f2e6acacd4d974496e0391f16d9f34dcb877d/config.json#L104 .
> 
> You can verify with
> 
> ```
> python -c 'from transformers import AutoConfig; print(AutoConfig.from_pretrained("/workspace/share_data/base_llms/InternVL2-26B-AWQ", trust_remote_code=True))'
> ```
Thanks, it's working now.👍

**Comment by xrc10** [comment]
I solve this by setting `HF_HOME` to the path with correct permission.
