### ISSUE TITLE
密集请求之后的报错

### ISSUE THREAD

**Issue by PredyDaddy** [InternLM/lmdeploy#2135]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

当我使用lmdeploy部署qwenvl，我是用了下面的指令， 
```bash
lmdeploy serve api_server /data/cqy/vlm_weights/qwen/Qwen-VL-Chat --server-port 23333
```

然后当我密集的去调用的时候发现了这些问题
```bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/vl/engine.py", line 82, in _work_thread
    self.loop.run_until_complete(self._forward_loop())
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/vl/engine.py", line 98, in _forward_loop
    outputs = self.forward(inputs)
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/vl/engine.py", line 106, in forward
    outputs = self.model.forward(inputs)
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/vl/model/qwen.py", line 68, in forward
    outputs = [x.convert('RGB') for x in images]
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/vl/model/qwen.py", line 68, in <listcomp>
    outputs = [x.convert('RGB') for x in images]
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/PIL/Image.py", line 995, in convert
    self.load()
  File "/home/len1/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/PIL/ImageFile.py", line 290, in load
    raise OSError(msg)
OSError: image file is truncated (49 bytes not processed)

```

### Reproduction

我密集的请求，用这种方式，请求多了就会变成这样

```python
from openai import OpenAI
import base64

def generate_image_description(image_path, prompt):
    # 将图片转换为 base64 格式
    def image_to_base64(image_path):
        with open(image_path, "rb") as image_file:
            return base64.b64encode(image_file.read()).decode('utf-8')

    client = OpenAI(api_key='YOUR_API_KEY', base_url='http://0.0.0.0:23333/v1')
    model_name = client.models.list().data[0].id

    # 获取本地图片路径并转换为 base64 格式
    image_base64 = image_to_base64(image_path)

    # 创建 base64 图片 URL
    image_url = f"data:image/jpeg;base64,{image_base64}"

    response = client.chat.completions.create(
        model=model_name,
        messages=[{
            'role': 'user',
            'content': [{
                'type': 'text',
                'text': prompt,
            }, {
                'type': 'image_url',
                'image_url': {
                    'url': image_url,
                },
            }],
        }],
        temperature=0.8,
        top_p=0.8
    )

    return response

if __name__ == "__main__":
    # 使用示例
    image_path = 'media/demo.jpeg'
    prompt = '描述这张图片'
    response = generate_image_description(image_path, prompt)
    print(response)

```

### Environment

```Shell
环境部分我使用了conda pip安装也通过最新的镜像安装仍然不行
```

**Comment by irexyc** [comment]
这个报错应该跟密集请求关系不大，从你的日志上来看，是 `x.convert('RGB')` 这个话挂掉了，挂掉的原因应该是个别图片损坏了，你应该用的是不同的图片对吧？

**Comment by PredyDaddy** [comment]
> 这个报错应该跟密集请求关系不大，从你的日志上来看，是 `x.convert('RGB')` 这句话挂掉了，挂掉的原因应该是个别图片损坏了，你应该用的是不同的图片对吧？

是的，有一个线程不停地存图片到那个路径

**Comment by irexyc** [comment]
可以传本地路径（openai格式的http url 换成本地路径），不过不管是base64，还是地址。最好先用 convert('RGB') 来测试下图片的完整性，然后再传给server，lmdeploy 目前对这种异常没怎么处理。

**Comment by PredyDaddy** [comment]
> 可以传本地路径（openai格式的http url 换成本地路径），不过不管是base64，还是地址。最好先用 convert('RGB') 来测试下图片的完整性，然后再传给server，lmdeploy 目前对这种异常没怎么处理。

from openai import OpenAI

client = OpenAI(api_key='YOUR_API_KEY', base_url='http://192.168.4.251:23333/v1')
model_name = client.models.list().data[0].id
response = client.chat.completions.create(
    model=model_name,
    messages=[{
        'role':
        'user',
        'content': [{
            'type': 'text',
            'text': 'Describe the image please',
        }, {
            'type': 'image_url',
            'image_url': {
                'url':
                'media/snapshot.jpg',
            },
        }],
    }],
    temperature=0.8,
    top_p=0.8)
print(response)

我试过使用这种方式来传本地路径，服务起在另外一台主机上，这样是不行的，请问有更好的本地图片访问方法吗？

**Comment by irexyc** [comment]
不在一个机器上那就不能用本地路径了。这种情况base64方便一些。

**Comment by PredyDaddy** [comment]
感谢
