### ISSUE TITLE
[Feature] Loading InternVL2-40B-AWQ within 24GB of VRAM

### ISSUE THREAD

**Issue by josephrocca** [InternLM/lmdeploy#2162]
### Motivation

I've been testing InternVL2-40B today (as an alternative to Sonnet 3.5) and it's is an *amazing* model.

On a 48GB GPU, the AWQ version uses 42% of the VRAM - i.e. about 20.16 GB. So it seems like it should fit on a 24GB GPU (with limited context), which could roughly halve the cost to run it (when task is not throughput-bound). But I get an OOM when trying to load it, and I'm wondering if this is caused by the init/loading process using more VRAM than is 'technically' needed?

Here's what I tried on a 4090 using `openmmlab/lmdeploy:v0.5.2.post1`:
```
pip install timm==1.0.7 # For some reason I had to install `timm` because I was giving me a module not found error
lmdeploy serve api_server OpenGVLab/InternVL2-40B-AWQ --model-name OpenGVLab/InternVL2-40B-AWQ --server-port 3000 --session-len 500 --model-format awq --quant-policy 4 --log-level INFO
```
As you can see, I reduced the session length significantly to try to see if that was the issue, but it doesn't seem to help.

And here are the logs with the OOM error at the end (I'm not sure if I should be concerned about the `use_flash_attn` warning?):
```
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
2024-07-26 18:40:43,651 - lmdeploy - [37mINFO[0m - matching vision model: InternVLVisionModel
FlashAttention is not installed.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
Warning: Flash Attention is not available, use_flash_attn is set to False.
2024-07-26 18:40:55,369 - lmdeploy - [37mINFO[0m - using InternVL-Chat-V1-5 vision preprocess
2024-07-26 18:40:55,369 - lmdeploy - [37mINFO[0m - input backend=turbomind, backend_config=TurbomindEngineConfig(model_name='OpenGVLab/InternVL2-40B-AWQ', model_format='awq', tp=1, session_len=500, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=4, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
2024-07-26 18:40:55,369 - lmdeploy - [37mINFO[0m - input chat_template_config=None
2024-07-26 18:40:55,372 - lmdeploy - [37mINFO[0m - updated chat_template_onfig=ChatTemplateConfig(model_name='internvl2-internlm2', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-07-26 18:40:55,372 - lmdeploy - [37mINFO[0m - model_source: hf_model
2024-07-26 18:40:55,372 - lmdeploy - [33mWARNING[0m - model_name is deprecated in TurbomindEngineConfig and has no effect
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
Unrecognized keys in `rope_scaling` for 'rope_type'='dynamic': {'type'}
2024-07-26 18:41:04,990 - lmdeploy - [37mINFO[0m - model_config:

[llama]
model_name = internvl2-internlm2
model_arch = InternVLChatModel
tensor_para_size = 1
head_num = 56
kv_head_num = 8
vocab_size = 64007
num_layer = 60
inter_size = 20480
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 7
session_len = 500
weight_type = int4
rotary_embedding = 128
rope_theta = 5000000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = False
num_tokens_per_iter = 8192
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 4
max_position_embeddings = 8192
original_max_position_embeddings = 0
rope_scaling_type = 
rope_scaling_factor = 3.0
use_dynamic_ntk = 1
low_freq_factor = 1.0
high_freq_factor = 1.0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 


[TM][WARNING] [LlamaTritonModel] `max_context_token_num` = 500.
Traceback (most recent call last):
  File "/opt/py38/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 298, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1285, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 24, in __init__
    super().__init__(model_path, **kwargs)
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 190, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 235, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 340, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 251, in _from_hf
    self._create_weight(model_comm)
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 170, in _create_weight
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 163, in _create_weight_func
    model_comm.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /opt/lmdeploy/src/turbomind/utils/memory_utils.cu:32 
```

**Comment by josephrocca** [comment]
I'm not familiar with the details, so it's only a guess, but could it have something to do with `num_tokens_per_iter` being so high? I.e. some sort of preallocation for that? And if so, is it possible yet to set `num_tokens_per_iter` via the command line arguments?

**Comment by lvhan028** [comment]
Hi, @josephrocca 
LMDeploy didn't quantize the vision part of Vision-Language models (VLMs). 

During runtime, it first loads the vision part of the VLMs, and then the LLM part. 
The vision part of InternVL2-40B-AWQ is [InternViT-6B-448px-V1-5](https://huggingface.co/OpenGVLab/InternViT-6B-448px-V1-5), making the memory footprint is 12G, because it is not quantized. 

Therefore, it leaves 48G-12G = 36G for the LLM part - [Nous-Hermes-2-Yi-34B](https://huggingface.co/NousResearch/Nous-Hermes-2-Yi-34B)

After AWQ quantization, its memory footprint is 17G, leaving 36 - 17 = 19G for the KV cache and the temp buffer used during inference. 

We haven't analyzed the memory in detail yet, will let you know if there is any update

**Comment by josephrocca** [comment]
Oh nice! Thanks, Stefan. I haven't tested it, but I'll close this as solved for now - I can re-open it later if there are any issues.
