### ISSUE TITLE
[Bug] GLM-4v多卡离线推理存在bug

### ISSUE THREAD

**Issue by Jalen-Zhong** [InternLM/lmdeploy#2193]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

使用pipe针对glm-4v-9b多模态权重进行推理时，设置多卡存在bug。其任然执行单卡推理导致现存不足。

### Reproduction

运行如下.py脚本：
`from lmdeploy import pipeline, TurbomindEngineConfig
from lmdeploy.vl import load_image

model = 'ZhipuAI/glm-4v-9b'
image = load_image('./testfile/tiger.jpeg')
backend_config = TurbomindEngineConfig(model_format='awq', tp=4)
pipe = pipeline(model, backend_config=backend_config, log_level='INFO')
response = pipe(('describe this image', image))
print(response.text)
`

### Environment

```Shell
Ubuntu==18.04
lmdeploy==0.5.2
python==3.9
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/data/jalen/intervl2-8B/inference_demo.py", line 7, in <module>
    pipe = pipeline(model, backend_config=backend_config, log_level='INFO')
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/lmdeploy/api.py", line 89, in pipeline
    return pipeline_class(model_path,
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/lmdeploy/serve/vl_async_engine.py", line 21, in __init__
    self.vl_encoder = ImageEncoder(model_path,
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/lmdeploy/vl/engine.py", line 85, in __init__
    self.model = load_vl_model(model_path, backend_config=backend_config)
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/lmdeploy/vl/model/builder.py", line 55, in load_vl_model
    return module(**kwargs)
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/lmdeploy/vl/model/base.py", line 31, in __init__
    self.build_model()
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/lmdeploy/vl/model/glm_4v.py", line 66, in build_model
    load_checkpoint_and_dispatch(
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/accelerate/big_modeling.py", line 613, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 1821, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/root/anaconda3/envs/internvl2/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 381, in set_module_tensor_to_device
    value = value.to(dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 54.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 15.88 MiB is free. Process 33072 has 10.88 GiB memory in use. Process 22634 has 1.39 GiB memory in use. Process 22663 has 1.39 GiB memory in use. Including non-PyTorch memory, this process has 9.98 GiB memory in use. Of the allocated memory 9.36 GiB is allocated by PyTorch, and 336.62 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by efsotr** [comment]
I encountered a similar issue, but downgrading lmdeploy to version 0.5.1 resolved it.

**Comment by Jalen-Zhong** [comment]
> I encountered a similar issue, but downgrading lmdeploy to version 0.5.1 resolved it.

Thanks, i'll try.

**Comment by Jalen-Zhong** [comment]
> I encountered a similar issue, but downgrading lmdeploy to version 0.5.1 resolved it.

Thanks for your suggestion. I tried to downgrading lmdeploy to version 0.5.1, but the problem still wait to be solving.

**Comment by lvhan028** [comment]
As far as I remember, there are only 2 kv_heads. 
LMDeploy cannot divide them into 4 GPUs.

So, only tp=2 is supported for glm-4v and glm4-9b-chat
