### ISSUE TITLE
benchmark llama-2-7b on A10G(out of memory)

### ISSUE THREAD

**Issue by Laych7** [InternLM/lmdeploy#220]
目前服务已经在docker上启动:
I0811 08:50:19.938032 1 grpc_server.cc:4819] Started GRPCInferenceService at 0.0.0.0:33337
I0811 08:50:19.938092 1 http_server.cc:184] Started Metrics Service at 0.0.0.0:8002

python3 lmdeploy/benchmark/profile_throughput.py vllm/benchmarks/ShareGPT_V3_unfiltered_cleaned_split.json workspace --concurrency 64

报错：
Exception in thread Thread-139:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leichenghao/.local/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 200, in _func
    output = self.model_insts[device_id].forward(
AttributeError: 'NoneType' object has no attribute 'forward'
Exception in thread Thread-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/leichenghao/.local/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 189, in _create_model_instance
    model_inst = self.tm_model.model.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/triton_backend/llama/LlamaTritonModel.cc:187

**Comment by Laych7** [comment]
don't run :bash workspace/service_docker_up.sh
...
