### ISSUE TITLE
[Bug] interenvl2 auto_awq quant failed

### ISSUE THREAD

**Issue by janelu9** [InternLM/lmdeploy#2244]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

```
Traceback (most recent call last):
  File "/opt/conda/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
    auto_awq(**kwargs)
  File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/lmdeploy/lite/apis/auto_awq.py", line 150, in auto_awq
    save_vl_model(vl_model, model_path, work_dir)
  File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/lmdeploy/lite/apis/auto_awq.py", line 47, in save_vl_model
    vl_model.save_pretrained(dst_path,
  File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2661, in save_pretrained
    shard = {tensor: state_dict[tensor] for tensor in tensors}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/e/conda-py311-cu118-torch21/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2661, in <dictcomp>
    shard = {tensor: state_dict[tensor] for tensor in tensors}
                     ^^^^^^^^^^
NameError: cannot access free variable 'state_dict' where it is not associated with a value in enclosing scope
```
### Reproduction

`lmdeploy lite auto_awq internvl2 --work-dir internvl2-4bit`

### Environment

```Shell
LMDeploy>=0.5.1
CUDA 11.8
torch==2.1.2
```

**Comment by janelu9** [comment]
修改了存储的批大小大于2G成功了
```
    vl_model.save_pretrained(dst_path,
                             **max_shard_size='10GB',**
                             safe_serialization=safe_serialization)
```

**Comment by AllentDan** [comment]
这个问题是 transformers 的 bug，已经修过了。
