### ISSUE TITLE
[Bug] ImportError: cannot import name 'VLAsyncEngine'

### ISSUE THREAD

**Issue by LSC527** [InternLM/lmdeploy#2247]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

ImportError: cannot import name 'VLAsyncEngine' from partially initialized module 'lmdeploy.serve.vl_async_engine'

### Reproduction

```python
from lmdeploy import pipeline, GenerationConfig, TurbomindEngineConfig, ChatTemplateConfig
from lmdeploy.vl import load_image

if __name__ == '__main__':
    pipe = pipeline(
        '/home/work/MiniCPM-Llama3-V-2_5',
        backend_config=TurbomindEngineConfig(tp=2, session_len=2048),
    )
    gen_config = GenerationConfig(temperature=0.0)
    image = load_image('./data/000d995c59608ed2b40e66cc1c2e5231.jpg')
    question = "请描述图片"
    response = pipe((question, image), gen_config=gen_config)
    print(response)
```

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA A30
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.2.2+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.2 (Git Hash 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.2.2, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.17.2+cu121
LMDeploy: 0.5.2.post1+
transformers: 4.43.3
gradio: Not Found
fastapi: 0.111.1
pydantic: 2.7.1
triton: 2.2.0
NVIDIA Topology:
	GPU0	GPU1	GPU2	GPU3	CPU Affinity	NUMA Affinity
GPU0	 X 	SYS	SYS	SYS	0-127		N/A
GPU1	SYS	 X 	SYS	SYS	0-127		N/A
GPU2	SYS	SYS	 X 	SYS	0-127		N/A
GPU3	SYS	SYS	SYS	 X 	0-127		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/work/minicpm_test/minicpm_lmdeploy.py", line 5, in <module>
    pipe = pipeline(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/api.py", line 72, in pipeline
    _, pipeline_class = get_task(model_path)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/archs.py", line 147, in get_task
    from lmdeploy.serve.vl_async_engine import VLAsyncEngine
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/vl_async_engine.py", line 10, in <module>
    from lmdeploy.vl.templates import VLPromptType, get_vl_prompt_template
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/vl/templates.py", line 4, in <module>
    pipe = pipeline(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/api.py", line 72, in pipeline
    _, pipeline_class = get_task(model_path)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/archs.py", line 147, in get_task
    from lmdeploy.serve.vl_async_engine import VLAsyncEngine
ImportError: cannot import name 'VLAsyncEngine' from partially initialized module 'lmdeploy.serve.vl_async_engine' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/vl_async_engine.py)
```

**Comment by irexyc** [comment]
```
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/vl/templates.py", line 4, in <module>
    pipe = pipeline(
```

This line is strange as [line 4 is empty](https://github.com/InternLM/lmdeploy/blob/main/lmdeploy/vl/templates.py#L4)

Could you check this file (/usr/local/lib/python3.10/dist-packages/lmdeploy/vl/templates.py) contents?

**Comment by LSC527** [comment]
Sry, my mistake. I was picking https://github.com/InternLM/lmdeploy/pull/2139 and copy some wrong code to `lmdeploy/vl/templates.py` 
Thanks!
