### ISSUE TITLE
[Bug] lmdeploy 在加载auto_awq 之后的 llava 模型之后显示没有 output.weight

### ISSUE THREAD

**Issue by Skyseaee** [InternLM/lmdeploy#2264]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在加载进行 auto_awq 的模型之后时候有
`[WARN  ][pid:14345][tid:14345][turbomind.py:277]the model may not be loaded successfully with 1 uninitialized params:  
['output.weight'] `
之后在推理的时候会报错 `IndexError: piece id is out of range.`

### Reproduction

awq 的命令是 python3 -m lmdeploy.lite.apis.auto_awq ../llava_compass/llava-1.5-merged-2/ --calib-dataset wikitext2 --calib-samples 128 --calib-seqlen 2048 --w-bits 4 --w-group-size 128 --work-dir tmp/llava-1.5-int4-0808/ 
服务启动的命令是 lmdeploy serve api_server ./downloads/vlm/tmp/ --server-name 0.0.0.0 --server-port 2333 --vision-max-batch-size 8 --tp 1 --model-name llava-v1 --model-foramt awq

### Environment

```Shell
/opt/py38/lib/python3.8/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/opt/py38/lib/python3.8/site-packages/torchvision/image.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
sys.platform: linux
Python: 3.8.10 (default, Jul 29 2024, 17:02:10) [GCC 9.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A100 80GB PCIe
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 2.3.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.16.2+cu121
LMDeploy: 0.4.2.1+
transformers: 4.37.2
gradio: 4.16.0
fastapi: 0.111.1
pydantic: 2.8.2
triton: 2.3.1
```

### Error traceback

```Shell
具体报错

INFO:     127.0.0.1:32950 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/py38/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/py38/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/py38/lib/python3.8/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/py38/lib/python3.8/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/py38/lib/python3.8/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/py38/lib/python3.8/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/opt/py38/lib/python3.8/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/opt/py38/lib/python3.8/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 508, in chat_completions_v1
    async for res in result_generator:
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 683, in generate
    response, state = self.tokenizer.detokenize_incrementally(
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 571, in detokenize_incrementally
    return self.model.detokenize_incrementally(
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 427, in detokenize_incrementally
    new_tokens = tokenizer.convert_ids_to_tokens(
  File "/opt/py38/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/root/.cache/huggingface/modules/transformers_modules/tokenizer_compass.py", line 191, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
  File "/opt/py38/lib/python3.8/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/opt/py38/lib/python3.8/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')


整个 log 是
024-08-08 09:10:42,588 - lmdeploy - WARNING - AutoConfig.from_pretrained failed for ./downloads/vlm/tmp/. Exception: The checkpoint you are trying to load has model type `llava_llama` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
/opt/py38/lib/python3.8/site-packages/huggingface_hub/file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
2024-08-08T09:10:52.420172+0000 [INFO  ][pid:15131][tid:15131][async_engine.py:177]input backend=turbomind, backend_config=TurbomindEngineConfig(model_name='llava-v1', model_format='awq', tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
2024-08-08T09:10:52.420481+0000 [INFO  ][pid:15131][tid:15131][async_engine.py:179]input chat_template_config=None
2024-08-08T09:10:52.424641+0000 [INFO  ][pid:15131][tid:15131][async_engine.py:201]updated chat_template_onfig=ChatTemplateConfig(model_name='llava-v1', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-08-08T09:10:52.424952+0000 [WARN  ][pid:15131][tid:15131][turbomind.py:358]model_source: hf_model
2024-08-08T09:10:52.425099+0000 [WARN  ][pid:15131][tid:15131][turbomind.py:78]model_name is deprecated in TurbomindEngineConfig and has no effect
2024-08-08T09:10:54.677272+0000 [INFO  ][pid:15131][tid:15131][turbomind.py:258]model_config:

[llama]
model_name = base
model_arch = LlavaLlamaForCausalLM
tensor_para_size = 1
head_num = 40
kv_head_num = 40
vocab_size = 84096
num_layer = 40
inter_size = 13824
norm_eps = 1e-05
attn_bias = 0
start_id = 1
end_id = 2
session_len = 4096
weight_type = int4
rotary_embedding = 128
rope_theta = 10000.0
size_per_head = 128
group_size = 128
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.8
cache_block_seq_len = 64
cache_chunk_size = -1
enable_prefix_caching = False
num_tokens_per_iter = 8192
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 4096
rope_scaling_factor = 0.0
use_dynamic_ntk = 0
use_logn_attn = 0
lora_policy = 
lora_r = 0
lora_scale = 0.0
lora_max_wo_r = 0
lora_rank_pattern = 
lora_scale_pattern = 
tie_word_embeddings = 0
use_normhead = 0


2024-08-08T09:10:54.955841+0000 [WARN  ][pid:15131][tid:15131][turbomind.py:272]get 403 model params
2024-08-08T09:11:01.210602+0000 [WARN  ][pid:15131][tid:15131][turbomind.py:277]the model may not be loaded successfully with 1 uninitialized params:  
['output.weight']
2024-08-08T09:11:01.414324+0000 [INFO  ][pid:15131][tid:15131][async_engine.py:217]updated backend_config=TurbomindEngineConfig(model_name='llava-v1', model_format='awq', tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[WARNING] gemm_config.in is not found; using default GEMM algo
HINT:    Please open http://0.0.0.0:2333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:2333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:2333 in a browser for detailed api usage!!!
INFO:     Started server process [15131]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:2333 (Press CTRL+C to quit)
INFO:     127.0.0.1:32948 - "GET /v1/models HTTP/1.1" 200 OK
2024-08-08 09:12:32,305 - lmdeploy - INFO - start ImageEncoder._forward_loop
2024-08-08 09:12:32,306 - lmdeploy - INFO - ImageEncoder received 1 images, left 1 images.
2024-08-08 09:12:32,306 - lmdeploy - INFO - ImageEncoder process 1 images, left 0 images.
2024-08-08 09:12:33,193 - lmdeploy - INFO - ImageEncoder forward 1 images, cost 0.887s
2024-08-08 09:12:33,193 - lmdeploy - INFO - ImageEncoder done 1 images, left 0 images.
2024-08-08T09:12:34.032561+0000 [WARN  ][pid:15131][tid:15131][turbomind.py:477]kwargs request_output_len is deprecated for inference, use GenerationConfig instead.
2024-08-08T09:12:34.037941+0000 [WARN  ][pid:15131][tid:15131][async_engine.py:339]stop_session cancel successfully
INFO:     127.0.0.1:32950 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
```

**Comment by irexyc** [comment]
看log有两个问题。

一个是output.weight，这个可以检查下 `./downloads/vlm/tmp/` 你的模型文件夹，看下权重index文件是不是有 `lm_head.weight` 这个权重。这个权重没初始化的话，会影响推理的结果，不会报错。

第二个问题是报错的这里，token id decode的时候报错了。
```
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 571, in detokenize_incrementally
    return self.model.detokenize_incrementally(
  File "/opt/lmdeploy/lmdeploy/tokenizer.py", line 427, in detokenize_incrementally
    new_tokens = tokenizer.convert_ids_to_tokens(
  File "/opt/py38/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 982, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/root/.cache/huggingface/modules/transformers_modules/tokenizer_compass.py", line 191, in _convert_id_to_token
    token = self.sp_model.IdToPiece(index)
```

问题不是很好猜，最好能把模型上传到hf或者modelscope上面再来看一下。

**Comment by Skyseaee** [comment]
啊 我们这边发现问题了，我们稍微改了一下模型然后config.json 里面tie_word_embedding需要是true，但 awq 好像我看是会把这个参数强制转成 false 好像，我们后面手动改了一下就好了

**Comment by lvhan028** [comment]
Is it a bug of `lmdeploy lite auto_awq`? @AllentDan

**Comment by AllentDan** [comment]
> Is it a bug of `lmdeploy lite auto_awq`? @AllentDan

No, it is not.
