### ISSUE TITLE
i want to run profile_throughput.py using the smooth_quant model. Why did an error occur?

### ISSUE THREAD

**Issue by zxy1119** [InternLM/lmdeploy#2295]
python profile_throughput.py /dataset/ShareGPT_V3_unfiltered_cleaned_split.json /model/llama2-7b-w8/

我想测试 smooth 量化后的推理性能，出现下面的错误，是什么原因导致的。
Convert to turbomind format:   0%|                                                 | 0/32 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/lmdeploy-main/benchmark/profile_throughput.py", line 348, in <module>
    main()
  File "/lmdeploy-main/benchmark/profile_throughput.py", line 334, in main
    engine = Engine(args.model_path, engine_config, csv=args.csv)
  File "/lmdeploy-main/benchmark/profile_throughput.py", line 77, in __init__
    tm_model = TurboMind.from_pretrained(model_path,
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 340, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 257, in _from_hf
    output_model.export()
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 289, in export
    self.export_transformer_block(bin, i)
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 61, in export_transformer_block
    self.save_split(qkv_w, f'layers.{i}.attention.w_qkv.weight', -1)
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 267, in save_split
    self.export_weight(split, f'{prefix}.{i}{ext}')
  File "/usr/local/python3.10.14_gcc8.5.0/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 234, in export_weight
    assert torch_tensor.dtype in [
AssertionError

**Comment by lvhan028** [comment]
turbomind engine doesn't support quantized models by smooth quant. 
Please try `--backend pytorch`

**Comment by zxy1119** [comment]
thank you， it has been solved.

**Comment by zxy1119** [comment]
> turbomind engine doesn't support quantized models by smooth quant. Please try `--backend pytorch`

 i use the quantized model by smooth quant ， Why hasn't the inference speed increased? 

`lmdeploy lite smooth_quant /model/llama2-7b-hf/ --work-dir /model/lmdeploy/llama2-7b-w8/`

`python profile_throughput.py /dataset/ShareGPT_V3_unfiltered_cleaned_split.json /model/llama2-7b-hf/ --backend pytorch`  result is 2850.681 token/s
but python profile_throughput.py /dataset/ShareGPT_V3_unfiltered_cleaned_split.json /model/lmdeploy/llama2-7b-w8/ --backend pytorch result is 2896.486 token/s
