### ISSUE TITLE
[Bug] LMDeploy docker image with finetuned InternVL model doesnt work

### ISSUE THREAD

**Issue by shiva-vardhineedi** [InternLM/lmdeploy#2301]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I have my model finetuned and uploaded to hugging face at ... https://huggingface.co/shivavardhineedi/mini_internVL_eval/
It works well with offline inference..
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/1c98144d-2537-4c79-8157-2fcc0bae0387">

but when i try to deploy it with lmdeploy server i get the following error:

`
[WARNING] gemm_config.in is not found; using default GEMM algo
August 13 12:35:21.116
Traceback (most recent call last):
August 13 12:35:21.116
  File "/opt/py3/bin/lmdeploy", line 33, in <module>
August 13 12:35:21.116
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
August 13 12:35:21.116
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
August 13 12:35:21.116
    args.run(args)
August 13 12:35:21.116
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 298, in api_server
August 13 12:35:21.116
    run_api_server(args.model_path,
August 13 12:35:21.116
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1285, in serve
August 13 12:35:21.116
    VariableInterface.async_engine = pipeline_class(
August 13 12:35:21.116
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 29, in __init__
August 13 12:35:21.116
    self.vl_prompt_template = get_vl_prompt_template(
August 13 12:35:21.116
  File "/opt/lmdeploy/lmdeploy/vl/templates.py", line 308, in get_vl_prompt_template
August 13 12:35:21.116
    assert type(chat_template) != type(BaseModel()), 'failed to match ' \
August 13 12:35:21.116
AssertionError: failed to match chat template, please explicit set chat_template_config
`

why is this not working with lmdeploy server... base model (https://huggingface.co/OpenGVLab/Mini-InternVL-Chat-2B-V1-5) works fine though..

### Reproduction

docker run --runtime nvidia --gpus all \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    --env "HUGGING_FACE_HUB_TOKEN=<secret>" \
    -p 23333:23333 \
    --ipc=host \
    openmmlab/lmdeploy:latest \
    lmdeploy serve api_server shivavardhineedi/mini_internVL_eval

### Environment

```Shell
FROM openmmlab/lmdeploy:latest

RUN apt-get update && apt-get install -y python3 python3-pip git

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install timm
RUN pip3 install git+https://github.com/haotian-liu/LLaVA.git --no-deps

RUN pip install flash-attn

COPY . .

EXPOSE 8080

CMD ["lmdeploy", "serve", "api_server", "shivavardhineedi/mini_internVL_eval"]
```

**Comment by shiva-vardhineedi** [comment]
working fine once i change the docker image to `openmmlab/lmdeploy:v0.5.1`
