### ISSUE TITLE
[Bug] lmdeploy卡住，不能接收任何请求

### ISSUE THREAD

**Issue by thesby** [InternLM/lmdeploy#2302]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

模型一直正常运行，但是一旦遇到某个图片报错`OSError: image file is truncated`，就会卡住，不能接收任何请求

### Reproduction

No

### Environment

```Shell
sys.platform: linux
Python: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA A10
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: gcc (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3 2.17)
PyTorch: 2.1.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.1.1 (Git Hash 64f6bcbcbab628e96f33a62c3e975f8535a7bde4)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.7  (built against CUDA 12.2)
    - Built with CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-unused-private-field -Wno-aligned-allocation-unavailable -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.1.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.16.1+cu121
LMDeploy: 0.5.3+
transformers: 4.44.0
gradio: Not Found
fastapi: 0.109.0
pydantic: 2.5.3
triton: 2.1.0
NVIDIA Topology: 
  GPU0  CPU Affinity  NUMA Affinity GPU NUMA ID
GPU0   X        N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

```Shell
Exception in callback _raise_exception_on_finish(<Future finis...s truncated')>) at /home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/engine.py:19
handle: <Handle _raise_exception_on_finish(<Future finis...s truncated')>) at /home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/engine.py:19>
Traceback (most recent call last):
  File "/home/admin/miniconda3/lib/python3.10/site-packages/PIL/ImageFile.py", line 271, in load
    s = read(self.decodermaxblock)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 932, in load_read
    cid, pos, length = self.png.read()
  File "/home/admin/miniconda3/lib/python3.10/site-packages/PIL/PngImagePlugin.py", line 167, in read
    length = i32(s)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/PIL/_binary.py", line 85, in i32be
    return unpack_from(">I", c, o)[0]
struct.error: unpack_from requires a buffer of at least 4 bytes for unpacking 4 bytes at offset 0 (actual buffer size is 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/admin/miniconda3/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 26, in _raise_exception_on_finish
    raise e
  File "/home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 22, in _raise_exception_on_finish
    task.result()
  File "/home/admin/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/engine.py", line 151, in forward
    outputs = self.model.forward(inputs)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 171, in forward
    images = [x.convert('RGB') for x in images]
  File "/home/admin/miniconda3/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 171, in <listcomp>
    images = [x.convert('RGB') for x in images]
  File "/home/admin/miniconda3/lib/python3.10/site-packages/PIL/Image.py", line 922, in convert
    self.load()
  File "/home/admin/miniconda3/lib/python3.10/site-packages/PIL/ImageFile.py", line 278, in load
    raise OSError(msg) from e
OSError: image file is truncated
```

**Comment by irexyc** [comment]
对于这块的异常处理不是很完善。出错的原因是图片损坏导致convert('RGB')抛异常了。

目前比较推荐能在传请求之前先对图片做一次convert检查一下图片的完整性。

**Comment by lvhan028** [comment]
@irexyc Can we make up a dummy image in this case? At least to avoid the "hung" issue.

**Comment by RandomCoins** [comment]
请问这个问题什么时候解决，我也碰到了这个问题，我跑的图量比较大，先检查一遍url耗时会很久

**Comment by lvhan028** [comment]
着急的话，可以使用 #2312，按照 installation 文档源码编译 lmdeploy

**Comment by hupeng47** [comment]
我注意到 [#2312](https://github.com/InternLM/lmdeploy/pull/2312) 在release的0.6.0就修复了，为什么我现在用0.7.2部署仍然会出现卡住的问题呢？
