### ISSUE TITLE
[Bug] Qwen2-7B-Instruct-GPTQ-Int8  deploy error！

### ISSUE THREAD

**Issue by ldknight** [InternLM/lmdeploy#2368]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Traceback (most recent call last):
  File "/opt/conda/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 43, in run
    args.run(args)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 310, in api_server
    run_api_server(args.model_path,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1197, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 189, in __init__
    self._build_turbomind(model_path=model_path,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 234, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 342, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 237, in _from_hf
    output_model = OUTPUT_MODELS.get(output_model_name)(
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 26, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 168, in __init__
    self.cfg = self.get_config(cfg)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/fp.py", line 38, in get_config
    w1, _, _ = bin.ffn(i)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 110, in ffn
    return self._ffn(i, 'weight')
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/llama.py", line 103, in _ffn
    tensor = self.params[
KeyError: 'model.layers.0.mlp.gate_proj.weight'

### Reproduction

CUDA_VISIBLE_DEVICES=1 lmdeploy serve api_server qwen/Qwen2-7B-Instruct-GPTQ-Int8 --server-port 23333 --max-batch-size 128 --tp 1 --model-name Qwen2-7B-Instruct-GPTQ-Int8 --quant-policy 8

### Environment

```Shell
lmdeploy==0.5.0
```

**Comment by songyinghao** [comment]
使用 Qwen2-7B-Instruct-awq

**Comment by lvhan028** [comment]
lmdeploy hasn't support GPTQ-Int8 yet.

**Comment by lvhan028** [comment]
The latest released version 0.6.0a0 supports GPTQ-INT4 with group_size 128. 
If GPTQ-INT4 is an option, you may try the latest version.
