### ISSUE TITLE
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pppppM** [InternLM/lmdeploy#238]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

When running TurboMind with the precompiled package, libnccl cannot be found.

### Reproduction

I followed the steps in the [w4a16.md](https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md) document and installed lmdeploy first.
```
pip install lmdeploy
```
Then I downloaded the weights for `W4`.
```
git lfs install
git clone https://huggingface.co/lmdeploy/internlm-chat-7b-w4
```
I encountered this problem when executing the `deploy.py` script.
```
# Convert the model's layout and store it in the default path, ./workspace.
python3 -m lmdeploy.serve.turbomind.deploy \
    --model-name internlm \
    --model-path ./internlm-chat-7b-w4 \
    --model-format awq \
    --group-size 128

```

### Error traceback

```Shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/share/gaojianfei/anaconda3/envs/ops/lib/python3.11/site-packages/lmdeploy/serve/turbomind/deploy.py", line 834, in <module>
    fire.Fire(main)
  File "/share/gaojianfei/anaconda3/envs/ops/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/gaojianfei/anaconda3/envs/ops/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/share/gaojianfei/anaconda3/envs/ops/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/share/gaojianfei/anaconda3/envs/ops/lib/python3.11/site-packages/lmdeploy/serve/turbomind/deploy.py", line 804, in main
    res = deploy_awq(model_name, model_path, tokenizer_path,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/share/gaojianfei/anaconda3/envs/ops/lib/python3.11/site-packages/lmdeploy/serve/turbomind/deploy.py", line 580, in deploy_awq
    import _turbomind as _tm  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libnccl.so.2: cannot open shared object file: No such file or directory
```

**Comment by pppppM** [comment]
![image](https://github.com/InternLM/lmdeploy/assets/67539920/e3ec10cc-1c84-4efc-9175-b348ae0d1cca)

**Comment by irexyc** [comment]
fix rpath
https://github.com/InternLM/lmdeploy/pull/239
