### ISSUE TITLE
[Bug] 部署baichuan2-13b-chat报错，是不支持吗？

### ISSUE THREAD

**Issue by sxk000** [InternLM/lmdeploy#2405]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

首先，感谢上海人工智能实验室及其成员对书生模型、代码框架、技术经验的分享！

尝试用lmdeploy部署baichuan2-13b-chat时报错，是不支持吗？

谢谢！

### Reproduction

部署命令：

model='/apply/model/original/Baichuan2-13B-Chat'
CUDA_VISIBLE_DEVICES=3 /root/miniconda3/envs/p312lmdeploy/bin/python api_server.py --server-port 23353 --model_path $model --model-name baichuan2-13b-chat --cache-max-entry-count 0.97 --enable-prefix-caching --tp 1

### Environment

```Shell
环境：
cuda12.2
python3.12
lmdeploy0.5.1
```

### Error traceback

```Shell
2024-08-30 21:08:49,559 - lmdeploy - INFO - input backend=turbomind, backend_config=None
2024-08-30 21:08:49,559 - lmdeploy - INFO - input chat_template_config=None
2024-08-30 21:08:49,649 - lmdeploy - INFO - updated chat_template_onfig=ChatTemplateConfig(model_name='baichuan2', system=None, meta_instruction=None, eosys=None, user=None, eoh=None, assistant=None, eoa=None, separator=None, capability=None, stop_words=None)
2024-08-30 21:08:49,672 - lmdeploy - INFO - model_source: ModelSource.HF_MODEL
2024-08-30 21:08:49,672 - lmdeploy - WARNING - kwargs cache_max_entry_count is deprecated to initialize model, use TurbomindEngineConfig instead.
2024-08-30 21:08:49,672 - lmdeploy - WARNING - kwargs enable_prefix_caching is deprecated to initialize model, use TurbomindEngineConfig instead.
2024-08-30 21:08:49,672 - lmdeploy - WARNING - model_name is deprecated in TurbomindEngineConfig and has no effect
Traceback (most recent call last):
  File "/apply/app/llm/intern_api/api_server.py", line 1337, in <module>
    fire.Fire(serve)
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/apply/app/llm/intern_api/api_server.py", line 1295, in serve
    VariableInterface.async_engine = pipeline_class(
                                     ^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/lmdeploy/serve/async_engine.py", line 189, in __init__
    self._build_turbomind(model_path=model_path,
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/lmdeploy/serve/async_engine.py", line 234, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/lmdeploy/turbomind/turbomind.py", line 342, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/lmdeploy/turbomind/turbomind.py", line 144, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312lmdeploy/lib/python3.12/site-packages/lmdeploy/turbomind/turbomind.py", line 221, in _from_hf
    assert is_supported(model_path), (
           ^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: turbomind does not support /apply/model/original/Baichuan2-13B-Chat. Plz try pytorch engine instead.
```

**Comment by bingoohe** [comment]
同样的模型，/v1/completions可正常调用，/v1/chat/completions失败

**Comment by lvhan028** [comment]
@sxk000 baichuan-13b uses alibi for position embedding, which is not supported by turbomind engine.

**Comment by lvhan028** [comment]
> 同样的模型，/v1/completions可正常调用，/v1/chat/completions失败

which one?
