### ISSUE TITLE
[Bug] CUDA runtime error: operation not supported /lmdeploy/src/turbomind/utils/allocator.h:197

### ISSUE THREAD

**Issue by JingMo** [InternLM/lmdeploy#2414]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

RuntimeError: [TM][ERROR] CUDA runtime error: operation not supported /lmdeploy/src/turbomind/utils/allocator.h:197

### Reproduction

lmdeploy serve api_server --model-name internlm/internlm2_5-7b-chat --server-port 23333

from https://huggingface.co/internlm/internlm2-chat-7b

### Environment

```Shell
sys.platform: linux
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: GRID A100D-3-40C MIG 3g.40gb
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.91
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.1+cu121
LMDeploy: 0.5.3+
transformers: 4.41.0
gradio: 4.42.0
fastapi: 0.112.2
pydantic: 2.8.2
triton: 2.3.1
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-15    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

```Shell
2024-09-02 14:34:00,529 - lmdeploy - INFO - updated backend_config=TurbomindEngineConfig(model_name=None, model_format=None, tp=1, session_len=None, max_batch_size=128, cache_max_entry_count=0.8, cache_block_seq_len=64, enable_prefix_caching=False, quant_policy=0, rope_scaling_factor=0.0, use_logn_attn=False, download_dir=None, revision=None, max_prefill_token_num=8192, num_tokens_per_iter=0, max_prefill_iters=1)
[TM][DEBUG] Set logger level by DEBUG
[TM][DEBUG] turbomind::Allocator<turbomind::AllocatorType::CUDA>::Allocator(int, bool)
Traceback (most recent call last):
  File "/data01/MindSearch/l.py", line 2, in <module>
    pipe = lmdeploy.pipeline("internlm/internlm2_5-7b-chat", log_level='DEBUG')
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/site-packages/lmdeploy/api.py", line 89, in pipeline
    return pipeline_class(model_path,
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 218, in __init__
    self.gens_set.add(self.engine.create_instance())
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 356, in create_instance
    return TurboMindInstance(self, cuda_stream_id)
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 388, in __init__
    future.result()
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/data01/miniconda3/envs/mindsearch2/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 397, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: operation not supported /lmdeploy/src/turbomind/utils/allocator.h:197
```

**Comment by meoqi** [comment]
I have the same problem!

**Comment by lzhangzz** [comment]
Most likely you you are running CUDA 12 with a driver that only supports CUDA<11.2, or there is some settings in your system that failed to expose the whole stream-ordered allocation API to the CUDA runtime.

**Comment by JingMo** [comment]
| NVIDIA-SMI 550.90.07              |Driver Version: 550.90.07      |CUDA Version: 12.4     |
|---------------------------------------------|--------------------------|--------------------------|
| GPU  Name                   Persistence-M | Bus-Id              Disp.A |     Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                                             |                                   |                        MIG M. |
|   0  GRID A100D-3-40C                  On  |   00000000:02:00.0 Off |                             N/A |
| N/A   N/A    P0                  N/A /  N/A  |        1MiB /  40960MiB |            N/A      Default |
|                                                            |                                    |                       Enabled |


| MIG devices:     |                                         |                              |                          |
|-------------------|---------------------------------|------------|---------------------------|
| GPU  GI  CI  MIG |                     Memory-Usage |            Vol|                Shared           |
|          ID  ID  Dev |                          BAR1-Usage | SM     Unc| CE ENC DEC OFA JPG    |
|                           |                                              |           ECC|                                      |
|       0    0   0   0  |                1MiB / 37612MiB    |   42    N/A |  3   0    2    0    0      |
|                          |                   0MiB /  4096MiB  |                  |                                     |
                                                                                         

| Processes:                                                                              |
|--------------------------------------------|
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|  No running processes found                                                             |

**Comment by JingMo** [comment]
> Most likely you are running CUDA 12 with a driver that only supports CUDA<11.2, or there are some settings in your system that failed to expose the whole stream-ordered allocation API to the CUDA runtime.

driver support CUDA 12，but use 12.2 or 12.4，has the same problem!

**Comment by lvhan028** [comment]
I cannot reproduce it with lmdeploy 0.5.3 on A100
Can you try the openmmlab/lmdeploy:v0.5.3 docker image?
Let's eliminate environmental factors.

**Comment by lvhan028** [comment]
from the discussion with the community in https://github.com/InternLM/lmdeploy/issues/2416, it is noted that `openmmlab/lmdeploy:v0.5.3-cu12` failed because of cublas version is low. 
`openmmlab/lmdeploy:v0.5.3-cu11` can work. Could you give it a try?
Sorry for the inconvenience. 
Another solution is to change the base image in the Docerfile and rebuild the image

**Comment by JingMo** [comment]
1. I try to use **openmmlab/lmdeploy:v0.5.3-cu11**, but not resolved
```
docker pull openmmlab/lmdeploy:v0.5.3-cu11

admin:/data01/lmdeploy/docker$ docker run --runtime nvidia --gpus all \
    -v /data01/huggingface:/root/.cache/huggingface \>     -v /data01/huggingface:/root/.cache/huggingface \
>     -p 23333:23333 \
>     --ipc=host \
>     openmmlab/lmdeploy:v0.5.3-cu11 \
>     lmdeploy serve api_server internlm/internlm2_5-7b-chat

==========
== CUDA ==
==========

CUDA Version 11.8.0

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Fetching 20 files: 100%|██████████| 20/20 [00:00<00:00, 160394.03it/s]
Traceback (most recent call last):                                          
  File "/opt/py3/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 36, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 298, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1285, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 218, in __init__
    self.gens_set.add(self.engine.create_instance())
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 356, in create_instance
    return TurboMindInstance(self, cuda_stream_id)
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 388, in __init__
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/lmdeploy/lmdeploy/turbomind/turbomind.py", line 397, in _create_model_instance
    model_inst = self.tm_model.model_comm.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: operation not supported /opt/lmdeploy/src/turbomind/utils/allocator.h:197
```
2. Next, I use Dockerfile to rebuild the image with no success, something is wrong.
```
git clone https://github.com/InternLM/lmdeploy.git
cd lmdeploy/docker
```
```
docker build -t local/lmdeploy .

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            Install the buildx component to build images with BuildKit:
            https://docs.docker.com/go/buildx/

Sending build context to Docker daemon  13.31kB
Step 1/22 : ARG CUDA_VERSION=cu12
Step 2/22 : FROM nvidia/cuda:12.4.1-devel-ubuntu22.04 AS cu12
 ---> 013178411579
Step 3/22 : ENV CUDA_VERSION_SHORT=cu121
 ---> Using cache
 ---> f49b1a6e3f9e
Step 4/22 : FROM nvidia/cuda:11.8.0-devel-ubuntu22.04 AS cu11
 ---> 6f9cc9f1ba9e
Step 5/22 : ENV CUDA_VERSION_SHORT=cu118
 ---> Using cache
 ---> 03d5995945f2
Step 6/22 : FROM ${CUDA_VERSION} AS final
 ---> f49b1a6e3f9e
Step 7/22 : ARG PYTHON_VERSION=3.10
 ---> Using cache
 ---> 841fe59028aa
Step 8/22 : ARG TORCH_VERSION=2.3.0
 ---> Using cache
 ---> b712ec42c65f
Step 9/22 : ARG TORCHVISION_VERSION=0.18.0
 ---> Using cache
 ---> 5e1188e03ba5
Step 10/22 : RUN apt-get update -y && apt-get install -y software-properties-common wget vim git curl &&    curl https://sh.rustup.rs -sSf | sh -s -- -y &&    add-apt-repository ppa:deadsnakes/ppa -y && apt-get update -y && apt-get install -y --no-install-recommends     ninja-build rapidjson-dev libgoogle-glog-dev gdb python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv     && apt-get clean -y && rm -rf /var/lib/apt/lists/* && cd /opt && python3 -m venv py3
 ---> Using cache
 ---> fb437d59bec6
Step 11/22 : ENV PATH=/opt/py3/bin:$PATH
 ---> Using cache
 ---> 7b604fd7398d
Step 12/22 : RUN wget https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.5.tar.gz &&    tar xf openmpi-4.1.5.tar.gz && cd openmpi-4.1.5 && ./configure --prefix=/usr/local/openmpi &&    make -j$(nproc) && make install && cd .. && rm -rf openmpi-4.1.5*
 ---> Using cache
 ---> b8200a022f26
Step 13/22 : ENV PATH=$PATH:/usr/local/openmpi/bin
 ---> Using cache
 ---> fe9fd3af8886
Step 14/22 : ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/openmpi/lib
 ---> Using cache
 ---> 7a343f16ab84
Step 15/22 : RUN --mount=type=cache,target=/root/.cache/pip python3 -m pip install --upgrade pip setuptools==69.5.1 &&    python3 -m pip install torch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION} --index-url https://download.pytorch.org/whl/${CUDA_VERSION_SHORT} &&    python3 -m pip install cmake packaging wheel
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
```
this is end！

3. have another  solution？

**Comment by JingMo** [comment]
> from the discussion with the community in #2416, it is noted that `openmmlab/lmdeploy:v0.5.3-cu12` failed because of cublas version is low. `openmmlab/lmdeploy:v0.5.3-cu11` can work. Could you give it a try? Sorry for the inconvenience. Another solution is to change the base image in the Docerfile and rebuild the image


no success!

**Comment by JingMo** [comment]
> from the discussion with the community in #2416, it is noted that `openmmlab/lmdeploy:v0.5.3-cu12` failed because of cublas version is low. `openmmlab/lmdeploy:v0.5.3-cu11` can work. Could you give it a try? Sorry for the inconvenience. Another solution is to change the base image in the Docerfile and rebuild the image

**Comment by kksmi** [comment]
请问你解决了吗大佬

**Comment by tbup** [comment]
same issue! and rebuilt.  
images: openmmlab/lmdeploy:v0.6.0-cu11

nvidia-smi:
Driver Version: 525.147.05   CUDA Version: 12.0

**Comment by lvhan028** [comment]
I am sorry that we cannot reproduce this issue in our environment. 
Can anyone provide an env for us to access by `ssh`?

**Comment by Salingo** [comment]
I met the same error with LMDeploy 0.6.1
Here is the results of `check_env`:
```
Python: 3.8.20 (default, Oct  3 2024, 15:24:27) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: GRID V100D-32C
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.140
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.3) 9.4.0
PyTorch: 2.3.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.1+cu121
LMDeploy: 0.6.1+
transformers: 4.36.2
gradio: 4.44.1
fastapi: 0.115.0
pydantic: 2.9.2
triton: 2.3.1
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-7     0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by lvhan028** [comment]
From the above env info, I found "GPU 0: GRID V100D-32C" and "GPU 0: GRID A100D-3-40C MIG 3g.40gb"
We have no such GPUs. 
Can anyone share an env for us to access by `ssh`?

**Comment by lzhangzz** [comment]
Maybe related to this https://github.com/triton-inference-server/tensorrtllm_backend/issues/328

**Comment by tanpham380** [comment]
@lvhan028 I meet this error too on  Grid VGPU P40, How I can give u SSH connection?

**Comment by lvhan028** [comment]
@tanpham380 the architecture of P40 is Pascal, which is not supported.
You can find the supported nvidia device models by lmdeploy from [here](https://lmdeploy.readthedocs.io/en/latest/get_started/installation.html)

**Comment by tbup** [comment]
> same issue! and rebuilt. images: openmmlab/lmdeploy:v0.6.0-cu11
> 
> nvidia-smi: Driver Version: 525.147.05 CUDA Version: 12.0

@lvhan028 I meet this error on Grid VGPU A800. VGPU is not support?  
Sorry，due to the regulations, I am unable to provide you with an SSH connection.

**Comment by hridog00** [comment]
i'm facing the same problem

**Comment by lvhan028** [comment]
what the hell
I am going to find a similar env and check this issue

**Comment by lvhan028** [comment]
@zhulinJulia24 could you help setup an env on internstudio platform?
As far as I know, it uses vGPU

**Comment by zhulinJulia24** [comment]
> @zhulinJulia24 could you help setup an env on internstudio platform? As far as I know, it uses vGPU

cannot be reproduced on vGpu of internstudio 

![image](https://github.com/user-attachments/assets/6c9cc63d-3b58-4b2f-8da4-c035e2ec0488)
lmdeploy v0.6.1

**Comment by lvhan028** [comment]
@zhulinJulia24 can you share the information about `lmdeploy check_env` on internstudio platform?

**Comment by triangle959** [comment]
The same issue on windows server 2019. I notice that has a wrong path in error message 
```
RuntimeError: [TM][ERROR] CUDA runtime error: operation not supported D:\a\lmdeploy\lmdeploy\src/turbomind/utils/allocator.h:197
```

**env info**
```
sys.platform: win32
Python: 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:15:49) [MSC v.1941 64 bit (AMD64)]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1: Quadro RTX 6000
CUDA_HOME: D:\software\cuda12.0.0
NVCC: Cuda compilation tools, release 12.0, V12.0.140
MSVC: 用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.41.34120 版
GCC: n/a
PyTorch: 2.4.0+cu121
PyTorch compiling details: PyTorch built with:
  - C++ Version: 201703
  - MSVC 192930154
  - Intel(R) oneAPI Math Kernel Library Version 2024.2-Product Build 20240605 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.4.2 (Git Hash 1137e04ec0b5251ca2b4400a4fd3c667ce843d67)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 90.1  (built against CUDA 12.4)
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=9.1.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.4.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=OFF, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF,

TorchVision: 0.19.0+cu121
LMDeploy: 0.6.3+
transformers: 4.46.3
gradio: Not Found
fastapi: 0.115.5
pydantic: 2.10.2
triton: Not Found
```
