### ISSUE TITLE
[Bug] [Quantization] raise CUDA Error when calib_seqlen is large

### ISSUE THREAD

**Issue by PYNing** [InternLM/lmdeploy#250]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

may be associated with https://github.com/InternLM/lmdeploy/issues/249

I have tried to quantify  the **Llama-2-70b-hf** model with parameter “--calib_seqlen 4096”, but encountered  an CUDA error.

This error can be avoided by using a smaller parameter，like "--calib_seqlen 128".

Version: 0.5.0
Device: 4090*8

The weights were downloaded from HuggingFace without any modification.

### Reproduction

// will NOT rasie the CUDA error when calib_seqlen=128 
`python -m lmdeploy.lite.apis.calibrate --models Llama-2-70b-hf --calib_dataset 'wikitext2' --calib_samples 128 --calib_seqlen 128 --work_dir /tmp`

// will rasie the CUDA error when calib_seqlen=4096 
`python -m lmdeploy.lite.apis.calibrate --models Llama-2-70b-hf --calib_dataset 'wikitext2' --calib_samples 128 --calib_seqlen 4096 --work_dir /tmp`

### Error traceback

```Shell
Traceback (most recent call last):                                                                                                                                                                    
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main                                                                                                                                
    return _run_code(code, main_globals, None,                                                                                                                                                        
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code                                                                                                                                           
    exec(code, run_globals)                                                                                                                                                                           
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 110, in <module>                                                                                                
    fire.Fire(calibrate)                                                                                                                                                                              
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire                                                                                                                       
    component_trace = _Fire(component, args, parsed_flag_args, context, name)                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire                                                                                                                      
    component, remaining_args = _CallAndUpdateTrace(                                                                                                                                                  
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace                                                                                                        
    component = fn(*varargs, **kwargs)                                                                                                                                                                
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 101, in calibrate                                                                                               
    calib_ctx.calibrate(all_data)                                                                                                                                                                     
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/quantization/calibration.py", line 274, in calibrate                                                                                     
    _ = self.model.model(data.to(self.device))                                                                                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                                  
    return forward_call(*input, **kwargs)                                                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 693, in forward                                                                                     
    layer_outputs = decoder_layer(                                                                                                                                                                    
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                                  
    return forward_call(*input, **kwargs)                                                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/quantization/calibration.py", line 160, in _forward                                                                                      
    out = self._ori_forwards[mod](*batch_args[i],                                                                                                                                                     
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 408, in forward                                                                                     
    hidden_states, self_attn_weights, present_key_value = self.self_attn(                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl                                                                                                  
    return forward_call(*input, **kwargs)                                                                                                                                                             
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/llama/modeling_llama.py", line 305, in forward                                                                                     
    query_states = self.q_proj(hidden_states)                                                                                                                                                         
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl                                                                                                  
    result = forward_call(*input, **kwargs)                                                                                                                                                           
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/linear.py", line 114, in forward                                                                                                      
    return F.linear(input, self.weight, self.bias)                                                                                                                                                    
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

**Comment by pppppM** [comment]
During the calibration phase, we use the PyTorch model forward. This issue might occur when the tensor's shape is too large. 

The calibration length doesn't have to be consistent with the model's maximum length. For example, 512 was used in the AWQ paper.

**Comment by PYNing** [comment]
Thank you for reply.
