### ISSUE TITLE
[Bug] accelerate包发生'NoneType' object has no attribute '_parameters'

### ISSUE THREAD

**Issue by mouweng** [InternLM/lmdeploy#2543]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

当我自己根据DockerFile构建镜像，并运行Qwen-VL-Chat时，会出现如下错误：
```
2024-10-02 00:24:01,186 - lmdeploy - ERROR - builder.py:58 - matching vision model: QwenVisionModel failed
```
可以定位到是这一行代码发生错误：
```
  File "/opt/lmdeploy/lmdeploy/vl/model/qwen.py", line 39, in build_model
    device_map = infer_auto_device_map(
  File "/opt/py3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1238, in infer_auto_device_map
    tied_parameters = find_tied_parameters(model)
  ...
  AttributeError: 'NoneType' object has no attribute '_parameters'
```
所有使用了infer_auto_device_map的vl模型，在启动模型服务时，都会出现这个错误。

### Reproduction

运行命令如下：
```
lmdeploy serve api_server --server-name 0.0.0.0 --server-port 8080 /data00/Qwen-VL-Chat
```
报错结果如下：
```
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
2024-10-02 00:24:01,186 - lmdeploy - ERROR - builder.py:58 - matching vision model: QwenVisionModel failed
Traceback (most recent call last):
  File "/opt/py3/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 329, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1048, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 24, in __init__
    self.vl_encoder = ImageEncoder(model_path,
  File "/opt/lmdeploy/lmdeploy/vl/engine.py", line 90, in __init__
    self.model = load_vl_model(model_path, backend_config=backend_config)
  File "/opt/lmdeploy/lmdeploy/vl/model/builder.py", line 56, in load_vl_model
    return module(**kwargs)
  File "/opt/lmdeploy/lmdeploy/vl/model/base.py", line 31, in __init__
    self.build_model()
  File "/opt/lmdeploy/lmdeploy/vl/model/qwen.py", line 39, in build_model
    device_map = infer_auto_device_map(
  File "/opt/py3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1238, in infer_auto_device_map
    tied_parameters = find_tied_parameters(model)
  File "/opt/py3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 708, in find_tied_parameters
    all_named_parameters = {name: param for name, param in _get_named_parameters(model, remove_duplicate=False)}
  File "/opt/py3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 708, in <dictcomp>
    all_named_parameters = {name: param for name, param in _get_named_parameters(model, remove_duplicate=False)}
  File "/opt/py3/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 667, in _get_named_parameters
    members = module._parameters.items()
AttributeError: 'NoneType' object has no attribute '_parameters'
```

### Environment

```Shell
lmdeploy check_env

sys.platform: linux
Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.0+cu121
LMDeploy: 0.6.1+2e49fc3
transformers: 4.45.1
gradio: 4.44.0
fastapi: 0.115.0
pydantic: 2.9.2
triton: 2.3.0
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-31    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

看起来是accelerate包版本导致的错误，目前我构建的镜像里面，accelerate版本如下：
```Shell
# pip list | grep accelerate
accelerate                    0.34.2
```
而官方提供的镜像中`openmmlab/lmdeploy:v0.6.1-cu12`，accelerate版本也是一致，也会在启动模型，运行这行代码时发生报错。
当我对`accelerate`进行降级，则可以解决这个问题。
```
pip install accelerate==0.33.0
```
所以是否可以考虑对requirements下的依赖锁定accelerate版本来解决这个问题？

**Comment by irexyc** [comment]
accelerate 昨天发了1.0.0的版本，这个问题应该没有了。

https://github.com/huggingface/accelerate/pull/3052
