### ISSUE TITLE
TypeError: issubclass() arg 1 must be a class[Bug] 

### ISSUE THREAD

**Issue by GZL11** [InternLM/lmdeploy#255]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

命令行执行：python3 -m lmdeploy.serve.gradio.app ./workspace
报错：TypeError: issubclass() arg 1 must be a class

### Reproduction

python3 -m lmdeploy.serve.gradio.app ./workspace

### Error traceback

```Shell
ARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Traceback (most recent call last):
  File "/root/miniconda/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 336, in <module>
    fire.Fire(run)
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 332, in run
    run_local(model_path_or_server, server_name, server_port)
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 292, in run_local
    send_event = instruction_txtbox.submit(
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/gradio/blocks.py", line 195, in set_event_trigger
    check_function_inputs_match(fn, inputs, inputs_as_dict)
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/gradio/utils.py", line 940, in check_function_inputs_match
    if not is_special_typed_parameter(name):
  File "/root/miniconda/envs/py310/lib/python3.10/site-packages/gradio/utils.py", line 929, in is_special_typed_parameter
    is_event_data = issubclass(parameter_types.get(name, int), EventData)
TypeError: issubclass() arg 1 must be a class
```

**Comment by AllentDan** [comment]
Which version of gradio were you using? Please use the latest gradio.

**Comment by GZL11** [comment]
> Which version of gradio were you using? Please use the latest gradio.

Thank you for your reply. Upgrading to the latest version has resolved my issue
