### ISSUE TITLE
[Bug] 在 docker 方式运行 Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4， throw RuntimeError: Unsupported quant method: gptq

### ISSUE THREAD

**Issue by xukecheng** [InternLM/lmdeploy#2556]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在 docker 方式运行 Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4， throw RuntimeError: Unsupported quant method: gptq

### Reproduction

docker run
  -d
  --name='Qwen2VL'
  --net='app'
  --pids-limit 2048
  -e TZ="Asia/Shanghai"
  -e HOST_CONTAINERNAME="Qwen2VL"
  -e 'HF_HOME'='/models'
  -e 'HF_TOKEN'='12321312'
  -l net.unraid.docker.managed=dockerman
  -p '28000:23333/tcp'
  -v '/mnt/cache/appdata/pytorch/project/models':'/models':'rw'
  --ipc=host
  --runtime nvidia
  --gpus all 'openmmlab/lmdeploy:latest' /bin/bash
  -c "pip install git+https://github.com/huggingface/transformers.git && pip install qwen_vl_utils && lmdeploy serve api_server Qwen/Qwen2-VL-7B-Instruct-GPTQ-Int4
  --model-name qwen2-vl"

### Environment

```Shell
==========
== CUDA ==
==========

CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

sys.platform: linux
Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 4060 Ti
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.0+cu121
LMDeploy: 0.6.1+2e49fc3
transformers: 4.45.1
gradio: 4.44.0
fastapi: 0.115.0
pydantic: 2.9.2
triton: 2.3.0
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-7     0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### Error traceback

```Shell
日志如下：

==========
== CUDA ==
==========

CUDA Version 12.4.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Collecting git+https://github.com/huggingface/transformers.git
  Cloning https://github.com/huggingface/transformers.git to /tmp/pip-req-build-lavzx0sj
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers.git /tmp/pip-req-build-lavzx0sj
  Resolved https://github.com/huggingface/transformers.git to commit 0dbc7090bac3fb50f679a8a93516bdc67019c997
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: filelock in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (3.13.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (0.25.1)
Requirement already satisfied: numpy>=1.17 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (1.26.3)
Requirement already satisfied: packaging>=20.0 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (2024.9.11)
Requirement already satisfied: requests in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (2.32.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (0.20.0)
Requirement already satisfied: safetensors>=0.4.1 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /opt/py3/lib/python3.10/site-packages (from transformers==4.46.0.dev0) (4.66.5)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/py3/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.0.dev0) (2024.2.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/py3/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers==4.46.0.dev0) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/py3/lib/python3.10/site-packages (from requests->transformers==4.46.0.dev0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/py3/lib/python3.10/site-packages (from requests->transformers==4.46.0.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/py3/lib/python3.10/site-packages (from requests->transformers==4.46.0.dev0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/py3/lib/python3.10/site-packages (from requests->transformers==4.46.0.dev0) (2024.8.30)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml): started
  Building wheel for transformers (pyproject.toml): finished with status 'done'
  Created wheel for transformers: filename=transformers-4.46.0.dev0-py3-none-any.whl size=9966048 sha256=3094de564df08ea7d9d4a806a5372efd7b4ffd86ba8834ae5d08b812cafa5a6a
  Stored in directory: /tmp/pip-ephem-wheel-cache-ebkbdnw4/wheels/e7/9c/5b/e1a9c8007c343041e61cc484433d512ea9274272e3fcbe7c16
Successfully built transformers
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 4.45.1
    Uninstalling transformers-4.45.1:
      Successfully uninstalled transformers-4.45.1
Successfully installed transformers-4.46.0.dev0
Collecting qwen_vl_utils
  Downloading qwen_vl_utils-0.0.8-py3-none-any.whl.metadata (3.6 kB)
Collecting av (from qwen_vl_utils)
  Downloading av-13.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: packaging in /opt/py3/lib/python3.10/site-packages (from qwen_vl_utils) (24.1)
Requirement already satisfied: pillow in /opt/py3/lib/python3.10/site-packages (from qwen_vl_utils) (10.2.0)
Requirement already satisfied: requests in /opt/py3/lib/python3.10/site-packages (from qwen_vl_utils) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/py3/lib/python3.10/site-packages (from requests->qwen_vl_utils) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/py3/lib/python3.10/site-packages (from requests->qwen_vl_utils) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/py3/lib/python3.10/site-packages (from requests->qwen_vl_utils) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/py3/lib/python3.10/site-packages (from requests->qwen_vl_utils) (2024.8.30)
Downloading qwen_vl_utils-0.0.8-py3-none-any.whl (5.9 kB)
Downloading av-13.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.1/33.1 MB 16.2 MB/s eta 0:00:00
Installing collected packages: av, qwen_vl_utils
Successfully installed av-13.1.0 qwen_vl_utils-0.0.8
Fetching 17 files: 100%|██████████| 17/17 [00:00<00:00, 111935.90it/s]
2024-10-08 09:58:07,928 - lmdeploy - WARNING - archs.py:53 - Fallback to pytorch engine because `/models/hub/models--Qwen--Qwen2-VL-7B-Instruct-GPTQ-Int4/snapshots/dec510a35a3e9b6481b6427c7a08984df2402535` not supported by turbomind engine.
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Traceback (most recent call last):
  File "/opt/py3/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/opt/lmdeploy/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/opt/lmdeploy/lmdeploy/cli/serve.py", line 329, in api_server
    run_api_server(args.model_path,
  File "/opt/lmdeploy/lmdeploy/serve/openai/api_server.py", line 1045, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/opt/lmdeploy/lmdeploy/serve/vl_async_engine.py", line 27, in __init__
    super().__init__(model_path, **kwargs)
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 162, in __init__
    self._build_pytorch(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/serve/async_engine.py", line 210, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/engine.py", line 147, in __init__
    self.model_agent = build_model_agent(
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 771, in build_model_agent
    model_agent = BaseModelAgent(model_path,
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 220, in __init__
    self.patched_model = self._build_model(model_path,
  File "/opt/lmdeploy/lmdeploy/pytorch/engine/model_agent.py", line 247, in _build_model
    patched_model = build_patched_model(self.model_config, device=device)
  File "/opt/py3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/patch.py", line 200, in build_patched_model
    return build_model_from_hf_config(model_config, dtype=dtype, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/patch.py", line 191, in build_model_from_hf_config
    model = model_cls(model_config, ctx_mgr, dtype=dtype, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/qwen2_vl.py", line 360, in __init__
    self.model = Qwen2Model(config, dtype=dtype, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/qwen2_vl.py", line 262, in __init__
    self.layers = nn.ModuleList([
  File "/opt/lmdeploy/lmdeploy/pytorch/models/qwen2_vl.py", line 263, in <listcomp>
    Qwen2DecoderLayer(config, layer_idx, dtype=dtype, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/qwen2_vl.py", line 189, in __init__
    self.self_attn = Qwen2Attention(config, dtype=dtype, device=device)
  File "/opt/lmdeploy/lmdeploy/pytorch/models/qwen2_vl.py", line 63, in __init__
    self.qkv_proj = build_qkv_proj(
  File "/opt/lmdeploy/lmdeploy/pytorch/nn/linear.py", line 1352, in build_qkv_proj
    raise RuntimeError(f'Unsupported quant method: {quant_method}')
RuntimeError: Unsupported quant method: gptq
```

**Comment by lvhan028** [comment]
Just as the log indicated, pytorch engine hasn't support gptq yet
