### ISSUE TITLE
[Bug] Deploy llama2-chat-13b-w4 failed with ‘tp=8’

### ISSUE THREAD

**Issue by PYNing** [InternLM/lmdeploy#268]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Version: 0.5.0（直接使用官方的Docker镜像）
Device: 4090*8

部署**llama2-chat-13b-w4**模型，tp设置为1、2、4时部署成功并正常运行，但设置为8时**触发断言报错**

### Reproduction

`python3 -m lmdeploy.serve.turbomind.deploy --model-name llama2 --model-path ./llama2-chat-13b-w4  --model-format awq --group-size 128 --dst_path ./i4t8 --tp 8`

### Error traceback

```Shell
*** splitting layers.0.feed_forward.w2.scales_zeros, shape=torch.Size([108, 5120]), split_dim=0
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/deploy.py", line 834, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/deploy.py", line 804, in main
    res = deploy_awq(model_name, model_path, tokenizer_path,
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/deploy.py", line 716, in deploy_awq
    return export(model_name,
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/serve/turbomind/deploy.py", line 167, in export
    assert param_data.shape[split_dim] % tp == 0
AssertionError
```

**Comment by lzhangzz** [comment]
13b模型的inter_size=13824，按group_size=128分组后是108，w2是按input_dims切分的，108除2, 4都没问题，但除8就除不尽了。

一个办法是把scale是和zeros repeat一下然后按group_size=64处理。不过由于要控制体积，预编译包中没有包含group_size=64的kernel。

**Comment by PYNing** [comment]
> 13b模型的inter_size=13824，按group_size=128分组后是108，w2是按input_dims切分的，108除2, 4都没问题，但除8就除不尽了。
> 
> 一个办法是把scales和zeros repeat一下然后按group_size=64处理。不过由于要控制体积，预编译包中没有包含group_size=64的kernel。

感谢回复。请问我需要怎么做（比如自己编译源码）才能使用其他group_size的kernel？

**Comment by lzhangzz** [comment]
实例化不同group size的代码在

https://github.com/InternLM/lmdeploy/blob/f8ed456e79c726a490b5223d9ecf4bcbc1811648/src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.cu#L236-L246

理论上 >= 32的2的整数幂都可以支持

**Comment by PYNing** [comment]
> 实例化不同group size的代码在
> 
> https://github.com/InternLM/lmdeploy/blob/f8ed456e79c726a490b5223d9ecf4bcbc1811648/src/turbomind/kernels/gemm_s_f16/gemm_s4_f16.cu#L236-L246
> 
> 理论上 >= 32的2的整数幂都可以支持

@lzhangzz 再次感谢回复，顺便问一下，降低group_size到64或32，推理性能会有提高吗？有没有这方面的试验数据？谢谢！

**Comment by lzhangzz** [comment]
> 降低group_size到64或32，推理性能会有提高吗？有没有这方面的试验数据？谢谢！

4-bit情况下128一般就够了，64可能会有微小的提高。这方面数据可以参考AWQ或者GPTQ的paper。

**Comment by PYNing** [comment]
了解了，感谢回复。

**Comment by lippman1125** [comment]
@lzhangzz 你们有验证过 group size = 64 时候的精度吗？
