### ISSUE TITLE
[Feature] 希望可以使用镜像站进行量化用语料的下载

### ISSUE THREAD

**Issue by HelloCard** [InternLM/lmdeploy#2729]
### Motivation

在autodl上使用lmdeploy lite smooth_quant指令量化模型非常不方便。

### Related resources

类似问题参见：https://github.com/InternLM/lmdeploy/issues/2643
Traceback (most recent call last):
  File "/root/miniconda3/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/root/miniconda3/lib/python3.12/site-packages/lmdeploy/cli/lite.py", line 152, in smooth_quant
    smooth_quant(**kwargs)
  File "/root/miniconda3/lib/python3.12/site-packages/lmdeploy/lite/apis/smooth_quant.py", line 80, in smooth_quant
    vl_model, model, tokenizer, work_dir = calibrate(model,
                                           ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/lmdeploy/lite/apis/calibrate.py", line 235, in calibrate
    calib_loader, _ = get_calib_loaders(calib_dataset,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/lmdeploy/lite/utils/calib_dataloader.py", line 323, in get_calib_loaders
    return get_ptb(tokenizer, nsamples, seed, seqlen)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/lmdeploy/lite/utils/calib_dataloader.py", line 64, in get_ptb
    traindata = load_dataset('ptb_text_only',
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/datasets/load.py", line 1832, in load_dataset_builder
    builder_instance: DatasetBuilder = builder_cls(
                                       ^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by akai-shuuichi** [comment]
可以试一下pip install datasets==2.20.0
