### ISSUE TITLE
[Bug] 从0.6.0开始，24G显存运行AWQ量化后的Qwen2.5-32B启动出现OOM

### ISSUE THREAD

**Issue by akai-shuuichi** [InternLM/lmdeploy#2731]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

量化命令：
`lmdeploy lite auto_awq    /Qwen2.5-32B-Instruct   --calib-dataset 'ptb'   --calib-samples 128   --calib-seqlen 1024   --w-bits 4   --w-group-size 128   --batch-size 8   --search-scale True   --work-dir /Qwen2.5-32B-Instruct-int4`
运行命令：
`lmdeploy serve api_server /Qwen2.5-32B-Instruct-int4 ---session-len 100 --quant-policy 4`
最后的报错结果：
`Traceback (most recent call last):
  File "/usr/local/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/cli/serve.py", line 338, in api_server
    run_api_server(args.model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/openai/api_server.py", line 1057, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 158, in __init__
    self._build_turbomind(model_path=model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 197, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 302, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 125, in __init__
    for _ in e.map(self.model_comm.create_engine,
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:246`

但是在0.5.3上是可以正常运行的, 0.6.0a0, 0.6.0, 0.6.2, 0.6.2.post1 这几个版本我都试了，问题是一样的

### Reproduction

`pip install lmdeploy==0.6.0a0
lmdeploy lite auto_awq    /Qwen2.5-32B-Instruct   --calib-dataset 'ptb'   --calib-samples 128   --calib-seqlen 1024   --w-bits 4   --w-group-size 128   --batch-size 8   --search-scale True   --work-dir /Qwen2.5-32B-Instruct-int4
lmdeploy serve api_server /Qwen2.5-32B-Instruct-int4 --server-port 9000 --session-len 8000 --quant-policy 4`

Run on RTX3090/4090  tp = 1

### Environment

```Shell
sys.platform: linux
Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.1+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.9.2
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=8.9.2, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.1, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.1+cu121
LMDeploy: 0.6.2+
transformers: 4.46.2
gradio: Not Found
fastapi: 0.115.4
pydantic: 2.9.2
triton: 2.3.1
NVIDIA Topology: 
        GPU0    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     0-17,36-53      0               N/A
NIC0    SYS      X      PIX
NIC1    SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/usr/local/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/cli/serve.py", line 338, in api_server
    run_api_server(args.model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/openai/api_server.py", line 1057, in serve
    VariableInterface.async_engine = pipeline_class(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 158, in __init__
    self._build_turbomind(model_path=model_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/serve/async_engine.py", line 197, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 302, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/lmdeploy/turbomind/turbomind.py", line 125, in __init__
    for _ in e.map(self.model_comm.create_engine,
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
RuntimeError: [TM][ERROR] CUDA runtime error: out of memory /lmdeploy/src/turbomind/utils/allocator.h:246
```

**Comment by XFNxiaofuni** [comment]
相同问题，

**Comment by akai-shuuichi** [comment]
> 用lmdeploy convert 提前把模型 转换成turbomind格式。
> 
> 现在的版本运行时转换的话 会导致显存多占用一些，而且没有释放掉

按这个方法可以成功运行，ths
