### ISSUE TITLE
Cannot deploy quantized LLaMA2

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [InternLM/lmdeploy#274]
Hello everyone. I am trying to quantize Llama-2-13b-hf model and deploy it. I did 4bit quantization exactly following README, and the process appears to be finished successfully. But when I try to convert this model to turbomind format, I get the following error:

```output.weight torch.Size([32000, 5120])
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 834, in <module>
    fire.Fire(main)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 801, in main
    res = deploy_hf(model_name, model_path, tokenizer_path,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 502, in deploy_hf
    return export(model_name, num_layer, norm_eps, kv_head_num, model_params,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 182, in export
    assert inter_size > 0
AssertionError
```

Is it possible at all to convert quantized model to turbomind format for deployment?

**Comment by lzhangzz** [comment]
Just verified that converting from [llama2-chat-13b-w4 model](https://huggingface.co/lmdeploy/llama2-chat-13b-w4) in the model zoo is working (latest main branch).

Can you give it try to see how it goes?

**Comment by Nikita-Sherstnev** [comment]
It works, thank you! Although if I enter Cyrillic symbols, the chat crashes with the decode error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 115, in <module>
    fire.Fire(main)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 59, in main
    prompt = input_prompt()
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 19, in input_prompt
    return '\n'.join(iter(input, sentinel))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 11: invalid continuation byte
```

**Comment by lvhan028** [comment]
LMDeploy assumes users' input prompts are encoded by 'utf-8'. 
I think a simple way to resolve such an issue is to change the terminal's locale to 'utf-8' that makes the input text from the terminal encoded by 'utf-8'
