### ISSUE TITLE
[Feature] turbomind后端是否会支持guided_decoding

### ISSUE THREAD

**Issue by shell-nlp** [InternLM/lmdeploy#2771]
### Motivation

 turbomind后端是否会支持guided_decoding

**Comment by sph116** [comment]
同问

**Comment by lvhan028** [comment]
估计12月份下旬可以开始。

**Comment by lvhan028** [comment]
组内现在在优先处理团队内部的一些需求，对这个feature的支持会延后

**Comment by shell-nlp** [comment]
这个feature 什么时候可以支持呀

**Comment by lvhan028** [comment]
怎么也得春节后了。。。

**Comment by shell-nlp** [comment]
节后什么时候支持呀

**Comment by lvhan028** [comment]
很抱歉，变化太快，组内现在没有人手来处理这个需求了

**Comment by shell-nlp** [comment]
guided_decoding 是一个非常好用的 Feature， 建议优先支持

**Comment by lvhan028** [comment]
很抱歉，现在组内的工作最高优先级是支持团队内的需求，guided decoding 暂排不上

**Comment by lvhan028** [comment]
@CUHKSZzxy may put it into your work list

**Comment by shell-nlp** [comment]
@lvhan028  很多agent框架（比如langchain）都需要使用 guided_decoding技术 作为构建agent的一部分，因此再次建议 尽早支持一下 guided_decoding，不然在使用agent框架的时候，只能使用vllm作为推理后端才能 支持。

**Comment by lvhan028** [comment]
pytorch engine 支持，能不能先用它。tm 这边因为人手原因，还没有排上这个feature

**Comment by shell-nlp** [comment]
最近有计划吗，这个feature 看似还是很容易实现的，而且是很重要的feature

**Comment by shell-nlp** [comment]
@lvhan028  这个feature排上计划了吗 ，我觉得性能再好，也不如某些feature在业务上的重要性。而且这个feature看似很容易实现。

**Comment by lvhan028** [comment]
最近没空处理社区提的feature，非常欢迎社区大佬们给 lmdeploy 提 PR 支持

**Comment by shell-nlp** [comment]
求支持啊

**Comment by lvhan028** [comment]
> [@lvhan028](https://github.com/lvhan028) 这个feature排上计划了吗 ，我觉得性能再好，也不如某些feature在业务上的重要性。而且这个feature看似很容易实现。

@shell-nlp 抱歉，团队一直处于工作量高度饱和的状态，实在分身乏术。
vllm, sglang等优秀的开源库有这个功能，可以用起来。
如果容易实现的话，可以自己动手实现看看。如果能给 lmdeploy PR这个功能，我们非常非常欢迎，深感荣幸。

**Comment by xiaoajie738** [comment]
你好，我想尝试区支持在turbomind backend下支持guided_decoding，这边可以提供一些指导吗? 我这边初步看了下，通过纯python code 的改动，貌似很难去支持这个feature。

**Comment by shell-nlp** [comment]
😁再来催一催

**Comment by lvhan028** [comment]
和 @irexyc 说好了。
这把真的排上，拉钩。

**Comment by tuilakhanh** [comment]
Any WIP guy.

**Comment by windreamer** [comment]
> Any WIP guy.

You can try PR #3965 and follow the progress there. Thanks.

**Comment by tuilakhanh** [comment]
> You can try PR [#3965](https://github.com/InternLM/lmdeploy/pull/3965) and follow the progress there. Thanks.

Thank you for your work.
Do you plan to implement response_format for the OpenAI API Server after?

**Comment by windreamer** [comment]
> > You can try PR [#3965](https://github.com/InternLM/lmdeploy/pull/3965) and follow the progress there. Thanks.
> 
> Thank you for your work. Do you plan to implement response_format for the OpenAI API Server after?

Thank you for your support and patience. #3965 is just a beginning to better support guided decoding in LMDeploy. We will see if it has enough quality to be merged. And after that, I think we still have some work to optimize the performance. For OpenAI style guided decoding, frankly speaking, we have not discussed on it.

If you have interests to implement it, I believe we will all be happy to accept it!

**Comment by windreamer** [comment]
> > You can try PR [#3965](https://github.com/InternLM/lmdeploy/pull/3965) and follow the progress there. Thanks.
> 
> Thank you for your work. Do you plan to implement response_format for the OpenAI API Server after?

After some dig-ups, I think I have enabled response_format for the OpenAI API Server in the last commit of the PR? Maybe you can have a try?

**Comment by tuilakhanh** [comment]
> After some dig-ups, I think I have enabled response_format for the OpenAI API Server in the last commit of the PR? Maybe you can have a try?


```log
2025-09-30 15:27:32,716 - lmdeploy - ERROR - async_engine.py:663 - [safe_run] exception caught: KeyError 'schema'
2025-09-30 15:27:32,716 - lmdeploy - ERROR - async_engine.py:648 - [model_inst] exception caught: 'schema'
INFO:     10.69.1.103:56928 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/py3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/py3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/py3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 123, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 109, in app
    response = await f(request)
  File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 387, in app
    raw_response = await run_endpoint_function(
  File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 288, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/py3/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 586, in chat_completions_v1
    if final_res.finish_reason == 'stop' and len(message.tool_calls) > 0:
AttributeError: 'NoneType' object has no attribute 'finish_reason'
```


Curl work but when try with python openai lib, lmdeploy raise 500 error. Above is logs.

**Comment by windreamer** [comment]
> schema

Can I have your test code？ I need some more info to debug. Thank you.

**Comment by windreamer** [comment]
> > After some dig-ups, I think I have enabled response_format for the OpenAI API Server in the last commit of the PR? Maybe you can have a try?
> 
> ```
> 2025-09-30 15:27:32,716 - lmdeploy - ERROR - async_engine.py:663 - [safe_run] exception caught: KeyError 'schema'
> 2025-09-30 15:27:32,716 - lmdeploy - ERROR - async_engine.py:648 - [model_inst] exception caught: 'schema'
> INFO:     10.69.1.103:56928 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/opt/py3/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/opt/py3/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
>     return await self.app(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/fastapi/applications.py", line 1133, in __call__
>     await super().__call__(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
>     raise exc
>   File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
>     await self.app(scope, receive, _send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
>     await self.app(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
>     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     raise exc
>   File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
>     await app(scope, receive, sender)
>   File "/opt/py3/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
>     await self.app(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/routing.py", line 716, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/routing.py", line 736, in app
>     await route.handle(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/routing.py", line 290, in handle
>     await self.app(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 123, in app
>     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
>   File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
>     raise exc
>   File "/opt/py3/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
>     await app(scope, receive, sender)
>   File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 109, in app
>     response = await f(request)
>   File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 387, in app
>     raw_response = await run_endpoint_function(
>   File "/opt/py3/lib/python3.10/site-packages/fastapi/routing.py", line 288, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/opt/py3/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 586, in chat_completions_v1
>     if final_res.finish_reason == 'stop' and len(message.tool_calls) > 0:
> AttributeError: 'NoneType' object has no attribute 'finish_reason'
> ```
> 
> Curl work but when try with python openai lib, lmdeploy raise 500 error. Above is logs.

I have tested successfully using the following script:

```python
from openai import OpenAI

client = OpenAI(api_key="YOUR_API_KEY", base_url="http://0.0.0.0:23333/v1")

model_name = client.models.list().data[0].id

response = client.chat.completions.create(
    model=model_name,
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Make a self introduction please."},
    ],
    temperature=0.8,
    top_p=0.8,
    response_format={
        "type": "json_schema",
        "json_schema": {
            "name": "user_profile",
            "schema": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "skills": {
                        "type": "array",
                        "items": {"type": "string", "maxLength": 10},
                        "minItems": 3,
                        "maxItems": 10,
                    },
                    "work history": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "company": {"type": "string"},
                                "duration": {"type": "string"},
                            },
                            "required": ["company"],
                        },
                    },
                },
                "required": ["name", "skills", "work history"],
            },
        },
    },
)

print(response)
```

I can get such response:

```
ChatCompletion(id='8', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='{"name": "Alice", "skills": ["HTML", "CSS", "JavaScript", "Python", "SQL", "Git", "Docker", "AWS", "Linux", "ReactJS"], "work history": [{"company": "Company A", "duration": "2020-2023"}, {"company": "Company B", "duration": "2023-2024"}] }', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=None, gen_tokens=None, reasoning_content=None))], created=1759227863, model='/home/windreamer/.cache/huggingface/hub/models--Qwen--Qwen3-0.6B/snapshots/c1899de289a04d12100db370d81485cdf75e47ca', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=89, prompt_tokens=25, total_tokens=114, completion_tokens_details=None, prompt_tokens_details=None))
```

**Comment by tuilakhanh** [comment]
```python
import json
from typing import List

from openai import OpenAI
from pydantic import BaseModel


class StoryOutput(BaseModel):
    title: str
    characters: List[str]
    moral: str


client = OpenAI(
    base_url="",
    api_key="EMPTY",
)

schema = StoryOutput.model_json_schema()

prompt = (
    "Kể một câu chuyện ngắn vui nhộn về một con mèo và một con robot trong công viên."
)

resp = client.chat.completions.create(
    model="",
    messages=[
        {
            "role": "system",
            "content": "Return ONLY valid JSON that matches the JSON Schema.",
        },
        {"role": "user", "content": prompt},
    ],
    response_format={
        "type": "json_schema",
        "json_schema": {
            "name": "StoryOutput",
            "schema": schema,
            "strict": True,
        },
    },
    temperature=0.7,
)

content = resp.choices[0].message.content
data = json.loads(content)
story = StoryOutput.model_validate(data)
```

Here is my code.

**Comment by windreamer** [comment]
> import json
> from typing import List
> 
> from openai import OpenAI
> from pydantic import BaseModel
> 
> 
> class StoryOutput(BaseModel):
>     title: str
>     characters: List[str]
>     moral: str
> 
> 
> client = OpenAI(
>     base_url="",
>     api_key="EMPTY",
> )
> 
> schema = StoryOutput.model_json_schema()
> 
> prompt = (
>     "Kể một câu chuyện ngắn vui nhộn về một con mèo và một con robot trong công viên."
> )
> 
> resp = client.chat.completions.create(
>     model="",
>     messages=[
>         {
>             "role": "system",
>             "content": "Return ONLY valid JSON that matches the JSON Schema.",
>         },
>         {"role": "user", "content": prompt},
>     ],
>     response_format={
>         "type": "json_schema",
>         "json_schema": {
>             "name": "StoryOutput",
>             "schema": schema,
>             "strict": True,
>         },
>     },
>     temperature=0.7,
> )
> 
> content = resp.choices[0].message.content
> data = json.loads(content)
> story = StoryOutput.model_validate(data)
> Here is my code.

Thank you for the code for reproduce the issue. I have identify the bug and fix it in the latest commit, you can try to verify if it has been fixed completely.

This is due to the Pydantic model used by LMDeploy, as `schema` is reseved for Pydantic BaseModel. So we need rename the field to `json_schema` to avoid name confliction and set an alias of `schema` to make sure the json is deserialized successfully. However, we also serialize the model to json internally and the result will use `json_schema` instread of `schema` as field name and this is the root cause of the bug.

So in the latest commit of the PR, I set the model to use alias in serialization too. I belive it can solve the current issue.

**Comment by windreamer** [comment]
According to https://github.com/InternLM/lmdeploy/pull/3965#issuecomment-3351130371

I think we need some more time for #3965 to fix the issue in Pytorch engine.

**Comment by tuilakhanh** [comment]
> Thank you for the code for reproduce the issue. I have identify the bug and fix it in the latest commit, you can try to verify if it has been fixed completely.
> 
> This is due to the Pydantic model used by LMDeploy, as `schema` is reseved for Pydantic BaseModel. So we need rename the field to `json_schema` to avoid name confliction and set an alias of `schema` to make sure the json is deserialized successfully. However, we also serialize the model to json internally and the result will use `json_schema` instread of `schema` as field name and this is the root cause of the bug.
> 
> So in the latest commit of the PR, I set the model to use alias in serialization too. I belive it can solve the current issue.

Testing with gpt-oss-20b model. Request complete without error but it return None content in ChatCompletionMessage

**Comment by windreamer** [comment]
> > Thank you for the code for reproduce the issue. I have identify the bug and fix it in the latest commit, you can try to verify if it has been fixed completely.
> > This is due to the Pydantic model used by LMDeploy, as `schema` is reseved for Pydantic BaseModel. So we need rename the field to `json_schema` to avoid name confliction and set an alias of `schema` to make sure the json is deserialized successfully. However, we also serialize the model to json internally and the result will use `json_schema` instread of `schema` as field name and this is the root cause of the bug.
> > So in the latest commit of the PR, I set the model to use alias in serialization too. I belive it can solve the current issue.
> 
> Testing with gpt-oss-20b model. Request complete without error but it return None content in ChatCompletionMessage

@tuilakhanh it is a bit weird. Does it work for other models despite gpt-oss-20b? I am wondering if there is something need to be dealt with specially in gpt-oss-20b. Can you kindly provide relative logs to help me debug it?

**Comment by windreamer** [comment]
and you may try if #4029 is relative with this.

**Comment by shell-nlp** [comment]
guided decoding 下个版本发布吗

**Comment by lvhan028** [comment]
> guided decoding 下个版本发布吗

会发布。不过，这个版本仅做了 xgrammar 的集成工作，效率方面可能不及预期。优化事项后面会在排

**Comment by jingyibo123** [comment]
> > guided decoding 下个版本发布吗
> 
> 会发布。不过，这个版本仅做了 xgrammar 的集成工作，效率方面可能不及预期。优化事项后面会在排

请问当前main分支已支持，可以自行编译测试对吗？ 下个版本预计发布时间是？

**Comment by jingyibo123** [comment]
@lvhan028 

经过测试，正式版本0.10.2和main上最新版本，如下代码都会报错崩溃
模型：GPT-OSS-120B， 环境：4 x V100, ubuntu 20.04

```
# 此处是否给参数response_format都会崩溃

client.beta.chat.completions.parse(

```
报错：
```
1926179 Segmentation fault      (core dumped) lmdeploy serve api_server openai/gpt-oss-120b --server-port 8004 --backend turbomind --model-name gpt-oss-120b --enable-prefix-caching --cache-max-entry-count 0.90 --tp 4 --communicator native --log-level INFO --max-log-len 200
```

**Comment by lvhan028** [comment]
> [@lvhan028](https://github.com/lvhan028)
> 
> 经过测试，正式版本0.10.2和main上最新版本，如下代码都会报错崩溃 模型：GPT-OSS-120B， 环境：4 x V100, ubuntu 20.04
> 
> ```
> # 此处是否给参数response_format都会崩溃
> 
> client.beta.chat.completions.parse(
> ```
> 
> 报错：
> 
> ```
> 1926179 Segmentation fault      (core dumped) lmdeploy serve api_server openai/gpt-oss-120b --server-port 8004 --backend turbomind --model-name gpt-oss-120b --enable-prefix-caching --cache-max-entry-count 0.90 --tp 4 --communicator native --log-level INFO --max-log-len 200
> ```

client 侧的用例可以分享下么？

**Comment by tuilakhanh** [comment]
This request will cause core dumped, :
```bash
curl --request POST \
        --url http://{lmdeploy}/v1/chat/completions \
        --header 'content-type: application/json' \
        --data '{
    "model": "Qwen3-30B-A3B-Instruct-2507",
    "response_format": {
      "type": "json_object"
    },
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant. Always output ONLY valid JSON following exactly this schema: {\"story_title\": string, \"language\": string, \"target_word_count\": number, \"chapters\": [ {\"chapter_number\": number, \"chapter_title\": string, \"chapter_summary\": string, \"chapter_content\": string} ] }"
      },
      {
        "role": "user",
        "content": "Hãy viết 1 câu chuyện tiếng Việt, mục tiêu khoảng 5000 từ, chia thành nhiều chương. Trả về đúng theo schema JSON mà system message đã mô tả, không được trả thêm text nào bên ngoài JSON."
      }
    ]
  }'
```
lmdeploy logs:
```
INFO:     10.69.1.250:39760 - "POST /v1/chat/completions HTTP/1.1" 200 OK
[TM][WARNING] [ProcessInferRequests] [197] total sequence length (2666 + 259478) exceeds `session_len` (262144), max_new_tokens is truncated to 259477
[TM][WARNING] [ProcessInferRequests] [198] total sequence length (130 + 262014) exceeds `session_len` (262144), max_new_tokens is truncated to 262013
double free or corruption (fasttop)           
Aborted (core dumped)    
```
GPU: x4 v100 32gb
lmdeploy serve command:
```
lmdeploy serve api_server Qwen/Qwen3-30B-A3B-Instruct-2507 --model-name Qwen3-30B-A3B-Instruct-2507 --tp 4 --tool-call-parser qwen3 --enable-prefix-caching
```
Is this bug related to this feature? Otherwise, I'll open a new issue.

**Comment by jingyibo123** [comment]
I'm using python-openai 's interface: 
```
class FormatClass(pydantic.Basemodel):
     pass

self.client = OpenAI(
            api_key=api_key,
            base_url=base_url,
        )
      response = self.client.beta.chat.completions.parse(
          messages=messages,
          model=self.model,
          temperature=temp,
          top_p=top_p,
          reasoning_effort=reasoning_effort,
          # max_completion_tokens=max_completion_tokens,
          response_format=FormatClass
      )
```
I think behind the scene, it's the same as tuilakhanh's request above. 
```
"response_format": {
      "type": "json_object"
    },
```
@lvhan028

**Comment by windreamer** [comment]
@tuilakhanh @jingyibo123 This is a bit weird to me. Could you please open a separate issue instead?
I suspect there's memory corruption on the C++ side caused by a Python object being garbage collected, but I can't seem to reproduce it here.

**Comment by windreamer** [comment]
Additionally, could you please test whether the following method also causes memory corruption?

```
response_format={
    "type": "json_schema",
    "json_schema": {
        "name": "permissive_object",
        "schema": {"type": "object", "additionalProperties": true}
    }
}
```

**Comment by tuilakhanh** [comment]
> [@tuilakhanh](https://github.com/tuilakhanh) [@jingyibo123](https://github.com/jingyibo123) This is a bit weird to me. Could you please open a separate issue instead?

Okey, let me open new one.

#4152

**Comment by lvhan028** [comment]
Regarding issue on V100, please try:
```shell
export TM_ANOMALY_HANDLER=level=2,inf=65504,nan=0
```

related issue: 
https://github.com/InternLM/lmdeploy/issues/4055
https://github.com/InternLM/lmdeploy/issues/4002
https://github.com/InternLM/lmdeploy/issues/3955
