### ISSUE TITLE
[Bug] SystemExit: 1       asyncio.exceptions.TimeoutError

### ISSUE THREAD

**Issue by LIUKAI0815** [InternLM/lmdeploy#2782]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

INFO:     10.12.17.5:64148 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 171, in __no_threadsafe_get
    return await asyncio.wait_for(self.resp_que.get(), timeout)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 483, in chat_completions_v1
    async for res in result_generator:
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 575, in generate
    async for outputs in generator.async_stream_infer(
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine_instance.py", line 178, in async_stream_infer
    resp = await self.req_sender.async_recv(req_id)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 312, in async_recv
    resp: Response = await self._async_resp_get()
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 187, in _async_resp_get
    return await __no_threadsafe_get()
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/site-packages/lmdeploy/pytorch/engine/request.py", line 175, in __no_threadsafe_get
    exit(1)
  File "/root/miniforge3/envs/LMDeploy/lib/python3.10/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1                                                                                                                            

### Reproduction

CUDA_VISIBLE_DEVICES=6 lmdeploy serve api_server /workspace/model/llm/Qwen/Qwen2_5-3B-Instruct \
    --server-port 2016 \
	--tp 1 \
	--cache-max-entry-count 0.2 \
	--session-len 10000 \
	--enable-prefix-caching  \
	--adapters rewrite_3B=/workspace/output/question_extration/qwen/qwen2_5-3b-instruct/v0-20241119-170654/checkpoint-1200 \
	--enable-prefix-caching  \
	--chat-template qwen \
	--backend pytorch \

### Environment

```Shell
lmdeploy                          0.6.3
```

**Comment by LIUKAI0815** [comment]
VLLM之前也有类似的报错，给的方案是提高 VLLM_RPC_TIMEOUT的默认参数，我给调高了就好了。不知道咱们这个是不是类似的

**Comment by AllentDan** [comment]
客户端是怎么使用的？可以给个复现的客户端代码脚本不？服务端必须要 --adapters 吗？我先复现下

**Comment by LIUKAI0815** [comment]
def llm(content_data,api,model):
    client = OpenAI(
        api_key=openai_api_key,
        base_url=api,
    )
    chat_completion = client.chat.completions.create(
        messages=[{
            "role": "system",
            "content": "You are a helpful assistant."
        },
            {
                "role": "user",
                "content": content_data
            },
        ],
        model=model,
        temperature=0.0,
    )

    print("Chat completion results:")
    print(chat_completion.choices[0].message.content)
    a = chat_completion.choices[0].message.content
    return a
就是普通的openai调用。加载lora路径可以节省资源

**Comment by AllentDan** [comment]
改这里 https://github.com/InternLM/lmdeploy/blob/v0.6.3/lmdeploy/pytorch/engine/request.py#L166 试试

**Comment by LIUKAI0815** [comment]
这里改成10/20都行？还是有个最大的限度

**Comment by AllentDan** [comment]
这个值你自己定

**Comment by AllentDan** [comment]
你那边可以把日志等级调 INFO，然后贴一下完整的错误日志吗？

**Comment by LIUKAI0815** [comment]
我这边对比了一下，发现7B的模型没问题，3B的就有问题。看了看qwen官网的内容，应该是因为3B的上下文比较小的原因
7B：Context Length: Full 131,072 tokens and generation 8192 tokens
3B：Context Length: Full 32,768 tokens and generation 8192 tokens

**Comment by AllentDan** [comment]
最好有个可供复现的简单方式。

**Comment by LIUKAI0815** [comment]
@AllentDan 你说得对，刚刚试了一下，不是我说的原因。下午跑一下，把日志贴上

**Comment by LIUKAI0815** [comment]
@AllentDan 下午试了，这次--cache-max-entry-count 0.8，测试数据跑到了730条，然后就卡住了，日志里没有任何报错，我这边调用的报错就是 time out。
我重新运行程序从731条开始跑，就可以继续改这里 https://github.com/InternLM/lmdeploy/blob/v0.6.3/lmdeploy/pytorch/engine/request.py#L166   这里我没改

**Comment by LIUKAI0815** [comment]
@AllentDan 同样的模型，merge之后再跑就没有问题，也没有卡住、time out报错的现象。使用lora路径就会长时间的卡住最终time out。（VLLM同样有这个问题）

**Comment by AllentDan** [comment]
那还是建议merge后跑吧，对 lora 外挂形式的支持在减弱。

**Comment by LIUKAI0815** [comment]
@AllentDan VLLM取消--enforce-eage就会速度变快。
请问lmdeploy有没有类似的功能取消（我没开启--eager-mode）

**Comment by AllentDan** [comment]
`--enforce-eager` 跟 `--eager-mode`一样，都是不用cuda_graph
