### ISSUE TITLE
How to deploy model with its lora adapter

### ISSUE THREAD

**Issue by pulkitmehtaworkmetacube** [InternLM/lmdeploy#2852]
We have finetuned Nemotron 70b model with Lora technique and has its adapter weights seperately . How do we host the same in lmdeploy . Please guide .

**Comment by pulkitmehtaworkmetacube** [comment]
When i tried following command .. CUDA_VISIBLE_DEVICES=0,1,2,3 lmdeploy serve api_server nvidia/Llama-3.1-Nemotron-70B-Instruct-HF --tp 4 --server-port 23333 --backend pytorch --adapters mylora=LLM-Adapters/trained_models/lora_gpt4/checkpoint-1794 --cache-max-entry-count 0.5 .. getting below error even though adapter weights are present in the specified path ..

error stack trace : 

[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/conda/bin/lmdeploy", line 8, in <module>
[rank0]:     sys.exit(run())
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 42, in run
[rank0]:     args.run(args)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 338, in api_server
[rank0]:     run_api_server(args.model_path,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 1074, in serve
[rank0]:     VariableInterface.async_engine = pipeline_class(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 163, in __init__
[rank0]:     self._build_pytorch(model_path=model_path,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 211, in _build_pytorch
[rank0]:     self.engine = Engine(model_path=model_path,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 149, in __init__
[rank0]:     self.model_agent = build_model_agent(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 788, in build_model_agent
[rank0]:     model_agent = TPModelAgent(model_path,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 584, in __init__
[rank0]:     model, cache_engine, cache_config = self._build_model(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 679, in _build_model
[rank0]:     model, cache_engine, cache_config = _tp_build_model(
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 392, in _tp_build_model
[rank0]:     raise e
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 367, in _tp_build_model
[rank0]:     add_adapters(patched_model,
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.10/site-packages/lmdeploy/pytorch/models/patch.py", line 243, in add_adapters
[rank0]:     target_names = target_names.union(cfg.target_modules)
[rank0]: AttributeError: 'PeftConfig' object has no attribute 'target_modules'
