### ISSUE TITLE
[Bug] raise error on transformers==4.47.0 when do awq or chat with awq models 

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#2877]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

raise error on transformers==4.47.0 when do awq or chat with awq models 

### Reproduction

`CUDA_VISIBLE_DEVICES=6 lmdeploy lite auto_awq /nvme/qa_test_models/OpenGVLab/InternVL-Chat-V1-5 --work-dir /nvme/qa_test_models/OpenGVLab/InternVL-Chat-V1-5-inner-4bits --batch-size 32`

```
2024-12-10 10:11:36,467 - lmdeploy - INFO - builder.py:64 - matching vision model: InternVLVisionModel
Encountered exception while importing peft: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/transformers/modeling_utils.py)
2024-12-10 10:11:36,623 - lmdeploy - ERROR - builder.py:67 - matching vision model: InternVLVisionModel failed
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/v62new/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/cli/lite.py", line 131, in auto_awq
    auto_awq(**kwargs)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/lite/apis/auto_awq.py", line 90, in auto_awq
    vl_model, model, tokenizer, work_dir = calibrate(model,
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 253, in calibrate
    vl_model, model, tokenizer = vl_model_with_tokenizer(model_path=model)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/vl/model/builder.py", line 75, in vl_model_with_tokenizer
    vl_model = load_vl_model(model_path, with_llm).vl_model
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/vl/model/builder.py", line 65, in load_vl_model
    return module(**kwargs)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/vl/model/base.py", line 31, in __init__
    self.build_model()
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/lmdeploy/vl/model/internvl.py", line 90, in build_model
    model = AutoModel.from_config(config, trust_remote_code=True)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 433, in from_config
    model_class = get_class_from_dynamic_module(class_ref, repo_id, **kwargs)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 541, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 366, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 186, in check_imports
    importlib.import_module(imp)
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/mapping.py", line 22, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/mixed_model.py", line 26, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/tuners/__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel, LoftQConfig
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/tuners/lora/__init__.py", line 20, in <module>
    from .model import LoraModel
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 50, in <module>
    from .awq import dispatch_awq
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/peft/tuners/lora/awq.py", line 26, in <module>
    from awq.modules.linear import WQLinear_GEMM
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/awq/__init__.py", line 2, in <module>
    from awq.models.auto import AutoAWQForCausalLM
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/awq/models/__init__.py", line 1, in <module>
    from .mpt import MptAWQForCausalLM
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/awq/models/mpt.py", line 1, in <module>
    from .base import BaseAWQForCausalLM
  File "/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/awq/models/base.py", line 14, in <module>
    from transformers.modeling_utils import shard_checkpoint
ImportError: cannot import name 'shard_checkpoint' from 'transformers.modeling_utils' (/home/zhulin1/miniconda3/envs/v62new/lib/python3.10/site-packages/transformers/modeling_utils.py)
```

### Environment

```Shell
Package                       Version        Editable project location
----------------------------- -------------- ------------------------------
accelerate                    1.2.0
addict                        2.4.0
aiofiles                      23.2.1
aiohappyeyeballs              2.4.4
aiohttp                       3.11.10
aiosignal                     1.3.1
allure-pytest                 2.13.5
allure-python-commons         2.13.5
altair                        5.5.0
annotated-types               0.7.0
antlr4-python3-runtime        4.7.2
anyio                         4.7.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
arxiv                         2.1.3
asttokens                     3.0.0
async-lru                     2.0.4
async-timeout                 5.0.1
attrdict                      2.0.1
attrs                         24.2.0
auto_gptq                     0.7.1
autoawq                       0.2.6
autoawq_kernels               0.0.7+cu118    /root/packages/AutoAWQ_kernels
av                            14.0.1
babel                         2.16.0
beautifulsoup4                4.12.3
bleach                        6.2.0
blinker                       1.9.0
Brotli                        1.1.0
cachetools                    5.5.0
certifi                       2024.8.30
cffi                          1.17.1
charset-normalizer            3.4.0
click                         8.1.7
cloudpickle                   3.1.0
cmake                         3.31.1
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.3.1
coverage                      7.6.9
cycler                        0.12.1
datasets                      3.1.0
debugpy                       1.8.9
decorator                     5.1.1
decord                        0.6.0
deepseek_vl                   1.0.0
defusedxml                    0.7.1
dill                          0.3.8
diskcache                     5.6.3
distro                        1.9.0
duckduckgo_search             5.3.1b1
einops                        0.8.0
exceptiongroup                1.2.2
execnet                       2.1.1
executing                     2.1.0
fastapi                       0.115.6
fastjsonschema                2.21.1
feedparser                    6.0.11
ffmpy                         0.4.0
filelock                      3.13.1
fire                          0.7.0
flash-attn                    2.6.3
fonttools                     4.55.2
fqdn                          1.5.1
frozenlist                    1.5.0
fsspec                        2024.2.0
func_timeout                  4.3.5
gekko                         1.2.1
gitdb                         4.0.11
GitPython                     3.1.43
gradio                        5.8.0
gradio_client                 1.5.1
griffe                        0.49.0
grpcio                        1.67.1
h11                           0.14.0
h2                            4.1.0
hpack                         4.0.0
httpcore                      1.0.7
httpx                         0.28.1
huggingface-hub               0.26.5
human-eval                    1.0.3
hyperframe                    6.0.1
idna                          3.10
iniconfig                     2.0.0
interegular                   0.3.3
ipykernel                     6.29.5
ipython                       8.30.0
ipywidgets                    8.1.5
isoduration                   20.11.0
jedi                          0.19.2
Jinja2                        3.1.3
jiter                         0.8.0
jmespath                      1.0.1
joblib                        1.4.2
json5                         0.10.0
jsonpointer                   3.0.0
jsonschema                    4.23.0
jsonschema-specifications     2024.10.1
jupyter                       1.1.1
jupyter_client                8.6.3
jupyter-console               6.6.3
jupyter_core                  5.7.2
jupyter-events                0.10.0
jupyter-lsp                   2.2.5
jupyter_server                2.14.2
jupyter_server_terminals      0.5.3
jupyterlab                    4.3.2
jupyterlab_pygments           0.3.0
jupyterlab_server             2.27.3
jupyterlab_widgets            3.0.13
kiwisolver                    1.4.7
lagent                        0.2.4
langdetect                    1.0.9
lark                          1.2.2
latex2sympy2                  1.9.1
llvmlite                      0.43.0
lmdeploy                      0.6.4
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.3
matplotlib-inline             0.1.7
mdurl                         0.1.2
mistune                       3.0.2
mmengine-lite                 0.10.5
modelscope                    1.21.0
mpmath                        1.3.0
multidict                     6.1.0
multiprocess                  0.70.16
narwhals                      1.16.0
nbclient                      0.10.1
nbconvert                     7.16.4
nbformat                      5.10.4
nest-asyncio                  1.6.0
networkx                      3.2.1
nltk                          3.9.1
notebook                      7.3.1
notebook_shim                 0.2.4
numba                         0.60.0
numpy                         1.26.3
nvidia-cublas-cu11            11.11.3.6
nvidia-cuda-cupti-cu11        11.8.87
nvidia-cuda-nvrtc-cu11        11.8.89
nvidia-cuda-runtime-cu11      11.8.89
nvidia-cudnn-cu11             8.7.0.84
nvidia-cufft-cu11             10.9.0.58
nvidia-curand-cu11            10.3.0.86
nvidia-cusolver-cu11          11.4.1.48
nvidia-cusparse-cu11          11.7.5.86
nvidia-ml-py                  12.560.30
nvidia-nvtx-cu11              11.8.86
openai                        1.57.0
orjson                        3.10.12
outlines                      0.0.46
overrides                     7.7.0
packaging                     24.2
pandas                        2.2.3
pandocfilters                 1.5.1
parso                         0.8.4
peft                          0.11.1
pexpect                       4.9.0
phx-class-registry            4.1.0
pillow                        10.2.0
pip                           24.3.1
platformdirs                  4.3.6
pluggy                        1.5.0
prometheus_client             0.21.1
prompt_toolkit                3.0.48
propcache                     0.2.1
protobuf                      5.29.1
psutil                        6.1.0
ptyprocess                    0.7.0
pure_eval                     0.2.3
pyairports                    2.1.1
pyarrow                       18.1.0
pybind11                      2.13.1
pycountry                     24.6.1
pycparser                     2.22
pydantic                      2.10.3
pydantic_core                 2.27.1
pydeck                        0.9.1
pydub                         0.25.1
Pygments                      2.18.0
pynvml                        12.0.0
pyparsing                     3.2.0
pytest                        8.3.4
pytest-assume                 2.4.3
pytest-cov                    6.0.0
pytest-order                  1.3.0
pytest-rerunfailures          15.0
pytest-sugar                  1.0.0
pytest-xdist                  3.6.1
python-dateutil               2.9.0.post0
python-json-logger            2.0.7
python-multipart              0.0.19
python-rapidjson              1.20
pytz                          2024.2
PyYAML                        6.0.2
pyzmq                         26.2.0
qwen-vl-utils                 0.0.8
referencing                   0.35.1
regex                         2024.11.6
requests                      2.32.3
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rich                          13.9.4
rouge                         1.0.1
rpds-py                       0.22.3
ruff                          0.8.2
safehttpx                     0.1.6
safetensors                   0.4.5
semantic-version              2.10.0
Send2Trash                    1.8.3
sentencepiece                 0.2.0
setuptools                    69.5.1
sgmllib3k                     1.0.0
shellingham                   1.5.4
shortuuid                     1.0.13
six                           1.17.0
smmap                         5.0.1
sniffio                       1.3.1
socksio                       1.0.0
soupsieve                     2.6
stack-data                    0.6.3
starlette                     0.41.3
streamlit                     1.40.2
sympy                         1.13.1
tenacity                      9.0.0
termcolor                     2.5.0
terminado                     0.18.1
tiktoken                      0.8.0
timeout-decorator             0.5.0
timm                          1.0.12
tinycss2                      1.4.0
tokenizers                    0.21.0
toml                          0.10.2
tomli                         2.2.1
tomlkit                       0.13.2
torch                         2.3.0+cu118
torchvision                   0.18.0+cu118
tornado                       6.4.2
tqdm                          4.67.1
traitlets                     5.14.3
transformers                  4.47.0
transformers-stream-generator 0.0.5
triton                        2.3.0
tritonclient                  2.52.0
typer                         0.15.1
types-python-dateutil         2.9.0.20241206
typing_extensions             4.12.2
tzdata                        2024.2
uri-template                  1.3.0
urllib3                       2.2.3
uvicorn                       0.32.1
watchdog                      6.0.0
wcwidth                       0.2.13
webcolors                     24.11.1
webencodings                  0.5.1
websocket-client              1.8.0
websockets                    14.1
wheel                         0.45.1
widgetsnbextension            4.0.13
xformers                      0.0.27+cu118
xxhash                        3.5.0
yapf                          0.43.0
yarl                          1.18.3
sys.platform: linux
Python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: x86_64-linux-gnu-gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.3.0+cu118
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.3.6 (Git Hash 86e6af5974177e513fd3fee58425e1063e7f1361)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.8
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_90,code=sm_90
  - CuDNN 8.7
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.8, CUDNN_VERSION=8.7.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.3.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.18.0+cu118
LMDeploy: 0.6.4+47fa7cf
transformers: 4.47.0
gradio: 5.8.0
fastapi: 0.115.6
pydantic: 2.10.3
triton: 2.3.0
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	NV12	NV12	NV12	NV12	NV12	NV12	0-27,56-83	0
GPU1	NV12	 X 	NV12	NV12	NV12	NV12	NV12	NV12	0-27,56-83	0
GPU2	NV12	NV12	 X 	NV12	NV12	NV12	NV12	NV12	0-27,56-83	0
GPU3	NV12	NV12	NV12	 X 	NV12	NV12	NV12	NV12	0-27,56-83	0
GPU4	NV12	NV12	NV12	NV12	 X 	NV12	NV12	NV12	28-55,84-111	1
GPU5	NV12	NV12	NV12	NV12	NV12	 X 	NV12	NV12	28-55,84-111	1
GPU6	NV12	NV12	NV12	NV12	NV12	NV12	 X 	NV12	28-55,84-111	1
GPU7	NV12	NV12	NV12	NV12	NV12	NV12	NV12	 X 	28-55,84-111	1

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

**Comment by AllentDan** [comment]
Duplicate of #2997. `lite auto_awq` does not depend on `awq` package.
