### ISSUE TITLE
[Bug] 遇到报错：AttributeError: 'dict' object has no attribute 'attn_implementation' 

### ISSUE THREAD

**Issue by lzk9508** [InternLM/lmdeploy#2899]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

在运行internvl2的量化代码：
from lmdeploy.lite.apis.auto_awq import auto_awq
input_path = "/ossfs/workspace/checkpoint-555-fused" # 输入模型路径
output_path = "/ossfs/workspace/checkpoint-555_fused_awq" # 工作目录
os.system(f'lmdeploy lite auto_awq {input_path} --work-dir {output_path} --search-scale True --batch-size 8')时,遇到报错：
lmdeploy - ERROR - matching vision model: InternVLVisionModel failed
Traceback (most recent call last):
File "/opt/conda/bin/lmdeploy", line 8, in <module>
sys.exit(run())
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
args.run(args)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
auto_awq(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/lite/apis/auto_awq.py", line 103, in auto_awq
vl_model, model, tokenizer, work_dir = calibrate(model,
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/lite/apis/calibrate.py", line 184, in calibrate
vl_model, model, tokenizer = vl_model_with_tokenizer(model_path=model)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/builder.py", line 65, in vl_model_with_tokenizer
vl_model = load_vl_model(model_path, with_llm).vl_model
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/builder.py", line 55, in load_vl_model
return module(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/base.py", line 31, in init
self.build_model()
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/internvl.py", line 89, in build_model
config.llm_config.attn_implementation = 'eager'
AttributeError: 'dict' object has no attribute 'attn_implementation'

checkpoint-555-fused这个模型的目录是已经经过lora合并好的：

## merge lora

import os
import argparse

import torch
from internvl.model.internvl_chat import InternVLChatModel
from transformers import AutoTokenizer

import shutil

input_path = '/ossfs/workspace/checkpoint-555-old'
output_path = '/ossfs/workspace/checkpoint-555-fused'

print('Loading model...')
model = InternVLChatModel.from_pretrained(
    input_path, low_cpu_mem_usage=True, torch_dtype=torch.bfloat16).eval()
print('Loading tokenizer...')
tokenizer = AutoTokenizer.from_pretrained(input_path, trust_remote_code=True)

if model.config.use_backbone_lora:
    model.vision_model.merge_and_unload()
    model.vision_model = model.vision_model.model
    model.config.use_backbone_lora = 0
if model.config.use_llm_lora:
    model.language_model.merge_and_unload()
    model.language_model = model.language_model.model
    model.config.use_llm_lora = 0

print('Saving model...')
model.save_pretrained(output_path)
print('Saving tokenizer...')
tokenizer.save_pretrained(output_path)
print('Done!')

### Reproduction

from lmdeploy.lite.apis.auto_awq import auto_awq
input_path = "/ossfs/workspace/checkpoint-555-fused" # 输入模型路径
output_path = "/ossfs/workspace/checkpoint-555_fused_awq" # 工作目录
os.system(f'lmdeploy lite auto_awq {input_path} --work-dir {output_path} --search-scale True --batch-size 8')

### Environment

```Shell
模型：internvl2_8Bit
linux centos
pytorch 2.1.0+cu121 torchvision 0.16.0
transformers 4.40.0
lmdeploy 0.5.1
```

### Error traceback

```Shell
Traceback (most recent call last):
File "/opt/conda/bin/lmdeploy", line 8, in <module>
sys.exit(run())
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/cli/entrypoint.py", line 36, in run
args.run(args)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/cli/lite.py", line 139, in auto_awq
auto_awq(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/lite/apis/auto_awq.py", line 103, in auto_awq
vl_model, model, tokenizer, work_dir = calibrate(model,
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/lite/apis/calibrate.py", line 184, in calibrate
vl_model, model, tokenizer = vl_model_with_tokenizer(model_path=model)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/builder.py", line 65, in vl_model_with_tokenizer
vl_model = load_vl_model(model_path, with_llm).vl_model
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/builder.py", line 55, in load_vl_model
return module(**kwargs)
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/base.py", line 31, in init
self.build_model()
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/model/internvl.py", line 89, in build_model
config.llm_config.attn_implementation = 'eager'
AttributeError: 'dict' object has no attribute 'attn_implementation'
```

**Comment by AllentDan** [comment]
There exists `attn_implementation` in official internvl2 model. Maybe you could add it in your own config or just modify the code to suit yourself.

**Comment by lzk9508** [comment]
> There exists `attn_implementation` in official internvl2 model. Maybe you could add it in your own config or just modify the code to suit yourself.

thank you , this problem is solved, i copy all the py file in the internvl2 official model path to the checkpoint.
