### ISSUE TITLE
[Bug] encounter assert type(chat_template) != type(BaseModel()) while runing an awq quant model of internvl2_8B 

### ISSUE THREAD

**Issue by lzk9508** [InternLM/lmdeploy#2904]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

 assert type(chat_template) != type(BaseModel()), 'failed to match ' \
AssertionError: failed to match chat template, please explicit set chat_template_config

### Reproduction

self.pipe = pipeline(model_path, backend_config=TurbomindEngineConfig(
                                    session_len=self.session_len, 
                                    cache_max_entry_count=self.cache_max_entry_count,model_format='awq'))
self.pipe.vl_encoder.model.config.max_dynamic_patch = self.max_dynamic_patch
response = self.pipe((self.prompt, img), gen_config=generation_config)

### Environment

```Shell
torch:2.4.0+cu121
os: centos7
transformers:4.46.3
lmdeploy:0.6.4
```

### Error traceback

```Shell
InternLM2ForCausalLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
/opt/conda/lib/python3.8/site-packages/accelerate/utils/modeling.py:1508: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  return torch.load(checkpoint_file, map_location=torch.device("cpu"))
2024-12-17 12:00:50,099 - lmdeploy - WARNING - model.py:1924 - Did not find a chat template matching /ossfs/workspace/checkpoint-555_fused_awq/.
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` is not set, default to 2048.
2024-12-17 12:00:52,281 - lmdeploy - WARNING - turbomind.py:231 - get 547 model params
Convert to turbomind format:   0%|                                                                                   | 0/32 [00:00<?, ?it/s]/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/loader.py:131: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  tmp = torch.load(shard, map_location='cpu')
[WARNING] gemm_config.in is not found; using default GEMM algo                                                                              
Traceback (most recent call last):
  File "intention_judge.py", line 564, in <module>
    intention_judge()
  File "intention_judge.py", line 431, in intention_judge
    judge_obj = IntentionJudge(model_path=model_path, init_params=init_params)
  File "/ossfs/workspace/EEyesMllmIntent/algorithm/intention_judge_interface.py", line 144, in __init__
    self.pipe = pipeline(model_path, backend_config=TurbomindEngineConfig(
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/api.py", line 85, in pipeline
    return pipeline_class(model_path,
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/vl_async_engine.py", line 32, in __init__
    self.vl_prompt_template = get_vl_prompt_template(
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/vl/templates.py", line 512, in get_vl_prompt_template
    assert type(chat_template) != type(BaseModel()), 'failed to match ' \
AssertionError: failed to match chat template, please explicit set chat_template_config
```

**Comment by LaoWangGB** [comment]
I meet the same problem. I find chat_template defined by the model_path. You should add origin model name in your model_path, which means your local model name should like "/data/models/internvl2_8B_xxxxx".

**Comment by lzk9508** [comment]
> self.pipe = pipeline(model_path, backend_config=TurbomindEngineConfig(
> session_len=self.session_len,
> cache_max_entry_count=self.cache_max_entry_count,model_format='awq'))
> self.pipe.vl_encoder.model.config.max_dynamic_patch = self.max_dynamic_patch
> response = self.pipe((self.prompt, img), gen_config=generation_config)

how to modify the start script? my model is located in /ossfs/workspace/checkpoint-555_fused_awq/ ，you mean that running like this : self.pipe = pipeline('/ossfs/workspace/checkpoint-555_fused_awq/', backend_config=TurbomindEngineConfig(
 session_len=self.session_len,
cache_max_entry_count=self.cache_max_entry_count,model_format='awq'))

**Comment by AllentDan** [comment]
You may just pass --chat-template internvl2_5 or set chat_template to 'internvl2_5' in your script.

**Comment by lzk9508** [comment]
> template

yes, i set self.pipe = pipeline(model_path, backend_config=TurbomindEngineConfig(
                                    session_len=self.session_len, cache_max_entry_count=self.cache_max_entry_count,model_format='awq'),chat_template_config=ChatTemplateConfig(model_name='internvl2-internlm2')) and solved the problem, thank you every much for instant help
