### ISSUE TITLE
[Bug] InternVL2_5-78B 量化+ tp=4报错

### ISSUE THREAD

**Issue by tian969** [InternLM/lmdeploy#2929]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

设置 backend_config = TurbomindEngineConfig(model_format="awq", tp=4), 在运行过程中报错.

### Reproduction

`
from lmdeploy import ChatTemplateConfig, pipeline,TurbomindEngineConfig, PytorchEngineConfig, GenerationConfig
from lmdeploy.vl import load_image
from tqdm import tqdm
import json
import os

backend_config = TurbomindEngineConfig(model_format="awq")
# backend_config = TurbomindEngineConfig(tp=4)
gen_config = GenerationConfig(max_new_tokens=128)
model_name = "OpenGVLab/InternVL2_5-78B"
pipe = pipeline(model_name, backend_config=backend_config)

`

### Environment

```Shell
sys.platform: linux
Python: 3.8.20 (default, Oct  3 2024, 15:24:27) [GCC 11.2.0]
CUDA available: True
MUSA available: False
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
GCC: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
PyTorch: 2.4.0+cu121
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v3.4.2 (Git Hash 1137e04ec0b5251ca2b4400a4fd3c667ce843d67)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 12.1
  - NVCC architecture flags: -gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_90,code=sm_90
  - CuDNN 90.1  (built against CUDA 12.4)
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=12.1, CUDNN_VERSION=9.1.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=pedantic -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=2.4.0, USE_CUDA=ON, USE_CUDNN=ON, USE_CUSPARSELT=1, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_GLOO=ON, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, USE_ROCM_KERNEL_ASSERT=OFF, 

TorchVision: 0.19.0+cu121
LMDeploy: 0.6.4+
transformers: 4.46.3
gradio: Not Found
fastapi: 0.115.6
pydantic: 2.10.3
triton: 3.0.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6       NIC7    NIC8    NIC9    NIC10   NIC11   CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    NODE    NODE    NODE       NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    PIX     NODE    NODE    NODE    NODE    NODE       NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    PIX     NODE    NODE    NODE    NODE       NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    NODE    NODE    NODE    NODE       PIX     SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     PIX     NODE    NODE    NODE    48-95,144-191   1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     NODE    PIX     NODE    NODE    48-95,144-191   1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     NODE    NODE    PIX     NODE    48-95,144-191   1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     NODE    NODE    NODE    PIX     48-95,144-191   1               N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    NODE    NODE    NODE       NODE    SYS     SYS     SYS     SYS
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    NODE    NODE    NODE       NODE    SYS     SYS     SYS     SYS
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    NODE    NODE    NODE       NODE    SYS     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      PIX     PXB     PXBNODE    SYS     SYS     SYS     SYS
NIC4    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX      X      PXB     PXBNODE    SYS     SYS     SYS     SYS
NIC5    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PXB     PXB      X      PIXNODE    SYS     SYS     SYS     SYS
NIC6    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PXB     PXB     PIX      X NODE    SYS     SYS     SYS     SYS
NIC7    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    NODE    NODE    NODE        X      SYS     SYS     SYS     SYS
NIC8    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS      X      NODE    NODE    NODE
NIC9    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     NODE     X      NODE    NODE
NIC10   SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     NODE    NODE     X      NODE
NIC11   SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYSSYS     NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11
```

### Error traceback

```Shell
[TM][WARNING] [LlamaTritonModel] `max_context_token_num` is not set, default to 32768.                                     
[TM][WARNING] pad vocab size from 151674 to 151676
[TM][WARNING] pad embed size from 151676 to 151676
[TM][WARNING] pad vocab size from 151674 to 151676
[TM][WARNING] pad embed size from 151676 to 151676
[TM][WARNING] pad vocab size from 151674 to 151676
[TM][WARNING] pad embed size from 151676 to 151676
[TM][WARNING] pad vocab size from 151674 to 151676
[TM][WARNING] pad embed size from 151676 to 151676
2024-12-20 02:48:31,529 - lmdeploy - WARNING - turbomind.py:231 - get 5609 model params
Convert to turbomind format:   0%|                                                                  | 0/80 [00:00<?, ?it/s]Traceback (most recent call last):
  File "image_filter_lmdeploy.py", line 34, in <module>
    pipe = pipeline(model_name, backend_config=backend_config)
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/api.py", line 85, in pipeline
    return pipeline_class(model_path,
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/vl_async_engine.py", line 27, in __init__
    super().__init__(model_path, **kwargs)
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 159, in __init__
    self._build_turbomind(model_path=model_path,
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/serve/async_engine.py", line 198, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 302, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 112, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/turbomind.py", line 232, in _from_hf
    tm_model.export()
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 223, in export
    if self.model(i, reader):
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/module.py", line 338, in __call__
    m(i, r)
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/module.py", line 72, in __call__
    return self.apply(*args, **kwargs)
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/module.py", line 224, in apply
    e(self._export, partial(r.attn, i), i)
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/parameter.py", line 58, in __call__
    f(i, g('weight'), 'weight', identity)
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/module.py", line 213, in _export
    self.model.save_split(pack_fn(qkv),
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 203, in save_split
    self.export_weight(split, f'{prefix}.{i}{ext}')
  File "/gpfs/public/raise/tianzujie/miniconda3/envs/lmdeploy/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 166, in export_weight
    for tm_tensor in tm_params[name]:
KeyError: 'layers.0.attention.w_qkv.0.weight'
```

**Comment by tian969** [comment]
找到问题了 得下载AWQ版本的 我理解的有问题
