### ISSUE TITLE
[Bug] lmdeploy 0.6.4 cannot quantize Llama3.1-8B?

### ISSUE THREAD

**Issue by yanchenmochen** [InternLM/lmdeploy#2951]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

```bash
root@b09c32a6a615:~# lmdeploy lite smooth_quant /public/model/llama3.1-8B --work-dir /mnt/self-define/songquanheng/model/llama3.1-8b-lmdeploy-smoothquant-1225
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/usr/local/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/workspace/lmdeploy/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/workspace/lmdeploy/lmdeploy/cli/lite.py", line 152, in smooth_quant
    smooth_quant(**kwargs)
  File "/workspace/lmdeploy/lmdeploy/lite/apis/smooth_quant.py", line 25, in smooth_quant
    vl_model, model, tokenizer, work_dir = calibrate(model,
  File "/workspace/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 247, in calibrate
    model = load_hf_from_pretrained(model,
  File "/workspace/lmdeploy/lmdeploy/lite/utils/load.py", line 19, in load_hf_from_pretrained
    hf_config = AutoConfig.from_pretrained(pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 989, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 772, in from_dict
    config = cls(**config_dict)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
```

### Reproduction

lmdeploy lite smooth_quant /public/model/llama3.1-8B --work-dir /mnt/self-define/songquanheng/model/llama3.1-8b-lmdeploy-smoothquant-1225

### Environment

```Shell
linux
```

### Error traceback

```Shell
root@b09c32a6a615:~# lmdeploy lite smooth_quant /public/model/llama3.1-8B --work-dir /mnt/self-define/songquanheng/model/llama3.1-8b-lmdeploy-smoothquant-1225
/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
You are using a model of type llama to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/usr/local/bin/lmdeploy", line 33, in <module>
    sys.exit(load_entry_point('lmdeploy', 'console_scripts', 'lmdeploy')())
  File "/workspace/lmdeploy/lmdeploy/cli/entrypoint.py", line 42, in run
    args.run(args)
  File "/workspace/lmdeploy/lmdeploy/cli/lite.py", line 152, in smooth_quant
    smooth_quant(**kwargs)
  File "/workspace/lmdeploy/lmdeploy/lite/apis/smooth_quant.py", line 25, in smooth_quant
    vl_model, model, tokenizer, work_dir = calibrate(model,
  File "/workspace/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 247, in calibrate
    model = load_hf_from_pretrained(model,
  File "/workspace/lmdeploy/lmdeploy/lite/utils/load.py", line 19, in load_hf_from_pretrained
    hf_config = AutoConfig.from_pretrained(pretrained_model_name_or_path,
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 989, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 772, in from_dict
    config = cls(**config_dict)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
    self._rope_scaling_validation()
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
    raise ValueError(
ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'low_freq_factor': 1.0, 'high_freq_factor': 4.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
```

**Comment by AllentDan** [comment]
Solution : pip install --upgrade transformers
