### ISSUE TITLE
[Bug] Deploy internlm-chat-7b-w4 on Windows(latest) ERROR

### ISSUE THREAD

**Issue by APX103** [InternLM/lmdeploy#311]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

deploy `internlm-chat-7b-w4`([huggingface](https://huggingface.co/lmdeploy/llama2-chat-7b-w4)) on Windows(latest) error

env:
python 3.11
pytorch 2.0
lmdeploy latest
windows latest

### Reproduction

python -m lmdeploy.serve.turbomind.deploy internlm-chat-7b .\internlm-chat-7b-w4 --model-format awq --group-size 128

### Error traceback

```Shell
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\ProgramData\Anaconda3\envs\lmdeploy_install_test_py311\Lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 1002, in <module> 
    fire.Fire(main)
  File "D:\ProgramData\Anaconda3\envs\lmdeploy_install_test_py311\Lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\lmdeploy_install_test_py311\Lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\lmdeploy_install_test_py311\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\lmdeploy_install_test_py311\Lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 969, in main      
    res = deploy_awq(model_name, model_path, tokenizer_path,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\Anaconda3\envs\lmdeploy_install_test_py311\Lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 606, in deploy_awq
    import _turbomind as _tm  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _turbomind: 找不到指定的模块。
```

**Comment by irexyc** [comment]
可以打印下$env:PATH，看看是否安装了cuda toolkit，版本是多少。目前需要cudatoolkit的版本 >= 11.2
