### ISSUE TITLE
[Feature] Support for CodeLlama 

### ISSUE THREAD

**Issue by vuonghoainam** [InternLM/lmdeploy#312]
### Motivation

CodeLlama just released and is very promising to use. I would like to see `lmdeploy` support for it, would be great!

### Related resources

https://huggingface.co/codellama
There are 7B, 13B and 34B models

### Additional context
I tried but encountered several errors:
- `python3 -m lmdeploy.serve.turbomind.deploy llama2 $MODEL_PATH` -> This runs fine

- `bash workspace/service_docker_up.sh` -> This yields error
```
nvidia-container-cli: mount error: failed to add device rules: unable to find any existing device filters attached to the cgroup: bpf_prog_query(BPF_CGROUP_DEVICE) failed: operation not permitted: unknown
```
-> Context
```
NVIDIA Container Runtime version unknown
spec: 1.1.0-rc.2

runc version 1.1.7
commit: v1.1.7-0-g860f061
spec: 1.0.2-dev
go: go1.19.9
libseccomp: 2.5.3

----------
Client: Docker Engine - Community
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:50:55 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:50:55 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 rootlesskit:
  Version:          1.1.1
  ApiVersion:       1.1.1
  NetworkDriver:    slirp4netns
  PortDriver:       builtin
  StateDir:         /tmp/rootlesskit3022055759
 slirp4netns:
  Version:          1.0.1
  GitCommit:        6a7b16babc95b6a3056b33fb45b74a6f62262dd4
```

- `python3 -m lmdeploy.lite.apis.kv_qparams --work_dir  $MODEL_PATH --kv_sym False --num_tp 2 --turbomind_dir workspace/trition_models/weights/` -> This yields error
```
Traceback (most recent call last):
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/lite/apis/kv_qparams.py", line 123, in <module>
    fire.Fire(main)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/lite/apis/kv_qparams.py", line 110, in main
    assert tm_dir.exists(), 'The specified TurboMind directory does not exist.'
AssertionError: The specified TurboMind directory does not exist.
```

- `python3 -m lmdeploy.lite.apis.calibrate $MODEL_PATH --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir quantized` -> This yields error
```
Traceback (most recent call last):
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 110, in <module>
    fire.Fire(calibrate)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 81, in calibrate
    load_checkpoint_in_model(model, checkpoint, device_map)
  File "/home/aardvark/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 1251, in load_checkpoint_in_model
    raise ValueError(
ValueError: /home/aardvark/Documents/lmdeploy/models/CodeLlama-7b-Instruct-hf/ containing more than one `.index.json` file, delete the irrelevant ones.
```

- `deepspeed --module --num_gpus 2 lmdeploy.pytorch.chat $MODEL_PATH --max_new_tokens 64 --temperture 0.8 --top_p 0.95 --seed 0` -> This yields error
```
Traceback (most recent call last):
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/pytorch/chat.py", line 212, in <module>
    cli()
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/pytorch/chat.py", line 208, in cli
    fire.Fire(main)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/pytorch/chat.py", line 158, in main
    model.generate(torch.tensor([[6]], device=get_local_rank()), warmup_config)
  File "/home/aardvark/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/aardvark/Documents/transformers/src/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/home/aardvark/Documents/transformers/src/transformers/generation/utils.py", line 2765, in sample
    raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.
Traceback (most recent call last):
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/aardvark/mambaforge/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/pytorch/chat.py", line 212, in <module>
    cli()
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/pytorch/chat.py", line 208, in cli
    fire.Fire(main)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/aardvark/.local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/aardvark/Documents/lmdeploy/lmdeploy/pytorch/chat.py", line 158, in main
    model.generate(torch.tensor([[6]], device=get_local_rank()), warmup_config)
  File "/home/aardvark/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/aardvark/Documents/transformers/src/transformers/generation/utils.py", line 1642, in generate
    return self.sample(
  File "/home/aardvark/Documents/transformers/src/transformers/generation/utils.py", line 2765, in sample
    raise ValueError("If `eos_token_id` is defined, make sure that `pad_token_id` is defined.")
ValueError: If `eos_token_id` is defined, make sure that `pad_token_id` is defined.
[2023-08-26 11:31:04,908] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 339410
[2023-08-26 11:31:04,908] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 339411
[2023-08-26 11:31:04,922] [ERROR] [launch.py:321:sigkill_handler] ['/home/aardvark/mambaforge/envs/lmdeploy/bin/python3.10', '-u', '-m', 'lmdeploy.pytorch.chat', '--local_rank=1', '/home/aardvark/Documents/lmdeploy/models/CodeLlama-7b-Instruct-hf/', '--max_new_tokens', '64', '--temperture', '0.8', '--top_p', '0.95', '--seed', '0'] exits with return code = 1
```

**Comment by kristiankielhofner** [comment]
I'm just getting started with lmdeploy but I was looking at this last night. At a minimum there needs to be a new model definition in [model.py](https://github.com/InternLM/lmdeploy/blob/cfabbbd7b76721b86ebdc180cd8e9be2dc052a37/lmdeploy/model.py#L266C25-L266C25) because of differences in prompt format and session length. Like I said just getting started but it looks like the LLaMA CUDA kernels may need to be updated for at least session length as well.

**Comment by lvhan028** [comment]
Hi, @vuonghoainam 
I could deploy `CodeLlama-7b-Instruct-hf` successfully. 
About kv-int8 quantization, please refer to #315

**Comment by lvhan028** [comment]
#359 supports code llama
