### ISSUE TITLE
[Bug] 千问部署openai后无法进行chat接口的调用

### ISSUE THREAD

**Issue by mafamily2496** [InternLM/lmdeploy#313]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

curl http://127.0.0.1:8000/v1/chat/completions -H "Content-Type: application/json" -d '{"model": "qwen-7b","messages": [{"role": "user", "content": "Hello! Ho are you?"}]}'
Internal Server Error

INFO:     127.0.0.1:65459 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\mafam\anaconda3\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 436, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\mafam\anaconda3\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\fastapi\applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\mafam\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\Users\mafam\anaconda3\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\mafam\anaconda3\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\Users\mafam\anaconda3\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\mafam\anaconda3\lib\site-packages\fastapi\routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\mafam\anaconda3\lib\site-packages\lmdeploy\serve\openai\api_server.py", line 191, in chat_completions_v1
    async for res in result_generator:
  File "C:\Users\mafam\anaconda3\lib\site-packages\lmdeploy\serve\async_engine.py", line 207, in generate_openai
    input_ids = self.tokenizer.encode(prompt)
  File "C:\Users\mafam\anaconda3\lib\site-packages\lmdeploy\turbomind\tokenizer.py", line 212, in encode
    return self.model.encode(s)
  File "C:\Users\mafam\anaconda3\lib\site-packages\lmdeploy\turbomind\tokenizer.py", line 134, in encode
    if s.find('<BOS>') != -1:
AttributeError: 'NoneType' object has no attribute 'find'

### Reproduction

看了下好像是qwen-7b的model类没有实现messages2prompt？

**Comment by AllentDan** [comment]
是的，两个PR差不多时间提的，没加，老哥方便加一个 PR 到 lmdeploy 不？:smirk:

**Comment by AllentDan** [comment]
Fixed in #309

**Comment by mafamily2496** [comment]
> Fixed in #309

ok，我自己改了改。。。但是好像有点问题

**Comment by AllentDan** [comment]
可以试试 #309

**Comment by huyang19881115** [comment]
AttributeError: 'ChatCompletionResponse' object has no attribute 'model_dump_json'
INFO:     127.0.0.1:48424 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/llmservice/Qwen-72-4bit/openai_api.py", line 386, in create_chat_completion
    response, _ = model.chat(
                  ^^^^^^^^^^^
  File "/home/zkyd/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-Int4/modeling_qwen.py", line 1139, in chat
    outputs = self.generate(
              ^^^^^^^^^^^^^^
  File "/home/zkyd/.cache/huggingface/modules/transformers_modules/Qwen-72B-Chat-Int4/modeling_qwen.py", line 1261, in generate
    return super().generate(
           ^^^^^^^^^^^^^^^^^
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 1485, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/home/zkyd/miniconda3/envs/qwen/lib/python3.11/site-packages/transformers/generation/utils.py", line 1262, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['append_history'] (note: typos in the generate arguments will also show up in this list)
