### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named '_turbomind'

### ISSUE THREAD

**Issue by amulil** [InternLM/lmdeploy#340]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

```python
import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'
```

### Reproduction
install lmdeploy by
`pip install lmdeploy`
then run the below command
```python
CUDA_VISIBLE_DEVICES=7 python3 -m lmdeploy.serve.turbomind.deploy llama2 /data/home/xxx/model/llama2/7b/origin/chat-hf/
python3 -m lmdeploy.turbomind.chat ./workspace
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/data/home/xxx/examples/lmdeploy/lmdeploy/turbomind/__init__.py", line 3, in <module>
    from .turbomind import TurboMind
  File "/data/home/xxx/examples/lmdeploy/lmdeploy/turbomind/turbomind.py", line 22, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'
```
### OS
```bash
Operating System: Ubuntu 20.04.6 LTS
Kernel: Linux 5.4.0-139-generic
Architecture: x86-64
```

**Comment by tpoisonooo** [comment]
如果 source 安装的话， 需要  cmake build with python && make install，然后 build 目录下有 so

建议 python3 -m pip 安装。

**Comment by amulil** [comment]
> 如果 source 安装的话， 需要 cmake build with python && make install，然后 build 目录下有 so
> 
> 建议 python3 -m pip 安装。

`python3 -m pip install lmdeploy` 还是会报同样的错误

**Comment by irexyc** [comment]
不要在/data/home/xxx/examples/lmdeploy 这个目录下执行命令

**Comment by amulil** [comment]
> ```python
> CUDA_VISIBLE_DEVICES=7
> ```
在 `/data/home/xxx/examples` 下运行出现新的错误：
```bash
Exception in thread Thread-2 (_create_model_instance):
Traceback (most recent call last):
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 190, in _create_model_instance
    model_inst = self.tm_model.model.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: API call is not supported in the installed CUDA driver /lmdeploy/src/turbomind/utils/allocator.h:163 
```

**Comment by amulil** [comment]
> 不要在/data/home/xxx/examples/lmdeploy 这个目录下执行命令


在 `/data/home/xxx/examples` 下运行
`python3 -m lmdeploy.turbomind.chat ./workspace`
出现新的错误：
```bash
Exception in thread Thread-2 (_create_model_instance):
Traceback (most recent call last):
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 190, in _create_model_instance
    model_inst = self.tm_model.model.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: API call is not supported in the installed CUDA driver /lmdeploy/src/turbomind/utils/allocator.h:163 
```

**Comment by irexyc** [comment]
所有的log就是这些么？

nvidia-smi 的输出是什么？

cuda 装的哪个版本？

**Comment by amulil** [comment]
> 所有的log就是这些么？
> 
> nvidia-smi 的输出是什么？
> 
> cuda 装的哪个版本？

运行 `CUDA_VISIBLE_DEVICES=7 python3 -m lmdeploy.
turbomind.chat ./workspace` 全部 log 信息：
```bash
Exception in thread Thread-2 (_create_model_instance):
Traceback (most recent call last):
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/xxx/.conda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 190, in _create_model_instance
    model_inst = self.tm_model.model.create_model_instance(
RuntimeError: [TM][ERROR] CUDA runtime error: API call is not supported in the installed CUDA driver /lmdeploy/src/turbomind/utils/allocator.h:163 


double enter to end input >>> 
```
nvidia-smi 输出：
```bash
Thu Aug 31 17:14:45 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      On   | 00000000:0B:01.0 Off |                    0 |
| N/A   45C    P0   355W / 400W |  20278MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  A100-SXM4-40GB      On   | 00000000:0B:02.0 Off |                    0 |
| N/A   59C    P0   369W / 400W |  38674MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  A100-SXM4-40GB      On   | 00000000:0B:03.0 Off |                    0 |
| N/A   57C    P0   369W / 400W |  35564MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   3  A100-SXM4-40GB      On   | 00000000:0B:04.0 Off |                    0 |
| N/A   53C    P0   377W / 400W |  33762MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   4  A100-SXM4-40GB      On   | 00000000:41:01.0 Off |                    0 |
| N/A   53C    P0   352W / 400W |  29434MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   5  A100-SXM4-40GB      On   | 00000000:41:02.0 Off |                    0 |
| N/A   60C    P0   347W / 400W |  36228MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   6  A100-SXM4-40GB      On   | 00000000:41:03.0 Off |                    0 |
| N/A   51C    P0   321W / 400W |  26806MiB / 40537MiB |    100%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   7  A100-SXM4-40GB      On   | 00000000:41:04.0 Off |                    0 |
| N/A   27C    P0    57W / 400W |  13712MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   3662408      C   .../llama_etuning/bin/python    20273MiB |
|    1   N/A  N/A   3662409      C   .../llama_etuning/bin/python    38669MiB |
|    2   N/A  N/A   3662410      C   .../llama_etuning/bin/python    35559MiB |
|    3   N/A  N/A   3662411      C   .../llama_etuning/bin/python    33757MiB |
|    4   N/A  N/A   3662412      C   .../llama_etuning/bin/python    29429MiB |
|    5   N/A  N/A   3662413      C   .../llama_etuning/bin/python    36223MiB |
|    6   N/A  N/A   3662414      C   .../llama_etuning/bin/python    26801MiB |
|    7   N/A  N/A   3939356      C   python3                         13709MiB |
+-----------------------------------------------------------------------------+
```

cuda 信息：
```bash
cuda-python               12.2.0
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
```

**Comment by irexyc** [comment]
1. 感觉驱动版本过低了。驱动支持到cuda 11.0，但是_turbomind编译时用到了cuda11.2的api，所以应该得更新一下显卡驱动。

2. 我问的 cuda 版本指的是 /usr/local/ 目录下的 cuda-toolkit版本。建议装个cuda11.8的
```
~ ❯ ls /usr/local -lh                                                                                                                                     cx@lab
total 36K
drwxr-xr-x  2 root root 4.0K  6月  9 20:37 bin
lrwxrwxrwx  1 root root   21  6月 12 16:05 cuda -> /usr/local/cuda-11.8/
drwxr-xr-x 17 root root 4.0K  6月 12 16:05 cuda-11.8
drwxr-xr-x  2 root root 4.0K  2月 23  2023 etc
drwxr-xr-x  2 root root 4.0K  2月 23  2023 games
drwxr-xr-x  2 root root 4.0K  2月 23  2023 include
drwxr-xr-x  3 root root 4.0K  2月 23  2023 lib
lrwxrwxrwx  1 root root    9  6月  9 20:12 man -> share/man
drwxr-xr-x  2 root root 4.0K  2月 23  2023 sbin
drwxr-xr-x  8 root root 4.0K  6月 12 14:11 share
drwxr-xr-x  2 root root 4.0K  2月 23  2023 src
```

**Comment by amulil** [comment]
```bash
root@4e6328027286:/opt/tritonserver# nvidia-smi
Fri Sep  1 09:32:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100-SXM4-40GB      On   | 00000000:0B:01.0 Off |                    0 |
| N/A   26C    P0    56W / 400W |  18618MiB / 40537MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```
使用 dcoker 方式运行，驱动没有改变，CUDA Version 变为 11.8  后，可以跑通

**Comment by JiangFeng07** [comment]
<img width="502" alt="image" src="https://github.com/InternLM/lmdeploy/assets/20489119/823fd69c-9b49-446d-a488-b046376daa02">

do not execute this command "python3 -m lmdeploy.serve.turbomind.deploy llama2 ..." at the root directory lmdeploy，“import lmdeploy”  , the path will be wrong.

**Comment by lvhan028** [comment]
Yes if you installed lmdeploy by `pip install lmdeploy`. That's why we suggest running commands out of lmdeploy's root directory

**Comment by chenxqiyu** [comment]
![屏幕截图 2023-09-26 205614](https://github.com/InternLM/lmdeploy/assets/10222853/fd345601-2462-4255-b8e7-6a9df23434bd)
ok

**Comment by janelu9** [comment]
> 1. 感觉驱动版本过低了。驱动支持到cuda 11.0，但是_turbomind编译时用到了cuda11.2的api，所以应该得更新一下显卡驱动。
> 2. 我问的 cuda 版本指的是 /usr/local/ 目录下的 cuda-toolkit版本。建议装个cuda11.8的
> 
> ```
> ~ ❯ ls /usr/local -lh                                                                                                                                     cx@lab
> total 36K
> drwxr-xr-x  2 root root 4.0K  6月  9 20:37 bin
> lrwxrwxrwx  1 root root   21  6月 12 16:05 cuda -> /usr/local/cuda-11.8/
> drwxr-xr-x 17 root root 4.0K  6月 12 16:05 cuda-11.8
> drwxr-xr-x  2 root root 4.0K  2月 23  2023 etc
> drwxr-xr-x  2 root root 4.0K  2月 23  2023 games
> drwxr-xr-x  2 root root 4.0K  2月 23  2023 include
> drwxr-xr-x  3 root root 4.0K  2月 23  2023 lib
> lrwxrwxrwx  1 root root    9  6月  9 20:12 man -> share/man
> drwxr-xr-x  2 root root 4.0K  2月 23  2023 sbin
> drwxr-xr-x  8 root root 4.0K  6月 12 14:11 share
> drwxr-xr-x  2 root root 4.0K  2月 23  2023 src
> ```

宿主机驱动版本太低，把容器内的/usr/local/cuda/compat添加到LD_LIBRARY_PATH 使用容器内的cuda驱动就可以了
