### ISSUE TITLE
[Bug] Unable to quantize llama-30b

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [InternLM/lmdeploy#343]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

Generation of quantization parameter with lmdeploy.lite.apis.calibrate raises error.

### Reproduction

I downloaded [llama-30b](https://huggingface.co/huggyllama/llama-30b) model from huggingface and tried to run following command:

python3 -m lmdeploy.lite.apis.calibrate \
  --model llama-30b \
  --calib_dataset 'wikitext2' \
  --calib_samples 128 \
  --calib_seqlen 2048 \
  --work_dir awq-llama-30b

### Error traceback

```Shell
You are using the legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This means that tokens that come after special tokens will not be properly handled. We recommend you to read the related pull request available at https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 110, in <module>
    fire.Fire(calibrate)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 55, in calibrate
    tokenizer = AutoTokenizer.from_pretrained(model,
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 702, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1841, in from_pretrained
    return cls._from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2004, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 144, in __init__
    self.sp_model.Load(vocab_file)
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]
```

**Comment by lvhan028** [comment]
It looks like `sentencepiece` loads tokenizer model failed. 
Can its tokenizer model be loaded successfully through AutoTokenizer?

**Comment by Nikita-Sherstnev** [comment]
@lvhan028 AutoTokenizer loads it without problem.

**Comment by lvhan028** [comment]
@pppppM Could you help investigate it?

**Comment by pppppM** [comment]
Hi, @Nikita-Sherstnev , did you change this line ?
https://github.com/InternLM/lmdeploy/blob/22e8b2ca2b38ff924ca1cbf82ae7e34b51d1d61a/lmdeploy/lite/apis/calibrate.py#L81

**Comment by Nikita-Sherstnev** [comment]
Hi, no, I did not. I use lmdeploy 0.0.6 from pip. I run calibration with following arguments:
python3 -m lmdeploy.lite.apis.calibrate --model llama-30b --calib_dataset 'wikitext2' --calib_samples 128 --calib_seqlen 1024   --work_dir awq-llama-30b --device 'cpu'

**Comment by pppppM** [comment]
Sorry, LMDeploy don't support quantize model in CPU, it will be very slowly.

 We will remove the `device` argument to avoid misleading.
If you don't have enough GPU memory, try turning `calib_seqlen` down
