### ISSUE TITLE
[Bug] Inference with TP 2 (Llamaa 70B W4A16)

### ISSUE THREAD

**Issue by hatrexltd** [InternLM/lmdeploy#420]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

When I use --tp 2, there is an error, and when I perform an inference, I get "meteo meteor meteor" 100 times, whereas with tp 1, everything works fine.

### Reproduction

python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 60000 --instance_num 32 --tp 2
(Model W4A16)

### Error traceback

```Shell
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/turbomind/turbomind.py", line 128, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /opt/tritonserver/lmdeploy/src/turbomind/utils/memory_utils.cu:136 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/turbomind/turbomind.py", line 128, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /opt/tritonserver/lmdeploy/src/turbomind/utils/memory_utils.cu:136 [WARNING] gemm_config.in is not found; using default GEMM algo
INFO:     Started server process [7474]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:60000 (Press CTRL+C to quit)
```
> Latest version of LMDeploy

**Comment by sjzhou4** [comment]
https://github.com/InternLM/lmdeploy/issues/243

**Comment by sjzhou4** [comment]
I tried this problem too, and it does exist.

**Comment by lzhangzz** [comment]
Slicing W4 weights at runtime is not supported yet. 

You may try to specify TP size when converting the model using `deploy.py`

**Comment by sjzhou4** [comment]
@lzhangzz THX，it well done

**Comment by qiuxuezhe123** [comment]
> Slicing W4 weights at runtime is not supported yet.
> 
> You may try to specify TP size when converting the model using `deploy.py`
deploy.py这个脚本是做什么的，我在地址中没有找到这个脚本

**Comment by lvhan028** [comment]
抱歉，文档没有同步更新。

从 lmdeploy v0.0.13 之后，deploy.py 被移除，使用CLI方式替代。
用法：
```
lmdeploy convert llama2 <model_path> --tp 2
```

**Comment by qiuxuezhe123** [comment]
> 抱歉，文档没有同步更新。
> 
> 从 lmdeploy v0.0.13 之后，deploy.py 被移除，使用CLI方式替代。 用法：
> 
> ```
> lmdeploy convert llama2 <model_path> --tp 2
> ```

发现qwen-7b-awq使用 lmdeploy convert llama2 <model_path> --tp 2命令能成功，但是qwen-14b-awq convert失败，命令如下：
lmdeploy convert \
    --model-name qwen-14b \
    --model-path ./Qwen-14B-Chat-awq \
    --model-format awq \
    --group-size 128 \
    --tp 2 \
    --dst_path ./workspace_qwen_14b_awq_test
   报错信息如下：
Traceback (most recent call last):
  File "/opt/conda/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/cli/cli.py", line 49, in convert
    convert(model_name,
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/converter.py", line 224, in main
    output_model.export()
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 173, in export
    self.export_transformer_block(bin, i)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 156, in export_transformer_block
    self.save_split(w2_sz, f'layers.{i}.feed_forward.w2.scales_zeros', 0)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 149, in save_split
    assert tensor.shape[split_dim] % tp == 0
AssertionError
Convert to turbomind format:   0%|                                                                             | 0/40 [00:04<?, ?it/s]

**Comment by lvhan028** [comment]
qwen量化时，group_size是128。量化参数zeros的shape不能被2整除了。所以没法tp 2。我们想想怎么支持下
