### ISSUE TITLE
[Bug] kv cache int8 failed

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#422]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

```shell
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:17<00:00,  5.80s/it]
Loading calibrate dataset ...
/opt/conda/lib/python3.8/site-packages/datasets/load.py:2072: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
/opt/conda/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
/opt/conda/lib/python3.8/site-packages/datasets/load.py:2072: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/lmdeploy/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 110, in <module>
    fire.Fire(calibrate)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/lmdeploy/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 84, in calibrate
    calib_loader, _ = get_calib_loaders(calib_dataset,
  File "/data/lmdeploy/lmdeploy/lmdeploy/lite/utils/calib_dataloader.py", line 308, in get_calib_loaders
    return get_c4(tokenizer, nsamples, seed, seqlen)
  File "/data/lmdeploy/lmdeploy/lmdeploy/lite/utils/calib_dataloader.py", line 110, in get_c4
    for _ in range(nsamples):
TypeError: 'str' object cannot be interpreted as an integer
quant.sh: line 7: --calib_samples: command not found
quant.sh: line 8: --calib_seqlen: command not found
quant.sh: line 9: --work_dir: command not found
```

### Reproduction

GPU: V100

shell script:
```
HF_MODEL=/data/vicuna-13b/vicuna-13b-v1.5
WORK_DIR=/data/lmdeploy/lmdeploy/benchmark/workspace/kv_int8
python3 -m lmdeploy.lite.apis.calibrate \
  --model $HF_MODEL \
  --calib_dataset 'c4' \             # Support c4, ptb, wikitext2, pileval
  --calib_samples 128 \              # Number of samples in the calibration set, if the memory is not enough, it can be adjusted appropriately
  --calib_seqlen 2048 \              # Length of a single text, if the memory is not enough, you can adjust it appropriately
  --work_dir $WORK_DIR \             # Directory for saving quantized statistical parameters and quantized weights in Pytorch format
~
```

**Comment by sleepwalker2017** [comment]
wtf   it's the shell format problem. I retype these commands and it's ok now
