### ISSUE TITLE
[Bug] KV cache int8 convert  failed

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#424]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

```
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:18<00:00,  6.26s/it]
Loading calibrate dataset ...
/opt/conda/lib/python3.8/site-packages/datasets/load.py:2072: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
/opt/conda/lib/python3.8/site-packages/scipy/__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.4)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "
/opt/conda/lib/python3.8/site-packages/datasets/load.py:2072: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Repo card metadata block was not found. Setting CardData to empty.
Token indices sequence length is longer than the specified maximum sequence length for this model (4131 > 4096). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data//lmdeploy/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 110, in <module>
    fire.Fire(calibrate)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data//lmdeploy/lmdeploy/lmdeploy/lite/apis/calibrate.py", line 101, in calibrate
    calib_ctx.calibrate(all_data)
  File "/data//lmdeploy/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 285, in calibrate
    _ = model(data.to(self.device))
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 693, in forward
    layer_outputs = decoder_layer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data//lmdeploy/lmdeploy/lmdeploy/lite/quantization/calibration.py", line 166, in _forward
    out = self._ori_forwards[mod](*batch_args[i],
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 408, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/llama/modeling_llama.py", line 346, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 31.75 GiB total capacity; 30.73 GiB already allocated; 318.19 MiB free; 31.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### Reproduction

在 V100 执行的 llama 13B，32G 的显存不够用吗？

另外，转换是不是也可以在 CPU 来做？

```shell
CUDA_VISIBLE_DEVICES=1 python3 -m lmdeploy.lite.apis.calibrate \
  --model $HF_MODEL \
  --calib_dataset 'c4' \
  --calib_samples 128  \
  --calib_seqlen 2048 \
  --work_dir $WORK_DIR
```

**Comment by tpoisonooo** [comment]
这不是转换，是在推理，记录内部结构的 min/max

**Comment by sleepwalker2017** [comment]
> 这不是转换，是在推理，记录内部结构的 min/max

奇怪   V100 32G 应该是够用的  这里面做了什么特殊操作吗

**Comment by sleepwalker2017** [comment]
中间保存了太多数据，到后面无法完成推理过程。后续：我在A100 完成了这个操作。

**Comment by wanzhenchn** [comment]
适当减小calib_samples也是可以的，只是统计的数据越多获得的 min/max更精确一些
