### ISSUE TITLE
[Bug] AttributeError: 'NoneType' object has no attribute 'find'

### ISSUE THREAD

**Issue by sleepwalker2017** [InternLM/lmdeploy#432]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

```shell
diff --git a/lmdeploy/model.py b/lmdeploy/model.py
index fd724a2..f7450c5 100644
--- a/lmdeploy/model.py
+++ b/lmdeploy/model.py
@@ -48,6 +48,7 @@ class BaseModel:
         Returns:
             str: the concatenated prompt
         """
+       return prompt
         if self.capability == 'completion':
             return prompt
         else:
```

我加了这一行   解决了问题。不知道self.capability的含义是什么，如果不是completion，返回的是None。导致后续encode失败。

### Reproduction

```python
for i in range(0, len(test_data)):
    datas = test_data[i]
    #for j in range(i, min(i + batch_size, len(test_data))):
    #    datas.append(test_data[j])
    input_dict = {
        'prompt': datas,
        'top_k': top_k,
        'top_p': top_p,
        #'beam_width': beam_width,
        'temperature': temperature,
        'repetition_penalty': repetition_penalty,
        'request_output_len': output_len,
        'sequence_start': True,
        'sequence_end': True
    }
    #req = json.dumps({
    #    "traceid": 1234567,
    #    "clientip": socket.gethostname(),
    #    "data": input_dict,
    #})
    req = json.dumps(input_dict)
    res = requests.post(url=url, data=req)
```

### Error traceback

```Shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/conda/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/lib/python3.8/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/lib/python3.8/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/data/lmdeploy/lmdeploy/lmdeploy/serve/openai/api_server.py", line 309, in generate
    async for out in generation:
  File "/data/lmdeploy/lmdeploy/lmdeploy/serve/async_engine.py", line 113, in generate
    input_ids = self.tokenizer.encode(prompt)
  File "/data/lmdeploy/lmdeploy/lmdeploy/turbomind/tokenizer.py", line 268, in encode
    return self.model.encode(s)
  File "/data/lmdeploy/lmdeploy/lmdeploy/turbomind/tokenizer.py", line 183, in encode
    if s.find('<BOS>') != -1:
AttributeError: 'NoneType' object has no attribute 'find'
```
```

**Comment by lvhan028** [comment]
capability表示模型能力，支持 codellama 的时候引入的。
- completion表示续写
- chat表示对话
- infilling 表示代码填空
- python: 表示codellama的python specialist

**Comment by lvhan028** [comment]
这个问题我在修，0.0.9 会解决

**Comment by lvhan028** [comment]
在 v0.0.9 中已经解决，相关PR #440

**Comment by chenhaoqiang** [comment]
@lvhan028 我使用的是lmdeploy-v0.0.14版本，仍热遇到了这个错误，不过报错的行号变了。您有时间了帮我看看哈，需要什么环境参数的我提供下。我是在4张GPU Tesla T4卡上跑的, --tp 4。谢谢哈！
![image](https://github.com/InternLM/lmdeploy/assets/20062034/f6704f96-32e3-4a1a-abca-3b73dbb467b2)

**Comment by lvhan028** [comment]
模型转换的时候用的是啥命令呢？
得用对话模型才行

**Comment by chenhaoqiang** [comment]
> 模型转换的时候用的是啥命令呢？ 得用对话模型才行

感谢回复！我用单卡A10的解决了，部署成功了，使用的这个量化好的：https://huggingface.co/lmdeploy/qwen-chat-14b-4bit/blob/main/README_zh-CN.md，但是发现好像function call功能没有了：
![image](https://github.com/InternLM/lmdeploy/assets/20062034/ac006e10-7573-44b6-8410-fe4697c412b5)

**Comment by lvhan028** [comment]
对，lmdeploy没有支持function call

**Comment by chenhaoqiang** [comment]
> 对，lmdeploy没有支持function call

感谢回复！后续有计划支持吗？

**Comment by lvhan028** [comment]
这个功能应该是在 [lagent](https://github.com/InternLM/lagent) 中支持的
lmdeploy目前没有 function_call 的规划

**Comment by chenhaoqiang** [comment]
> 这个功能应该是在 [lagent](https://github.com/InternLM/lagent) 中支持的
> 
> lmdeploy目前没有 function_call 的规划

好的谢谢 我先去研究下lagent

**Comment by chenhaoqiang** [comment]
> 这个功能应该是在 [lagent](https://github.com/InternLM/lagent) 中支持的
> 
> lmdeploy目前没有 function_call 的规划

看了下 function call应该是模型本身的能力，qwen14b-chat本身是有function call能力的，但是通过你们的方式量化后function call就没有了，不知道是不是我哪里没设置对
