### ISSUE TITLE
[Bug] RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:136

### ISSUE THREAD

**Issue by mzxhzhp** [InternLM/lmdeploy#450]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### 运行环境：
GPU：RTX 4090
lmdeploy：lmdeploy-0.0.9
模型文件：internlm-chat-20b-turbomind-w4

### 操作指令：
python -m lmdeploy.turbomind.chat ./models/internlm/internlm-chat-20b-turbomind-w4/ --tp 2

### 报错详情：
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
Exception in thread Thread-2 (_create_weight):
Traceback (most recent call last):
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 128, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:136 

Exception in thread Thread-1 (_create_weight):
Traceback (most recent call last):
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 128, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:136

### 备注：
--tp 1 不会报错

### Reproduction

python -m lmdeploy.turbomind.chat ./models/internlm/internlm-chat-20b-turbomind-w4/ --tp 2

### Error traceback

```Shell
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
Exception in thread Thread-2 (_create_weight):
Traceback (most recent call last):
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 128, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:136 

Exception in thread Thread-1 (_create_weight):
Traceback (most recent call last):
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/llm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/llm/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 128, in _create_weight
    model.create_shared_weights(device_id, rank)
RuntimeError: [TM][ERROR] CUDA runtime error: invalid argument /lmdeploy/src/turbomind/utils/memory_utils.cu:136
```

**Comment by lzhangzz** [comment]
same as #420
