### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by vansin** [InternLM/lmdeploy#457]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

```shell
(lmdeploy) ➜  ~ python -m lmdeploy.serve.turbomind.deploy internlm-chat \ 
    --model-path ./internlm-chat-20b \
    --model-format awq \
    --group-size 128
create workspace in directory ./workspace
copy triton model templates from "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/turbomind/triton_models" to "./workspace/triton_models" successfully
0
Traceback (most recent call last):
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 1028, in <module>
    fire.Fire(main)
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 995, in main
    res = deploy_awq(model_name, model_path, tokenizer_path,
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 678, in deploy_awq
    q_qw = get_tensor(f'model.layers.{i}.self_attn.q_proj.qweight')
  File "/cpfs01/user/huwenxing/miniconda/envs/lmdeploy/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 623, in get_tensor
    return _params[name].cuda().contiguous()
KeyError: 'model.layers.0.self_attn.q_proj.qweight'
```

### Reproduction

```shell
pip install 'lmdeploy>=0.0.9'`

git-lfs install
git clone https://huggingface.co/internlm/internlm-chat-20b

python3 -m lmdeploy.serve.turbomind.deploy internlm-chat \
    --model-path ./internlm-chat-20b \
    --model-format awq \
    --group-size 128

```

**Comment by wangschang** [comment]
are you fix this problem?
