### ISSUE TITLE
[Bug] Qwen kv int8推理

### ISSUE THREAD

**Issue by Vincent131499** [InternLM/lmdeploy#529]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

在使用kv int8量化时，针对[qwen-7b-chat](https://huggingface.co/Qwen/Qwen-7B-Chat)模型生成搜索参数，出现如下bug信息：

Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|████████████████████████████████████████| 8/8 [00:00<00:00, 25.86it/s]
Loading calibrate dataset ...
/usr/local/lib/python3.8/dist-packages/datasets/load.py:2089: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=False' instead.
  warnings.warn(
Token indices sequence length is longer than the specified maximum sequence length for this model (11845 > 8192). Running this sequence through the model will result in indexing errors
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 110, in <module>
    fire.Fire(calibrate)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/apis/calibrate.py", line 101, in calibrate
    calib_ctx.calibrate(all_data)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/quantization/calibration.py", line 285, in calibrate
    _ = model(data.to(self.device))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 930, in forward
    outputs = block(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/lite/quantization/calibration.py", line 166, in _forward
    out = self._ori_forwards[mod](*batch_args[i],
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 631, in forward
    attn_outputs = self.attn(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 472, in forward
    query = apply_rotary_pos_emb(query, q_pos_emb)
  File "/root/.cache/huggingface/modules/transformers_modules/modeling_qwen.py", line 1399, in apply_rotary_pos_emb
    t_ = (t_ * cos) + (_rotate_half(t_) * sin)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Reproduction

使用命令如下：
 python3 -m lmdeploy.lite.apis.calibrate --model ../pretrain_models/Qwen-7B-chat/ --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir ./qwen-7b-int8

麻烦定位下啊

**Comment by wangschang** [comment]
请问这个可以了吗

**Comment by LiuKai22** [comment]
@pppppM  我遇到了同样的问题，看起来是添加位置编码时，一部分中间特征值没有转移到GPU上， 麻烦定位一下，或者release一下你们如何量化Qwen的kv cache int8的方法。

**Comment by pppppM** [comment]
@wangschang @LiuKai22 @Vincent131499 应该是 qwen 模型代码有更新，我们开发环境里的 qwen 是没问题，正在下载新的 qwen 模型进行测试

**Comment by AU-CPU** [comment]
@pppppM 请问这个问题解决了吗？ 我也遇到了同样的问题RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by AU-CPU** [comment]
attn_weights = torch.where(
            causal_mask, attn_weights.to(attn_weights.dtype), mask_value
        )我是在这个位置出现的错误

**Comment by pppppM** [comment]
#605 中已经解决，这两天会 merge @Vincent131499 @AU-CPU @LiuKai22

**Comment by pppppM** [comment]
@Vincent131499 @AU-CPU @LiuKai22 #605 已经合入 main 分支
