### ISSUE TITLE
[Bug]AttributeError: 'ErrorResponse' object has no attribute 'model_dump' 

### ISSUE THREAD

**Issue by wangschang** [InternLM/lmdeploy#542]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

model: qwen-7b-chat 微调后合并的版本 直接运行没问题, kv int8后的也是这个问题，int4目前官方支持不了
step：

1.create workspace files success
python -m lmdeploy.serve.turbomind.deploy qwen-7b  /hy-tmp/quantize/qwen1009

2.run openai success
python -m lmdeploy.serve.openai.api_server /hy-tmp/workspace  0.0.0.0  8080 --instance_num 32 --tp 1

[WARNING] gemm_config.in is not found; using default GEMM algo
INFO:     Started server process [1027762]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

3.request api error

follow error is blow 

INFO:     172.17.0.1:51102 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application

### Reproduction

1.create workspace files success
python -m lmdeploy.serve.turbomind.deploy qwen-7b  /hy-tmp/quantize/qwen1009

2.run openai success
python -m lmdeploy.serve.openai.api_server /hy-tmp/workspace  0.0.0.0  8080 --instance_num 32 --tp 1

[WARNING] gemm_config.in is not found; using default GEMM algo
INFO:     Started server process [1027762]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)

3.request api error

### Error traceback

```Shell
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/miniconda3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 110, in chat_completions_v1
    error_check_ret = await check_request(request)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 70, in check_request
    ret = create_error_response(
  File "/usr/local/miniconda3/lib/python3.8/site-packages/lmdeploy/serve/openai/api_server.py", line 61, in create_error_response
    ErrorResponse(message=message,
AttributeError: 'ErrorResponse' object has no attribute 'model_dump'
```

**Comment by AllentDan** [comment]
Please update fastpi and pydantic package.

**Comment by wangschang** [comment]
It is works!
thanks very much!
