### ISSUE TITLE
[Bug] Max retries exceeded while serving with `lmdeploy.serve.gradio.app`

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#561]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Doc:
`https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/restful_api.md`
Cmd: 
`python -m lmdeploy.serve.gradio.app http://127.0.0.1:10001 127.0.0.1 10001 --restful_api True`

### Reproduction

`python -m lmdeploy.serve.gradio.app http://127.0.0.1:10001 127.0.0.1 10001 --restful_api True`

### Error traceback

```Shell
Traceback (most recent call last):
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fb219d27730>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/cpfs01/user/lizhenxiang/miniconda3/envs/lmdeploy006/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=10001): Max retries exceeded with url: /v1/models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb219d27730>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
```

**Comment by AllentDan** [comment]
Did you launch the api_server service first? And proxy should be closed BTW。
