### ISSUE TITLE
[Bug] Server exited while `profile_restful_api`

### ISSUE THREAD

**Issue by del-zhenwu** [InternLM/lmdeploy#562]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Model: internlm-20b

Cmd:
`python benchmark/profile_restful_api.py http://127.0.0.1:6006 ../workspace/triton_models/tokenizer/tokenizer.model benchmark/src.json --concurrency 32`
Client log:
```
start to warmup ...
Process Process-1:
Traceback (most recent call last):
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/urllib3/response.py", line 710, in _error_catcher
    yield
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/urllib3/response.py", line 1077, in read_chunked
    self._update_chunk_length()
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/urllib3/response.py", line 1012, in _update_chunk_length
    raise InvalidChunkLength(self, line) from None
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/requests/models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/urllib3/response.py", line 937, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/urllib3/response.py", line 1065, in read_chunked
    with self._error_catcher():
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/urllib3/response.py", line 727, in _error_catcher
    raise ProtocolError(f"Connection broken: {e!r}", e) from e
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home//lmdeploy/benchmark/profile_restful_api.py", line 83, in _infer
    for _, _ in get_streaming_response(
  File "/home//lmdeploy/benchmark/profile_restful_api.py", line 37, in get_streaming_response
    for chunk in response.iter_lines(chunk_size=8192,
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/requests/models.py", line 865, in iter_lines
    for chunk in self.iter_content(
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/requests/models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Process Process-2:
Process Process-7:
Process Process-3:
```

### Reproduction

`python benchmark/profile_restful_api.py http://127.0.0.1:6006 ../workspace/triton_models/tokenizer/tokenizer.model benchmark/src.json --concurrency 32`

### Error traceback

```Shell
Server start cmd:
```
python3 -m lmdeploy.serve.openai.api_server ./workspace 0.0.0.0 6006 --instance_num 32 --tp 1
```
Server log:


INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
INFO:     127.0.0.1:47604 - "POST /generate HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/home//df/envs/lmdeploy0.0.8/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 297, in stream_results
    data = chunk.model_dump_json()
AttributeError: 'GenerateResponse' object has no attribute 'model_dump_json'
INFO:     127.0.0.1:47606 - "POST /generate HTTP/1.1" 200 OK
Aborted
```
```

**Comment by AllentDan** [comment]
Please update fastapi and pydantic to the latest
