### ISSUE TITLE
部署时报错：ModuleNotFoundError: No module named '_turbomind'

### ISSUE THREAD

**Issue by cat-knight** [InternLM/lmdeploy#569]
如题，将千问14b模型导出后，通过以下命令部署：
python3 -m lmdeploy.serve.openai.api_server /root/autodl-fs/llm_models/workspace 0.0.0.0 6006
结果报错：
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/QA/lmdeploy_main/lmdeploy/serve/openai/api_server.py", line 360, in <module>
    fire.Fire(main)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/QA/lmdeploy_main/lmdeploy/serve/openai/api_server.py", line 353, in main
    VariableInterface.async_engine = AsyncEngine(model_path=model_path,
  File "/data/QA/lmdeploy_main/lmdeploy/serve/async_engine.py", line 32, in __init__
    from lmdeploy import turbomind as tm
  File "/data/QA/lmdeploy_main/lmdeploy/turbomind/__init__.py", line 2, in <module>
    from .turbomind import TurboMind
  File "/data/QA/lmdeploy_main/lmdeploy/turbomind/turbomind.py", line 23, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'

**Comment by lvhan028** [comment]
有安装么？pip install lmdeploy==0.0.11

**Comment by cat-knight** [comment]
> 你应该安装了 lmdeploy 了。 但从上面的日志中，可以看出，python找的是"/data/QA/lmdeploy_main/lmdeploy/serve/openai/api_server.py"。 但应该让 python 找 /root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages 下的 lmdeploy。
> 
> 估计你是在 lmdeploy 源码根目录下运行的上述命令。换个目录试试。

按照你的意见，我换到了项目目录下，依然报错：
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy-0.0.11-py3.10.egg/lmdeploy/serve/openai/api_server.py", line 360, in <module>
    fire.Fire(main)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy-0.0.11-py3.10.egg/lmdeploy/serve/openai/api_server.py", line 353, in main
    VariableInterface.async_engine = AsyncEngine(model_path=model_path,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy-0.0.11-py3.10.egg/lmdeploy/serve/async_engine.py", line 32, in __init__
    from lmdeploy import turbomind as tm
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy-0.0.11-py3.10.egg/lmdeploy/turbomind/__init__.py", line 2, in <module>
    from .turbomind import TurboMind
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy-0.0.11-py3.10.egg/lmdeploy/turbomind/turbomind.py", line 23, in <module>
    import _turbomind as _tm  # noqa: E402
ModuleNotFoundError: No module named '_turbomind'

**Comment by lvhan028** [comment]
`root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy-0.0.11-py3.10.egg/lmdeploy/serve/openai/api_server.py`
你这边的安装路径比较奇怪。是通过 pip install lmdeploy 安装的么？

**Comment by lvhan028** [comment]
感觉有些混乱。建议用 pip install lmdeploy==0.0.11。这个是最新的版本。
`_turbomind`的包是在 lib 中的。
你源码编译的目标明文件中，有_turbomind.cpython-310-x86_64-linux-gnu.so吗？

```
(lmdeploy) [lvhan@SH-IDC1-10-140-24-140 lmdeploy]$ ll
total 48
drwxrwsr-x 2 lvhan lvhan    24 Oct 17 19:06 bin
-rw-rw-r-- 1 lvhan lvhan   446 Oct 17 19:06 __init__.py
drwxrwsr-x 2 lvhan lvhan    56 Oct 17 19:06 lib
drwxrwsr-x 6 lvhan lvhan   108 Oct 17 19:06 lite
-rw-rw-r-- 1 lvhan lvhan 21794 Oct 17 19:06 model.py
drwxrwsr-x 2 lvhan lvhan   160 Oct 17 19:06 __pycache__
drwxrwsr-x 5 lvhan lvhan   188 Oct 17 19:06 pytorch
drwxrwsr-x 6 lvhan lvhan   129 Oct 17 19:06 serve
-rw-rw-r-- 1 lvhan lvhan  9045 Oct 17 19:06 tokenizer.py
drwxrwsr-x 3 lvhan lvhan   127 Oct 17 19:06 turbomind
-rw-rw-r-- 1 lvhan lvhan  3291 Oct 17 19:06 utils.py
-rw-rw-r-- 1 lvhan lvhan   838 Oct 17 19:06 version.py
```

**Comment by cat-knight** [comment]
> 感觉有些混乱。建议用 pip install lmdeploy==0.0.11。这个是最新的版本。 `_turbomind`的包是在 lib 中的。 你源码编译的目标明文件中，有_turbomind.cpython-310-x86_64-linux-gnu.so吗？
> 
> ```
> (lmdeploy) [lvhan@SH-IDC1-10-140-24-140 lmdeploy]$ ll
> total 48
> drwxrwsr-x 2 lvhan lvhan    24 Oct 17 19:06 bin
> -rw-rw-r-- 1 lvhan lvhan   446 Oct 17 19:06 __init__.py
> drwxrwsr-x 2 lvhan lvhan    56 Oct 17 19:06 lib
> drwxrwsr-x 6 lvhan lvhan   108 Oct 17 19:06 lite
> -rw-rw-r-- 1 lvhan lvhan 21794 Oct 17 19:06 model.py
> drwxrwsr-x 2 lvhan lvhan   160 Oct 17 19:06 __pycache__
> drwxrwsr-x 5 lvhan lvhan   188 Oct 17 19:06 pytorch
> drwxrwsr-x 6 lvhan lvhan   129 Oct 17 19:06 serve
> -rw-rw-r-- 1 lvhan lvhan  9045 Oct 17 19:06 tokenizer.py
> drwxrwsr-x 3 lvhan lvhan   127 Oct 17 19:06 turbomind
> -rw-rw-r-- 1 lvhan lvhan  3291 Oct 17 19:06 utils.py
> -rw-rw-r-- 1 lvhan lvhan   838 Oct 17 19:06 version.py
> ```

按照你的意见， pip install lmdeploy==0.0.11 卸载重装后，服务启动成功，但按照文档的方式访问还是又问题。
报错信息如下，中途报错那次使用代码访问的，之后的成功也是代码访问，虽然显示成功，但是pycharm直接没反应，一直处于运行状态：
(chatglm_etuning) root@autodl-container-afc311993c-586ea314:~# python3 -m lmdeploy.serve.openai.api_server /root/autodl-fs/llm_models/workspace 0.0.0.0 6006
[WARNING] gemm_config.in is not found; using default GEMM algo
INFO:     Started server process [1016]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6006 (Press CTRL+C to quit)
INFO:     127.0.0.1:51066 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:51078 - "POST / HTTP/1.1" 405 Method Not Allowed
INFO:     127.0.0.1:51096 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:51186 - "POST /generate HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 297, in stream_results
    data = chunk.model_dump_json()
AttributeError: 'GenerateResponse' object has no attribute 'model_dump_json'
INFO:     127.0.0.1:51220 - "POST /generate HTTP/1.1" 200 OK
INFO:     127.0.0.1:51280 - "POST /generate HTTP/1.1" 200 OK
INFO:     127.0.0.1:51412 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:51412 - "GET /openapi.json HTTP/1.1" 200 OK

访问代码如下：
import json
import requests
from typing import Iterable, List


def get_streaming_response(prompt: str,
                           api_url: str,
                           session_id: int,
                           request_output_len: int,
                           stream: bool = True,
                           sequence_start: bool = True,
                           sequence_end: bool = True,
                           ignore_eos: bool = False) -> Iterable[List[str]]:
    headers = {'User-Agent': 'Test Client'}
    pload = {
        'prompt': prompt,
        'stream': stream,
        'session_id': session_id,
        'request_output_len': request_output_len,
        'sequence_start': sequence_start,
        'sequence_end': sequence_end,
        'ignore_eos': ignore_eos
    }
    response = requests.post(
        api_url, headers=headers, json=pload, stream=stream)
    for chunk in response.iter_lines(
            chunk_size=8192, decode_unicode=False, delimiter=b'\n'):
        if chunk:
            data = json.loads(chunk.decode('utf-8'))
            output = data['text']
            tokens = data['tokens']
            yield output, tokens

# http://region-31.seetacloud.com:46124
for output, tokens in get_streaming_response(
        "你好", "http://region-31.seetacloud.com:46124/v1/chat/completions", 0,
        512):
    print(output, end='')

**Comment by lvhan028** [comment]
` AttributeError: 'GenerateResponse' object has no attribute 'model_dump_json'`
@AllentDan 是不是升级下 fastapi 可以解决？

**Comment by AllentDan** [comment]
对，更新下 pydantic 和 fastapi。我们正常 requirements.txt 不指定不应该就是最新嘛 :thinking:

**Comment by lvhan028** [comment]
会不会是因为之前安装过？

**Comment by cat-knight** [comment]
> 对，更新下 pydantic 和 fastapi。我们正常 requirements.txt 不指定不应该就是最新嘛 🤔

可以了，成功部署。

**Comment by AU-CPU** [comment]
@lvhan028 大佬 我使用了最新版本更新的代码 发现之前的deploy.py 迁移到了converter.py里面 然后使用命令 python3 -m lmdeploy.turbomind.deploy.converter  --model-name qwen-7b --model-path xxx --dst_path xxx --tp 4 --model-format awq --group-size 128 出现错误ModuleNotFoundError: No module named '_turbomind' 应该如何解决呢

**Comment by lvhan028** [comment]
看下文档，现在convert要用 lmdeploy convert 来转换，不是python3 -m 这种了

**Comment by AU-CPU** [comment]
> 看下文档，现在convert要用 lmdeploy convert 来转换，不是python3 -m 这种了

大佬 我按照build.md文档中一步一步安装 pip install -e . 然后指令用lmdeploy convert 还是出现ModuleNotFoundError: No module named '_turbomind'应该如何解决呢

**Comment by lvhan028** [comment]
应该没在 lmdeploy/lib下生成了.so。
把你的操作步骤，以及日志贴上来吧。
