### ISSUE TITLE
[Bug] ImportError: DLL load failed while importing _turbomind: 找不到指定的模块。

### ISSUE THREAD

**Issue by DrawAChicken** [InternLM/lmdeploy#613]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

使用的lmdeploy/turbomind-internlm-chat-7b-w4模型
在执行 python -m lmdeploy.serve.turbomind.deploy llama2 .\model\ awq 后报错
相关变量是
`(lmdeploy) PS E:\4b> echo $env:PATH
C:\ProgramData\miniconda3\envs\lmdeploy;C:\ProgramData\miniconda3\envs\lmdeploy\Library\mingw-w64\bin;C:\ProgramData\miniconda3\envs\lmdeploy\Library\usr\bin;C:\ProgramData\miniconda3\envs\lmdeploy\Library\bin;C:\ProgramData\miniconda3\envs\lmdeploy\Scripts;C:\ProgramData\miniconda3\envs\lmdeploy\bin;C:\ProgramData\miniconda3\condabin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0;C:\windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.3.0;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\libnvvp;C:\Users\shenlibo\AppData\Local\Microsoft\WindowsApps;C:\Users\shenlibo\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.3\libnvvp;.`
看了其他相关的问题， 仍无法解决， 请求帮助 期待回复

### Reproduction

 python -m lmdeploy.serve.turbomind.deploy llama2 .\model\ awq 

### Error traceback

```Shell
(lmdeploy) PS E:\4b> python -m lmdeploy.serve.turbomind.deploy llama2 .\model\ awq
create workspace in directory ./workspace
copy triton model templates from "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\triton_models" to "./workspace\triton_models" successfully
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 1046, in <module>
    fire.Fire(main)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 1013, in main
    res = deploy_awq(model_name, model_path, tokenizer_path,
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 652, in deploy_awq
    import _turbomind as _tm  # noqa: E402
ImportError: DLL load failed while importing _turbomind: 找不到指定的模块。
```

**Comment by DrawAChicken** [comment]
lmdeploy版本是：
`(lmdeploy) PS E:\4b> pip show lmdeploy
Name: lmdeploy
Version: 0.0.12
Summary: A toolset for compressing, deploying and serving LLM
Home-page: UNKNOWN
Author: OpenMMLab
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: c:\programdata\miniconda3\envs\lmdeploy\lib\site-packages
Requires: accelerate, datasets, fastapi, fire, gradio, mmengine, numpy, pybind11, safetensors, sentencepiece, setuptools, shortuuid, tiktoken, torch, transformers, tritonclient, uvicorn
Required-by:`

python是 3.8.18

**Comment by lvhan028** [comment]
@irexyc may update FAQ for this issue.

**Comment by irexyc** [comment]
@DrawAChicken 

不支持cuda12。装一下cuda 11.8，然后把12.3从 $env:PATH  里面去掉试试

**Comment by DrawAChicken** [comment]
@irexyc  感谢大佬答疑
还有一个问题麻烦请教一下， 用的FlagAlpha/Atom-7B 是基于llama2的中文预训练模型
执行`python -m lmdeploy.serve.turbomind.deploy llama2 ./model/atom7b/`后
有一个报错`tok_embeddings.weight torch.Size([65000, 4096])
norm.weight torch.Size([4096])
output.weight torch.Size([65000, 4096])
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 1046, in <module>
    fire.Fire(main)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 1034, in main
    pack_model_repository(dst_path)
  File "C:\ProgramData\miniconda3\envs\lmdeploy\lib\site-packages\lmdeploy\serve\turbomind\deploy.py", line 938, in pack_model_repository
    os.symlink(src='../../tokenizer',
PermissionError: [WinError 5] 拒绝访问。: '../../tokenizer' -> './workspace\\triton_models\\preprocessing\\1\\tokenizer'
` 查了一圈，也增加了各种权限，还是报这个错误， 能帮忙看下吗， 十分感谢

**Comment by irexyc** [comment]
```python
os.symlink(src='../../tokenizer',
                   dst=osp.join(workspace_path, 'triton_models', 'preprocessing', '1', 'tokenizer'))
```

windows 上貌似应该改成
```python
os.symlink(src=osp.join('..', '..', 'tokenizer'), 
               dst=osp.join(workspace_path, 'triton_models', 'preprocessing', '1', 'tokenizer'))
```

不过这个步骤是为了triton inference server使用的，windows上面没办法用，所以这个错误你可以不管就行了。

**Comment by DrawAChicken** [comment]
@irexyc  感谢大佬 已经成功跑起来了
