### ISSUE TITLE
Support for LLama2 model using HF tokenizers [Feature] 

### ISSUE THREAD

**Issue by bibekyess** [InternLM/lmdeploy#614]
### Motivation

Hello everyone! I found some Llama2 models using the FastTokenizer provided by the Hugging Face tokenizers library, not the SentencePiece package used by regular Llama models. For instance, `beomi/llama-2-ko-7b`. Since the conversion to TurboMind's format requires `tokenizer.model`, can you please add support for Hugging Face tokenizers as well? I tried manually converting the `tokenizer.json` file to `tokenizer.model` and running it, but I didn't achieve good results.

Thank you!

### Related resources

https://huggingface.co/beomi/llama-2-ko-7b

**Comment by lvhan028** [comment]
Yes. Turbomind support both SentencePiece and hf transformers tokenizer. You can refer to `lmdeploy/tokenizer.py` for detailed info.

**Comment by bibekyess** [comment]
Hi @lvhan028! Thank you for your response. It was useful. After trying with different combinations of the `model_name` and `model_format`, I succesfully converted into turbomind format. But it required me manually edit this file `lmdeploy/serve/turbomind/deploy.py` specifically this line `vocab_size, bos_id, eos_id = tokenizer_info(tokenizer_path)` as shown in the logs below:
I got this when executing this command:
```bash
python -m lmdeploy.serve.turbomind.deploy llama2 ./llama-2-ko-7b --model_format hf --tokenizer_path ./llama-2-ko-7b/tokenizer.json
```

```bash
Traceback (most recent call last):
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 1046, in <module>
    fire.Fire(main)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 1010, in main
    res = deploy_hf(model_name, model_path, tokenizer_path,
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 564, in deploy_hf
    return export(model_name,
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 236, in export
    vocab_size, bos_id, eos_id = tokenizer_info(tokenizer_path)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/lmdeploy/serve/turbomind/deploy.py", line 97, in tokenizer_info_sp
    sp_model = SentencePieceProcessor(model_file=model_path)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/home/bibekyess/miniconda3/envs/final_test/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
```
Thank you! :)

**Comment by lvhan028** [comment]
Hi, @bibekyess 
Sorry for the late reply.

`--tokenizer-path` means the path of tokenizer model, not the path of tokenizer.json

If [llama-2-ko-7b](https://huggingface.co/beomi/llama-2-ko-7b) uses llama2's tokenizer model, please pass the tokenizer model's path to `deploy.py`:

```shell
python -m lmdeploy.serve.turbomind.deploy llama2 ./llama-2-ko-7b --model_format hf --tokenizer_path /the/path/to/llama2/tokenizer/model
```
