### ISSUE TITLE
[Bug] 将llama2-13b模型转换成lmdeploy格式报错

### ISSUE THREAD

**Issue by zhangjiawei5911** [InternLM/lmdeploy#635]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

copy triton model templates from "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/triton_models" to "./workspace/triton_models" successfully
0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 1047, in <module>
    fire.Fire(main)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 1012, in main
    res = deploy_awq(model_name, model_path, tokenizer_path,
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 700, in deploy_awq
    q_qw = get_tensor(f'model.layers.{i}.self_attn.q_proj.qweight')
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 645, in get_tensor
    return _params[name].cuda().contiguous()
KeyError: 'model.layers.0.self_attn.q_proj.qweight'

### Reproduction

version:
python 3.8.5
lmdeploy 0.0.11

model:
https://github.com/ymcui/Chinese-LLaMA-Alpaca-2 该项目中预训练得到的chinese-llama2-13b，hf地址为https://huggingface.co/hfl/chinese-alpaca-2-13b

command： 
python -m lmdeploy.serve.turbomind.deploy  --model-name llama2  --model-path ./chinese-llama2-13b-hf --model-format awq  --group-size 128 

有趣的是将该模型量化成int4之后再使用上述命令，能成功运行。直接将该模型运行上述的命令则会失败。

**Comment by lvhan028** [comment]
“有趣的是将该模型量化成int4之后再使用上述命令，能成功运行。"
但是提供的日志，错误信息就是转量化模型报出的。
```
File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 700, in deploy_awq
```
deploy_awq是量化模型转换的入口

所以，issue标题，llama2-13b 转失败，是指的 fp16，还是w4a16？

**Comment by zhangjiawei5911** [comment]
> “有趣的是将该模型量化成int4之后再使用上述命令，能成功运行。" 但是提供的日志，错误信息就是转量化模型报出的。
> 
> ```
> File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/turbomind/deploy.py", line 700, in deploy_awq
> ```
> 
> deploy_awq是量化模型转换的入口
> 
> 所以，issue标题，llama2-13b 转失败，是指的 fp16，还是w4a16？

fp16，是我command里面设置的参数不对吗

**Comment by lvhan028** [comment]
如果是转 fp16 的模型，使用命令：

```
python -m lmdeploy.serve.turbomind.deploy --model-name llama2 --model-path ./chinese-llama2-13b-hf 
```

**Comment by zhangjiawei5911** [comment]
> 如果是转 fp16 的模型，使用命令：
> 
> ```
> python -m lmdeploy.serve.turbomind.deploy --model-name llama2 --model-path ./chinese-llama2-13b-hf 
> ```

好的，已经成功运行了，感谢
