### ISSUE TITLE
[Bug] 访问服务，流式返回，返回到一般报错

### ISSUE THREAD

**Issue by cat-knight** [InternLM/lmdeploy#646]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

如题，我用千问14b模型起服务，流式返回，返回到一半出问题了，Imdeploy的版本为0.0.13。报错信息如下：
![image](https://github.com/InternLM/lmdeploy/assets/72443535/3bb9cc28-cc8b-4104-918c-df9cd962f3d1)

### Reproduction

  history = [{'role': "system", 'content': system},
             {'role': "assistant", 'content': '好的'},
             {'role': "user", 'content': query}]
system = ('你是一个精通python的数据开发，我会给你提供数据的元信息，以及数据样例，之后我会给你提供一个问题，你需要根据问题，使用python编程，读取数据，然后打印答案。'
          '如果问题中出现变化了多少，回答时应该明确是多了还是少了。'
          '当涉及人名时，请注意统一繁体与简体，可能出现同一个人名在不同表里分别是简体和繁体的情况。这里给你提供一个函数，可以将繁体转化为简体。'
          'import zhconv\ndef hant_2_hans(hant_str: str):\n return zhconv.convert(hant_str, "zh-hans")')

其中query的内容为：
表格1为xlsx格式，表格的地址为"data/合同/table/数据分析样本1.xlsx"，表格的列有 "['客户类型', '处理进度', '专项方案', '客户所在地址', '客户', '机构', '大区', '销售经理', '签订日期', '合同总金额', '方案金额']"， 第一行的数据为 "['老客户', '我方先盖章', '千里聆-信息采集', '太原', '山西天地煤机装备有限公司', '太原', '山西大区', '郝悦悦', Timestamp('2023-10-13 00:00:00'), 249600, 84240]"。
表格2为xlsx格式，表格的地址为"data/合同/table/数据分析样本2.xlsx"，表格的列有 "['专项方案', '人员数量']"， 第一行的数据为 "['千里聆-信息采集', 25]"。
表格3为xlsx格式，表格的地址为"data/合同/table/数据分析样本3.xlsx"，表格的列有 "['客户名称', '所属行业']"， 第一行的数据为 "['山西天地煤机装备有限公司', '制造行业']"。
当前时间为2023-11-05 14:43:13
问题是：郝悦悦今年签了哪些制造业客户？哪些是新客户？
先给出你的思路(你要解决几个问题，按什么顺序做)

**Comment by AllentDan** [comment]
main 分支修了

**Comment by cat-knight** [comment]
> main 分支修了
装了最新的main分支，结果服务起不来了。ctrl+c，终端服务，报错信息如下：

  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 369, in <module>
    fire.Fire(main)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/serve/openai/api_server.py", line 360, in main
    VariableInterface.async_engine = AsyncEngine(model_path=model_path,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 37, in __init__
    self.tm_model = tm.TurboMind(model_path,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 143, in __init__
    t.join()
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):

**Comment by AllentDan** [comment]
什么硬件？能用 `lmdeploy chat turbomind` 和模型对话吗？

**Comment by cat-knight** [comment]
> 什么硬件？能用 `lmdeploy chat turbomind` 和模型对话吗？

autodl平台租的A40，lmdeploy chat turbomind也卡主了，ctrl+c中断后，报错信息如下：
^CTraceback (most recent call last):
  File "/root/miniconda3/envs/chatglm_etuning/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 61, in run
    fire.Fire(cli, name='lmdeploy')
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/cli/chat.py", line 85, in turbomind
    run_turbomind_model(model_path,
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 92, in main
    tm_model = tm.TurboMind(model_path, eos_id=tokenizer.eos_token_id, tp=tp)
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/site-packages/lmdeploy/turbomind/turbomind.py", line 143, in __init__
    t.join()
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/root/miniconda3/envs/chatglm_etuning/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by AllentDan** [comment]
A40 没用过，其他模型试过吗？

**Comment by cat-knight** [comment]
> A40 没用过，其他模型试过吗？

刚才又试了下，是启动太慢了，启动起来之后还是有问题。Imdeploy是卸载重新 pip install lmdeploy 。还是会报错：

**Comment by AllentDan** [comment]
没输出是因为你的 prompt 不管用吧。把 `ignore_eos` 设置 True，`max_tokens` 设置小一点，512。
```
def get_streaming_response(history: List,
                           api_url: str,
                           session_id: int,
                           request_output_len: int,
                           stream: bool = True,
                           sequence_start: bool = True,
                           sequence_end: bool = True,
                           ignore_eos: bool = False) -> str:
    headers = {'User-Agent': 'Test Client'}

    pload = {
        'stream': stream,
        'session_id': session_id,
        'request_output_len': request_output_len,
        'sequence_start': sequence_start,
        'sequence_end': sequence_end,
        'ignore_eos': True,
        'model': 'qwen-14b',
        'max_tokens': 512,
        'messages': history,
        'renew_session': True,
        'temperature': 1,
        'top_p': 0.9,
    }


    response = requests.post(api_url, headers=headers, json=pload, stream=stream)

    if stream:
        txt = ''
        for chunk in response.iter_lines(chunk_size=8192, decode_unicode=False, delimiter=b'\n'):
            if chunk:
                chunk = chunk.decode('utf-8')
                print(chunk)
                chunk = '{' + chunk.replace('data', '"data"') + '}'
                if '[DONE]' not in chunk:
                    data = json.loads(chunk)
                    xxx = data['data']['choices'][0]['delta']
                    if 'content' in xxx:
                        token = xxx['content']
                        txt += token
                        print(token, end='')
                else:
                    print('\n')
                    return txt
    else:
        data = response.json()
        xxx = data['choices'][0]['message']['content']
        print(xxx)
        return xxx
```

**Comment by AllentDan** [comment]
你别用你写的了，用下面的吧
```python
def get_streaming_response(model_name: str,
                           prompt: str,
                           api_url: str,
                           stream: bool = True,
                           renew_session: bool = True,) -> Iterable[List[str]]:
    headers = {'content-type': 'application/json'}
    pload = {
        'model': model_name,
        'messages': prompt,
        'stream': stream,
        'renew_session': renew_session
    }
    response = requests.post(
        api_url, headers=headers, json=pload, stream=stream)
    for chunk in response.iter_lines(
            chunk_size=8192, decode_unicode=False, delimiter=b'\n'):
        if chunk:
            decoded = chunk.decode('utf-8')[6:]
            if decoded == '[DONE]':
                continue
            data = json.loads(decoded)
            output = data['choices'][0]
            yield output
```

**Comment by lvhan028** [comment]
close it since no more activities over a month. Feel free to reopen it if it is still an issue
