### ISSUE TITLE
[Bug] Command line crashes during use, cannot be reproduced consistently.

### ISSUE THREAD

**Issue by WillowsZhu** [InternLM/lmdeploy#672]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

convert llama2
`lmdeploy convert --model-name llama2  --model-path /nvme/qa_test_models/llama2-chat-7b-w4  --model-format awq  --group-size 128 --dst_path ./workspacellama`

start command line
`lmdeploy chat turbomind ./workspacellama`

While interacting through the command line, an exception occurred and the command line exited. 

### Reproduction

cannot be reproduced consistently.

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
LMDeploy: 0.0.14+
transformers: 4.33.2
gradio: 3.50.2
fastapi: 0.104.0
pydantic: 2.4.2
```

### Error traceback

```Shell
(baselineOld) [zhulin1@SH-IDC1-10-140-0-187 ~]$ lmdeploy chat turbomind ./workshopllama
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
[WARNING] gemm_config.in is not found; using default GEMM algo
session 1

double enter to end input >>> 你好 你叫什么名字

<BOS>[INST] <<SYS>>
 You are a helpful, respectful and honest assistant. Always answer as helpfully as possible, while being safe. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content. Please ensure that your responses are socially unbiased and positive in nature.

If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct. If you don't know the answer to a question, please don't share false information.
<</SYS>>

你好 你叫什么名字 [/INST]  Hello! I'm here to help you with any questions you may have. My name is Assistant, and I'm here to provide helpful and respectful responses. Please feel free to ask me anything, and I will do my best to assist you.
As a responsible AI language model, I must ensure that my responses are socially unbiased and positive in nature. I will not provide any content that is harmful, unethical, racist, sexist, toxic, dangerous, or illegal. My purpose is to assist and provide accurate information, while always being safe and respectful.
If a question does not make any sense or is not factually coherent, I will explain why instead of answering something not correct. And if I don't know the answer to a question, I will politely inform you rather than providing false information.
So, please feel free to ask me anything, and I will do my best to assist you.

double enter to end input >>>  成都的景点

[INST] 成成都的景点 [/INST]  As a responsible AI language model, I must inform you that 成都 (Chengdu) is a city in China, and it does not have any scenic spots. However, Chengdu is known for its rich cultural heritage, delicious cuisine, and beautiful natural surroundings.
Some of the popular attractions in Chengdu include:
1. Giant Panda Research and Breeding Center: This is a must-visit attraction for any animal lover. The center is home to over 100 giant pandas, and visitors can observe these adorable creatures up close.
2. Wide and Narrow Alleys (铺街): This is a historic area in Chengdu that features a network of narrow streets and alleys. Visitors can explore the local culture and try various delicious street foods.
3. Jinli Street (锦里街): This is a popular shopping and dining street in Chengdu that offers a wide range of goods, from local handicrafts to high-end fashion.
4. Leshan Giant Buddha Scenic Area (乐山大佛景观): This is a UNESCO World Heritage Site located about 120 kilometers south of Chengdu. The area features a 71-meter tall stone Buddha statue that is carved into the side of a mountain.
5. Dujiangyan Irrigation System (都江堰): This is an ancient irrigation system that was built over 2,000 years ago. It is still in use today and is a testament to the ingenuity of ancient Chinese engineering.
I hope this information is helpful in planning your trip to Chengdu!

double enter to end input >>> 美食

[INST] 美食 [/INST]  Certainly! Chengdu is known for its rich culinary culture and spicy cuisine. Here are some popular dishes and foods to try in Chengdu:
1. Hot Pot (火锅): Hot pot is a popular dish in Chengdu that involves cooking various ingredients, such as meat, seafood, and vegetables, in a simmering pot of broth. The broth is usually spicy and flavorful, and the dish is often shared with friends and family.
2. Sichuan Noodles (川味面): Sichuan noodles are a staple dish in Chengdu that features a flavorful and spicy sauce made with chili oil, garlic, and ginger. The noodles are usually served with a variety of toppings, such as vegetables, meat, and eggs.
3. Kung Pao Chicken (宫保鸡): Kung Pao chicken is a famous dish in Chengdu that is made with crispy fried chicken, peanuts, vegetables, and chili peppers. The dish is spicy and flavorful, and it is often served with rice or noodles.
4. Mapo Tofu (麻婆豆腐): Mapo tofu is a popular dish in Chengdu that features a spicy and flavorful tofu sauce made with chili oil, garlic, and ginger. The dish is often served with a variety of toppings, such as vegetables, meat, and eggs.
5. Chengdu-style Roast Duck (成都烤鸭): Chengdu-style roast duck is a popular dish in Chengdu that features a crispy and flavorful duck that is roasted to perfection. The dish is often served with a variety of dipping sauces and sides, such as pancakes and scallions.
I hope this information is helpful in planning your culinary adventures in Chengdu!

double enter to end input >>> end


double enter to end input >>> 美食
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/baselineOld/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/cli/chat.py", line 85, in turbomind
    run_turbomind_model(model_path,
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 106, in main
    prompt = input_prompt(model_name)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 30, in input_prompt
    return '\n'.join(iter(input, sentinel))
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte
```

**Comment by lvhan028** [comment]
According to the log, the last prompt "美食" cannot be decoded by "utf-8" codec.
When you input the prompt, did you use backspace to delete or modify the prompt?

**Comment by WillowsZhu** [comment]
thanks, I think it's not a valid bug.
