### ISSUE TITLE
[Bug] 应该如何启动WebUI服务

### ISSUE THREAD

**Issue by zhangjiawei5911** [InternLM/lmdeploy#687]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

安装的lmdeploy为0.0.11版本，将llama2模型转成lmdeploy格式之后，使用python3 -m lmdeploy.serve.gradio.app workspace 命令，发现报端口错误
[WARNING] gemm_config.in is not found; using default GEMM algo
server is gonna mount on: http://localhost:6009
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 6009, 0, 0): cannot assign requested address
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/gradio/app.py", line 542, in <module>
    fire.Fire(run)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/gradio/app.py", line 537, in run
    run_local(model_path_or_server, server_name, server_port, batch_size,
  File "/opt/conda/lib/python3.8/site-packages/lmdeploy/serve/gradio/app.py", line 501, in run_local
    demo.queue(concurrency_count=batch_size, max_size=100,
  File "/opt/conda/lib/python3.8/site-packages/gradio/blocks.py", line 1899, in launch
    ) = networking.start_server(
  File "/opt/conda/lib/python3.8/site-packages/gradio/networking.py", line 169, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 6009-6009. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.
将端口替换为其他的端口号，如19235,6009,8999等报的是同样的错误。
但是看README.md中，好像web服务又不是这么起的，想请问下应该怎么样起这个web服务

### Reproduction

python3 -m lmdeploy.serve.gradio.app workspace 

python -m lmdeploy.serve.gradio.app http://localhost:23333 localhost 6006 --restful_api True

python -m lmdeploy.serve.gradio.app http://0.0.0.0:23333 0.0.0.0 6006 --restful_api True

### Environment

```Shell
略
```

**Comment by AllentDan** [comment]
用最新版试试。你是在docker中还是物理机上？没有可用的端口可能是环境配置问题

**Comment by zhangjiawei5911** [comment]
> 用最新版试试。你是在docker中还是物理机上？没有可用的端口可能是环境配置问题

我是在docker中运行的

**Comment by AllentDan** [comment]
那就是没有给docker做内外端口映射，启动做下映射就可以了
