### ISSUE TITLE
[Bug] Qwen-14B awq转换报错

### ISSUE THREAD

**Issue by LianxinGao** [InternLM/lmdeploy#705]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

```
model_name             qwen-14b
model_format           awq
inferred_model_format  qwen-awq
model_path             /root/.cache/huggingface/hub/models--Qwen--Qwen-14B/snapshots/d08b22ae22ee52b7fd762bf6e44711d90cc96794/
tokenizer_path         /root/.cache/huggingface/hub/models--Qwen--Qwen-14B/snapshots/d08b22ae22ee52b7fd762bf6e44711d90cc96794/qwen.tiktoken
output_format          w4
Traceback (most recent call last):
  File "/opt/conda/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/conda/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 49, in convert
    convert(model_name,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/converter.py", line 220, in main
    output_model = OUTPUT_MODELS.get(output_format)(input_model=input_model,
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 80, in __init__
    super().__init__(input_model, cfg, to_file, out_dir)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 92, in __init__
    self.cfg = self.get_config(cfg)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 92, in get_config
    w1s, _, _ = bin.ffn_scale(i)
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/qwen_awq.py", line 41, in ffn_scale
    return ensure_fp16orint32(self._ffn(i, 'scales'))
  File "/opt/conda/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/source_model/qwen.py", line 55, in _ffn
    tensor = self.params[f'transformer.h.{i}.mlp.{key}.{kind}']
KeyError: 'transformer.h.0.mlp.w2.scales'
```

### Reproduction

`lmdeploy convert qwen-14b /root/.cache/huggingface/hub/models--Qwen--Qwen-14B/snapshots/d08b22ae22ee52b7fd762bf6e44711d90cc96794/ -d ./converted --model-format awq --group-size 128`

### Environment

```Shell
...
```

**Comment by pppppM** [comment]
For FP16 models, you first need to generate INT4 weights before executing `lmdeploy convert`.
https://github.com/InternLM/lmdeploy/blob/0fcc3034afe46564ef3a857ea9abd0d20ca374f2/docs/en/w4a16.md?plain=1#L73-L101

Alternatively, you can directly download our pre-quantized models from the [HuggingFace Hub](https://huggingface.co/lmdeploy).

**Comment by irexyc** [comment]
报错的原因是你给的模型路径是一个非量化的模型。

你需要下载这里的：https://huggingface.co/lmdeploy/qwen-chat-14b-4bit


生成 lmdeploy/qwen-chat-14b-4bit 里面的内容可以参考这个文档 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md#4bit-%E6%9D%83%E9%87%8D%E9%87%8F%E5%8C%96

**Comment by LianxinGao** [comment]
Thank you guys

**Comment by chenhaoqiang** [comment]
> 报错的原因是你给的模型路径是一个非量化的模型。
> 
> 你需要下载这里的：https://huggingface.co/lmdeploy/qwen-chat-14b-4bit
> 
> 生成 lmdeploy/qwen-chat-14b-4bit 里面的内容可以参考这个文档 https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/w4a16.md#4bit-%E6%9D%83%E9%87%8D%E9%87%8F%E5%8C%96

试了下，部署成功了。但是没有function call的功能，在其他issue里咨询了[lvhan028](https://github.com/lvhan028)，说是不支持function call
