### ISSUE TITLE
[Bug] internlm_chat_20b model cannot generate quantization parameter

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#734]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

down load internlm_chat_20b from [hf](https://huggingface.co/internlm/internlm-chat-20b internlm-chat-20b)

according to 
https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md#step-1-generate-quantization-parameter

the commond line is
`lmdeploy lite calibrate --model /nvme/qa_test_models/internlm_chat_20b --calib_dataset 'c4'  --calib_samples 128 --calib_seqlen 2048  --work_dir /nvme/qa_test_models/internlm_chat_20b-inner-w4`

Baichuan2-7b-chat, Qwen-14b-chat, Qwen-7b-chat can generate quantization parameter successfully

### Reproduction

down load internlm_chat_20b from [hf](https://huggingface.co/internlm/internlm-chat-20b internlm-chat-20b)

according to 
https://github.com/InternLM/lmdeploy/blob/main/docs/en/w4a16.md#step-1-generate-quantization-parameter

the commond line is
`lmdeploy lite calibrate --model /nvme/qa_test_models/internlm_chat_20b --calib_dataset 'c4'  --calib_samples 128 --calib_seqlen 2048  --work_dir /nvme/qa_test_models/internlm_chat_20b-inner-w4`

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
LMDeploy: 0.0.14+
transformers: 4.33.2
gradio: 3.50.2
fastapi: 0.104.0
pydantic: 2.4.2
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/baselineOld/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/cli/lite.py", line 57, in calibrate
    calibrate(model,
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/lmdeploy/lite/apis/calibrate.py", line 129, in calibrate
    tokenizer = AutoTokenizer.from_pretrained(model,
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 686, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 519, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/zhulin1/miniconda3/envs/baselineOld/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/nvme/qa_test_models/internlm_chat_20b'. Use `repo_type` argument if needed.
```

**Comment by lvhan028** [comment]
Please paste the result of `ll /nvme/qa_test_models/internlm_chat_20b`.
Let's check if this folder container all the files of the model

**Comment by zhulinJulia24** [comment]
yes, it's a typo between internlm_chat_20b an internlm-chat-20b. Thanks.
