### ISSUE TITLE
[Bug] llama v1 65B w4a16量化后转换成turbomind格式 不支持tp=8

### ISSUE THREAD

**Issue by CokeDong** [InternLM/lmdeploy#741]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

[Bug] llama v1 65B w4a16量化后转换成turbomind格式 不支持tp=8

### Reproduction

```
# 量化
lmdeploy lite calibrate   --model /path/to/lama-65b-hf --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir /path/to/workdir/w4a16 

lmdeploy lite auto_awq --model /path/to/lama-65b-hf --w_bits 4 --w_group_size 128 --work_dir /path/to/workdir/w4a16 


# 转换
lmdeploy convert --model-name llama --model-path /path/to/workdir/w4a16   --model-format awq --group-size 128 --dst_path /path/to/65B/workspace_w4 --tp 8

# 支持tp=4
lmdeploy convert --model-name llama --model-path /path/to/workdir/w4a16   --model-format awq --group-size 128 --dst_path /path/to/65B/workspace_w4 --tp 4
```

### Environment

```Shell
sys.platform: linux
Python: 3.10.0 | packaged by conda-forge | (default, Nov 20 2021, 02:24:10) [GCC 9.4.0]
CUDA available: False
numpy_random_seed: 2147483648
GCC: gcc (GCC) 10.2.0
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

LMDeploy: 0.0.14+1076f5b
transformers: 4.33.0
gradio: 3.42.0
fastapi: 0.103.1
pydantic: 2.4.2
```

### Error traceback

```Shell
*** splitting layers.0.feed_forward.w2.scales_zeros, shape=torch.Size([172, 8192]), split_dim=0, tp=8
Convert to turbomind format:   0%|          | 0/80 [00:06<?, ?it/s]Traceback (most recent call last):
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 49, in convert
    convert(model_name,
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/converter.py", line 224, in main
    output_model.export()
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 173, in export
    self.export_transformer_block(bin, i)
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/w4.py", line 156, in export_transformer_block
    self.save_split(w2_sz, f'layers.{i}.feed_forward.w2.scales_zeros', 0)
  File "/mnt/cachenew2/dongkaixing1.vendor/.conda/envs/lmdeploy2/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/target_model/base.py", line 149, in save_split
    assert tensor.shape[split_dim] % tp == 0
AssertionError


```
```

**Comment by lvhan028** [comment]
` assert tensor.shape[split_dim] % tp == 0`
After quantization, shape of some weights cannot be divided by TP
