### ISSUE TITLE
[Feature] requerment is not enough during Qwen and Llama2 model quantization

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#755]
### Motivation

during quantization, some model have special dependency, there requirement is not in requirement list.  
Llama-2-7b-chat-hf  need protobuf
Qwen need transformers_stream_generator

Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/cleanenv/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/cli/lite.py", line 57, in calibrate
    calibrate(model,
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/lite/apis/calibrate.py", line 128, in calibrate
    tokenizer = AutoTokenizer.from_pretrained(model,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 736, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
    self.sp_model = self.get_spm_processor()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/models/llama/tokenization_llama.py", line 171, in get_spm_processor
    model_pb2 = import_protobuf(f"The new behaviour of {self.__class__.__name__} (with `self.legacy = False`)")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/convert_slow_tokenizer.py", line 43, in import_protobuf
    raise ImportError(PROTOBUF_IMPORT_ERROR.format(error_message))
ImportError: 
The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.

commondLine get_param_cmd: lmdeploy lite calibrate --model /nvme/qa_test_models/Llama-2-7b-chat-hf --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir /nvme/qa_test_models/Llama-2-7b-chat-hf-inner-w4

(cleanenv) [zhulin1@SH-IDC1-10-140-0-187 log]$ tail -fn 100 quantization_param_Qwen-7B-Chat-inner-w4.log 
/home/zhulin1/lmdeploy
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/cleanenv/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/cli/lite.py", line 57, in calibrate
    calibrate(model,
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/lite/apis/calibrate.py", line 132, in calibrate
    model = load_hf_from_pretrained(model,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/lmdeploy/lite/utils/load.py", line 32, in load_hf_from_pretrained
    model = AutoModelForCausalLM.from_pretrained(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhulin1/miniconda3/envs/cleanenv/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: transformers_stream_generator. Run `pip install transformers_stream_generator`
commondLine get_param_cmd: lmdeploy lite calibrate --model /nvme/qa_test_models/Qwen-7B-Chat --calib_dataset 'c4' --calib_samples 128 --calib_seqlen 2048 --work_dir /nvme/qa_test_models/Qwen-7B-Chat-inner-w4

**Comment by lvhan028** [comment]
Could you help provide a full dependent package list?

**Comment by zhulinJulia24** [comment]
this two dependences need to be added: 
protobuf
transformers_stream_generator

**Comment by lvhan028** [comment]
The requirement will explode if every model's dependencies are taken into consideration.
We suggest users installing the requested package when they meet such hints
