### ISSUE TITLE
[Feature]  Cuda12 wheel?

### ISSUE THREAD

**Issue by yhyu13** [InternLM/lmdeploy#781]
### Motivation

Hi, my local setup is CUDA 12.2 on Ubuntu adm64 python3.11

After installing serve lmdeploy package
```
pip install lmdeploy[serve]
```

It encountered this error:

```
/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/gradio/components/button.py:89: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Button(...)` instead of `return gr.Button.update(...)`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/hangyu5/anaconda3/envs/lmdeploy/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/cli/serve.py", line 42, in gradio
    run(model_path_or_server,
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/gradio/app.py", line 34, in run
    run_local(model_path_or_server, server_name, server_port, batch_size,
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/gradio/turbomind_coupled.py", line 131, in run_local
    InterFace.async_engine = AsyncEngine(model_path=model_path,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/serve/async_engine.py", line 30, in __init__
    from lmdeploy import turbomind as tm
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/__init__.py", line 2, in <module>
    from .turbomind import TurboMind
  File "/home/hangyu5/anaconda3/envs/lmdeploy/lib/python3.11/site-packages/lmdeploy/turbomind/turbomind.py", line 23, in <module>
    import _turbomind as _tm  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

Seemes it only expecting cuda11. Would you release wheels for CUDA12.1? It is quite popular since pytorch has that version of cuda

**Comment by lvhan028** [comment]
The prebuilt package is built on cuda 11.8 platform.

@irexyc Can you provide a guide about wheel built on cuda 12.x platform?

**Comment by irexyc** [comment]
@yhyu13 
可以试一下看看能不能用
https://github.com/irexyc/lmdeploy/releases

**Comment by yhyu13** [comment]
> 可以参考一下build文档中的[这个章节](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/build.md#%E5%9C%A8-docker-%E5%86%85%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E5%BC%BA%E7%83%88%E6%8E%A8%E8%8D%90)
> 
> 需要将[这个文件](https://github.com/InternLM/lmdeploy/blob/main/builder/manywheel/build_all_wheel.sh)中的 11.8 改成 12.2

May I know whic cuda11.8 docker image that you used for building the wheel? There are plenty of these docker images

**Comment by yhyu13** [comment]
> > 可以参考一下build文档中的[这个章节](https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/build.md#%E5%9C%A8-docker-%E5%86%85%E7%BC%96%E8%AF%91%E5%AE%89%E8%A3%85%E5%BC%BA%E7%83%88%E6%8E%A8%E8%8D%90)
> > 需要将[这个文件](https://github.com/InternLM/lmdeploy/blob/main/builder/manywheel/build_all_wheel.sh)中的 11.8 改成 12.2
> 
> May I know which cuda11.8 docker image that you used for building the wheel? There are plenty of these docker images

ok, I found it https://github.com/irexyc/lmdeploy/commit/2a48db3c8e18fc6ca6cf3f511d2f8076f7b6c54e

**Comment by lvhan028** [comment]
cuda 12.x wheel will be attached to the release note rather than uploading to pypi. 
The prebuilt package will still be complied with cuda 11.8

**Comment by lvhan028** [comment]
不用。cuda 12 的预编译包在 release note 中

**Comment by lvhan028** [comment]
所有的都是cuda12的。pypi网站上的是cuda11的。
