### ISSUE TITLE
Remove input&output len limit in benchmark/profile_serving.py, generate 0 tokens. 

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#836]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

remove the long sequences limit, then run benchmark/profile_serving.py.

![image](https://github.com/InternLM/lmdeploy/assets/145004780/97862e2e-c4b5-417b-bd37-17655b712d2d)

assert error. generate 0 tokens. 

```
File "/home/zhulin1/miniconda3/envs/lmdeploy0.1.0/lib/python3.10/threading.py", line 953, in run
 54%|█████████████████████████████████████████████████████████████████████████████████████▏                                                                         | 1385/2584 [05:05<02:56,  6.81it/s]    self._target(*self._args, **self._kwargs)
  File "/home/zhulin1/lmdeploy/benchmark/profile_serving_reproduce.py", line 98, in _inference
    assert output_seqlen <= completion_tokens <= output_seqlen + 1, \
 54%|█████████████████████████████████████████████████████████████████████████████████████▎                                                                         | 1386/2584 [05:06<03:49,  5.22it/s]AssertionError: Error. session_id(7) request 2321 tokens, but generate 0 tokens.
prompt: 请介绍100位世界名人及其成就
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████▏                                                             | 1580/2584 [05:53<05:53,  2.84it/s]Exception in thread Thread-43 (_inference):
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/lmdeploy0.1.0/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 1581/2584 [05:53<05:24,  3.09it/s]  File "/home/zhulin1/miniconda3/envs/lmdeploy0.1.0/lib/python3.10/threading.py", line 953, in run
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████▎                                                             | 1582/2584 [05:53<03:59,  4.18it/s]    self._target(*self._args, **self._kwargs)
  File "/home/zhulin1/lmdeploy/benchmark/profile_serving_reproduce.py", line 98, in _inference
 61%|█████████████████████████████████████████████████████████████████████████████████████████████████▍                                                             | 1583/2584 [05:53<03:36,  4.63it/s]    assert output_seqlen <= completion_tokens <= output_seqlen + 1, \
AssertionError: Error. session_id(41) request 2510 tokens, but generate 0 tokens.
prompt: 请写一篇关于秋天的2500字作文
```

### Reproduction

start triton server

1. remove long sequences limit in benchmark/profile_serving.py

2. start triton server. 

3. commondline, dataset reproduce.log contains conversation with expected outputlen > 2500. 
`python benchmark/profile_serving.py 10.140.0.187:33337 /mnt/models-new/puyu-123b-w4a16-tp4-v0.8.11-lmdeploy-v0.1.0a1/triton_models/tokenizer/tokenizer.model ../reproduce.log --concurrency 48 --num-prompts 100`

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda-11.7
NVCC: Cuda compilation tools, release 11.7, V11.7.64
GCC: gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
PyTorch: 2.0.1+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.15.2
LMDeploy: 0.1.0a2+cfa8097
transformers: 4.33.0
gradio: 3.50.2
fastapi: 0.104.1
pydantic: 2.5.2
```

**Comment by lvhan028** [comment]
The default `session_len` in the chat template is 2056. But the requested token size is 2510 larger than the `session_len`.
In this case, the request will be rejected. That's why the generated token size is 0

**Comment by zhulinJulia24** [comment]
Need add session_len=XX when initialize chatbot.
