### ISSUE TITLE
Server aborted on API call

### ISSUE THREAD

**Issue by WNjun** [InternLM/lmdeploy#841]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.

### Describe the bug

I can launch the inference server, but it crashes when receiving a call for inference.

### Reproduction

1、Launch the server：
`lmdeploy serve api_server /path/to/my/model/internlm-chat-7b --model-name internlm-chat-7b --instance_num 32 --tp 4`
Output：
```
model_source: hf_model
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
WARNING: Can not find tokenizer.json. It may take long time to initialize the tokenizer.
model_config:
{
  "model_name": "internlm-chat-7b",
  "tensor_para_size": 4,
  "head_num": 32,
  "kv_head_num": 32,
  "vocab_size": 103168,
  "num_layer": 32,
  "inter_size": 11008,
  "norm_eps": 1e-06,
  "attn_bias": 1,
  "start_id": 1,
  "end_id": 2,
  "session_len": 2056,
  "weight_type": "fp16",
  "rotary_embedding": 128,
  "rope_theta": 10000.0,
  "size_per_head": 128,
  "group_size": 0,
  "max_batch_size": 64,
  "max_context_token_num": 1,
  "step_length": 1,
  "cache_max_entry_count": 0.5,
  "cache_block_seq_len": 128,
  "cache_chunk_size": 1,
  "use_context_fmha": 1,
  "quant_policy": 0,
  "max_position_embeddings": 2048,
  "rope_scaling_factor": 0.0,
  "use_logn_attn": 0
}
get 1091 model params
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
[WARNING] gemm_config.in is not found; using default GEMM algo
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
HINT:    Please open http://0.0.0.0:23333 in a browser for detailed api usage!!!
INFO:     Started server process [593518]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:23333 (Press CTRL+C to quit)
```
2、Execute python：
```
from lmdeploy.serve.openai.api_client import APIClient
api_client = APIClient('http://127.0.0.1:23333')
model_name = api_client.available_models[0]
print(model_name)
messages = [{"role": "user", "content": "Say this is a test!"}]
for item in api_client.chat_completions_v1(model=model_name, messages=messages):
    print(item)
```

model_name was printed as ”internlm-chat-7b“，and then output error：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda2021/envs/lmdeploy_a2-env/lib/python3.10/site-packages/lmdeploy/serve/openai/api_client.py", line 89, in chat_completions_v1
    response = requests.post(self.chat_completions_v1_url,
  File "/usr/local/anaconda2021/envs/lmdeploy_a2-env/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/anaconda2021/envs/lmdeploy_a2-env/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda2021/envs/lmdeploy_a2-env/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda2021/envs/lmdeploy_a2-env/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda2021/envs/lmdeploy_a2-env/lib/python3.10/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

At the same time the server crashed：
```
INFO:     127.0.0.1:50104 - "GET /v1/models HTTP/1.1" 200 OK
Aborted (core dumped)
```

### Environment

```Shell
sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0,1,2,3: NVIDIA TITAN Xp
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.1, V11.1.105
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
PyTorch: 2.0.0+cu117
PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201703
  - Intel(R) oneAPI Math Kernel Library Version 2022.2-Product Build 20220804 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.7.3 (Git Hash 6dbeffbae1f23cbbeae17adb7b5b13f1f37c080e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5  (built against CUDA 11.1)
    - Built with CuDNN 8.5
  - Magma 2.6.1
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -D_GLIBCXX_USE_CXX11_ABI=0 -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wall -Wextra -Werror=return-type -Werror=non-virtual-dtor -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wunused-local-typedefs -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_DISABLE_GPU_ASSERTS=ON, TORCH_VERSION=2.0.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=1, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

LMDeploy: 0.1.0a2+
transformers: 4.36.0
gradio: 3.50.2
fastapi: 0.105.0
pydantic: 2.5.2
```

### Error traceback

```Shell
Use gdb to read the core file, we get：
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fa8cfd6a859 in __GI_abort () at abort.c:79
#2  0x00007fa84802835a in __cxxabiv1::__terminate (handler=<optimized out>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#3  0x00007fa8480283c5 in std::terminate ()
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#4  0x00007fa848028658 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x7fa567655830, tinfo=0x7fa84817d220 <typeinfo for std::runtime_error>,
    dest=0x7fa84803d110 <std::runtime_error::~runtime_error()>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#5  0x00007fa7d8eaf0bd in turbomind::check<cudaError> (result=<optimized out>, func=<optimized out>, file=<optimized out>, line=1077)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/new_allocator.h:89
#6  0x00007fa7d8fbe877 in turbomind::invokeBatchTopPSampling<float> (workspace=workspace@entry=0x0,
    workspace_size=@0x7fa56be37210: 140348456400784, cub_temp_storage_size=@0x7fa56be372c0: 0, output_ids=output_ids@entry=0x0,
    sequence_length=sequence_length@entry=0x0, finished_buf=finished_buf@entry=0x0, cum_log_probs=0x0, output_log_probs=0x0,
    log_probs=0x0, id_vals=0x0, offset_buf=0x0, begin_offset_buf=0x0, curandstate=0x0, batch_size=1, vocab_size_padded=103168,
    end_ids=0x0, max_top_p=1, top_ps=0x0, stream=0x7fa57d4c82d0, cuda_device_prop=0x7fa56a2ac2e0, skip_decode=0x11f6fc9a00)
    at /tmp/tmpxft_0000056c_00000000-6_sampling_topp_kernels.compute_86.cudafe1.stub.c:6
#7  0x00007fa7d8fbe8f0 in turbomind::invokeTopPSampling<float> (workspace=workspace@entry=0x0,
    workspace_size=@0x7fa56be37210: 140348456400784, cub_temp_storage_size=@0x7fa56be372c0: 0, output_ids=output_ids@entry=0x0,
    sequence_length=sequence_length@entry=0x0, finished_buf=finished_buf@entry=0x0, cum_log_probs=0x0, output_log_probs=0x0,
    log_probs=0x0, id_vals=0x0, offset_buf=0x0, begin_offset_buf=0x0, curandstate=0x0, batch_size=1, vocab_size_padded=103168,
    end_ids=0x0, top_p=<optimized out>, stream=0x7fa57d4c82d0, cuda_device_prop=0x7fa56a2ac2e0, skip_decode=0x11f6fc9a00)
    at /lmdeploy/src/turbomind/kernels/sampling_topp_kernels.cu:1208
#8  0x00007fa7d8fa73cf in turbomind::TopPSamplingLayer<float>::allocateBuffer (this=0x7fa56be371d0, batch_size=<optimized out>, top_k=...,
    top_p=...) at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/new_allocator.h:89
#9  0x00007fa7d8fb00b8 in turbomind::BaseSamplingLayer<float>::setup (this=this@entry=0x7fa56be371d0, batch_size=batch_size@entry=1,
    beam_width=<optimized out>, runtime_args=runtime_args@entry=0x7fa56ae03328)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/stl_algobase.h:465
#10 0x00007fa7d8fa7db6 in turbomind::TopPSamplingLayer<float>::setup (this=0x7fa56be371d0, batch_size=1, beam_width=<optimized out>,
    runtime_args=0x7fa56ae03328) at /lmdeploy/src/turbomind/utils/logger.h:83
#11 0x00007fa7d8f92e07 in turbomind::DynamicDecodeLayer<float>::setup (this=0x7fa119158200, batch_size=batch_size@entry=1,
    beam_width=beam_width@entry=1, runtime_args=runtime_args@entry=0x7fa56ae03328) at /lmdeploy/src/turbomind/utils/logger.h:83
#12 0x00007fa7d8efd3c9 in turbomind::LlamaBatch<__half>::InitializeSampling (this=this@entry=0x7fa56ae02ff0, g=...)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/hashtable.h:1002
#13 0x00007fa7d8f0e552 in turbomind::LlamaBatch<__half>::Initialize (this=this@entry=0x7fa56ae02ff0, g=...)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/new_allocator.h:89
#14 0x00007fa7d8f0ec54 in turbomind::LlamaBatch<__half>::InternalThreadEntry (this=<optimized out>, device_id=<optimized out>)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/ext/new_allocator.h:89
#15 0x00007fa848052bf4 in std::execute_native_thread_routine (__p=0x7fa119164fd0) at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/src/c++11/thread.cc:82
#16 0x00007fa8d009c609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#17 0x00007fa8cfe67353 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by AllentDan** [comment]
We did not test turbomind on SM 61 cards including TiTan xp.

**Comment by WNjun** [comment]
Do you have list of supported GPU?

**Comment by AllentDan** [comment]
GPUs with SM 70+
