### ISSUE TITLE
[Bug] 模型推理时报错

### ISSUE THREAD

**Issue by kaoyansoft123** [InternLM/lmdeploy#865]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

当前模型目录：
drwxr-xr-x 3 sysadm sysadm 4096 Nov 27 09:22 internlm-20b
drwxr-xr-x 3 sysadm sysadm 4096 Nov 27 09:24 internlm-7b

Traceback (most recent call last):
  File "/export/anaconda3/envs/xtuner-env/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/cli/chat.py", line 85, in turbomind
    run_turbomind_model(model_path,
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/chat.py", line 90, in main
    tokenizer = Tokenizer(tokenizer_model_path)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/tokenizer.py", line 247, in __init__
    self.model = HuggingFaceTokenizer(model_folder)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/tokenizer.py", line 123, in __init__
    self.model = AutoTokenizer.from_pretrained(model_dir,
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 701, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 534, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/transformers/utils/hub.py", line 429, in cached_file
    resolved_file = hf_hub_download(
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 158, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'internlm-20b/triton_models/tokenizer'. Use `repo_type` argument if needed.

### Reproduction

lmdeploy chat turbomind  internlm-20b --model-name internlm-20b

### Environment

```Shell
lmdeploy v0.1.0a2
cuda11.7
v100
```

**Comment by lvhan028** [comment]
Please list the content in the directory `internlm-20b`.  Is there `tokenizer.model` file?

**Comment by kaoyansoft123** [comment]
drwxr-xr-x 3 sysadm sysadm         52 Dec 18 17:33 cache
-rw-r--r-- 1 sysadm sysadm        894 Dec 18 17:31 config.json
-rw-r--r-- 1 sysadm sysadm       5311 Dec 18 17:31 configuration_internlm.py
-rw-r--r-- 1 sysadm sysadm        111 Dec 18 17:31 generation_config.json
-rw-r--r-- 1 sysadm sysadm      48133 Dec 18 17:31 modeling_internlm.py
-rw-r--r-- 1 sysadm sysadm 9990638603 Dec 18 17:32 pytorch_model-00001-of-00005.bin
-rw-r--r-- 1 sysadm sysadm 9956584547 Dec 18 17:32 pytorch_model-00002-of-00005.bin
-rw-r--r-- 1 sysadm sysadm 9867476673 Dec 18 17:33 pytorch_model-00003-of-00005.bin
-rw-r--r-- 1 sysadm sysadm 9306474783 Dec 18 17:33 pytorch_model-00004-of-00005.bin
-rw-r--r-- 1 sysadm sysadm 1056441258 Dec 18 17:33 pytorch_model-00005-of-00005.bin
-rw-r--r-- 1 sysadm sysadm      44754 Dec 18 17:33 pytorch_model.bin.index.json
-rw-r--r-- 1 sysadm sysadm      14894 Dec 18 17:33 README.md
-rw-r--r-- 1 sysadm sysadm         95 Dec 18 17:33 special_tokens_map.json
-rw-r--r-- 1 sysadm sysadm       8954 Dec 18 17:33 tokenization_internlm.py
-rw-r--r-- 1 sysadm sysadm        343 Dec 18 17:33 tokenizer_config.json
-rw-r--r-- 1 sysadm sysadm    1658691 Dec 18 17:33 tokenizer.model

**Comment by lvhan028** [comment]
@kaoyansoft123 不好意思耽误这么久。从日志看，tokenizer加载就失败了。
可以参考下面的代码，使用transformers来检查tokenizer model是否可以正确加载。

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer('./internlm-20b')
print(tokenizer('hello'))l
```

**Comment by lvhan028** [comment]
Hi, @kaoyansoft123 
不好意思，耽搁这么久。
使用 v0.1.0a2，请先通过 lmdeploy convert 命令，把 hf 模型转成 turbomind 模型格式：
```shell
lmdeploy convert internlm-20b ./internlm-20b --dst-path ./internlm-20b-turbomind
```
然后，再通过 lmdeploy chat turbomind 验证
```shell
lmdeploy chat turbomind ./internlm-20b-turbomind
```
