### ISSUE TITLE
[Bug] 转成turbomind报错

### ISSUE THREAD

**Issue by kaoyansoft123** [InternLM/lmdeploy#866]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.

### Describe the bug

Traceback (most recent call last):
  File "/export/anaconda3/envs/xtuner-env/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 135, in run
    fire.Fire(cli, name='lmdeploy')
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/cli/cli.py", line 49, in convert
    convert(model_name,
  File "/export/anaconda3/envs/xtuner-env/lib/python3.10/site-packages/lmdeploy/turbomind/deploy/converter.py", line 176, in main
    assert model_format in supported_formats, 'the model format ' \
AssertionError: the model format should be in ['llama', 'hf', 'awq', None]

### Reproduction

lmdeploy convert Shanghai_AI_Laboratory/internlm-chat-7b ./workspace --model-name internlm-chat-7b

### Environment

```Shell
lmdeploy 0.0.14
cuda11.7
torch2.0.1
```

**Comment by lvhan028** [comment]
The right command for your case is:
```
lmdeploy convert internlm-chat-7b Shanghai_AI_Laboratory/internlm-chat-7b ./workspace
```
You can use `-h` to check the positional arguments and optional arguments

```
lmdeploy convert -h 
```
