### ISSUE TITLE
an error about llama-65b

### ISSUE THREAD

**Issue by leizhao1234** [InternLM/lmdeploy#89]
65B
python3 lmdeploy.serve.turbomind.deploy llama-13B /path/to/llama-13b llama \
    --tokenizer_path /path/to/tokenizer/model --tp 8
bash workspace/service_docker_up.sh

is this correct？i found this in docs.

**Comment by tpoisonooo** [comment]
Just a typo,  please feel free to fix it.

**Comment by tpoisonooo** [comment]
Directly edit the doc and give a Pull Request ~ QvQ

**Comment by leizhao1234** [comment]
thanks, but I got another error when executing the command：python3 -m lmdeploy.serve.turbomind.deploy llama-65B /root/llama-65b-hf/ hf --tokenizer_path /root/llama-65b-hf/ --tp 8。I don't know where I made a mistake, can you check it for me?

python3 -m lmdeploy.serve.turbomind.deploy llama-65B /root/llama-65b-hf/ hf --tokenizer_path /root/llama-65b-hf/ --tp 8
create workspace in directory ./workspace
copy triton model templates from "/home/zhaolei/lmdeploy/lmdeploy/serve/turbomind/triton_models" to "./workspace/triton_models" successfully
Traceback (most recent call last):
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/zhaolei/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 481, in <module>
    fire.Fire(main)
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/zhaolei/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 454, in main
    res = deploy_hf(model_name, model_path, tokenizer_path,
  File "/home/zhaolei/lmdeploy/lmdeploy/serve/turbomind/deploy.py", line 281, in deploy_hf
    shutil.copy(tokenizer_path,
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/zhaolei/miniconda/envs/lmdeploy/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
IsADirectoryError: [Errno 21] Is a directory: '/root/llama-65b-hf/'

**Comment by lvhan028** [comment]
`--tokenizer_path` is the path of `tokenizer.model`, not a directory

**Comment by lvhan028** [comment]
Close it since no more activity over two weeks. Feel free to reopen it if it is still an issue
