### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by CocaColaKing** [InternLM/lmdeploy#96]
将llama-7b转换格式后docker启动报错
转换命令：
`python3 -m lmdeploy.serve.turbomind.deploy llama-7b  /home/nlp/lwp/pre_models/llama-7b-hf hf`
启动命令：
` docker run --gpus "device=8" --rm -v $(pwd)/workspace:/workspace -it openmmlab/lmdeploy:latest     python3 -m lmdeploy.turbomind.chat llama  /workspace`
报错信息：
`[WARNING] gemm_config.in is not found; using default GEMM algo
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/turbomind/chat.py", line 96, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.8/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/lmdeploy/turbomind/chat.py", line 35, in main
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_model_path,
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/auto/tokenization_auto.py", line 690, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.`

使用workerspace下面的脚本运行的时候也会报错，会报`error: creating server: Internal - failed to load all models`

**Comment by tpoisonooo** [comment]
https://github.com/InternLM/lmdeploy/blob/main/docs/zh_cn/serving.md   部署 LLaMa/Vicuna 用这个文档，因为支持 InternLM 的原因折叠了
