### ISSUE TITLE
[Bug] Qwen-VL-Chat遇到ValueError: Unclosed image token

### ISSUE THREAD

**Issue by stone002** [InternLM/lmdeploy#971]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

用main分支的代码源码编译，运行examples/vl/app.py时一直遇到这个问题
![image](https://github.com/InternLM/lmdeploy/assets/12168104/a899fe2d-504b-4437-90cd-14616c936fd8)
但是pip install lmdeploy==0.1.0，这个脚本就可以正常运行，但我想用源码编译的方式，请问怎么解决？

### Reproduction

python examples/vl/app.py --model-name qwen-vl-chat --hf-ckpt Qwen/Qwen-VL-Chat

### Environment

```Shell
TorchVision: 0.15.2+cu117
LMDeploy: 0.1.0+
transformers: 4.33.0
gradio: 3.50.2
fastapi: 0.104.0
pydantic: 2.4.2
```

### Error traceback

```Shell
/opt/conda/envs/lmdeploy_pytorch/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
change working dir to /home/jovyan/test/lmdeploy_multimodal/examples/vl
Fetching 23 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 26834.21it/s]
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Fetching 23 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 23/23 [00:00<00:00, 13123.25it/s]
model_source: hf_model
01/17 02:00:51 - turbomind - WARNING - kwargs model_name is deprecated to initialize model, use TurbomindEngineConfig instead.
model_config:

[llama]
model_name = qwen-vl-chat
tensor_para_size = 1
head_num = 32
kv_head_num = 32
vocab_size = 151936
num_layer = 32
inter_size = 11008
norm_eps = 1e-06
attn_bias = 1
start_id = 0
end_id = 151643
session_len = 8200
weight_type = bf16
rotary_embedding = 128
rope_theta = 10000.0
size_per_head = 128
group_size = 0
max_batch_size = 128
max_context_token_num = 1
step_length = 1
cache_max_entry_count = 0.5
cache_block_seq_len = 128
cache_chunk_size = -1
num_tokens_per_iter = 0
max_prefill_iters = 1
extra_tokens_per_iter = 0
use_context_fmha = 1
quant_policy = 0
max_position_embeddings = 2048
rope_scaling_factor = 0.0
use_logn_attn = 1


get 323 model params
Traceback (most recent call last):                                                                                                                       
  File "/home/jovyan/test/lmdeploy_multimodal/examples/vl/app.py", line 252, in <module>
    main()
  File "/home/jovyan/test/lmdeploy_multimodal/examples/vl/app.py", line 247, in main
    preprocessor, model = load_preprocessor_model(args)
  File "/home/jovyan/test/lmdeploy_multimodal/examples/vl/app.py", line 97, in load_preprocessor_model
    model = TurboMind.from_pretrained(llm_ckpt, model_name=args.model_name)
  File "/home/jovyan/test/lmdeploy_multimodal/lmdeploy/turbomind/turbomind.py", line 446, in from_pretrained
    return cls(model_path=local_path,
  File "/home/jovyan/test/lmdeploy_multimodal/lmdeploy/turbomind/turbomind.py", line 216, in __init__
    self.stop_words = _stop_words(self.model.stop_words, self.tokenizer)
  File "/home/jovyan/test/lmdeploy_multimodal/lmdeploy/turbomind/turbomind.py", line 49, in _stop_words
    stop_indexes += tokenizer.indexes_containing_token(stop_word)
  File "/home/jovyan/test/lmdeploy_multimodal/lmdeploy/tokenizer.py", line 380, in indexes_containing_token
    return self.model.indexes_containing_token(token)
  File "/home/jovyan/test/lmdeploy_multimodal/lmdeploy/tokenizer.py", line 235, in indexes_containing_token
    self.token2id = {
  File "/home/jovyan/test/lmdeploy_multimodal/lmdeploy/tokenizer.py", line 236, in <dictcomp>
    self.model.decode(i): i
  File "/opt/conda/envs/lmdeploy_pytorch/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 3550, in decode
    return self._decode(
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/6665c780ade5ff3f08853b4262dcb9c8f9598d42/tokenization_qwen.py", line 358, in _decode
    token_ids = _replace_closed_tag(token_ids, self.img_start_id, self.img_end_id, _decode_imgurl)
  File "/home/jovyan/.cache/huggingface/modules/transformers_modules/6665c780ade5ff3f08853b4262dcb9c8f9598d42/tokenization_qwen.py", line 94, in _replace_closed_tag
    raise ValueError("Unclosed image token")
ValueError: Unclosed image token
```

**Comment by irexyc** [comment]
@stone002 可以根据PR改一下，或者等这个PR合入。原因是0.1.0之后改了获取stop words token id的逻辑，新的逻辑和qwen-vl的tokenzier有点冲突

**Comment by stone002** [comment]
> @stone002 可以根据PR改一下，或者等这个PR合入。原因是0.1.0之后改了获取stop words token id的逻辑，新的逻辑和qwen-vl的tokenzier有点冲突

好的，我下午改改试试，感谢~

**Comment by stone002** [comment]
turbomind.py按照v0.1.0修改后模型加载成功了，感谢
