### ISSUE TITLE
[Feature] hope to add einops into requirements.

### ISSUE THREAD

**Issue by zhulinJulia24** [InternLM/lmdeploy#980]
### Motivation

When I use a clean cuda env, then run 
`lmdeploy serve gradio --backend pytorch /nvme/qa_test_models/internlm2-chat-20b`
error occurs, I need `pip install einops`. 

can we add einops into requirements?

### Related resources

` lmdeploy serve gradio --backend pytorch /nvme/qa_test_models/internlm2-chat-20b
`

/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
01/18 09:38:26 - lmdeploy - WARNING - Best matched chat template name: internlm2-chat-20b
Traceback (most recent call last):
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/bin/lmdeploy", line 8, in <module>
    sys.exit(run())
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/cli/entrypoint.py", line 18, in run
    args.run(args)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/cli/serve.py", line 203, in gradio
    run(args.model_path_or_server,
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/serve/gradio/app.py", line 49, in run
    run_local(model_path_or_server,
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/serve/gradio/turbomind_coupled.py", line 157, in run_local
    InterFace.async_engine = AsyncEngine(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 74, in __init__
    self._build_pytorch(model_path=model_path,
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/serve/async_engine.py", line 158, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/pytorch/engine/engine.py", line 115, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 427, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1004, in build_model_agent
    model_agent = BaseModelAgent(model_path,
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 455, in __init__
    self.patched_model = self._build_model(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 478, in _build_model
    hf_model = AutoModelForCausalLM.from_pretrained(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 550, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 485, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 313, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/zhulin1/miniconda3/envs/lmdeployv2/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 179, in check_imports
    raise ImportError(
ImportError: This modeling file requires the following packages that were not found in your environment: einops. Run `pip install einops`

**Comment by lvhan028** [comment]
We are not going to fix this issue because It might result in package conflicts, bringing troubles to install lmdeploy
