### ISSUE TITLE
[Bug] Pytorch引擎部署Baichuan2-13B，程序卡在lmdeploy - INFO - distribute model parameters.

### ISSUE THREAD

**Issue by lzq603** [InternLM/lmdeploy#983]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.

### Describe the bug

下面是我的代码
```python
from lmdeploy import pipeline, GenerationConfig, PytorchEngineConfig

if __name__ == '__main__':
    backend_config = PytorchEngineConfig(session_len=2024, tp=2)
    gen_config = GenerationConfig(top_p=0.8,
                                  top_k=40,
                                  temperature=0.8,
                                  max_new_tokens=1024)
    print("11111111111")
    pipe = pipeline('/root/autodl-tmp/baichuan-inc/Baichuan2-13B-Chat',
                    backend_config=backend_config)
    print("22222222222")
    prompts = [[{
        'role': 'user',
        'content': 'Hi, pls intro yourself'
    }], [{
        'role': 'user',
        'content': 'Shanghai is'
    }]]
    response = pipe(prompts, gen_config=gen_config)
    print("33333333333")
    print(response)
```
提示信息：
![1705546785487](https://github.com/InternLM/lmdeploy/assets/30162988/69f68845-4ecf-46d8-ac11-8c855be5bcdf)

### Reproduction

使用autodl服务器，配置3张4090，在命令行执行上述代码
python lmdeploy_test.py

### Environment

```Shell
- 操作系统：Ubuntu 20.04
- GPU：RTX 4090(24GB) * 3
- python：3.9.18
- pytorch：2.1.2
```

### Error traceback

```Shell
(aichat) root@autodl-container-acc940bcfe-016293e9:~# python lmdeploy_test.py
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
11111111111
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/root/miniconda3/envs/aichat/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:06<00:00,  1.01s/it]
01/18 10:17:59 - lmdeploy - INFO - distribute model parameters.
[E ProcessGroupNCCL.cpp:475] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=24, OpType=SCATTER, NumelIn=35061760, NumelOut=0, Timeout(ms)=1800000) ran for 1800004 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=24, OpType=SCATTER, NumelIn=35061760, NumelOut=0, Timeout(ms)=1800000) ran for 1800004 milliseconds before timing out.
Traceback (most recent call last):
  File "/root/lmdeploy_test.py", line 10, in <module>
    pipe = pipeline('/root/autodl-tmp/baichuan-inc/Baichuan2-13B-Chat',
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/api.py", line 61, in pipeline
    return AsyncEngine(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 74, in __init__
    self._build_pytorch(model_path=model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 158, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 115, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 427, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1010, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 903, in __init__
    self.patch_model_tp(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 959, in patch_model_tp
    resp: TPResponse = _queue_get_response(out_que, self.mp_context)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 875, in _queue_get_response
    __check_context_alive()
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 868, in __check_context_alive
    raise RuntimeError(f'Rank[{idx}] failed.')
RuntimeError: Rank[1] failed.
(aichat) root@autodl-container-acc940bcfe-016293e9:~# /root/miniconda3/envs/aichat/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by grimoire** [comment]
能不能打印一下 https://github.com/InternLM/lmdeploy/blob/4cc59fad2e626a20f4cfa9c5e630e5e4c33e2084/lmdeploy/pytorch/engine/model_agent.py#L656 这里的 e，看下有没有抓到什么异常

**Comment by lzq603** [comment]
traceback打印出来就异常退出，好像是显存爆了，不打印就会卡住
01/18 15:13:25 - lmdeploy - INFO - distribute model parameters.
traceback.print_exc(e)：
01/18 15:13:28 - lmdeploy - ERROR - /root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py - _start_tp_process - 855 - Rank[1] failed.
Traceback (most recent call last):
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 638, in _tp_build_model
    patched_model = patch(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 274, in patch
    model = _dist_model(model, rank, device_mesh=device_mesh)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 211, in _dist_model
    new_child = _dist_model(child, rank, device_mesh)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 211, in _dist_model
    new_child = _dist_model(child, rank, device_mesh)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 211, in _dist_model
    new_child = _dist_model(child, rank, device_mesh)
  [Previous line repeated 1 more time]
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 216, in _dist_model
    _dist_params()
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/patch.py", line 186, in _dist_params
    partition_module(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/dist_utils.py", line 263, in partition_module
    _partition_module('',
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/dist_utils.py", line 240, in _partition_module
    _partition_module(child_name,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/dist_utils.py", line 246, in _partition_module
    func(mod_name, module, device_mesh)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/models/llama.py", line 274, in _distribute_partition_fn
    colwise_parallelize_linear_fn(mod,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/dist_utils.py", line 209, in colwise_parallelize_linear_fn
    return colwise_parallelize_linear(module,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/dist_utils.py", line 161, in colwise_parallelize_linear
    dist_tensor = distribute_tensor(param, device_mesh, [Shard(0)])
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/torch/distributed/_tensor/api.py", line 460, in distribute_tensor
    local_tensor = placement._shard_tensor(local_tensor, device_mesh, idx)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/torch/distributed/_tensor/placement_types.py", line 169, in _shard_tensor
    output = torch.empty_like(scatter_list[my_coordinate[mesh_dim]])
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 68.00 MiB. GPU 1 has a total capacty of 23.65 GiB of which 50.50 MiB is free. Process 97810 has 9.67 GiB memory in use. Process 97809 has 13.92 GiB memory in use. Of the allocated memory 8.47 GiB is allocated by PyTorch, and 508.93 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 852, in _start_tp_process
    func(rank, *args, **kwargs)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 791, in _tp_model_loop
    patched_model, cache_engine = _tp_build_model(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 659, in _tp_build_model
    traceback.print_exc(e)
  File "/root/miniconda3/envs/aichat/lib/python3.9/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/root/miniconda3/envs/aichat/lib/python3.9/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/root/miniconda3/envs/aichat/lib/python3.9/traceback.py", line 517, in __init__
    self.stack = StackSummary.extract(
  File "/root/miniconda3/envs/aichat/lib/python3.9/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'OutOfMemoryError' and 'int'
Traceback (most recent call last):
  File "/root/lmdeploy_test.py", line 10, in <module>
    pipe = pipeline('/root/autodl-tmp/baichuan-inc/Baichuan2-13B-Chat',
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/api.py", line 61, in pipeline
    return AsyncEngine(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 74, in __init__
    self._build_pytorch(model_path=model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 158, in _build_pytorch
    self.engine = Engine(model_path=model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/engine.py", line 115, in __init__
    self.model_agent = AutoModelAgent.from_pretrained(
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 428, in from_pretrained
    return build_model_agent(pretrained_model_name_or_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 1013, in build_model_agent
    model_agent = TPModelAgent(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 906, in __init__
    self.patch_model_tp(model_path,
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 962, in patch_model_tp
    resp: TPResponse = _queue_get_response(out_que, self.mp_context)
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 878, in _queue_get_response
    __check_context_alive()
  File "/root/miniconda3/envs/aichat/lib/python3.9/site-packages/lmdeploy/pytorch/engine/model_agent.py", line 871, in __check_context_alive
    raise RuntimeError(f'Rank[{idx}] failed.')
RuntimeError: Rank[1] failed.
(aichat) root@autodl-container-ab8942b722-add1d362:~# /root/miniconda3/envs/aichat/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by grimoire** [comment]
https://github.com/InternLM/lmdeploy/pull/987 可以试一下这个
